package com.jxparallel.fx.peer.geometry;

/** JavaFX peer of {@link com.jxparallel.fx.geometry.BoundingBox}; forwards overridable methods to it (generated by scripts/GenerateFxApi.java). */
@SuppressWarnings({"unchecked", "rawtypes", "deprecation", "serial"})
public class BoundingBox extends javafx.geometry.BoundingBox implements com.jxparallel.fx.Fx.Owned {
    private Object jxOwner;

    public BoundingBox(@javafx.beans.NamedArg(value = "minX") double arg0, @javafx.beans.NamedArg(value = "minY") double arg1, @javafx.beans.NamedArg(value = "minZ") double arg2, @javafx.beans.NamedArg(value = "width") double arg3, @javafx.beans.NamedArg(value = "height") double arg4, @javafx.beans.NamedArg(value = "depth") double arg5) {
        super(arg0, arg1, arg2, arg3, arg4, arg5);
    }

    public BoundingBox(@javafx.beans.NamedArg(value = "minX") double arg0, @javafx.beans.NamedArg(value = "minY") double arg1, @javafx.beans.NamedArg(value = "width") double arg2, @javafx.beans.NamedArg(value = "height") double arg3) {
        super(arg0, arg1, arg2, arg3);
    }

    @Override
    public Object jxOwner() {
        return jxOwner;
    }

    @Override
    public void jxOwner(Object owner) {
        this.jxOwner = owner;
    }

    @Override
    public Object callSuper(String method, Object[] a) {
        try {
        switch (method) {
            default:
                throw new AbstractMethodError(method);
        }
        } catch (Exception e) {
            throw com.jxparallel.fx.Fx.sneaky(e);
        }
    }
}
