package com.jxparallel.fx.peer.geometry;

/** JavaFX peer of {@link com.jxparallel.fx.geometry.Insets}; forwards overridable methods to it (generated by scripts/GenerateFxApi.java). */
@SuppressWarnings({"unchecked", "rawtypes", "deprecation", "serial"})
public class Insets extends javafx.geometry.Insets implements com.jxparallel.fx.Fx.Owned {
    private Object jxOwner;

    public Insets(@javafx.beans.NamedArg(value = "topRightBottomLeft") double arg0) {
        super(arg0);
    }

    public Insets(@javafx.beans.NamedArg(value = "top") double arg0, @javafx.beans.NamedArg(value = "right") double arg1, @javafx.beans.NamedArg(value = "bottom") double arg2, @javafx.beans.NamedArg(value = "left") double arg3) {
        super(arg0, arg1, arg2, arg3);
    }

    @Override
    public Object jxOwner() {
        return jxOwner;
    }

    @Override
    public void jxOwner(Object owner) {
        this.jxOwner = owner;
    }

    @Override
    public Object callSuper(String method, Object[] a) {
        try {
        switch (method) {
            default:
                throw new AbstractMethodError(method);
        }
        } catch (Exception e) {
            throw com.jxparallel.fx.Fx.sneaky(e);
        }
    }
}
