package com.jxparallel.fx.scene.layout;

/** JXParallel counterpart of {@link javafx.scene.layout.BackgroundImage} (generated by scripts/GenerateFxApi.java). */
@SuppressWarnings({"unchecked", "rawtypes", "deprecation"})
public final class BackgroundImage implements com.jxparallel.fx.Fx.Backed {
    private final Object fxPeer;

    protected BackgroundImage(com.jxparallel.fx.Fx.Wrap wrap, Object peer) {
        this.fxPeer = peer;
    }

    @Override
    public Object fxPeer() {
        return fxPeer;
    }

    @Override
    public boolean equals(Object o) {
        return o == this || fxPeer.equals(com.jxparallel.fx.Fx.fx(o));
    }

    @Override
    public int hashCode() {
        return fxPeer.hashCode();
    }

    @Override
    public String toString() {
        return fxPeer.toString();
    }

    public BackgroundImage(@javafx.beans.NamedArg(value = "image") com.jxparallel.fx.scene.image.Image arg0, @javafx.beans.NamedArg(value = "repeatX") com.jxparallel.fx.scene.layout.BackgroundRepeat arg1, @javafx.beans.NamedArg(value = "repeatY") com.jxparallel.fx.scene.layout.BackgroundRepeat arg2, @javafx.beans.NamedArg(value = "position") com.jxparallel.fx.scene.layout.BackgroundPosition arg3, @javafx.beans.NamedArg(value = "size") com.jxparallel.fx.scene.layout.BackgroundSize arg4) {
        this(com.jxparallel.fx.Fx.WRAP, new javafx.scene.layout.BackgroundImage((javafx.scene.image.Image) com.jxparallel.fx.Fx.fx(arg0), (javafx.scene.layout.BackgroundRepeat) com.jxparallel.fx.Fx.fx(arg1), (javafx.scene.layout.BackgroundRepeat) com.jxparallel.fx.Fx.fx(arg2), (javafx.scene.layout.BackgroundPosition) com.jxparallel.fx.Fx.fx(arg3), (javafx.scene.layout.BackgroundSize) com.jxparallel.fx.Fx.fx(arg4)));
        com.jxparallel.fx.Fx.own(fxPeer(), this);
    }

    public com.jxparallel.fx.scene.image.Image getImage() {
        return (com.jxparallel.fx.scene.image.Image) com.jxparallel.fx.Fx.jx(((javafx.scene.layout.BackgroundImage) fxPeer()).getImage());
    }

    public com.jxparallel.fx.scene.layout.BackgroundPosition getPosition() {
        return (com.jxparallel.fx.scene.layout.BackgroundPosition) com.jxparallel.fx.Fx.jx(((javafx.scene.layout.BackgroundImage) fxPeer()).getPosition());
    }

    public com.jxparallel.fx.scene.layout.BackgroundRepeat getRepeatX() {
        return (com.jxparallel.fx.scene.layout.BackgroundRepeat) com.jxparallel.fx.Fx.jx(((javafx.scene.layout.BackgroundImage) fxPeer()).getRepeatX());
    }

    public com.jxparallel.fx.scene.layout.BackgroundRepeat getRepeatY() {
        return (com.jxparallel.fx.scene.layout.BackgroundRepeat) com.jxparallel.fx.Fx.jx(((javafx.scene.layout.BackgroundImage) fxPeer()).getRepeatY());
    }

    public com.jxparallel.fx.scene.layout.BackgroundSize getSize() {
        return (com.jxparallel.fx.scene.layout.BackgroundSize) com.jxparallel.fx.Fx.jx(((javafx.scene.layout.BackgroundImage) fxPeer()).getSize());
    }
}
