package com.jxparallel.fx.scene.layout;

/** JXParallel counterpart of {@link javafx.scene.layout.BackgroundPosition} (generated by scripts/GenerateFxApi.java). */
@SuppressWarnings({"unchecked", "rawtypes", "deprecation"})
public class BackgroundPosition implements com.jxparallel.fx.Fx.Backed {
    private final Object fxPeer;

    protected BackgroundPosition(com.jxparallel.fx.Fx.Wrap wrap, Object peer) {
        this.fxPeer = peer;
    }

    @Override
    public Object fxPeer() {
        return fxPeer;
    }

    @Override
    public boolean equals(Object o) {
        return o == this || fxPeer.equals(com.jxparallel.fx.Fx.fx(o));
    }

    @Override
    public int hashCode() {
        return fxPeer.hashCode();
    }

    @Override
    public String toString() {
        return fxPeer.toString();
    }

    public BackgroundPosition(@javafx.beans.NamedArg(value = "horizontalSide") com.jxparallel.fx.geometry.Side arg0, @javafx.beans.NamedArg(value = "horizontalPosition") double arg1, @javafx.beans.NamedArg(value = "horizontalAsPercentage") boolean arg2, @javafx.beans.NamedArg(value = "verticalSide") com.jxparallel.fx.geometry.Side arg3, @javafx.beans.NamedArg(value = "verticalPosition") double arg4, @javafx.beans.NamedArg(value = "verticalAsPercentage") boolean arg5) {
        this(com.jxparallel.fx.Fx.WRAP, new com.jxparallel.fx.peer.scene.layout.BackgroundPosition((javafx.geometry.Side) com.jxparallel.fx.Fx.fx(arg0), arg1, arg2, (javafx.geometry.Side) com.jxparallel.fx.Fx.fx(arg3), arg4, arg5));
        com.jxparallel.fx.Fx.own(fxPeer(), this);
    }

    public static final com.jxparallel.fx.scene.layout.BackgroundPosition DEFAULT = (com.jxparallel.fx.scene.layout.BackgroundPosition) com.jxparallel.fx.Fx.jx(javafx.scene.layout.BackgroundPosition.DEFAULT);

    public static final com.jxparallel.fx.scene.layout.BackgroundPosition CENTER = (com.jxparallel.fx.scene.layout.BackgroundPosition) com.jxparallel.fx.Fx.jx(javafx.scene.layout.BackgroundPosition.CENTER);

    public double getHorizontalPosition() {
        return ((javafx.scene.layout.BackgroundPosition) fxPeer()).getHorizontalPosition();
    }

    public com.jxparallel.fx.geometry.Side getHorizontalSide() {
        return (com.jxparallel.fx.geometry.Side) com.jxparallel.fx.Fx.jx(((javafx.scene.layout.BackgroundPosition) fxPeer()).getHorizontalSide());
    }

    public double getVerticalPosition() {
        return ((javafx.scene.layout.BackgroundPosition) fxPeer()).getVerticalPosition();
    }

    public com.jxparallel.fx.geometry.Side getVerticalSide() {
        return (com.jxparallel.fx.geometry.Side) com.jxparallel.fx.Fx.jx(((javafx.scene.layout.BackgroundPosition) fxPeer()).getVerticalSide());
    }

    public boolean isHorizontalAsPercentage() {
        return ((javafx.scene.layout.BackgroundPosition) fxPeer()).isHorizontalAsPercentage();
    }

    public boolean isVerticalAsPercentage() {
        return ((javafx.scene.layout.BackgroundPosition) fxPeer()).isVerticalAsPercentage();
    }
}
