package com.jxparallel.fx.scene.layout;

/** JXParallel counterpart of {@link javafx.scene.layout.Border} (generated by scripts/GenerateFxApi.java). */
@SuppressWarnings({"unchecked", "rawtypes", "deprecation"})
public final class Border implements com.jxparallel.fx.Fx.Backed {
    private final Object fxPeer;

    protected Border(com.jxparallel.fx.Fx.Wrap wrap, Object peer) {
        this.fxPeer = peer;
    }

    @Override
    public Object fxPeer() {
        return fxPeer;
    }

    @Override
    public boolean equals(Object o) {
        return o == this || fxPeer().equals(com.jxparallel.fx.Fx.fx(o));
    }

    @Override
    public int hashCode() {
        return fxPeer().hashCode();
    }

    @Override
    public String toString() {
        return fxPeer().toString();
    }

    public Border(@javafx.beans.NamedArg(value = "strokes") java.util.List<com.jxparallel.fx.scene.layout.BorderStroke> arg0, @javafx.beans.NamedArg(value = "images") java.util.List<com.jxparallel.fx.scene.layout.BorderImage> arg1) {
        this(com.jxparallel.fx.Fx.WRAP, new javafx.scene.layout.Border((java.util.List) com.jxparallel.fx.Fx.fxCollection(arg0), (java.util.List) com.jxparallel.fx.Fx.fxCollection(arg1)));
        com.jxparallel.fx.Fx.own(fxPeer(), this);
    }

    public Border(@javafx.beans.NamedArg(value = "images") com.jxparallel.fx.scene.layout.BorderImage... arg0) {
        this(com.jxparallel.fx.Fx.WRAP, new javafx.scene.layout.Border((javafx.scene.layout.BorderImage[]) com.jxparallel.fx.Fx.fxArray(arg0, javafx.scene.layout.BorderImage.class)));
        com.jxparallel.fx.Fx.own(fxPeer(), this);
    }

    public Border(@javafx.beans.NamedArg(value = "strokes") com.jxparallel.fx.scene.layout.BorderStroke... arg0) {
        this(com.jxparallel.fx.Fx.WRAP, new javafx.scene.layout.Border((javafx.scene.layout.BorderStroke[]) com.jxparallel.fx.Fx.fxArray(arg0, javafx.scene.layout.BorderStroke.class)));
        com.jxparallel.fx.Fx.own(fxPeer(), this);
    }

    public Border(@javafx.beans.NamedArg(value = "strokes") com.jxparallel.fx.scene.layout.BorderStroke[] arg0, @javafx.beans.NamedArg(value = "images") com.jxparallel.fx.scene.layout.BorderImage[] arg1) {
        this(com.jxparallel.fx.Fx.WRAP, new javafx.scene.layout.Border((javafx.scene.layout.BorderStroke[]) com.jxparallel.fx.Fx.fxArray(arg0, javafx.scene.layout.BorderStroke.class), (javafx.scene.layout.BorderImage[]) com.jxparallel.fx.Fx.fxArray(arg1, javafx.scene.layout.BorderImage.class)));
        com.jxparallel.fx.Fx.own(fxPeer(), this);
    }

    public static final com.jxparallel.fx.scene.layout.Border EMPTY = (com.jxparallel.fx.scene.layout.Border) com.jxparallel.fx.Fx.jx(javafx.scene.layout.Border.EMPTY);

    public static java.util.List<javafx.css.CssMetaData<? extends javafx.css.Styleable, ?>> getClassCssMetaData() {
        return javafx.scene.layout.Border.getClassCssMetaData();
    }

    public java.util.List<com.jxparallel.fx.scene.layout.BorderImage> getImages() {
        return (java.util.List) com.jxparallel.fx.Fx.jxList((java.util.List) ((javafx.scene.layout.Border) fxPeer()).getImages());
    }

    public com.jxparallel.fx.geometry.Insets getInsets() {
        return (com.jxparallel.fx.geometry.Insets) com.jxparallel.fx.Fx.jx(((javafx.scene.layout.Border) fxPeer()).getInsets());
    }

    public com.jxparallel.fx.geometry.Insets getOutsets() {
        return (com.jxparallel.fx.geometry.Insets) com.jxparallel.fx.Fx.jx(((javafx.scene.layout.Border) fxPeer()).getOutsets());
    }

    public java.util.List<com.jxparallel.fx.scene.layout.BorderStroke> getStrokes() {
        return (java.util.List) com.jxparallel.fx.Fx.jxList((java.util.List) ((javafx.scene.layout.Border) fxPeer()).getStrokes());
    }

    public boolean isEmpty() {
        return ((javafx.scene.layout.Border) fxPeer()).isEmpty();
    }
}
