package com.jxparallel.fx.scene.layout;

/** JXParallel counterpart of {@link javafx.scene.layout.ColumnConstraints} (generated by scripts/GenerateFxApi.java). */
@SuppressWarnings({"unchecked", "rawtypes", "deprecation"})
public class ColumnConstraints extends com.jxparallel.fx.scene.layout.ConstraintsBase {
    protected ColumnConstraints(com.jxparallel.fx.Fx.Wrap wrap, Object peer) {
        super(wrap, peer);
    }

    public ColumnConstraints(double arg0, double arg1, double arg2, com.jxparallel.fx.scene.layout.Priority arg3, com.jxparallel.fx.geometry.HPos arg4, boolean arg5) {
        this(com.jxparallel.fx.Fx.WRAP, new com.jxparallel.fx.peer.scene.layout.ColumnConstraints(arg0, arg1, arg2, (javafx.scene.layout.Priority) com.jxparallel.fx.Fx.fx(arg3), (javafx.geometry.HPos) com.jxparallel.fx.Fx.fx(arg4), arg5));
        com.jxparallel.fx.Fx.own(fxPeer(), this);
    }

    public ColumnConstraints(double arg0, double arg1, double arg2) {
        this(com.jxparallel.fx.Fx.WRAP, new com.jxparallel.fx.peer.scene.layout.ColumnConstraints(arg0, arg1, arg2));
        com.jxparallel.fx.Fx.own(fxPeer(), this);
    }

    public ColumnConstraints(double arg0) {
        this(com.jxparallel.fx.Fx.WRAP, new com.jxparallel.fx.peer.scene.layout.ColumnConstraints(arg0));
        com.jxparallel.fx.Fx.own(fxPeer(), this);
    }

    public ColumnConstraints() {
        this(com.jxparallel.fx.Fx.WRAP, new com.jxparallel.fx.peer.scene.layout.ColumnConstraints());
        com.jxparallel.fx.Fx.own(fxPeer(), this);
    }

    public com.jxparallel.fx.beans.property.BooleanProperty fillWidthProperty() {
        return (com.jxparallel.fx.beans.property.BooleanProperty) com.jxparallel.fx.Fx.jx(((javafx.scene.layout.ColumnConstraints) fxPeer()).fillWidthProperty());
    }

    public com.jxparallel.fx.geometry.HPos getHalignment() {
        return (com.jxparallel.fx.geometry.HPos) com.jxparallel.fx.Fx.jx(((javafx.scene.layout.ColumnConstraints) fxPeer()).getHalignment());
    }

    public com.jxparallel.fx.scene.layout.Priority getHgrow() {
        return (com.jxparallel.fx.scene.layout.Priority) com.jxparallel.fx.Fx.jx(((javafx.scene.layout.ColumnConstraints) fxPeer()).getHgrow());
    }

    public double getMaxWidth() {
        return ((javafx.scene.layout.ColumnConstraints) fxPeer()).getMaxWidth();
    }

    public double getMinWidth() {
        return ((javafx.scene.layout.ColumnConstraints) fxPeer()).getMinWidth();
    }

    public double getPercentWidth() {
        return ((javafx.scene.layout.ColumnConstraints) fxPeer()).getPercentWidth();
    }

    public double getPrefWidth() {
        return ((javafx.scene.layout.ColumnConstraints) fxPeer()).getPrefWidth();
    }

    public com.jxparallel.fx.beans.property.ObjectProperty<com.jxparallel.fx.geometry.HPos> halignmentProperty() {
        return (com.jxparallel.fx.beans.property.ObjectProperty) com.jxparallel.fx.Fx.jx(((javafx.scene.layout.ColumnConstraints) fxPeer()).halignmentProperty());
    }

    public com.jxparallel.fx.beans.property.ObjectProperty<com.jxparallel.fx.scene.layout.Priority> hgrowProperty() {
        return (com.jxparallel.fx.beans.property.ObjectProperty) com.jxparallel.fx.Fx.jx(((javafx.scene.layout.ColumnConstraints) fxPeer()).hgrowProperty());
    }

    public boolean isFillWidth() {
        return ((javafx.scene.layout.ColumnConstraints) fxPeer()).isFillWidth();
    }

    public com.jxparallel.fx.beans.property.DoubleProperty maxWidthProperty() {
        return (com.jxparallel.fx.beans.property.DoubleProperty) com.jxparallel.fx.Fx.jx(((javafx.scene.layout.ColumnConstraints) fxPeer()).maxWidthProperty());
    }

    public com.jxparallel.fx.beans.property.DoubleProperty minWidthProperty() {
        return (com.jxparallel.fx.beans.property.DoubleProperty) com.jxparallel.fx.Fx.jx(((javafx.scene.layout.ColumnConstraints) fxPeer()).minWidthProperty());
    }

    public com.jxparallel.fx.beans.property.DoubleProperty percentWidthProperty() {
        return (com.jxparallel.fx.beans.property.DoubleProperty) com.jxparallel.fx.Fx.jx(((javafx.scene.layout.ColumnConstraints) fxPeer()).percentWidthProperty());
    }

    public com.jxparallel.fx.beans.property.DoubleProperty prefWidthProperty() {
        return (com.jxparallel.fx.beans.property.DoubleProperty) com.jxparallel.fx.Fx.jx(((javafx.scene.layout.ColumnConstraints) fxPeer()).prefWidthProperty());
    }

    public void setFillWidth(boolean arg0) {
        ((javafx.scene.layout.ColumnConstraints) fxPeer()).setFillWidth(arg0);
    }

    public void setHalignment(com.jxparallel.fx.geometry.HPos arg0) {
        ((javafx.scene.layout.ColumnConstraints) fxPeer()).setHalignment((javafx.geometry.HPos) com.jxparallel.fx.Fx.fx(arg0));
    }

    public void setHgrow(com.jxparallel.fx.scene.layout.Priority arg0) {
        ((javafx.scene.layout.ColumnConstraints) fxPeer()).setHgrow((javafx.scene.layout.Priority) com.jxparallel.fx.Fx.fx(arg0));
    }

    public void setMaxWidth(double arg0) {
        ((javafx.scene.layout.ColumnConstraints) fxPeer()).setMaxWidth(arg0);
    }

    public void setMinWidth(double arg0) {
        ((javafx.scene.layout.ColumnConstraints) fxPeer()).setMinWidth(arg0);
    }

    public void setPercentWidth(double arg0) {
        ((javafx.scene.layout.ColumnConstraints) fxPeer()).setPercentWidth(arg0);
    }

    public void setPrefWidth(double arg0) {
        ((javafx.scene.layout.ColumnConstraints) fxPeer()).setPrefWidth(arg0);
    }
}
