package com.jxparallel.fx.peer.scene.paint;

/** JavaFX peer of {@link com.jxparallel.fx.scene.paint.PhongMaterial}; forwards overridable methods to it (generated by scripts/GenerateFxApi.java). */
@SuppressWarnings({"unchecked", "rawtypes", "deprecation", "serial"})
public class PhongMaterial extends javafx.scene.paint.PhongMaterial implements com.jxparallel.fx.Fx.Owned {
    private Object jxOwner;

    public PhongMaterial() {
        super();
    }

    public PhongMaterial(javafx.scene.paint.Color arg0) {
        super(arg0);
    }

    public PhongMaterial(javafx.scene.paint.Color arg0, javafx.scene.image.Image arg1, javafx.scene.image.Image arg2, javafx.scene.image.Image arg3, javafx.scene.image.Image arg4) {
        super(arg0, arg1, arg2, arg3, arg4);
    }

    @Override
    public Object jxOwner() {
        return jxOwner;
    }

    @Override
    public void jxOwner(Object owner) {
        this.jxOwner = owner;
    }

    @Override
    public Object callSuper(String method, Object[] a) {
        try {
        switch (method) {
            default:
                throw new AbstractMethodError(method);
        }
        } catch (Exception e) {
            throw com.jxparallel.fx.Fx.sneaky(e);
        }
    }
}
