package com.jxparallel.fx.peer.scene.control.cell;

/** JavaFX peer of {@link com.jxparallel.fx.scene.control.cell.ProgressBarTreeTableCell}; forwards overridable methods to it (generated by scripts/GenerateFxApi.java). */
@SuppressWarnings({"unchecked", "rawtypes", "deprecation", "serial"})
public class ProgressBarTreeTableCell<S> extends javafx.scene.control.cell.ProgressBarTreeTableCell<S> implements com.jxparallel.fx.Fx.Owned {
    private Object jxOwner;

    public ProgressBarTreeTableCell() {
        super();
    }

    @Override
    public Object jxOwner() {
        return jxOwner;
    }

    @Override
    public void jxOwner(Object owner) {
        this.jxOwner = owner;
    }

    @Override
    public void updateItem(java.lang.Double arg0, boolean arg1) {
        if (jxOwner == null) {
            super.updateItem(arg0, arg1);
            return;
        }
        com.jxparallel.fx.scene.control.cell.ProgressBarTreeTableCell.$hook(jxOwner, "updateItem(Double,boolean)", new Object[] {com.jxparallel.fx.Fx.jx(arg0), arg1});
    }

    @Override
    public void cancelEdit() {
        if (jxOwner == null) {
            super.cancelEdit();
            return;
        }
        com.jxparallel.fx.scene.control.cell.ProgressBarTreeTableCell.$hook(jxOwner, "cancelEdit()", new Object[] {});
    }

    @Override
    public void commitEdit(java.lang.Double arg0) {
        if (jxOwner == null) {
            super.commitEdit(arg0);
            return;
        }
        com.jxparallel.fx.scene.control.cell.ProgressBarTreeTableCell.$hook(jxOwner, "commitEdit(Object)", new Object[] {com.jxparallel.fx.Fx.jx(arg0)});
    }

    @Override
    public void startEdit() {
        if (jxOwner == null) {
            super.startEdit();
            return;
        }
        com.jxparallel.fx.scene.control.cell.ProgressBarTreeTableCell.$hook(jxOwner, "startEdit()", new Object[] {});
    }

    @Override
    public void updateSelected(boolean arg0) {
        if (jxOwner == null) {
            super.updateSelected(arg0);
            return;
        }
        com.jxparallel.fx.scene.control.cell.ProgressBarTreeTableCell.$hook(jxOwner, "updateSelected(boolean)", new Object[] {arg0});
    }

    @Override
    public void updateIndex(int arg0) {
        if (jxOwner == null) {
            super.updateIndex(arg0);
            return;
        }
        com.jxparallel.fx.scene.control.cell.ProgressBarTreeTableCell.$hook(jxOwner, "updateIndex(int)", new Object[] {arg0});
    }

    @Override
    public Object callSuper(String method, Object[] a) {
        try {
        switch (method) {
            case "updateItem(Double,boolean)":
                super.updateItem((java.lang.Double) a[0], (Boolean) a[1]);
                return null;
            case "cancelEdit()":
                super.cancelEdit();
                return null;
            case "commitEdit(Object)":
                super.commitEdit((java.lang.Double) a[0]);
                return null;
            case "startEdit()":
                super.startEdit();
                return null;
            case "updateSelected(boolean)":
                super.updateSelected((Boolean) a[0]);
                return null;
            case "updateIndex(int)":
                super.updateIndex((Integer) a[0]);
                return null;
            default:
                throw new AbstractMethodError(method);
        }
        } catch (Exception e) {
            throw com.jxparallel.fx.Fx.sneaky(e);
        }
    }
}
