package com.jxparallel.fx.beans.binding;

/** JXParallel counterpart of {@link javafx.beans.binding.BooleanExpression} (generated by scripts/GenerateFxApi.java). */
@SuppressWarnings({"unchecked", "rawtypes", "deprecation"})
public class BooleanExpression implements com.jxparallel.fx.beans.value.ObservableBooleanValue, com.jxparallel.fx.Fx.Backed {
    private final Object fxPeer;

    protected BooleanExpression(com.jxparallel.fx.Fx.Wrap wrap, Object peer) {
        this.fxPeer = peer;
    }

    @Override
    public Object fxPeer() {
        return fxPeer;
    }

    @Override
    public boolean equals(Object o) {
        return o == this || fxPeer().equals(com.jxparallel.fx.Fx.fx(o));
    }

    @Override
    public int hashCode() {
        return fxPeer().hashCode();
    }

    @Override
    public String toString() {
        return fxPeer().toString();
    }

    public BooleanExpression() {
        this(com.jxparallel.fx.Fx.WRAP, new com.jxparallel.fx.peer.beans.binding.BooleanExpression());
        com.jxparallel.fx.Fx.own(fxPeer(), this);
    }

    public com.jxparallel.fx.beans.binding.BooleanBinding and(com.jxparallel.fx.beans.value.ObservableBooleanValue arg0) {
        return (com.jxparallel.fx.beans.binding.BooleanBinding) com.jxparallel.fx.Fx.jx(((javafx.beans.binding.BooleanExpression) fxPeer()).and((javafx.beans.value.ObservableBooleanValue) com.jxparallel.fx.Fx.fx(arg0)));
    }

    public com.jxparallel.fx.beans.binding.ObjectExpression<java.lang.Boolean> asObject() {
        return (com.jxparallel.fx.beans.binding.ObjectExpression) com.jxparallel.fx.Fx.jx(((javafx.beans.binding.BooleanExpression) fxPeer()).asObject());
    }

    public com.jxparallel.fx.beans.binding.StringBinding asString() {
        return (com.jxparallel.fx.beans.binding.StringBinding) com.jxparallel.fx.Fx.jx(((javafx.beans.binding.BooleanExpression) fxPeer()).asString());
    }

    public static com.jxparallel.fx.beans.binding.BooleanExpression booleanExpression(com.jxparallel.fx.beans.value.ObservableBooleanValue arg0) {
        return (com.jxparallel.fx.beans.binding.BooleanExpression) com.jxparallel.fx.Fx.jx(javafx.beans.binding.BooleanExpression.booleanExpression((javafx.beans.value.ObservableBooleanValue) com.jxparallel.fx.Fx.fx(arg0)));
    }

    public static com.jxparallel.fx.beans.binding.BooleanExpression booleanExpression(com.jxparallel.fx.beans.value.ObservableValue<java.lang.Boolean> arg0) {
        return (com.jxparallel.fx.beans.binding.BooleanExpression) com.jxparallel.fx.Fx.jx(javafx.beans.binding.BooleanExpression.booleanExpression((javafx.beans.value.ObservableValue) com.jxparallel.fx.Fx.fx(arg0)));
    }

    public java.lang.Boolean getValue() {
        return ((javafx.beans.binding.BooleanExpression) fxPeer()).getValue();
    }

    public com.jxparallel.fx.beans.binding.BooleanBinding isEqualTo(com.jxparallel.fx.beans.value.ObservableBooleanValue arg0) {
        return (com.jxparallel.fx.beans.binding.BooleanBinding) com.jxparallel.fx.Fx.jx(((javafx.beans.binding.BooleanExpression) fxPeer()).isEqualTo((javafx.beans.value.ObservableBooleanValue) com.jxparallel.fx.Fx.fx(arg0)));
    }

    public com.jxparallel.fx.beans.binding.BooleanBinding isNotEqualTo(com.jxparallel.fx.beans.value.ObservableBooleanValue arg0) {
        return (com.jxparallel.fx.beans.binding.BooleanBinding) com.jxparallel.fx.Fx.jx(((javafx.beans.binding.BooleanExpression) fxPeer()).isNotEqualTo((javafx.beans.value.ObservableBooleanValue) com.jxparallel.fx.Fx.fx(arg0)));
    }

    public com.jxparallel.fx.beans.binding.BooleanBinding not() {
        return (com.jxparallel.fx.beans.binding.BooleanBinding) com.jxparallel.fx.Fx.jx(((javafx.beans.binding.BooleanExpression) fxPeer()).not());
    }

    public com.jxparallel.fx.beans.binding.BooleanBinding or(com.jxparallel.fx.beans.value.ObservableBooleanValue arg0) {
        return (com.jxparallel.fx.beans.binding.BooleanBinding) com.jxparallel.fx.Fx.jx(((javafx.beans.binding.BooleanExpression) fxPeer()).or((javafx.beans.value.ObservableBooleanValue) com.jxparallel.fx.Fx.fx(arg0)));
    }

    public boolean get() {
        return (Boolean) (fxPeer() instanceof com.jxparallel.fx.Fx.Owned ? ((com.jxparallel.fx.Fx.Owned) fxPeer()).callSuper("get()", new Object[] {}) : com.jxparallel.fx.Fx.invoke(fxPeer(), javafx.beans.value.ObservableBooleanValue.class, "get", new Class<?>[] {}));
    }

    public void addListener(com.jxparallel.fx.beans.InvalidationListener arg0) {
        if (fxPeer() instanceof com.jxparallel.fx.Fx.Owned) {
            ((com.jxparallel.fx.Fx.Owned) fxPeer()).callSuper("addListener(InvalidationListener)", new Object[] {(javafx.beans.InvalidationListener) com.jxparallel.fx.Fx.fx(arg0)});
        } else {
            com.jxparallel.fx.Fx.invoke(fxPeer(), javafx.beans.Observable.class, "addListener", new Class<?>[] {javafx.beans.InvalidationListener.class}, (javafx.beans.InvalidationListener) com.jxparallel.fx.Fx.fx(arg0));
        }
    }

    public void removeListener(com.jxparallel.fx.beans.InvalidationListener arg0) {
        if (fxPeer() instanceof com.jxparallel.fx.Fx.Owned) {
            ((com.jxparallel.fx.Fx.Owned) fxPeer()).callSuper("removeListener(InvalidationListener)", new Object[] {(javafx.beans.InvalidationListener) com.jxparallel.fx.Fx.fx(arg0)});
        } else {
            com.jxparallel.fx.Fx.invoke(fxPeer(), javafx.beans.Observable.class, "removeListener", new Class<?>[] {javafx.beans.InvalidationListener.class}, (javafx.beans.InvalidationListener) com.jxparallel.fx.Fx.fx(arg0));
        }
    }

    public void addListener(com.jxparallel.fx.beans.value.ChangeListener<? super java.lang.Boolean> arg0) {
        if (fxPeer() instanceof com.jxparallel.fx.Fx.Owned) {
            ((com.jxparallel.fx.Fx.Owned) fxPeer()).callSuper("addListener(ChangeListener)", new Object[] {(javafx.beans.value.ChangeListener) com.jxparallel.fx.Fx.fx(arg0)});
        } else {
            com.jxparallel.fx.Fx.invoke(fxPeer(), javafx.beans.value.ObservableValue.class, "addListener", new Class<?>[] {javafx.beans.value.ChangeListener.class}, (javafx.beans.value.ChangeListener) com.jxparallel.fx.Fx.fx(arg0));
        }
    }

    public void removeListener(com.jxparallel.fx.beans.value.ChangeListener<? super java.lang.Boolean> arg0) {
        if (fxPeer() instanceof com.jxparallel.fx.Fx.Owned) {
            ((com.jxparallel.fx.Fx.Owned) fxPeer()).callSuper("removeListener(ChangeListener)", new Object[] {(javafx.beans.value.ChangeListener) com.jxparallel.fx.Fx.fx(arg0)});
        } else {
            com.jxparallel.fx.Fx.invoke(fxPeer(), javafx.beans.value.ObservableValue.class, "removeListener", new Class<?>[] {javafx.beans.value.ChangeListener.class}, (javafx.beans.value.ChangeListener) com.jxparallel.fx.Fx.fx(arg0));
        }
    }

    /** Called by the peer: runs the JX (possibly overridden) method. */
    public static Object $hook(Object self, String method, Object[] a) {
        BooleanExpression jx = (BooleanExpression) self;
        try {
        switch (method) {
            case "get()":
                return (Object) jx.get();
            case "addListener(InvalidationListener)":
                jx.addListener((com.jxparallel.fx.beans.InvalidationListener) a[0]);
                return null;
            case "removeListener(InvalidationListener)":
                jx.removeListener((com.jxparallel.fx.beans.InvalidationListener) a[0]);
                return null;
            case "addListener(ChangeListener)":
                jx.addListener((com.jxparallel.fx.beans.value.ChangeListener) a[0]);
                return null;
            case "removeListener(ChangeListener)":
                jx.removeListener((com.jxparallel.fx.beans.value.ChangeListener) a[0]);
                return null;
            default:
                throw new IllegalArgumentException(method);
        }
        } catch (Exception e) {
            throw com.jxparallel.fx.Fx.sneaky(e);
        }
    }
}
