package com.jxparallel.fx.beans.binding;

/** JXParallel counterpart of {@link javafx.beans.binding.BooleanBinding} (generated by scripts/GenerateFxApi.java). */
@SuppressWarnings({"unchecked", "rawtypes", "deprecation"})
public class BooleanBinding extends com.jxparallel.fx.beans.binding.BooleanExpression implements com.jxparallel.fx.beans.binding.Binding<java.lang.Boolean> {
    protected BooleanBinding(com.jxparallel.fx.Fx.Wrap wrap, Object peer) {
        super(wrap, peer);
    }

    public BooleanBinding() {
        this(com.jxparallel.fx.Fx.WRAP, new com.jxparallel.fx.peer.beans.binding.BooleanBinding());
        com.jxparallel.fx.Fx.own(fxPeer(), this);
    }

    public void addListener(com.jxparallel.fx.beans.value.ChangeListener<? super java.lang.Boolean> arg0) {
        ((javafx.beans.binding.BooleanBinding) fxPeer()).addListener((javafx.beans.value.ChangeListener) com.jxparallel.fx.Fx.fx(arg0));
    }

    public void addListener(com.jxparallel.fx.beans.InvalidationListener arg0) {
        ((javafx.beans.binding.BooleanBinding) fxPeer()).addListener((javafx.beans.InvalidationListener) com.jxparallel.fx.Fx.fx(arg0));
    }

    protected void bind(com.jxparallel.fx.beans.Observable... arg0) {
        com.jxparallel.fx.Fx.invoke(fxPeer(), javafx.beans.binding.BooleanBinding.class, "bind", new Class<?>[] {javafx.beans.Observable[].class}, (javafx.beans.Observable[]) com.jxparallel.fx.Fx.fxArray(arg0, javafx.beans.Observable.class));
    }

    protected boolean computeValue() {
        return (Boolean) (fxPeer() instanceof com.jxparallel.fx.Fx.Owned ? ((com.jxparallel.fx.Fx.Owned) fxPeer()).callSuper("computeValue()", new Object[] {}) : com.jxparallel.fx.Fx.invoke(fxPeer(), javafx.beans.binding.BooleanBinding.class, "computeValue", new Class<?>[] {}));
    }

    public void dispose() {
        ((javafx.beans.binding.BooleanBinding) fxPeer()).dispose();
    }

    public boolean get() {
        return ((javafx.beans.binding.BooleanBinding) fxPeer()).get();
    }

    public com.jxparallel.fx.collections.ObservableList<?> getDependencies() {
        return (com.jxparallel.fx.collections.ObservableList) com.jxparallel.fx.Fx.jx(((javafx.beans.binding.BooleanBinding) fxPeer()).getDependencies());
    }

    public void invalidate() {
        ((javafx.beans.binding.BooleanBinding) fxPeer()).invalidate();
    }

    public boolean isValid() {
        return ((javafx.beans.binding.BooleanBinding) fxPeer()).isValid();
    }

    protected void onInvalidating() {
        com.jxparallel.fx.Fx.invoke(fxPeer(), javafx.beans.binding.BooleanBinding.class, "onInvalidating", new Class<?>[] {});
    }

    public void removeListener(com.jxparallel.fx.beans.value.ChangeListener<? super java.lang.Boolean> arg0) {
        ((javafx.beans.binding.BooleanBinding) fxPeer()).removeListener((javafx.beans.value.ChangeListener) com.jxparallel.fx.Fx.fx(arg0));
    }

    public void removeListener(com.jxparallel.fx.beans.InvalidationListener arg0) {
        ((javafx.beans.binding.BooleanBinding) fxPeer()).removeListener((javafx.beans.InvalidationListener) com.jxparallel.fx.Fx.fx(arg0));
    }

    protected void unbind(com.jxparallel.fx.beans.Observable... arg0) {
        com.jxparallel.fx.Fx.invoke(fxPeer(), javafx.beans.binding.BooleanBinding.class, "unbind", new Class<?>[] {javafx.beans.Observable[].class}, (javafx.beans.Observable[]) com.jxparallel.fx.Fx.fxArray(arg0, javafx.beans.Observable.class));
    }

    /** Called by the peer: runs the JX (possibly overridden) method. */
    public static Object $hook(Object self, String method, Object[] a) {
        BooleanBinding jx = (BooleanBinding) self;
        try {
        switch (method) {
            case "computeValue()":
                return (Object) jx.computeValue();
            default:
                throw new IllegalArgumentException(method);
        }
        } catch (Exception e) {
            throw com.jxparallel.fx.Fx.sneaky(e);
        }
    }
}
