package com.jxparallel.fx.beans.binding;

/** JXParallel counterpart of {@link javafx.beans.binding.NumberExpressionBase} (generated by scripts/GenerateFxApi.java). */
@SuppressWarnings({"unchecked", "rawtypes", "deprecation"})
public class NumberExpressionBase implements com.jxparallel.fx.beans.binding.NumberExpression, com.jxparallel.fx.Fx.Backed {
    private final Object fxPeer;

    protected NumberExpressionBase(com.jxparallel.fx.Fx.Wrap wrap, Object peer) {
        this.fxPeer = peer;
    }

    @Override
    public Object fxPeer() {
        return fxPeer;
    }

    @Override
    public boolean equals(Object o) {
        return o == this || fxPeer.equals(com.jxparallel.fx.Fx.fx(o));
    }

    @Override
    public int hashCode() {
        return fxPeer.hashCode();
    }

    @Override
    public String toString() {
        return fxPeer.toString();
    }

    public NumberExpressionBase() {
        this(com.jxparallel.fx.Fx.WRAP, new com.jxparallel.fx.peer.beans.binding.NumberExpressionBase());
        com.jxparallel.fx.Fx.own(fxPeer(), this);
    }

    public com.jxparallel.fx.beans.binding.NumberBinding add(com.jxparallel.fx.beans.value.ObservableNumberValue arg0) {
        return (com.jxparallel.fx.beans.binding.NumberBinding) com.jxparallel.fx.Fx.jx(((javafx.beans.binding.NumberExpressionBase) fxPeer()).add((javafx.beans.value.ObservableNumberValue) com.jxparallel.fx.Fx.fx(arg0)));
    }

    public com.jxparallel.fx.beans.binding.StringBinding asString() {
        return (com.jxparallel.fx.beans.binding.StringBinding) com.jxparallel.fx.Fx.jx(((javafx.beans.binding.NumberExpressionBase) fxPeer()).asString());
    }

    public com.jxparallel.fx.beans.binding.StringBinding asString(java.util.Locale arg0, java.lang.String arg1) {
        return (com.jxparallel.fx.beans.binding.StringBinding) com.jxparallel.fx.Fx.jx(((javafx.beans.binding.NumberExpressionBase) fxPeer()).asString(arg0, arg1));
    }

    public com.jxparallel.fx.beans.binding.StringBinding asString(java.lang.String arg0) {
        return (com.jxparallel.fx.beans.binding.StringBinding) com.jxparallel.fx.Fx.jx(((javafx.beans.binding.NumberExpressionBase) fxPeer()).asString(arg0));
    }

    public com.jxparallel.fx.beans.binding.NumberBinding divide(com.jxparallel.fx.beans.value.ObservableNumberValue arg0) {
        return (com.jxparallel.fx.beans.binding.NumberBinding) com.jxparallel.fx.Fx.jx(((javafx.beans.binding.NumberExpressionBase) fxPeer()).divide((javafx.beans.value.ObservableNumberValue) com.jxparallel.fx.Fx.fx(arg0)));
    }

    public com.jxparallel.fx.beans.binding.BooleanBinding greaterThan(com.jxparallel.fx.beans.value.ObservableNumberValue arg0) {
        return (com.jxparallel.fx.beans.binding.BooleanBinding) com.jxparallel.fx.Fx.jx(((javafx.beans.binding.NumberExpressionBase) fxPeer()).greaterThan((javafx.beans.value.ObservableNumberValue) com.jxparallel.fx.Fx.fx(arg0)));
    }

    public com.jxparallel.fx.beans.binding.BooleanBinding greaterThan(double arg0) {
        return (com.jxparallel.fx.beans.binding.BooleanBinding) com.jxparallel.fx.Fx.jx(((javafx.beans.binding.NumberExpressionBase) fxPeer()).greaterThan(arg0));
    }

    public com.jxparallel.fx.beans.binding.BooleanBinding greaterThan(float arg0) {
        return (com.jxparallel.fx.beans.binding.BooleanBinding) com.jxparallel.fx.Fx.jx(((javafx.beans.binding.NumberExpressionBase) fxPeer()).greaterThan(arg0));
    }

    public com.jxparallel.fx.beans.binding.BooleanBinding greaterThan(int arg0) {
        return (com.jxparallel.fx.beans.binding.BooleanBinding) com.jxparallel.fx.Fx.jx(((javafx.beans.binding.NumberExpressionBase) fxPeer()).greaterThan(arg0));
    }

    public com.jxparallel.fx.beans.binding.BooleanBinding greaterThan(long arg0) {
        return (com.jxparallel.fx.beans.binding.BooleanBinding) com.jxparallel.fx.Fx.jx(((javafx.beans.binding.NumberExpressionBase) fxPeer()).greaterThan(arg0));
    }

    public com.jxparallel.fx.beans.binding.BooleanBinding greaterThanOrEqualTo(com.jxparallel.fx.beans.value.ObservableNumberValue arg0) {
        return (com.jxparallel.fx.beans.binding.BooleanBinding) com.jxparallel.fx.Fx.jx(((javafx.beans.binding.NumberExpressionBase) fxPeer()).greaterThanOrEqualTo((javafx.beans.value.ObservableNumberValue) com.jxparallel.fx.Fx.fx(arg0)));
    }

    public com.jxparallel.fx.beans.binding.BooleanBinding greaterThanOrEqualTo(double arg0) {
        return (com.jxparallel.fx.beans.binding.BooleanBinding) com.jxparallel.fx.Fx.jx(((javafx.beans.binding.NumberExpressionBase) fxPeer()).greaterThanOrEqualTo(arg0));
    }

    public com.jxparallel.fx.beans.binding.BooleanBinding greaterThanOrEqualTo(float arg0) {
        return (com.jxparallel.fx.beans.binding.BooleanBinding) com.jxparallel.fx.Fx.jx(((javafx.beans.binding.NumberExpressionBase) fxPeer()).greaterThanOrEqualTo(arg0));
    }

    public com.jxparallel.fx.beans.binding.BooleanBinding greaterThanOrEqualTo(int arg0) {
        return (com.jxparallel.fx.beans.binding.BooleanBinding) com.jxparallel.fx.Fx.jx(((javafx.beans.binding.NumberExpressionBase) fxPeer()).greaterThanOrEqualTo(arg0));
    }

    public com.jxparallel.fx.beans.binding.BooleanBinding greaterThanOrEqualTo(long arg0) {
        return (com.jxparallel.fx.beans.binding.BooleanBinding) com.jxparallel.fx.Fx.jx(((javafx.beans.binding.NumberExpressionBase) fxPeer()).greaterThanOrEqualTo(arg0));
    }

    public com.jxparallel.fx.beans.binding.BooleanBinding isEqualTo(com.jxparallel.fx.beans.value.ObservableNumberValue arg0) {
        return (com.jxparallel.fx.beans.binding.BooleanBinding) com.jxparallel.fx.Fx.jx(((javafx.beans.binding.NumberExpressionBase) fxPeer()).isEqualTo((javafx.beans.value.ObservableNumberValue) com.jxparallel.fx.Fx.fx(arg0)));
    }

    public com.jxparallel.fx.beans.binding.BooleanBinding isEqualTo(com.jxparallel.fx.beans.value.ObservableNumberValue arg0, double arg1) {
        return (com.jxparallel.fx.beans.binding.BooleanBinding) com.jxparallel.fx.Fx.jx(((javafx.beans.binding.NumberExpressionBase) fxPeer()).isEqualTo((javafx.beans.value.ObservableNumberValue) com.jxparallel.fx.Fx.fx(arg0), arg1));
    }

    public com.jxparallel.fx.beans.binding.BooleanBinding isEqualTo(double arg0, double arg1) {
        return (com.jxparallel.fx.beans.binding.BooleanBinding) com.jxparallel.fx.Fx.jx(((javafx.beans.binding.NumberExpressionBase) fxPeer()).isEqualTo(arg0, arg1));
    }

    public com.jxparallel.fx.beans.binding.BooleanBinding isEqualTo(float arg0, double arg1) {
        return (com.jxparallel.fx.beans.binding.BooleanBinding) com.jxparallel.fx.Fx.jx(((javafx.beans.binding.NumberExpressionBase) fxPeer()).isEqualTo(arg0, arg1));
    }

    public com.jxparallel.fx.beans.binding.BooleanBinding isEqualTo(int arg0) {
        return (com.jxparallel.fx.beans.binding.BooleanBinding) com.jxparallel.fx.Fx.jx(((javafx.beans.binding.NumberExpressionBase) fxPeer()).isEqualTo(arg0));
    }

    public com.jxparallel.fx.beans.binding.BooleanBinding isEqualTo(int arg0, double arg1) {
        return (com.jxparallel.fx.beans.binding.BooleanBinding) com.jxparallel.fx.Fx.jx(((javafx.beans.binding.NumberExpressionBase) fxPeer()).isEqualTo(arg0, arg1));
    }

    public com.jxparallel.fx.beans.binding.BooleanBinding isEqualTo(long arg0) {
        return (com.jxparallel.fx.beans.binding.BooleanBinding) com.jxparallel.fx.Fx.jx(((javafx.beans.binding.NumberExpressionBase) fxPeer()).isEqualTo(arg0));
    }

    public com.jxparallel.fx.beans.binding.BooleanBinding isEqualTo(long arg0, double arg1) {
        return (com.jxparallel.fx.beans.binding.BooleanBinding) com.jxparallel.fx.Fx.jx(((javafx.beans.binding.NumberExpressionBase) fxPeer()).isEqualTo(arg0, arg1));
    }

    public com.jxparallel.fx.beans.binding.BooleanBinding isNotEqualTo(com.jxparallel.fx.beans.value.ObservableNumberValue arg0) {
        return (com.jxparallel.fx.beans.binding.BooleanBinding) com.jxparallel.fx.Fx.jx(((javafx.beans.binding.NumberExpressionBase) fxPeer()).isNotEqualTo((javafx.beans.value.ObservableNumberValue) com.jxparallel.fx.Fx.fx(arg0)));
    }

    public com.jxparallel.fx.beans.binding.BooleanBinding isNotEqualTo(com.jxparallel.fx.beans.value.ObservableNumberValue arg0, double arg1) {
        return (com.jxparallel.fx.beans.binding.BooleanBinding) com.jxparallel.fx.Fx.jx(((javafx.beans.binding.NumberExpressionBase) fxPeer()).isNotEqualTo((javafx.beans.value.ObservableNumberValue) com.jxparallel.fx.Fx.fx(arg0), arg1));
    }

    public com.jxparallel.fx.beans.binding.BooleanBinding isNotEqualTo(double arg0, double arg1) {
        return (com.jxparallel.fx.beans.binding.BooleanBinding) com.jxparallel.fx.Fx.jx(((javafx.beans.binding.NumberExpressionBase) fxPeer()).isNotEqualTo(arg0, arg1));
    }

    public com.jxparallel.fx.beans.binding.BooleanBinding isNotEqualTo(float arg0, double arg1) {
        return (com.jxparallel.fx.beans.binding.BooleanBinding) com.jxparallel.fx.Fx.jx(((javafx.beans.binding.NumberExpressionBase) fxPeer()).isNotEqualTo(arg0, arg1));
    }

    public com.jxparallel.fx.beans.binding.BooleanBinding isNotEqualTo(int arg0) {
        return (com.jxparallel.fx.beans.binding.BooleanBinding) com.jxparallel.fx.Fx.jx(((javafx.beans.binding.NumberExpressionBase) fxPeer()).isNotEqualTo(arg0));
    }

    public com.jxparallel.fx.beans.binding.BooleanBinding isNotEqualTo(int arg0, double arg1) {
        return (com.jxparallel.fx.beans.binding.BooleanBinding) com.jxparallel.fx.Fx.jx(((javafx.beans.binding.NumberExpressionBase) fxPeer()).isNotEqualTo(arg0, arg1));
    }

    public com.jxparallel.fx.beans.binding.BooleanBinding isNotEqualTo(long arg0) {
        return (com.jxparallel.fx.beans.binding.BooleanBinding) com.jxparallel.fx.Fx.jx(((javafx.beans.binding.NumberExpressionBase) fxPeer()).isNotEqualTo(arg0));
    }

    public com.jxparallel.fx.beans.binding.BooleanBinding isNotEqualTo(long arg0, double arg1) {
        return (com.jxparallel.fx.beans.binding.BooleanBinding) com.jxparallel.fx.Fx.jx(((javafx.beans.binding.NumberExpressionBase) fxPeer()).isNotEqualTo(arg0, arg1));
    }

    public com.jxparallel.fx.beans.binding.BooleanBinding lessThan(com.jxparallel.fx.beans.value.ObservableNumberValue arg0) {
        return (com.jxparallel.fx.beans.binding.BooleanBinding) com.jxparallel.fx.Fx.jx(((javafx.beans.binding.NumberExpressionBase) fxPeer()).lessThan((javafx.beans.value.ObservableNumberValue) com.jxparallel.fx.Fx.fx(arg0)));
    }

    public com.jxparallel.fx.beans.binding.BooleanBinding lessThan(double arg0) {
        return (com.jxparallel.fx.beans.binding.BooleanBinding) com.jxparallel.fx.Fx.jx(((javafx.beans.binding.NumberExpressionBase) fxPeer()).lessThan(arg0));
    }

    public com.jxparallel.fx.beans.binding.BooleanBinding lessThan(float arg0) {
        return (com.jxparallel.fx.beans.binding.BooleanBinding) com.jxparallel.fx.Fx.jx(((javafx.beans.binding.NumberExpressionBase) fxPeer()).lessThan(arg0));
    }

    public com.jxparallel.fx.beans.binding.BooleanBinding lessThan(int arg0) {
        return (com.jxparallel.fx.beans.binding.BooleanBinding) com.jxparallel.fx.Fx.jx(((javafx.beans.binding.NumberExpressionBase) fxPeer()).lessThan(arg0));
    }

    public com.jxparallel.fx.beans.binding.BooleanBinding lessThan(long arg0) {
        return (com.jxparallel.fx.beans.binding.BooleanBinding) com.jxparallel.fx.Fx.jx(((javafx.beans.binding.NumberExpressionBase) fxPeer()).lessThan(arg0));
    }

    public com.jxparallel.fx.beans.binding.BooleanBinding lessThanOrEqualTo(com.jxparallel.fx.beans.value.ObservableNumberValue arg0) {
        return (com.jxparallel.fx.beans.binding.BooleanBinding) com.jxparallel.fx.Fx.jx(((javafx.beans.binding.NumberExpressionBase) fxPeer()).lessThanOrEqualTo((javafx.beans.value.ObservableNumberValue) com.jxparallel.fx.Fx.fx(arg0)));
    }

    public com.jxparallel.fx.beans.binding.BooleanBinding lessThanOrEqualTo(double arg0) {
        return (com.jxparallel.fx.beans.binding.BooleanBinding) com.jxparallel.fx.Fx.jx(((javafx.beans.binding.NumberExpressionBase) fxPeer()).lessThanOrEqualTo(arg0));
    }

    public com.jxparallel.fx.beans.binding.BooleanBinding lessThanOrEqualTo(float arg0) {
        return (com.jxparallel.fx.beans.binding.BooleanBinding) com.jxparallel.fx.Fx.jx(((javafx.beans.binding.NumberExpressionBase) fxPeer()).lessThanOrEqualTo(arg0));
    }

    public com.jxparallel.fx.beans.binding.BooleanBinding lessThanOrEqualTo(int arg0) {
        return (com.jxparallel.fx.beans.binding.BooleanBinding) com.jxparallel.fx.Fx.jx(((javafx.beans.binding.NumberExpressionBase) fxPeer()).lessThanOrEqualTo(arg0));
    }

    public com.jxparallel.fx.beans.binding.BooleanBinding lessThanOrEqualTo(long arg0) {
        return (com.jxparallel.fx.beans.binding.BooleanBinding) com.jxparallel.fx.Fx.jx(((javafx.beans.binding.NumberExpressionBase) fxPeer()).lessThanOrEqualTo(arg0));
    }

    public com.jxparallel.fx.beans.binding.NumberBinding multiply(com.jxparallel.fx.beans.value.ObservableNumberValue arg0) {
        return (com.jxparallel.fx.beans.binding.NumberBinding) com.jxparallel.fx.Fx.jx(((javafx.beans.binding.NumberExpressionBase) fxPeer()).multiply((javafx.beans.value.ObservableNumberValue) com.jxparallel.fx.Fx.fx(arg0)));
    }

    public static <S extends java.lang.Number> com.jxparallel.fx.beans.binding.NumberExpressionBase numberExpression(com.jxparallel.fx.beans.value.ObservableNumberValue arg0) {
        return (com.jxparallel.fx.beans.binding.NumberExpressionBase) com.jxparallel.fx.Fx.jx(javafx.beans.binding.NumberExpressionBase.numberExpression((javafx.beans.value.ObservableNumberValue) com.jxparallel.fx.Fx.fx(arg0)));
    }

    public com.jxparallel.fx.beans.binding.NumberBinding subtract(com.jxparallel.fx.beans.value.ObservableNumberValue arg0) {
        return (com.jxparallel.fx.beans.binding.NumberBinding) com.jxparallel.fx.Fx.jx(((javafx.beans.binding.NumberExpressionBase) fxPeer()).subtract((javafx.beans.value.ObservableNumberValue) com.jxparallel.fx.Fx.fx(arg0)));
    }

    public com.jxparallel.fx.beans.binding.NumberBinding add(long arg0) {
        return (com.jxparallel.fx.beans.binding.NumberBinding) com.jxparallel.fx.Fx.jx((fxPeer() instanceof com.jxparallel.fx.Fx.Owned ? ((com.jxparallel.fx.Fx.Owned) fxPeer()).callSuper("add(long)", new Object[] {arg0}) : com.jxparallel.fx.Fx.invoke(fxPeer(), javafx.beans.binding.NumberExpression.class, "add", new Class<?>[] {long.class}, arg0)));
    }

    public com.jxparallel.fx.beans.binding.NumberBinding add(float arg0) {
        return (com.jxparallel.fx.beans.binding.NumberBinding) com.jxparallel.fx.Fx.jx((fxPeer() instanceof com.jxparallel.fx.Fx.Owned ? ((com.jxparallel.fx.Fx.Owned) fxPeer()).callSuper("add(float)", new Object[] {arg0}) : com.jxparallel.fx.Fx.invoke(fxPeer(), javafx.beans.binding.NumberExpression.class, "add", new Class<?>[] {float.class}, arg0)));
    }

    public com.jxparallel.fx.beans.binding.NumberBinding add(double arg0) {
        return (com.jxparallel.fx.beans.binding.NumberBinding) com.jxparallel.fx.Fx.jx((fxPeer() instanceof com.jxparallel.fx.Fx.Owned ? ((com.jxparallel.fx.Fx.Owned) fxPeer()).callSuper("add(double)", new Object[] {arg0}) : com.jxparallel.fx.Fx.invoke(fxPeer(), javafx.beans.binding.NumberExpression.class, "add", new Class<?>[] {double.class}, arg0)));
    }

    public com.jxparallel.fx.beans.binding.NumberBinding add(int arg0) {
        return (com.jxparallel.fx.beans.binding.NumberBinding) com.jxparallel.fx.Fx.jx((fxPeer() instanceof com.jxparallel.fx.Fx.Owned ? ((com.jxparallel.fx.Fx.Owned) fxPeer()).callSuper("add(int)", new Object[] {arg0}) : com.jxparallel.fx.Fx.invoke(fxPeer(), javafx.beans.binding.NumberExpression.class, "add", new Class<?>[] {int.class}, arg0)));
    }

    public com.jxparallel.fx.beans.binding.NumberBinding divide(long arg0) {
        return (com.jxparallel.fx.beans.binding.NumberBinding) com.jxparallel.fx.Fx.jx((fxPeer() instanceof com.jxparallel.fx.Fx.Owned ? ((com.jxparallel.fx.Fx.Owned) fxPeer()).callSuper("divide(long)", new Object[] {arg0}) : com.jxparallel.fx.Fx.invoke(fxPeer(), javafx.beans.binding.NumberExpression.class, "divide", new Class<?>[] {long.class}, arg0)));
    }

    public com.jxparallel.fx.beans.binding.NumberBinding divide(int arg0) {
        return (com.jxparallel.fx.beans.binding.NumberBinding) com.jxparallel.fx.Fx.jx((fxPeer() instanceof com.jxparallel.fx.Fx.Owned ? ((com.jxparallel.fx.Fx.Owned) fxPeer()).callSuper("divide(int)", new Object[] {arg0}) : com.jxparallel.fx.Fx.invoke(fxPeer(), javafx.beans.binding.NumberExpression.class, "divide", new Class<?>[] {int.class}, arg0)));
    }

    public com.jxparallel.fx.beans.binding.NumberBinding divide(double arg0) {
        return (com.jxparallel.fx.beans.binding.NumberBinding) com.jxparallel.fx.Fx.jx((fxPeer() instanceof com.jxparallel.fx.Fx.Owned ? ((com.jxparallel.fx.Fx.Owned) fxPeer()).callSuper("divide(double)", new Object[] {arg0}) : com.jxparallel.fx.Fx.invoke(fxPeer(), javafx.beans.binding.NumberExpression.class, "divide", new Class<?>[] {double.class}, arg0)));
    }

    public com.jxparallel.fx.beans.binding.NumberBinding divide(float arg0) {
        return (com.jxparallel.fx.beans.binding.NumberBinding) com.jxparallel.fx.Fx.jx((fxPeer() instanceof com.jxparallel.fx.Fx.Owned ? ((com.jxparallel.fx.Fx.Owned) fxPeer()).callSuper("divide(float)", new Object[] {arg0}) : com.jxparallel.fx.Fx.invoke(fxPeer(), javafx.beans.binding.NumberExpression.class, "divide", new Class<?>[] {float.class}, arg0)));
    }

    public com.jxparallel.fx.beans.binding.NumberBinding negate() {
        return (com.jxparallel.fx.beans.binding.NumberBinding) com.jxparallel.fx.Fx.jx((fxPeer() instanceof com.jxparallel.fx.Fx.Owned ? ((com.jxparallel.fx.Fx.Owned) fxPeer()).callSuper("negate()", new Object[] {}) : com.jxparallel.fx.Fx.invoke(fxPeer(), javafx.beans.binding.NumberExpression.class, "negate", new Class<?>[] {})));
    }

    public com.jxparallel.fx.beans.binding.NumberBinding subtract(float arg0) {
        return (com.jxparallel.fx.beans.binding.NumberBinding) com.jxparallel.fx.Fx.jx((fxPeer() instanceof com.jxparallel.fx.Fx.Owned ? ((com.jxparallel.fx.Fx.Owned) fxPeer()).callSuper("subtract(float)", new Object[] {arg0}) : com.jxparallel.fx.Fx.invoke(fxPeer(), javafx.beans.binding.NumberExpression.class, "subtract", new Class<?>[] {float.class}, arg0)));
    }

    public com.jxparallel.fx.beans.binding.NumberBinding subtract(double arg0) {
        return (com.jxparallel.fx.beans.binding.NumberBinding) com.jxparallel.fx.Fx.jx((fxPeer() instanceof com.jxparallel.fx.Fx.Owned ? ((com.jxparallel.fx.Fx.Owned) fxPeer()).callSuper("subtract(double)", new Object[] {arg0}) : com.jxparallel.fx.Fx.invoke(fxPeer(), javafx.beans.binding.NumberExpression.class, "subtract", new Class<?>[] {double.class}, arg0)));
    }

    public com.jxparallel.fx.beans.binding.NumberBinding subtract(long arg0) {
        return (com.jxparallel.fx.beans.binding.NumberBinding) com.jxparallel.fx.Fx.jx((fxPeer() instanceof com.jxparallel.fx.Fx.Owned ? ((com.jxparallel.fx.Fx.Owned) fxPeer()).callSuper("subtract(long)", new Object[] {arg0}) : com.jxparallel.fx.Fx.invoke(fxPeer(), javafx.beans.binding.NumberExpression.class, "subtract", new Class<?>[] {long.class}, arg0)));
    }

    public com.jxparallel.fx.beans.binding.NumberBinding subtract(int arg0) {
        return (com.jxparallel.fx.beans.binding.NumberBinding) com.jxparallel.fx.Fx.jx((fxPeer() instanceof com.jxparallel.fx.Fx.Owned ? ((com.jxparallel.fx.Fx.Owned) fxPeer()).callSuper("subtract(int)", new Object[] {arg0}) : com.jxparallel.fx.Fx.invoke(fxPeer(), javafx.beans.binding.NumberExpression.class, "subtract", new Class<?>[] {int.class}, arg0)));
    }

    public com.jxparallel.fx.beans.binding.NumberBinding multiply(double arg0) {
        return (com.jxparallel.fx.beans.binding.NumberBinding) com.jxparallel.fx.Fx.jx((fxPeer() instanceof com.jxparallel.fx.Fx.Owned ? ((com.jxparallel.fx.Fx.Owned) fxPeer()).callSuper("multiply(double)", new Object[] {arg0}) : com.jxparallel.fx.Fx.invoke(fxPeer(), javafx.beans.binding.NumberExpression.class, "multiply", new Class<?>[] {double.class}, arg0)));
    }

    public com.jxparallel.fx.beans.binding.NumberBinding multiply(int arg0) {
        return (com.jxparallel.fx.beans.binding.NumberBinding) com.jxparallel.fx.Fx.jx((fxPeer() instanceof com.jxparallel.fx.Fx.Owned ? ((com.jxparallel.fx.Fx.Owned) fxPeer()).callSuper("multiply(int)", new Object[] {arg0}) : com.jxparallel.fx.Fx.invoke(fxPeer(), javafx.beans.binding.NumberExpression.class, "multiply", new Class<?>[] {int.class}, arg0)));
    }

    public com.jxparallel.fx.beans.binding.NumberBinding multiply(long arg0) {
        return (com.jxparallel.fx.beans.binding.NumberBinding) com.jxparallel.fx.Fx.jx((fxPeer() instanceof com.jxparallel.fx.Fx.Owned ? ((com.jxparallel.fx.Fx.Owned) fxPeer()).callSuper("multiply(long)", new Object[] {arg0}) : com.jxparallel.fx.Fx.invoke(fxPeer(), javafx.beans.binding.NumberExpression.class, "multiply", new Class<?>[] {long.class}, arg0)));
    }

    public com.jxparallel.fx.beans.binding.NumberBinding multiply(float arg0) {
        return (com.jxparallel.fx.beans.binding.NumberBinding) com.jxparallel.fx.Fx.jx((fxPeer() instanceof com.jxparallel.fx.Fx.Owned ? ((com.jxparallel.fx.Fx.Owned) fxPeer()).callSuper("multiply(float)", new Object[] {arg0}) : com.jxparallel.fx.Fx.invoke(fxPeer(), javafx.beans.binding.NumberExpression.class, "multiply", new Class<?>[] {float.class}, arg0)));
    }

    public int intValue() {
        return (Integer) (fxPeer() instanceof com.jxparallel.fx.Fx.Owned ? ((com.jxparallel.fx.Fx.Owned) fxPeer()).callSuper("intValue()", new Object[] {}) : com.jxparallel.fx.Fx.invoke(fxPeer(), javafx.beans.value.ObservableNumberValue.class, "intValue", new Class<?>[] {}));
    }

    public long longValue() {
        return (Long) (fxPeer() instanceof com.jxparallel.fx.Fx.Owned ? ((com.jxparallel.fx.Fx.Owned) fxPeer()).callSuper("longValue()", new Object[] {}) : com.jxparallel.fx.Fx.invoke(fxPeer(), javafx.beans.value.ObservableNumberValue.class, "longValue", new Class<?>[] {}));
    }

    public float floatValue() {
        return (Float) (fxPeer() instanceof com.jxparallel.fx.Fx.Owned ? ((com.jxparallel.fx.Fx.Owned) fxPeer()).callSuper("floatValue()", new Object[] {}) : com.jxparallel.fx.Fx.invoke(fxPeer(), javafx.beans.value.ObservableNumberValue.class, "floatValue", new Class<?>[] {}));
    }

    public double doubleValue() {
        return (Double) (fxPeer() instanceof com.jxparallel.fx.Fx.Owned ? ((com.jxparallel.fx.Fx.Owned) fxPeer()).callSuper("doubleValue()", new Object[] {}) : com.jxparallel.fx.Fx.invoke(fxPeer(), javafx.beans.value.ObservableNumberValue.class, "doubleValue", new Class<?>[] {}));
    }

    public java.lang.Number getValue() {
        return (java.lang.Number) (fxPeer() instanceof com.jxparallel.fx.Fx.Owned ? ((com.jxparallel.fx.Fx.Owned) fxPeer()).callSuper("getValue()", new Object[] {}) : com.jxparallel.fx.Fx.invoke(fxPeer(), javafx.beans.value.ObservableValue.class, "getValue", new Class<?>[] {}));
    }

    public void removeListener(com.jxparallel.fx.beans.value.ChangeListener<? super java.lang.Number> arg0) {
        if (fxPeer() instanceof com.jxparallel.fx.Fx.Owned) {
            ((com.jxparallel.fx.Fx.Owned) fxPeer()).callSuper("removeListener(ChangeListener)", new Object[] {(javafx.beans.value.ChangeListener) com.jxparallel.fx.Fx.fx(arg0)});
        } else {
            com.jxparallel.fx.Fx.invoke(fxPeer(), javafx.beans.value.ObservableValue.class, "removeListener", new Class<?>[] {javafx.beans.value.ChangeListener.class}, (javafx.beans.value.ChangeListener) com.jxparallel.fx.Fx.fx(arg0));
        }
    }

    public void addListener(com.jxparallel.fx.beans.value.ChangeListener<? super java.lang.Number> arg0) {
        if (fxPeer() instanceof com.jxparallel.fx.Fx.Owned) {
            ((com.jxparallel.fx.Fx.Owned) fxPeer()).callSuper("addListener(ChangeListener)", new Object[] {(javafx.beans.value.ChangeListener) com.jxparallel.fx.Fx.fx(arg0)});
        } else {
            com.jxparallel.fx.Fx.invoke(fxPeer(), javafx.beans.value.ObservableValue.class, "addListener", new Class<?>[] {javafx.beans.value.ChangeListener.class}, (javafx.beans.value.ChangeListener) com.jxparallel.fx.Fx.fx(arg0));
        }
    }

    public void removeListener(com.jxparallel.fx.beans.InvalidationListener arg0) {
        if (fxPeer() instanceof com.jxparallel.fx.Fx.Owned) {
            ((com.jxparallel.fx.Fx.Owned) fxPeer()).callSuper("removeListener(InvalidationListener)", new Object[] {(javafx.beans.InvalidationListener) com.jxparallel.fx.Fx.fx(arg0)});
        } else {
            com.jxparallel.fx.Fx.invoke(fxPeer(), javafx.beans.Observable.class, "removeListener", new Class<?>[] {javafx.beans.InvalidationListener.class}, (javafx.beans.InvalidationListener) com.jxparallel.fx.Fx.fx(arg0));
        }
    }

    public void addListener(com.jxparallel.fx.beans.InvalidationListener arg0) {
        if (fxPeer() instanceof com.jxparallel.fx.Fx.Owned) {
            ((com.jxparallel.fx.Fx.Owned) fxPeer()).callSuper("addListener(InvalidationListener)", new Object[] {(javafx.beans.InvalidationListener) com.jxparallel.fx.Fx.fx(arg0)});
        } else {
            com.jxparallel.fx.Fx.invoke(fxPeer(), javafx.beans.Observable.class, "addListener", new Class<?>[] {javafx.beans.InvalidationListener.class}, (javafx.beans.InvalidationListener) com.jxparallel.fx.Fx.fx(arg0));
        }
    }

    /** Called by the peer: runs the JX (possibly overridden) method. */
    public static Object $hook(Object self, String method, Object[] a) {
        NumberExpressionBase jx = (NumberExpressionBase) self;
        try {
        switch (method) {
            case "add(long)":
                return jx.add((Long) a[0]);
            case "add(float)":
                return jx.add((Float) a[0]);
            case "add(double)":
                return jx.add((Double) a[0]);
            case "add(int)":
                return jx.add((Integer) a[0]);
            case "divide(long)":
                return jx.divide((Long) a[0]);
            case "divide(int)":
                return jx.divide((Integer) a[0]);
            case "divide(double)":
                return jx.divide((Double) a[0]);
            case "divide(float)":
                return jx.divide((Float) a[0]);
            case "negate()":
                return jx.negate();
            case "subtract(float)":
                return jx.subtract((Float) a[0]);
            case "subtract(double)":
                return jx.subtract((Double) a[0]);
            case "subtract(long)":
                return jx.subtract((Long) a[0]);
            case "subtract(int)":
                return jx.subtract((Integer) a[0]);
            case "multiply(double)":
                return jx.multiply((Double) a[0]);
            case "multiply(int)":
                return jx.multiply((Integer) a[0]);
            case "multiply(long)":
                return jx.multiply((Long) a[0]);
            case "multiply(float)":
                return jx.multiply((Float) a[0]);
            case "intValue()":
                return (Object) jx.intValue();
            case "longValue()":
                return (Object) jx.longValue();
            case "floatValue()":
                return (Object) jx.floatValue();
            case "doubleValue()":
                return (Object) jx.doubleValue();
            case "getValue()":
                return jx.getValue();
            case "removeListener(ChangeListener)":
                jx.removeListener((com.jxparallel.fx.beans.value.ChangeListener) a[0]);
                return null;
            case "addListener(ChangeListener)":
                jx.addListener((com.jxparallel.fx.beans.value.ChangeListener) a[0]);
                return null;
            case "removeListener(InvalidationListener)":
                jx.removeListener((com.jxparallel.fx.beans.InvalidationListener) a[0]);
                return null;
            case "addListener(InvalidationListener)":
                jx.addListener((com.jxparallel.fx.beans.InvalidationListener) a[0]);
                return null;
            default:
                throw new IllegalArgumentException(method);
        }
        } catch (Exception e) {
            throw com.jxparallel.fx.Fx.sneaky(e);
        }
    }
}
