package com.jxparallel.fx.beans.binding;

/** JXParallel counterpart of {@link javafx.beans.binding.ObjectExpression} (generated by scripts/GenerateFxApi.java). */
@SuppressWarnings({"unchecked", "rawtypes", "deprecation"})
public class ObjectExpression<T> implements com.jxparallel.fx.beans.value.ObservableObjectValue<T>, com.jxparallel.fx.Fx.Backed {
    private final Object fxPeer;

    protected ObjectExpression(com.jxparallel.fx.Fx.Wrap wrap, Object peer) {
        this.fxPeer = peer;
    }

    @Override
    public Object fxPeer() {
        return fxPeer;
    }

    @Override
    public boolean equals(Object o) {
        return o == this || fxPeer().equals(com.jxparallel.fx.Fx.fx(o));
    }

    @Override
    public int hashCode() {
        return fxPeer().hashCode();
    }

    @Override
    public String toString() {
        return fxPeer().toString();
    }

    public ObjectExpression() {
        this(com.jxparallel.fx.Fx.WRAP, new com.jxparallel.fx.peer.beans.binding.ObjectExpression());
        com.jxparallel.fx.Fx.own(fxPeer(), this);
    }

    public com.jxparallel.fx.beans.binding.StringBinding asString() {
        return (com.jxparallel.fx.beans.binding.StringBinding) com.jxparallel.fx.Fx.jx(((javafx.beans.binding.ObjectExpression) fxPeer()).asString());
    }

    public com.jxparallel.fx.beans.binding.StringBinding asString(java.util.Locale arg0, java.lang.String arg1) {
        return (com.jxparallel.fx.beans.binding.StringBinding) com.jxparallel.fx.Fx.jx(((javafx.beans.binding.ObjectExpression) fxPeer()).asString(arg0, arg1));
    }

    public com.jxparallel.fx.beans.binding.StringBinding asString(java.lang.String arg0) {
        return (com.jxparallel.fx.beans.binding.StringBinding) com.jxparallel.fx.Fx.jx(((javafx.beans.binding.ObjectExpression) fxPeer()).asString(arg0));
    }

    public T getValue() {
        return (T) com.jxparallel.fx.Fx.jx(((javafx.beans.binding.ObjectExpression) fxPeer()).getValue());
    }

    public com.jxparallel.fx.beans.binding.BooleanBinding isEqualTo(java.lang.Object arg0) {
        return (com.jxparallel.fx.beans.binding.BooleanBinding) com.jxparallel.fx.Fx.jx(((javafx.beans.binding.ObjectExpression) fxPeer()).isEqualTo((java.lang.Object) com.jxparallel.fx.Fx.fx(arg0)));
    }

    public com.jxparallel.fx.beans.binding.BooleanBinding isEqualTo(com.jxparallel.fx.beans.value.ObservableObjectValue<?> arg0) {
        return (com.jxparallel.fx.beans.binding.BooleanBinding) com.jxparallel.fx.Fx.jx(((javafx.beans.binding.ObjectExpression) fxPeer()).isEqualTo((javafx.beans.value.ObservableObjectValue) com.jxparallel.fx.Fx.fx(arg0)));
    }

    public com.jxparallel.fx.beans.binding.BooleanBinding isNotEqualTo(java.lang.Object arg0) {
        return (com.jxparallel.fx.beans.binding.BooleanBinding) com.jxparallel.fx.Fx.jx(((javafx.beans.binding.ObjectExpression) fxPeer()).isNotEqualTo((java.lang.Object) com.jxparallel.fx.Fx.fx(arg0)));
    }

    public com.jxparallel.fx.beans.binding.BooleanBinding isNotEqualTo(com.jxparallel.fx.beans.value.ObservableObjectValue<?> arg0) {
        return (com.jxparallel.fx.beans.binding.BooleanBinding) com.jxparallel.fx.Fx.jx(((javafx.beans.binding.ObjectExpression) fxPeer()).isNotEqualTo((javafx.beans.value.ObservableObjectValue) com.jxparallel.fx.Fx.fx(arg0)));
    }

    public com.jxparallel.fx.beans.binding.BooleanBinding isNotNull() {
        return (com.jxparallel.fx.beans.binding.BooleanBinding) com.jxparallel.fx.Fx.jx(((javafx.beans.binding.ObjectExpression) fxPeer()).isNotNull());
    }

    public com.jxparallel.fx.beans.binding.BooleanBinding isNull() {
        return (com.jxparallel.fx.beans.binding.BooleanBinding) com.jxparallel.fx.Fx.jx(((javafx.beans.binding.ObjectExpression) fxPeer()).isNull());
    }

    public static <T> com.jxparallel.fx.beans.binding.ObjectExpression<T> objectExpression(com.jxparallel.fx.beans.value.ObservableObjectValue<T> arg0) {
        return (com.jxparallel.fx.beans.binding.ObjectExpression) com.jxparallel.fx.Fx.jx(javafx.beans.binding.ObjectExpression.objectExpression((javafx.beans.value.ObservableObjectValue) com.jxparallel.fx.Fx.fx(arg0)));
    }

    public T get() {
        return (T) com.jxparallel.fx.Fx.jx((fxPeer() instanceof com.jxparallel.fx.Fx.Owned ? ((com.jxparallel.fx.Fx.Owned) fxPeer()).callSuper("get()", new Object[] {}) : com.jxparallel.fx.Fx.invoke(fxPeer(), javafx.beans.value.ObservableObjectValue.class, "get", new Class<?>[] {})));
    }

    public void addListener(com.jxparallel.fx.beans.InvalidationListener arg0) {
        if (fxPeer() instanceof com.jxparallel.fx.Fx.Owned) {
            ((com.jxparallel.fx.Fx.Owned) fxPeer()).callSuper("addListener(InvalidationListener)", new Object[] {(javafx.beans.InvalidationListener) com.jxparallel.fx.Fx.fx(arg0)});
        } else {
            com.jxparallel.fx.Fx.invoke(fxPeer(), javafx.beans.Observable.class, "addListener", new Class<?>[] {javafx.beans.InvalidationListener.class}, (javafx.beans.InvalidationListener) com.jxparallel.fx.Fx.fx(arg0));
        }
    }

    public void removeListener(com.jxparallel.fx.beans.InvalidationListener arg0) {
        if (fxPeer() instanceof com.jxparallel.fx.Fx.Owned) {
            ((com.jxparallel.fx.Fx.Owned) fxPeer()).callSuper("removeListener(InvalidationListener)", new Object[] {(javafx.beans.InvalidationListener) com.jxparallel.fx.Fx.fx(arg0)});
        } else {
            com.jxparallel.fx.Fx.invoke(fxPeer(), javafx.beans.Observable.class, "removeListener", new Class<?>[] {javafx.beans.InvalidationListener.class}, (javafx.beans.InvalidationListener) com.jxparallel.fx.Fx.fx(arg0));
        }
    }

    public void addListener(com.jxparallel.fx.beans.value.ChangeListener<? super T> arg0) {
        if (fxPeer() instanceof com.jxparallel.fx.Fx.Owned) {
            ((com.jxparallel.fx.Fx.Owned) fxPeer()).callSuper("addListener(ChangeListener)", new Object[] {(javafx.beans.value.ChangeListener) com.jxparallel.fx.Fx.fx(arg0)});
        } else {
            com.jxparallel.fx.Fx.invoke(fxPeer(), javafx.beans.value.ObservableValue.class, "addListener", new Class<?>[] {javafx.beans.value.ChangeListener.class}, (javafx.beans.value.ChangeListener) com.jxparallel.fx.Fx.fx(arg0));
        }
    }

    public void removeListener(com.jxparallel.fx.beans.value.ChangeListener<? super T> arg0) {
        if (fxPeer() instanceof com.jxparallel.fx.Fx.Owned) {
            ((com.jxparallel.fx.Fx.Owned) fxPeer()).callSuper("removeListener(ChangeListener)", new Object[] {(javafx.beans.value.ChangeListener) com.jxparallel.fx.Fx.fx(arg0)});
        } else {
            com.jxparallel.fx.Fx.invoke(fxPeer(), javafx.beans.value.ObservableValue.class, "removeListener", new Class<?>[] {javafx.beans.value.ChangeListener.class}, (javafx.beans.value.ChangeListener) com.jxparallel.fx.Fx.fx(arg0));
        }
    }

    /** Called by the peer: runs the JX (possibly overridden) method. */
    public static Object $hook(Object self, String method, Object[] a) {
        ObjectExpression jx = (ObjectExpression) self;
        try {
        switch (method) {
            case "get()":
                return jx.get();
            case "addListener(InvalidationListener)":
                jx.addListener((com.jxparallel.fx.beans.InvalidationListener) a[0]);
                return null;
            case "removeListener(InvalidationListener)":
                jx.removeListener((com.jxparallel.fx.beans.InvalidationListener) a[0]);
                return null;
            case "addListener(ChangeListener)":
                jx.addListener((com.jxparallel.fx.beans.value.ChangeListener) a[0]);
                return null;
            case "removeListener(ChangeListener)":
                jx.removeListener((com.jxparallel.fx.beans.value.ChangeListener) a[0]);
                return null;
            default:
                throw new IllegalArgumentException(method);
        }
        } catch (Exception e) {
            throw com.jxparallel.fx.Fx.sneaky(e);
        }
    }
}
