package com.jxparallel.fx.scene.text;

/** JXParallel counterpart of {@link javafx.scene.text.Text} (generated by scripts/GenerateFxApi.java). */
@SuppressWarnings({"unchecked", "rawtypes", "deprecation"})
@javafx.beans.DefaultProperty("text")
public class Text extends com.jxparallel.fx.scene.shape.Shape {
    protected Text(com.jxparallel.fx.Fx.Wrap wrap, Object peer) {
        super(wrap, peer);
    }

    public Text(java.lang.String arg0) {
        this(com.jxparallel.fx.Fx.WRAP, com.jxparallel.fx.Fx.NATIVE ? com.jxparallel.fx.nativeimpl.Native.create(javafx.scene.text.Text.class, new String[] {null}, new Object[] {arg0}) : new com.jxparallel.fx.peer.scene.text.Text(arg0));
        com.jxparallel.fx.Fx.own(fxPeer(), this);
    }

    public Text() {
        this(com.jxparallel.fx.Fx.WRAP, com.jxparallel.fx.Fx.NATIVE ? com.jxparallel.fx.nativeimpl.Native.create(javafx.scene.text.Text.class, new String[] {}, new Object[] {}) : new com.jxparallel.fx.peer.scene.text.Text());
        com.jxparallel.fx.Fx.own(fxPeer(), this);
    }

    public Text(double arg0, double arg1, java.lang.String arg2) {
        this(com.jxparallel.fx.Fx.WRAP, com.jxparallel.fx.Fx.NATIVE ? com.jxparallel.fx.nativeimpl.Native.create(javafx.scene.text.Text.class, new String[] {null, null, null}, new Object[] {arg0, arg1, arg2}) : new com.jxparallel.fx.peer.scene.text.Text(arg0, arg1, arg2));
        com.jxparallel.fx.Fx.own(fxPeer(), this);
    }

    public com.jxparallel.fx.beans.property.ReadOnlyDoubleProperty baselineOffsetProperty() {
        if (com.jxparallel.fx.Fx.NATIVE) {
            return (com.jxparallel.fx.beans.property.ReadOnlyDoubleProperty) com.jxparallel.fx.nativeimpl.Native.call(this, com.jxparallel.fx.scene.text.Text.class, "baselineOffsetProperty", new Class<?>[] {}, com.jxparallel.fx.beans.property.ReadOnlyDoubleProperty.class);
        }
        return (com.jxparallel.fx.beans.property.ReadOnlyDoubleProperty) com.jxparallel.fx.Fx.jx(((javafx.scene.text.Text) fxPeer()).baselineOffsetProperty());
    }

    public com.jxparallel.fx.beans.property.ObjectProperty<com.jxparallel.fx.scene.text.TextBoundsType> boundsTypeProperty() {
        if (com.jxparallel.fx.Fx.NATIVE) {
            return (com.jxparallel.fx.beans.property.ObjectProperty) com.jxparallel.fx.nativeimpl.Native.call(this, com.jxparallel.fx.scene.text.Text.class, "boundsTypeProperty", new Class<?>[] {}, com.jxparallel.fx.beans.property.ObjectProperty.class);
        }
        return (com.jxparallel.fx.beans.property.ObjectProperty) com.jxparallel.fx.Fx.jx(((javafx.scene.text.Text) fxPeer()).boundsTypeProperty());
    }

    public com.jxparallel.fx.beans.property.ObjectProperty<com.jxparallel.fx.scene.text.Font> fontProperty() {
        if (com.jxparallel.fx.Fx.NATIVE) {
            return (com.jxparallel.fx.beans.property.ObjectProperty) com.jxparallel.fx.nativeimpl.Native.call(this, com.jxparallel.fx.scene.text.Text.class, "fontProperty", new Class<?>[] {}, com.jxparallel.fx.beans.property.ObjectProperty.class);
        }
        return (com.jxparallel.fx.beans.property.ObjectProperty) com.jxparallel.fx.Fx.jx(((javafx.scene.text.Text) fxPeer()).fontProperty());
    }

    public com.jxparallel.fx.beans.property.ObjectProperty<com.jxparallel.fx.scene.text.FontSmoothingType> fontSmoothingTypeProperty() {
        if (com.jxparallel.fx.Fx.NATIVE) {
            return (com.jxparallel.fx.beans.property.ObjectProperty) com.jxparallel.fx.nativeimpl.Native.call(this, com.jxparallel.fx.scene.text.Text.class, "fontSmoothingTypeProperty", new Class<?>[] {}, com.jxparallel.fx.beans.property.ObjectProperty.class);
        }
        return (com.jxparallel.fx.beans.property.ObjectProperty) com.jxparallel.fx.Fx.jx(((javafx.scene.text.Text) fxPeer()).fontSmoothingTypeProperty());
    }

    public double getBaselineOffset() {
        if (com.jxparallel.fx.Fx.NATIVE) {
            return (Double) com.jxparallel.fx.nativeimpl.Native.call(this, com.jxparallel.fx.scene.text.Text.class, "getBaselineOffset", new Class<?>[] {}, double.class);
        }
        return ((javafx.scene.text.Text) fxPeer()).getBaselineOffset();
    }

    public com.jxparallel.fx.scene.text.TextBoundsType getBoundsType() {
        if (com.jxparallel.fx.Fx.NATIVE) {
            return (com.jxparallel.fx.scene.text.TextBoundsType) com.jxparallel.fx.nativeimpl.Native.call(this, com.jxparallel.fx.scene.text.Text.class, "getBoundsType", new Class<?>[] {}, com.jxparallel.fx.scene.text.TextBoundsType.class);
        }
        return (com.jxparallel.fx.scene.text.TextBoundsType) com.jxparallel.fx.Fx.jx(((javafx.scene.text.Text) fxPeer()).getBoundsType());
    }

    public static java.util.List<javafx.css.CssMetaData<? extends javafx.css.Styleable, ?>> getClassCssMetaData() {
        if (com.jxparallel.fx.Fx.NATIVE) {
            return (java.util.List) com.jxparallel.fx.nativeimpl.Native.call(null, com.jxparallel.fx.scene.text.Text.class, "getClassCssMetaData", new Class<?>[] {}, java.util.List.class);
        }
        return javafx.scene.text.Text.getClassCssMetaData();
    }

    public java.util.List<javafx.css.CssMetaData<? extends javafx.css.Styleable, ?>> getCssMetaData() {
        if (com.jxparallel.fx.Fx.NATIVE) {
            return (java.util.List) com.jxparallel.fx.nativeimpl.Native.call(this, com.jxparallel.fx.scene.text.Text.class, "getCssMetaData", new Class<?>[] {}, java.util.List.class);
        }
        return ((javafx.scene.text.Text) fxPeer()).getCssMetaData();
    }

    public com.jxparallel.fx.scene.text.Font getFont() {
        if (com.jxparallel.fx.Fx.NATIVE) {
            return (com.jxparallel.fx.scene.text.Font) com.jxparallel.fx.nativeimpl.Native.call(this, com.jxparallel.fx.scene.text.Text.class, "getFont", new Class<?>[] {}, com.jxparallel.fx.scene.text.Font.class);
        }
        return (com.jxparallel.fx.scene.text.Font) com.jxparallel.fx.Fx.jx(((javafx.scene.text.Text) fxPeer()).getFont());
    }

    public com.jxparallel.fx.scene.text.FontSmoothingType getFontSmoothingType() {
        if (com.jxparallel.fx.Fx.NATIVE) {
            return (com.jxparallel.fx.scene.text.FontSmoothingType) com.jxparallel.fx.nativeimpl.Native.call(this, com.jxparallel.fx.scene.text.Text.class, "getFontSmoothingType", new Class<?>[] {}, com.jxparallel.fx.scene.text.FontSmoothingType.class);
        }
        return (com.jxparallel.fx.scene.text.FontSmoothingType) com.jxparallel.fx.Fx.jx(((javafx.scene.text.Text) fxPeer()).getFontSmoothingType());
    }

    public int getImpl_caretPosition() {
        if (com.jxparallel.fx.Fx.NATIVE) {
            return (Integer) com.jxparallel.fx.nativeimpl.Native.call(this, com.jxparallel.fx.scene.text.Text.class, "getImpl_caretPosition", new Class<?>[] {}, int.class);
        }
        return ((javafx.scene.text.Text) fxPeer()).getImpl_caretPosition();
    }

    public javafx.scene.shape.PathElement[] getImpl_caretShape() {
        if (com.jxparallel.fx.Fx.NATIVE) {
            return (javafx.scene.shape.PathElement[]) com.jxparallel.fx.nativeimpl.Native.call(this, com.jxparallel.fx.scene.text.Text.class, "getImpl_caretShape", new Class<?>[] {}, javafx.scene.shape.PathElement[].class);
        }
        return ((javafx.scene.text.Text) fxPeer()).getImpl_caretShape();
    }

    public int getImpl_selectionEnd() {
        if (com.jxparallel.fx.Fx.NATIVE) {
            return (Integer) com.jxparallel.fx.nativeimpl.Native.call(this, com.jxparallel.fx.scene.text.Text.class, "getImpl_selectionEnd", new Class<?>[] {}, int.class);
        }
        return ((javafx.scene.text.Text) fxPeer()).getImpl_selectionEnd();
    }

    public javafx.scene.shape.PathElement[] getImpl_selectionShape() {
        if (com.jxparallel.fx.Fx.NATIVE) {
            return (javafx.scene.shape.PathElement[]) com.jxparallel.fx.nativeimpl.Native.call(this, com.jxparallel.fx.scene.text.Text.class, "getImpl_selectionShape", new Class<?>[] {}, javafx.scene.shape.PathElement[].class);
        }
        return ((javafx.scene.text.Text) fxPeer()).getImpl_selectionShape();
    }

    public int getImpl_selectionStart() {
        if (com.jxparallel.fx.Fx.NATIVE) {
            return (Integer) com.jxparallel.fx.nativeimpl.Native.call(this, com.jxparallel.fx.scene.text.Text.class, "getImpl_selectionStart", new Class<?>[] {}, int.class);
        }
        return ((javafx.scene.text.Text) fxPeer()).getImpl_selectionStart();
    }

    public double getLineSpacing() {
        if (com.jxparallel.fx.Fx.NATIVE) {
            return (Double) com.jxparallel.fx.nativeimpl.Native.call(this, com.jxparallel.fx.scene.text.Text.class, "getLineSpacing", new Class<?>[] {}, double.class);
        }
        return ((javafx.scene.text.Text) fxPeer()).getLineSpacing();
    }

    public java.lang.String getText() {
        if (com.jxparallel.fx.Fx.NATIVE) {
            return (java.lang.String) com.jxparallel.fx.nativeimpl.Native.call(this, com.jxparallel.fx.scene.text.Text.class, "getText", new Class<?>[] {}, java.lang.String.class);
        }
        return ((javafx.scene.text.Text) fxPeer()).getText();
    }

    public com.jxparallel.fx.scene.text.TextAlignment getTextAlignment() {
        if (com.jxparallel.fx.Fx.NATIVE) {
            return (com.jxparallel.fx.scene.text.TextAlignment) com.jxparallel.fx.nativeimpl.Native.call(this, com.jxparallel.fx.scene.text.Text.class, "getTextAlignment", new Class<?>[] {}, com.jxparallel.fx.scene.text.TextAlignment.class);
        }
        return (com.jxparallel.fx.scene.text.TextAlignment) com.jxparallel.fx.Fx.jx(((javafx.scene.text.Text) fxPeer()).getTextAlignment());
    }

    public com.jxparallel.fx.geometry.VPos getTextOrigin() {
        if (com.jxparallel.fx.Fx.NATIVE) {
            return (com.jxparallel.fx.geometry.VPos) com.jxparallel.fx.nativeimpl.Native.call(this, com.jxparallel.fx.scene.text.Text.class, "getTextOrigin", new Class<?>[] {}, com.jxparallel.fx.geometry.VPos.class);
        }
        return (com.jxparallel.fx.geometry.VPos) com.jxparallel.fx.Fx.jx(((javafx.scene.text.Text) fxPeer()).getTextOrigin());
    }

    public double getWrappingWidth() {
        if (com.jxparallel.fx.Fx.NATIVE) {
            return (Double) com.jxparallel.fx.nativeimpl.Native.call(this, com.jxparallel.fx.scene.text.Text.class, "getWrappingWidth", new Class<?>[] {}, double.class);
        }
        return ((javafx.scene.text.Text) fxPeer()).getWrappingWidth();
    }

    public double getX() {
        if (com.jxparallel.fx.Fx.NATIVE) {
            return (Double) com.jxparallel.fx.nativeimpl.Native.call(this, com.jxparallel.fx.scene.text.Text.class, "getX", new Class<?>[] {}, double.class);
        }
        return ((javafx.scene.text.Text) fxPeer()).getX();
    }

    public double getY() {
        if (com.jxparallel.fx.Fx.NATIVE) {
            return (Double) com.jxparallel.fx.nativeimpl.Native.call(this, com.jxparallel.fx.scene.text.Text.class, "getY", new Class<?>[] {}, double.class);
        }
        return ((javafx.scene.text.Text) fxPeer()).getY();
    }

    public com.jxparallel.fx.beans.property.BooleanProperty impl_caretBiasProperty() {
        if (com.jxparallel.fx.Fx.NATIVE) {
            return (com.jxparallel.fx.beans.property.BooleanProperty) com.jxparallel.fx.nativeimpl.Native.call(this, com.jxparallel.fx.scene.text.Text.class, "impl_caretBiasProperty", new Class<?>[] {}, com.jxparallel.fx.beans.property.BooleanProperty.class);
        }
        return (com.jxparallel.fx.beans.property.BooleanProperty) com.jxparallel.fx.Fx.jx(((javafx.scene.text.Text) fxPeer()).impl_caretBiasProperty());
    }

    public com.jxparallel.fx.beans.property.IntegerProperty impl_caretPositionProperty() {
        if (com.jxparallel.fx.Fx.NATIVE) {
            return (com.jxparallel.fx.beans.property.IntegerProperty) com.jxparallel.fx.nativeimpl.Native.call(this, com.jxparallel.fx.scene.text.Text.class, "impl_caretPositionProperty", new Class<?>[] {}, com.jxparallel.fx.beans.property.IntegerProperty.class);
        }
        return (com.jxparallel.fx.beans.property.IntegerProperty) com.jxparallel.fx.Fx.jx(((javafx.scene.text.Text) fxPeer()).impl_caretPositionProperty());
    }

    public void impl_displaySoftwareKeyboard(boolean arg0) {
        if (com.jxparallel.fx.Fx.NATIVE) {
            com.jxparallel.fx.nativeimpl.Native.call(this, com.jxparallel.fx.scene.text.Text.class, "impl_displaySoftwareKeyboard", new Class<?>[] {boolean.class}, void.class, arg0);
            return;
        }
        ((javafx.scene.text.Text) fxPeer()).impl_displaySoftwareKeyboard(arg0);
    }

    public com.jxparallel.fx.beans.property.IntegerProperty impl_selectionEndProperty() {
        if (com.jxparallel.fx.Fx.NATIVE) {
            return (com.jxparallel.fx.beans.property.IntegerProperty) com.jxparallel.fx.nativeimpl.Native.call(this, com.jxparallel.fx.scene.text.Text.class, "impl_selectionEndProperty", new Class<?>[] {}, com.jxparallel.fx.beans.property.IntegerProperty.class);
        }
        return (com.jxparallel.fx.beans.property.IntegerProperty) com.jxparallel.fx.Fx.jx(((javafx.scene.text.Text) fxPeer()).impl_selectionEndProperty());
    }

    public com.jxparallel.fx.beans.property.ObjectProperty<com.jxparallel.fx.scene.paint.Paint> impl_selectionFillProperty() {
        if (com.jxparallel.fx.Fx.NATIVE) {
            return (com.jxparallel.fx.beans.property.ObjectProperty) com.jxparallel.fx.nativeimpl.Native.call(this, com.jxparallel.fx.scene.text.Text.class, "impl_selectionFillProperty", new Class<?>[] {}, com.jxparallel.fx.beans.property.ObjectProperty.class);
        }
        return (com.jxparallel.fx.beans.property.ObjectProperty) com.jxparallel.fx.Fx.jx(((javafx.scene.text.Text) fxPeer()).impl_selectionFillProperty());
    }

    public com.jxparallel.fx.beans.property.IntegerProperty impl_selectionStartProperty() {
        if (com.jxparallel.fx.Fx.NATIVE) {
            return (com.jxparallel.fx.beans.property.IntegerProperty) com.jxparallel.fx.nativeimpl.Native.call(this, com.jxparallel.fx.scene.text.Text.class, "impl_selectionStartProperty", new Class<?>[] {}, com.jxparallel.fx.beans.property.IntegerProperty.class);
        }
        return (com.jxparallel.fx.beans.property.IntegerProperty) com.jxparallel.fx.Fx.jx(((javafx.scene.text.Text) fxPeer()).impl_selectionStartProperty());
    }

    public void impl_updatePeer() {
        if (com.jxparallel.fx.Fx.NATIVE) {
            com.jxparallel.fx.nativeimpl.Native.call(this, com.jxparallel.fx.scene.text.Text.class, "impl_updatePeer", new Class<?>[] {}, void.class);
            return;
        }
        ((javafx.scene.text.Text) fxPeer()).impl_updatePeer();
    }

    public boolean isImpl_caretBias() {
        if (com.jxparallel.fx.Fx.NATIVE) {
            return (Boolean) com.jxparallel.fx.nativeimpl.Native.call(this, com.jxparallel.fx.scene.text.Text.class, "isImpl_caretBias", new Class<?>[] {}, boolean.class);
        }
        return ((javafx.scene.text.Text) fxPeer()).isImpl_caretBias();
    }

    public boolean isStrikethrough() {
        if (com.jxparallel.fx.Fx.NATIVE) {
            return (Boolean) com.jxparallel.fx.nativeimpl.Native.call(this, com.jxparallel.fx.scene.text.Text.class, "isStrikethrough", new Class<?>[] {}, boolean.class);
        }
        return ((javafx.scene.text.Text) fxPeer()).isStrikethrough();
    }

    public boolean isUnderline() {
        if (com.jxparallel.fx.Fx.NATIVE) {
            return (Boolean) com.jxparallel.fx.nativeimpl.Native.call(this, com.jxparallel.fx.scene.text.Text.class, "isUnderline", new Class<?>[] {}, boolean.class);
        }
        return ((javafx.scene.text.Text) fxPeer()).isUnderline();
    }

    public com.jxparallel.fx.beans.property.DoubleProperty lineSpacingProperty() {
        if (com.jxparallel.fx.Fx.NATIVE) {
            return (com.jxparallel.fx.beans.property.DoubleProperty) com.jxparallel.fx.nativeimpl.Native.call(this, com.jxparallel.fx.scene.text.Text.class, "lineSpacingProperty", new Class<?>[] {}, com.jxparallel.fx.beans.property.DoubleProperty.class);
        }
        return (com.jxparallel.fx.beans.property.DoubleProperty) com.jxparallel.fx.Fx.jx(((javafx.scene.text.Text) fxPeer()).lineSpacingProperty());
    }

    public java.lang.Object queryAccessibleAttribute(com.jxparallel.fx.scene.AccessibleAttribute arg0, java.lang.Object... arg1) {
        if (com.jxparallel.fx.Fx.NATIVE) {
            return (java.lang.Object) com.jxparallel.fx.nativeimpl.Native.call(this, com.jxparallel.fx.scene.text.Text.class, "queryAccessibleAttribute", new Class<?>[] {com.jxparallel.fx.scene.AccessibleAttribute.class, java.lang.Object[].class}, java.lang.Object.class, arg0, arg1);
        }
        return (java.lang.Object) com.jxparallel.fx.Fx.jx(((javafx.scene.text.Text) fxPeer()).queryAccessibleAttribute((javafx.scene.AccessibleAttribute) com.jxparallel.fx.Fx.fx(arg0), (java.lang.Object[]) com.jxparallel.fx.Fx.fxArray(arg1, java.lang.Object.class)));
    }

    public void setBoundsType(com.jxparallel.fx.scene.text.TextBoundsType arg0) {
        if (com.jxparallel.fx.Fx.NATIVE) {
            com.jxparallel.fx.nativeimpl.Native.call(this, com.jxparallel.fx.scene.text.Text.class, "setBoundsType", new Class<?>[] {com.jxparallel.fx.scene.text.TextBoundsType.class}, void.class, arg0);
            return;
        }
        ((javafx.scene.text.Text) fxPeer()).setBoundsType((javafx.scene.text.TextBoundsType) com.jxparallel.fx.Fx.fx(arg0));
    }

    public void setFont(com.jxparallel.fx.scene.text.Font arg0) {
        if (com.jxparallel.fx.Fx.NATIVE) {
            com.jxparallel.fx.nativeimpl.Native.call(this, com.jxparallel.fx.scene.text.Text.class, "setFont", new Class<?>[] {com.jxparallel.fx.scene.text.Font.class}, void.class, arg0);
            return;
        }
        ((javafx.scene.text.Text) fxPeer()).setFont((javafx.scene.text.Font) com.jxparallel.fx.Fx.fx(arg0));
    }

    public void setFontSmoothingType(com.jxparallel.fx.scene.text.FontSmoothingType arg0) {
        if (com.jxparallel.fx.Fx.NATIVE) {
            com.jxparallel.fx.nativeimpl.Native.call(this, com.jxparallel.fx.scene.text.Text.class, "setFontSmoothingType", new Class<?>[] {com.jxparallel.fx.scene.text.FontSmoothingType.class}, void.class, arg0);
            return;
        }
        ((javafx.scene.text.Text) fxPeer()).setFontSmoothingType((javafx.scene.text.FontSmoothingType) com.jxparallel.fx.Fx.fx(arg0));
    }

    public void setImpl_caretBias(boolean arg0) {
        if (com.jxparallel.fx.Fx.NATIVE) {
            com.jxparallel.fx.nativeimpl.Native.call(this, com.jxparallel.fx.scene.text.Text.class, "setImpl_caretBias", new Class<?>[] {boolean.class}, void.class, arg0);
            return;
        }
        ((javafx.scene.text.Text) fxPeer()).setImpl_caretBias(arg0);
    }

    public void setImpl_caretPosition(int arg0) {
        if (com.jxparallel.fx.Fx.NATIVE) {
            com.jxparallel.fx.nativeimpl.Native.call(this, com.jxparallel.fx.scene.text.Text.class, "setImpl_caretPosition", new Class<?>[] {int.class}, void.class, arg0);
            return;
        }
        ((javafx.scene.text.Text) fxPeer()).setImpl_caretPosition(arg0);
    }

    public void setImpl_selectionEnd(int arg0) {
        if (com.jxparallel.fx.Fx.NATIVE) {
            com.jxparallel.fx.nativeimpl.Native.call(this, com.jxparallel.fx.scene.text.Text.class, "setImpl_selectionEnd", new Class<?>[] {int.class}, void.class, arg0);
            return;
        }
        ((javafx.scene.text.Text) fxPeer()).setImpl_selectionEnd(arg0);
    }

    public void setImpl_selectionStart(int arg0) {
        if (com.jxparallel.fx.Fx.NATIVE) {
            com.jxparallel.fx.nativeimpl.Native.call(this, com.jxparallel.fx.scene.text.Text.class, "setImpl_selectionStart", new Class<?>[] {int.class}, void.class, arg0);
            return;
        }
        ((javafx.scene.text.Text) fxPeer()).setImpl_selectionStart(arg0);
    }

    public void setLineSpacing(double arg0) {
        if (com.jxparallel.fx.Fx.NATIVE) {
            com.jxparallel.fx.nativeimpl.Native.call(this, com.jxparallel.fx.scene.text.Text.class, "setLineSpacing", new Class<?>[] {double.class}, void.class, arg0);
            return;
        }
        ((javafx.scene.text.Text) fxPeer()).setLineSpacing(arg0);
    }

    public void setStrikethrough(boolean arg0) {
        if (com.jxparallel.fx.Fx.NATIVE) {
            com.jxparallel.fx.nativeimpl.Native.call(this, com.jxparallel.fx.scene.text.Text.class, "setStrikethrough", new Class<?>[] {boolean.class}, void.class, arg0);
            return;
        }
        ((javafx.scene.text.Text) fxPeer()).setStrikethrough(arg0);
    }

    public void setText(java.lang.String arg0) {
        if (com.jxparallel.fx.Fx.NATIVE) {
            com.jxparallel.fx.nativeimpl.Native.call(this, com.jxparallel.fx.scene.text.Text.class, "setText", new Class<?>[] {java.lang.String.class}, void.class, arg0);
            return;
        }
        ((javafx.scene.text.Text) fxPeer()).setText(arg0);
    }

    public void setTextAlignment(com.jxparallel.fx.scene.text.TextAlignment arg0) {
        if (com.jxparallel.fx.Fx.NATIVE) {
            com.jxparallel.fx.nativeimpl.Native.call(this, com.jxparallel.fx.scene.text.Text.class, "setTextAlignment", new Class<?>[] {com.jxparallel.fx.scene.text.TextAlignment.class}, void.class, arg0);
            return;
        }
        ((javafx.scene.text.Text) fxPeer()).setTextAlignment((javafx.scene.text.TextAlignment) com.jxparallel.fx.Fx.fx(arg0));
    }

    public void setTextOrigin(com.jxparallel.fx.geometry.VPos arg0) {
        if (com.jxparallel.fx.Fx.NATIVE) {
            com.jxparallel.fx.nativeimpl.Native.call(this, com.jxparallel.fx.scene.text.Text.class, "setTextOrigin", new Class<?>[] {com.jxparallel.fx.geometry.VPos.class}, void.class, arg0);
            return;
        }
        ((javafx.scene.text.Text) fxPeer()).setTextOrigin((javafx.geometry.VPos) com.jxparallel.fx.Fx.fx(arg0));
    }

    public void setUnderline(boolean arg0) {
        if (com.jxparallel.fx.Fx.NATIVE) {
            com.jxparallel.fx.nativeimpl.Native.call(this, com.jxparallel.fx.scene.text.Text.class, "setUnderline", new Class<?>[] {boolean.class}, void.class, arg0);
            return;
        }
        ((javafx.scene.text.Text) fxPeer()).setUnderline(arg0);
    }

    public void setWrappingWidth(double arg0) {
        if (com.jxparallel.fx.Fx.NATIVE) {
            com.jxparallel.fx.nativeimpl.Native.call(this, com.jxparallel.fx.scene.text.Text.class, "setWrappingWidth", new Class<?>[] {double.class}, void.class, arg0);
            return;
        }
        ((javafx.scene.text.Text) fxPeer()).setWrappingWidth(arg0);
    }

    public void setX(double arg0) {
        if (com.jxparallel.fx.Fx.NATIVE) {
            com.jxparallel.fx.nativeimpl.Native.call(this, com.jxparallel.fx.scene.text.Text.class, "setX", new Class<?>[] {double.class}, void.class, arg0);
            return;
        }
        ((javafx.scene.text.Text) fxPeer()).setX(arg0);
    }

    public void setY(double arg0) {
        if (com.jxparallel.fx.Fx.NATIVE) {
            com.jxparallel.fx.nativeimpl.Native.call(this, com.jxparallel.fx.scene.text.Text.class, "setY", new Class<?>[] {double.class}, void.class, arg0);
            return;
        }
        ((javafx.scene.text.Text) fxPeer()).setY(arg0);
    }

    public com.jxparallel.fx.beans.property.BooleanProperty strikethroughProperty() {
        if (com.jxparallel.fx.Fx.NATIVE) {
            return (com.jxparallel.fx.beans.property.BooleanProperty) com.jxparallel.fx.nativeimpl.Native.call(this, com.jxparallel.fx.scene.text.Text.class, "strikethroughProperty", new Class<?>[] {}, com.jxparallel.fx.beans.property.BooleanProperty.class);
        }
        return (com.jxparallel.fx.beans.property.BooleanProperty) com.jxparallel.fx.Fx.jx(((javafx.scene.text.Text) fxPeer()).strikethroughProperty());
    }

    public com.jxparallel.fx.beans.property.ObjectProperty<com.jxparallel.fx.scene.text.TextAlignment> textAlignmentProperty() {
        if (com.jxparallel.fx.Fx.NATIVE) {
            return (com.jxparallel.fx.beans.property.ObjectProperty) com.jxparallel.fx.nativeimpl.Native.call(this, com.jxparallel.fx.scene.text.Text.class, "textAlignmentProperty", new Class<?>[] {}, com.jxparallel.fx.beans.property.ObjectProperty.class);
        }
        return (com.jxparallel.fx.beans.property.ObjectProperty) com.jxparallel.fx.Fx.jx(((javafx.scene.text.Text) fxPeer()).textAlignmentProperty());
    }

    public com.jxparallel.fx.beans.property.ObjectProperty<com.jxparallel.fx.geometry.VPos> textOriginProperty() {
        if (com.jxparallel.fx.Fx.NATIVE) {
            return (com.jxparallel.fx.beans.property.ObjectProperty) com.jxparallel.fx.nativeimpl.Native.call(this, com.jxparallel.fx.scene.text.Text.class, "textOriginProperty", new Class<?>[] {}, com.jxparallel.fx.beans.property.ObjectProperty.class);
        }
        return (com.jxparallel.fx.beans.property.ObjectProperty) com.jxparallel.fx.Fx.jx(((javafx.scene.text.Text) fxPeer()).textOriginProperty());
    }

    public com.jxparallel.fx.beans.property.StringProperty textProperty() {
        if (com.jxparallel.fx.Fx.NATIVE) {
            return (com.jxparallel.fx.beans.property.StringProperty) com.jxparallel.fx.nativeimpl.Native.call(this, com.jxparallel.fx.scene.text.Text.class, "textProperty", new Class<?>[] {}, com.jxparallel.fx.beans.property.StringProperty.class);
        }
        return (com.jxparallel.fx.beans.property.StringProperty) com.jxparallel.fx.Fx.jx(((javafx.scene.text.Text) fxPeer()).textProperty());
    }

    public com.jxparallel.fx.beans.property.BooleanProperty underlineProperty() {
        if (com.jxparallel.fx.Fx.NATIVE) {
            return (com.jxparallel.fx.beans.property.BooleanProperty) com.jxparallel.fx.nativeimpl.Native.call(this, com.jxparallel.fx.scene.text.Text.class, "underlineProperty", new Class<?>[] {}, com.jxparallel.fx.beans.property.BooleanProperty.class);
        }
        return (com.jxparallel.fx.beans.property.BooleanProperty) com.jxparallel.fx.Fx.jx(((javafx.scene.text.Text) fxPeer()).underlineProperty());
    }

    public boolean usesMirroring() {
        if (com.jxparallel.fx.Fx.NATIVE) {
            return (Boolean) com.jxparallel.fx.nativeimpl.Native.call(this, com.jxparallel.fx.scene.text.Text.class, "usesMirroring", new Class<?>[] {}, boolean.class);
        }
        return ((javafx.scene.text.Text) fxPeer()).usesMirroring();
    }

    public com.jxparallel.fx.beans.property.DoubleProperty wrappingWidthProperty() {
        if (com.jxparallel.fx.Fx.NATIVE) {
            return (com.jxparallel.fx.beans.property.DoubleProperty) com.jxparallel.fx.nativeimpl.Native.call(this, com.jxparallel.fx.scene.text.Text.class, "wrappingWidthProperty", new Class<?>[] {}, com.jxparallel.fx.beans.property.DoubleProperty.class);
        }
        return (com.jxparallel.fx.beans.property.DoubleProperty) com.jxparallel.fx.Fx.jx(((javafx.scene.text.Text) fxPeer()).wrappingWidthProperty());
    }

    public com.jxparallel.fx.beans.property.DoubleProperty xProperty() {
        if (com.jxparallel.fx.Fx.NATIVE) {
            return (com.jxparallel.fx.beans.property.DoubleProperty) com.jxparallel.fx.nativeimpl.Native.call(this, com.jxparallel.fx.scene.text.Text.class, "xProperty", new Class<?>[] {}, com.jxparallel.fx.beans.property.DoubleProperty.class);
        }
        return (com.jxparallel.fx.beans.property.DoubleProperty) com.jxparallel.fx.Fx.jx(((javafx.scene.text.Text) fxPeer()).xProperty());
    }

    public com.jxparallel.fx.beans.property.DoubleProperty yProperty() {
        if (com.jxparallel.fx.Fx.NATIVE) {
            return (com.jxparallel.fx.beans.property.DoubleProperty) com.jxparallel.fx.nativeimpl.Native.call(this, com.jxparallel.fx.scene.text.Text.class, "yProperty", new Class<?>[] {}, com.jxparallel.fx.beans.property.DoubleProperty.class);
        }
        return (com.jxparallel.fx.beans.property.DoubleProperty) com.jxparallel.fx.Fx.jx(((javafx.scene.text.Text) fxPeer()).yProperty());
    }
}
