package com.jxparallel.fx.peer.scene.control;

/** JavaFX peer of {@link com.jxparallel.fx.scene.control.Alert}; forwards overridable methods to it (generated by scripts/GenerateFxApi.java). */
@SuppressWarnings({"unchecked", "rawtypes", "deprecation", "serial"})
public class Alert extends javafx.scene.control.Alert implements com.jxparallel.fx.Fx.Owned {
    private Object jxOwner;

    public Alert(@javafx.beans.NamedArg(value = "alertType") javafx.scene.control.Alert.AlertType arg0) {
        super(arg0);
    }

    public Alert(@javafx.beans.NamedArg(value = "alertType") javafx.scene.control.Alert.AlertType arg0, @javafx.beans.NamedArg(value = "contentText") java.lang.String arg1, javafx.scene.control.ButtonType... arg2) {
        super(arg0, arg1, arg2);
    }

    @Override
    public Object jxOwner() {
        return jxOwner;
    }

    @Override
    public void jxOwner(Object owner) {
        this.jxOwner = owner;
    }

    @Override
    public Object callSuper(String method, Object[] a) {
        try {
        switch (method) {
            default:
                throw new AbstractMethodError(method);
        }
        } catch (Exception e) {
            throw com.jxparallel.fx.Fx.sneaky(e);
        }
    }
}
