package com.jxparallel.fx.peer.scene.control;

/** JavaFX peer of {@link com.jxparallel.fx.scene.control.TableView.TableViewSelectionModel}; forwards overridable methods to it (generated by scripts/GenerateFxApi.java). */
@SuppressWarnings({"unchecked", "rawtypes", "deprecation", "serial"})
public class TableView_TableViewSelectionModel<S> extends javafx.scene.control.TableView.TableViewSelectionModel<S> implements com.jxparallel.fx.Fx.Owned {
    private Object jxOwner;

    public TableView_TableViewSelectionModel(javafx.scene.control.TableView<S> arg0) {
        super(arg0);
    }

    @Override
    public Object jxOwner() {
        return jxOwner;
    }

    @Override
    public void jxOwner(Object owner) {
        this.jxOwner = owner;
    }

    @Override
    public void select(int arg0, javafx.scene.control.TableColumn<S, ?> arg1) {
        if (jxOwner == null) {
            throw new IllegalStateException("select before the JX object exists");
        }
        com.jxparallel.fx.scene.control.TableView.TableViewSelectionModel.$hook(jxOwner, "select(int,TableColumn)", new Object[] {arg0, com.jxparallel.fx.Fx.jx(arg1)});
    }

    @Override
    public boolean isSelected(int arg0, javafx.scene.control.TableColumn<S, ?> arg1) {
        if (jxOwner == null) {
            throw new IllegalStateException("isSelected before the JX object exists");
        }
        return (Boolean) com.jxparallel.fx.Fx.fx(com.jxparallel.fx.scene.control.TableView.TableViewSelectionModel.$hook(jxOwner, "isSelected(int,TableColumn)", new Object[] {arg0, com.jxparallel.fx.Fx.jx(arg1)}));
    }

    @Override
    public void clearSelection(int arg0, javafx.scene.control.TableColumn<S, ?> arg1) {
        if (jxOwner == null) {
            throw new IllegalStateException("clearSelection before the JX object exists");
        }
        com.jxparallel.fx.scene.control.TableView.TableViewSelectionModel.$hook(jxOwner, "clearSelection(int,TableColumn)", new Object[] {arg0, com.jxparallel.fx.Fx.jx(arg1)});
    }

    @Override
    public void clearAndSelect(int arg0, javafx.scene.control.TableColumn<S, ?> arg1) {
        if (jxOwner == null) {
            throw new IllegalStateException("clearAndSelect before the JX object exists");
        }
        com.jxparallel.fx.scene.control.TableView.TableViewSelectionModel.$hook(jxOwner, "clearAndSelect(int,TableColumn)", new Object[] {arg0, com.jxparallel.fx.Fx.jx(arg1)});
    }

    @Override
    public javafx.collections.ObservableList<javafx.scene.control.TablePosition> getSelectedCells() {
        if (jxOwner == null) {
            throw new IllegalStateException("getSelectedCells before the JX object exists");
        }
        return (javafx.collections.ObservableList<javafx.scene.control.TablePosition>) com.jxparallel.fx.Fx.fx(com.jxparallel.fx.scene.control.TableView.TableViewSelectionModel.$hook(jxOwner, "getSelectedCells()", new Object[] {}));
    }

    @Override
    public void selectLeftCell() {
        if (jxOwner == null) {
            throw new IllegalStateException("selectLeftCell before the JX object exists");
        }
        com.jxparallel.fx.scene.control.TableView.TableViewSelectionModel.$hook(jxOwner, "selectLeftCell()", new Object[] {});
    }

    @Override
    public void selectBelowCell() {
        if (jxOwner == null) {
            throw new IllegalStateException("selectBelowCell before the JX object exists");
        }
        com.jxparallel.fx.scene.control.TableView.TableViewSelectionModel.$hook(jxOwner, "selectBelowCell()", new Object[] {});
    }

    @Override
    public void selectRightCell() {
        if (jxOwner == null) {
            throw new IllegalStateException("selectRightCell before the JX object exists");
        }
        com.jxparallel.fx.scene.control.TableView.TableViewSelectionModel.$hook(jxOwner, "selectRightCell()", new Object[] {});
    }

    @Override
    public void selectAboveCell() {
        if (jxOwner == null) {
            throw new IllegalStateException("selectAboveCell before the JX object exists");
        }
        com.jxparallel.fx.scene.control.TableView.TableViewSelectionModel.$hook(jxOwner, "selectAboveCell()", new Object[] {});
    }

    @Override
    public Object callSuper(String method, Object[] a) {
        try {
        switch (method) {
            default:
                throw new AbstractMethodError(method);
        }
        } catch (Exception e) {
            throw com.jxparallel.fx.Fx.sneaky(e);
        }
    }
}
