package com.jxparallel.fx.peer.scene.control;

/** JavaFX peer of {@link com.jxparallel.fx.scene.control.TextFormatter}; forwards overridable methods to it (generated by scripts/GenerateFxApi.java). */
@SuppressWarnings({"unchecked", "rawtypes", "deprecation", "serial"})
public class TextFormatter<V> extends javafx.scene.control.TextFormatter<V> implements com.jxparallel.fx.Fx.Owned {
    private Object jxOwner;

    public TextFormatter(@javafx.beans.NamedArg(value = "filter") java.util.function.UnaryOperator<javafx.scene.control.TextFormatter.Change> arg0) {
        super(arg0);
    }

    public TextFormatter(@javafx.beans.NamedArg(value = "valueConverter") javafx.util.StringConverter<V> arg0) {
        super(arg0);
    }

    public TextFormatter(@javafx.beans.NamedArg(value = "valueConverter") javafx.util.StringConverter<V> arg0, @javafx.beans.NamedArg(value = "defaultValue") V arg1) {
        super(arg0, arg1);
    }

    public TextFormatter(@javafx.beans.NamedArg(value = "valueConverter") javafx.util.StringConverter<V> arg0, @javafx.beans.NamedArg(value = "defaultValue") V arg1, @javafx.beans.NamedArg(value = "filter") java.util.function.UnaryOperator<javafx.scene.control.TextFormatter.Change> arg2) {
        super(arg0, arg1, arg2);
    }

    @Override
    public Object jxOwner() {
        return jxOwner;
    }

    @Override
    public void jxOwner(Object owner) {
        this.jxOwner = owner;
    }

    @Override
    public Object callSuper(String method, Object[] a) {
        try {
        switch (method) {
            default:
                throw new AbstractMethodError(method);
        }
        } catch (Exception e) {
            throw com.jxparallel.fx.Fx.sneaky(e);
        }
    }
}
