package com.jxparallel.fx.peer.scene.control;

/** JavaFX peer of {@link com.jxparallel.fx.scene.control.TreeItem.TreeModificationEvent}; forwards overridable methods to it (generated by scripts/GenerateFxApi.java). */
@SuppressWarnings({"unchecked", "rawtypes", "deprecation", "serial"})
public class TreeItem_TreeModificationEvent<T> extends javafx.scene.control.TreeItem.TreeModificationEvent<T> implements com.jxparallel.fx.Fx.Owned {
    private Object jxOwner;

    public TreeItem_TreeModificationEvent(javafx.event.EventType<? extends javafx.event.Event> arg0, javafx.scene.control.TreeItem<T> arg1) {
        super(arg0, arg1);
    }

    public TreeItem_TreeModificationEvent(javafx.event.EventType<? extends javafx.event.Event> arg0, javafx.scene.control.TreeItem<T> arg1, T arg2) {
        super(arg0, arg1, arg2);
    }

    public TreeItem_TreeModificationEvent(javafx.event.EventType<? extends javafx.event.Event> arg0, javafx.scene.control.TreeItem<T> arg1, boolean arg2) {
        super(arg0, arg1, arg2);
    }

    public TreeItem_TreeModificationEvent(javafx.event.EventType<? extends javafx.event.Event> arg0, javafx.scene.control.TreeItem<T> arg1, java.util.List<? extends javafx.scene.control.TreeItem<T>> arg2, java.util.List<? extends javafx.scene.control.TreeItem<T>> arg3) {
        super(arg0, arg1, arg2, arg3);
    }

    @Override
    public Object jxOwner() {
        return jxOwner;
    }

    @Override
    public void jxOwner(Object owner) {
        this.jxOwner = owner;
    }

    @Override
    public Object callSuper(String method, Object[] a) {
        try {
        switch (method) {
            default:
                throw new AbstractMethodError(method);
        }
        } catch (Exception e) {
            throw com.jxparallel.fx.Fx.sneaky(e);
        }
    }
}
