package com.jxparallel.fx.peer.scene.control;

/** JavaFX peer of {@link com.jxparallel.fx.scene.control.TreeItem}; forwards overridable methods to it (generated by scripts/GenerateFxApi.java). */
@SuppressWarnings({"unchecked", "rawtypes", "deprecation", "serial"})
public class TreeItem<T> extends javafx.scene.control.TreeItem<T> implements com.jxparallel.fx.Fx.Owned {
    private Object jxOwner;

    public TreeItem() {
        super();
    }

    public TreeItem(T arg0) {
        super(arg0);
    }

    public TreeItem(T arg0, javafx.scene.Node arg1) {
        super(arg0, arg1);
    }

    @Override
    public Object jxOwner() {
        return jxOwner;
    }

    @Override
    public void jxOwner(Object owner) {
        this.jxOwner = owner;
    }

    @Override
    public Object callSuper(String method, Object[] a) {
        try {
        switch (method) {
            default:
                throw new AbstractMethodError(method);
        }
        } catch (Exception e) {
            throw com.jxparallel.fx.Fx.sneaky(e);
        }
    }
}
