package com.jxparallel.fx.peer.scene.layout;

/** JavaFX peer of {@link com.jxparallel.fx.scene.layout.HBox}; forwards overridable methods to it (generated by scripts/GenerateFxApi.java). */
@SuppressWarnings({"unchecked", "rawtypes", "deprecation", "serial"})
public class HBox extends javafx.scene.layout.HBox implements com.jxparallel.fx.Fx.Owned {
    private Object jxOwner;

    public HBox() {
        super();
    }

    public HBox(double arg0) {
        super(arg0);
    }

    public HBox(double arg0, javafx.scene.Node... arg1) {
        super(arg0, arg1);
    }

    public HBox(javafx.scene.Node... arg0) {
        super(arg0);
    }

    @Override
    public Object jxOwner() {
        return jxOwner;
    }

    @Override
    public void jxOwner(Object owner) {
        this.jxOwner = owner;
    }

    @Override
    public Object callSuper(String method, Object[] a) {
        try {
        switch (method) {
            default:
                throw new AbstractMethodError(method);
        }
        } catch (Exception e) {
            throw com.jxparallel.fx.Fx.sneaky(e);
        }
    }
}
