package com.jxparallel.fx.util;

/** JXParallel counterpart of {@link javafx.util.BuilderFactory} (generated by scripts/GenerateFxApi.java). */
@SuppressWarnings({"unchecked", "rawtypes", "deprecation"})
@FunctionalInterface
public interface BuilderFactory {

    javafx.util.Builder<?> getBuilder(java.lang.Class<?> arg0);
}
