package com.jxparallel.fx.peer.scene.image;

/** JavaFX peer of {@link com.jxparallel.fx.scene.image.WritableImage}; forwards overridable methods to it (generated by scripts/GenerateFxApi.java). */
@SuppressWarnings({"unchecked", "rawtypes", "deprecation", "serial"})
public class WritableImage extends javafx.scene.image.WritableImage implements com.jxparallel.fx.Fx.Owned {
    private Object jxOwner;

    public WritableImage(@javafx.beans.NamedArg(value = "reader") javafx.scene.image.PixelReader arg0, @javafx.beans.NamedArg(value = "x") int arg1, @javafx.beans.NamedArg(value = "y") int arg2, @javafx.beans.NamedArg(value = "width") int arg3, @javafx.beans.NamedArg(value = "height") int arg4) {
        super(arg0, arg1, arg2, arg3, arg4);
    }

    public WritableImage(@javafx.beans.NamedArg(value = "reader") javafx.scene.image.PixelReader arg0, @javafx.beans.NamedArg(value = "width") int arg1, @javafx.beans.NamedArg(value = "height") int arg2) {
        super(arg0, arg1, arg2);
    }

    public WritableImage(@javafx.beans.NamedArg(value = "width") int arg0, @javafx.beans.NamedArg(value = "height") int arg1) {
        super(arg0, arg1);
    }

    @Override
    public Object jxOwner() {
        return jxOwner;
    }

    @Override
    public void jxOwner(Object owner) {
        this.jxOwner = owner;
    }

    @Override
    public Object callSuper(String method, Object[] a) {
        try {
        switch (method) {
            default:
                throw new AbstractMethodError(method);
        }
        } catch (Exception e) {
            throw com.jxparallel.fx.Fx.sneaky(e);
        }
    }
}
