package com.jxparallel.fx.scene.effect;

/** JXParallel counterpart of {@link javafx.scene.effect.Effect} (generated by scripts/GenerateFxApi.java). */
@SuppressWarnings({"unchecked", "rawtypes", "deprecation"})
public class Effect implements com.jxparallel.fx.Fx.Backed {
    private final Object fxPeer;

    protected Effect(com.jxparallel.fx.Fx.Wrap wrap, Object peer) {
        this.fxPeer = peer;
    }

    @Override
    public Object fxPeer() {
        return fxPeer;
    }

    @Override
    public boolean equals(Object o) {
        return o == this || fxPeer().equals(com.jxparallel.fx.Fx.fx(o));
    }

    @Override
    public int hashCode() {
        return fxPeer().hashCode();
    }

    @Override
    public String toString() {
        return fxPeer().toString();
    }

    public com.jxparallel.fx.beans.property.IntegerProperty impl_effectDirtyProperty() {
        return (com.jxparallel.fx.beans.property.IntegerProperty) com.jxparallel.fx.Fx.jx(((javafx.scene.effect.Effect) fxPeer()).impl_effectDirtyProperty());
    }

    public boolean impl_isEffectDirty() {
        return ((javafx.scene.effect.Effect) fxPeer()).impl_isEffectDirty();
    }

    public void impl_sync() {
        ((javafx.scene.effect.Effect) fxPeer()).impl_sync();
    }
}
