package com.jxparallel.fx.css;

/** JXParallel counterpart of {@link javafx.css.Styleable} (generated by scripts/GenerateFxApi.java). */
@SuppressWarnings({"unchecked", "rawtypes", "deprecation"})
public interface Styleable {

    java.util.List<javafx.css.CssMetaData<? extends javafx.css.Styleable, ?>> getCssMetaData();

    java.lang.String getId();

    javafx.collections.ObservableSet<javafx.css.PseudoClass> getPseudoClassStates();

    java.lang.String getStyle();

    com.jxparallel.fx.collections.ObservableList<java.lang.String> getStyleClass();

    com.jxparallel.fx.css.Styleable getStyleableParent();

    java.lang.String getTypeSelector();
}
