package com.jxparallel.fx.stage;

/** JXParallel counterpart of {@link javafx.stage.DirectoryChooser} (generated by scripts/GenerateFxApi.java). */
@SuppressWarnings({"unchecked", "rawtypes", "deprecation"})
public final class DirectoryChooser implements com.jxparallel.fx.Fx.Backed {
    private final Object fxPeer;

    protected DirectoryChooser(com.jxparallel.fx.Fx.Wrap wrap, Object peer) {
        this.fxPeer = peer;
    }

    @Override
    public Object fxPeer() {
        return fxPeer;
    }

    @Override
    public boolean equals(Object o) {
        return o == this || fxPeer().equals(com.jxparallel.fx.Fx.fx(o));
    }

    @Override
    public int hashCode() {
        return fxPeer().hashCode();
    }

    @Override
    public String toString() {
        return fxPeer().toString();
    }

    public DirectoryChooser() {
        this(com.jxparallel.fx.Fx.WRAP, com.jxparallel.fx.Fx.NATIVE ? com.jxparallel.fx.nativeimpl.Native.create(javafx.stage.DirectoryChooser.class, new String[] {}, new Object[] {}) : new javafx.stage.DirectoryChooser());
        com.jxparallel.fx.Fx.own(fxPeer(), this);
    }

    public java.io.File getInitialDirectory() {
        if (com.jxparallel.fx.Fx.NATIVE) {
            return (java.io.File) com.jxparallel.fx.nativeimpl.Native.call(this, com.jxparallel.fx.stage.DirectoryChooser.class, "getInitialDirectory", new Class<?>[] {}, java.io.File.class);
        }
        return ((javafx.stage.DirectoryChooser) fxPeer()).getInitialDirectory();
    }

    public java.lang.String getTitle() {
        if (com.jxparallel.fx.Fx.NATIVE) {
            return (java.lang.String) com.jxparallel.fx.nativeimpl.Native.call(this, com.jxparallel.fx.stage.DirectoryChooser.class, "getTitle", new Class<?>[] {}, java.lang.String.class);
        }
        return ((javafx.stage.DirectoryChooser) fxPeer()).getTitle();
    }

    public com.jxparallel.fx.beans.property.ObjectProperty<java.io.File> initialDirectoryProperty() {
        if (com.jxparallel.fx.Fx.NATIVE) {
            return (com.jxparallel.fx.beans.property.ObjectProperty) com.jxparallel.fx.nativeimpl.Native.call(this, com.jxparallel.fx.stage.DirectoryChooser.class, "initialDirectoryProperty", new Class<?>[] {}, com.jxparallel.fx.beans.property.ObjectProperty.class);
        }
        return (com.jxparallel.fx.beans.property.ObjectProperty) com.jxparallel.fx.Fx.jx(((javafx.stage.DirectoryChooser) fxPeer()).initialDirectoryProperty());
    }

    public void setInitialDirectory(java.io.File arg0) {
        if (com.jxparallel.fx.Fx.NATIVE) {
            com.jxparallel.fx.nativeimpl.Native.call(this, com.jxparallel.fx.stage.DirectoryChooser.class, "setInitialDirectory", new Class<?>[] {java.io.File.class}, void.class, arg0);
            return;
        }
        ((javafx.stage.DirectoryChooser) fxPeer()).setInitialDirectory(arg0);
    }

    public void setTitle(java.lang.String arg0) {
        if (com.jxparallel.fx.Fx.NATIVE) {
            com.jxparallel.fx.nativeimpl.Native.call(this, com.jxparallel.fx.stage.DirectoryChooser.class, "setTitle", new Class<?>[] {java.lang.String.class}, void.class, arg0);
            return;
        }
        ((javafx.stage.DirectoryChooser) fxPeer()).setTitle(arg0);
    }

    public java.io.File showDialog(com.jxparallel.fx.stage.Window arg0) {
        if (com.jxparallel.fx.Fx.NATIVE) {
            return (java.io.File) com.jxparallel.fx.nativeimpl.Native.call(this, com.jxparallel.fx.stage.DirectoryChooser.class, "showDialog", new Class<?>[] {com.jxparallel.fx.stage.Window.class}, java.io.File.class, arg0);
        }
        return ((javafx.stage.DirectoryChooser) fxPeer()).showDialog((javafx.stage.Window) com.jxparallel.fx.Fx.fx(arg0));
    }

    public com.jxparallel.fx.beans.property.StringProperty titleProperty() {
        if (com.jxparallel.fx.Fx.NATIVE) {
            return (com.jxparallel.fx.beans.property.StringProperty) com.jxparallel.fx.nativeimpl.Native.call(this, com.jxparallel.fx.stage.DirectoryChooser.class, "titleProperty", new Class<?>[] {}, com.jxparallel.fx.beans.property.StringProperty.class);
        }
        return (com.jxparallel.fx.beans.property.StringProperty) com.jxparallel.fx.Fx.jx(((javafx.stage.DirectoryChooser) fxPeer()).titleProperty());
    }
}
