package com.jxparallel.fx.stage;

/** JXParallel counterpart of {@link javafx.stage.StageStyle} (generated by scripts/GenerateFxApi.java). */
@SuppressWarnings({"unchecked", "rawtypes", "deprecation"})
public enum StageStyle {
    DECORATED,
    UNDECORATED,
    TRANSPARENT,
    UTILITY,
    UNIFIED;
}
