package com.jxparallel.fx.stage;

/** JXParallel counterpart of {@link javafx.stage.WindowEvent} (generated by scripts/GenerateFxApi.java). */
@SuppressWarnings({"unchecked", "rawtypes", "deprecation"})
public class WindowEvent extends com.jxparallel.fx.event.Event {
    protected WindowEvent(com.jxparallel.fx.Fx.Wrap wrap, Object peer) {
        super(wrap, peer);
    }

    public WindowEvent(@javafx.beans.NamedArg(value = "source") com.jxparallel.fx.stage.Window arg0, @javafx.beans.NamedArg(value = "eventType") com.jxparallel.fx.event.EventType<? extends com.jxparallel.fx.event.Event> arg1) {
        this(com.jxparallel.fx.Fx.WRAP, new com.jxparallel.fx.peer.stage.WindowEvent((javafx.stage.Window) com.jxparallel.fx.Fx.fxAs(arg0, javafx.stage.Window.class), (javafx.event.EventType) com.jxparallel.fx.Fx.fx(arg1)));
        com.jxparallel.fx.Fx.own(fxPeer(), this);
    }

    public static final com.jxparallel.fx.event.EventType<com.jxparallel.fx.stage.WindowEvent> ANY = (com.jxparallel.fx.event.EventType) com.jxparallel.fx.Fx.jx(javafx.stage.WindowEvent.ANY);

    public static final com.jxparallel.fx.event.EventType<com.jxparallel.fx.stage.WindowEvent> WINDOW_SHOWING = (com.jxparallel.fx.event.EventType) com.jxparallel.fx.Fx.jx(javafx.stage.WindowEvent.WINDOW_SHOWING);

    public static final com.jxparallel.fx.event.EventType<com.jxparallel.fx.stage.WindowEvent> WINDOW_SHOWN = (com.jxparallel.fx.event.EventType) com.jxparallel.fx.Fx.jx(javafx.stage.WindowEvent.WINDOW_SHOWN);

    public static final com.jxparallel.fx.event.EventType<com.jxparallel.fx.stage.WindowEvent> WINDOW_HIDING = (com.jxparallel.fx.event.EventType) com.jxparallel.fx.Fx.jx(javafx.stage.WindowEvent.WINDOW_HIDING);

    public static final com.jxparallel.fx.event.EventType<com.jxparallel.fx.stage.WindowEvent> WINDOW_HIDDEN = (com.jxparallel.fx.event.EventType) com.jxparallel.fx.Fx.jx(javafx.stage.WindowEvent.WINDOW_HIDDEN);

    public static final com.jxparallel.fx.event.EventType<com.jxparallel.fx.stage.WindowEvent> WINDOW_CLOSE_REQUEST = (com.jxparallel.fx.event.EventType) com.jxparallel.fx.Fx.jx(javafx.stage.WindowEvent.WINDOW_CLOSE_REQUEST);

    public com.jxparallel.fx.stage.WindowEvent copyFor(java.lang.Object arg0, com.jxparallel.fx.event.EventTarget arg1) {
        return (com.jxparallel.fx.stage.WindowEvent) com.jxparallel.fx.Fx.jx(((javafx.stage.WindowEvent) fxPeer()).copyFor((java.lang.Object) com.jxparallel.fx.Fx.fx(arg0), (javafx.event.EventTarget) com.jxparallel.fx.Fx.fx(arg1)));
    }

    public com.jxparallel.fx.stage.WindowEvent copyFor(java.lang.Object arg0, com.jxparallel.fx.event.EventTarget arg1, com.jxparallel.fx.event.EventType<com.jxparallel.fx.stage.WindowEvent> arg2) {
        return (com.jxparallel.fx.stage.WindowEvent) com.jxparallel.fx.Fx.jx(((javafx.stage.WindowEvent) fxPeer()).copyFor((java.lang.Object) com.jxparallel.fx.Fx.fx(arg0), (javafx.event.EventTarget) com.jxparallel.fx.Fx.fx(arg1), (javafx.event.EventType) com.jxparallel.fx.Fx.fx(arg2)));
    }

    public com.jxparallel.fx.event.EventType<com.jxparallel.fx.stage.WindowEvent> getEventType() {
        return (com.jxparallel.fx.event.EventType) com.jxparallel.fx.Fx.jx(((javafx.stage.WindowEvent) fxPeer()).getEventType());
    }
}
