package com.jxparallel.fx.animation;

/** JXParallel counterpart of {@link javafx.animation.AnimationTimer} (generated by scripts/GenerateFxApi.java). */
@SuppressWarnings({"unchecked", "rawtypes", "deprecation"})
public class AnimationTimer implements com.jxparallel.fx.Fx.Backed {
    private final Object fxPeer;

    protected AnimationTimer(com.jxparallel.fx.Fx.Wrap wrap, Object peer) {
        this.fxPeer = peer;
    }

    @Override
    public Object fxPeer() {
        return fxPeer;
    }

    @Override
    public boolean equals(Object o) {
        return o == this || fxPeer.equals(com.jxparallel.fx.Fx.fx(o));
    }

    @Override
    public int hashCode() {
        return fxPeer.hashCode();
    }

    @Override
    public String toString() {
        return fxPeer.toString();
    }

    public AnimationTimer() {
        this(com.jxparallel.fx.Fx.WRAP, new com.jxparallel.fx.peer.animation.AnimationTimer());
        com.jxparallel.fx.Fx.own(fxPeer(), this);
    }

    public void handle(long arg0) {
        if (fxPeer() instanceof com.jxparallel.fx.Fx.Owned) {
            ((com.jxparallel.fx.Fx.Owned) fxPeer()).callSuper("handle(long)", new Object[] {arg0});
        } else {
            com.jxparallel.fx.Fx.invoke(fxPeer(), javafx.animation.AnimationTimer.class, "handle", new Class<?>[] {long.class}, arg0);
        }
    }

    public void start() {
        ((javafx.animation.AnimationTimer) fxPeer()).start();
    }

    public void stop() {
        if (fxPeer() instanceof com.jxparallel.fx.Fx.Owned) {
            ((com.jxparallel.fx.Fx.Owned) fxPeer()).callSuper("stop()", new Object[] {});
        } else {
            com.jxparallel.fx.Fx.invoke(fxPeer(), javafx.animation.AnimationTimer.class, "stop", new Class<?>[] {});
        }
    }

    /** Called by the peer: runs the JX (possibly overridden) method. */
    public static Object $hook(Object self, String method, Object[] a) {
        AnimationTimer jx = (AnimationTimer) self;
        try {
        switch (method) {
            case "stop()":
                jx.stop();
                return null;
            case "handle(long)":
                jx.handle((Long) a[0]);
                return null;
            default:
                throw new IllegalArgumentException(method);
        }
        } catch (Exception e) {
            throw com.jxparallel.fx.Fx.sneaky(e);
        }
    }
}
