package com.jxparallel.fx.animation;

/** JXParallel counterpart of {@link javafx.animation.Animation} (generated by scripts/GenerateFxApi.java). */
@SuppressWarnings({"unchecked", "rawtypes", "deprecation"})
public class Animation implements com.jxparallel.fx.Fx.Backed {
    private final Object fxPeer;

    protected Animation(com.jxparallel.fx.Fx.Wrap wrap, Object peer) {
        this.fxPeer = peer;
    }

    @Override
    public Object fxPeer() {
        return fxPeer;
    }

    @Override
    public boolean equals(Object o) {
        return o == this || fxPeer.equals(com.jxparallel.fx.Fx.fx(o));
    }

    @Override
    public int hashCode() {
        return fxPeer.hashCode();
    }

    @Override
    public String toString() {
        return fxPeer.toString();
    }

    public static final int INDEFINITE = javafx.animation.Animation.INDEFINITE;

    public com.jxparallel.fx.beans.property.BooleanProperty autoReverseProperty() {
        return (com.jxparallel.fx.beans.property.BooleanProperty) com.jxparallel.fx.Fx.jx(((javafx.animation.Animation) fxPeer()).autoReverseProperty());
    }

    public com.jxparallel.fx.beans.property.ReadOnlyDoubleProperty currentRateProperty() {
        return (com.jxparallel.fx.beans.property.ReadOnlyDoubleProperty) com.jxparallel.fx.Fx.jx(((javafx.animation.Animation) fxPeer()).currentRateProperty());
    }

    public com.jxparallel.fx.beans.property.ReadOnlyObjectProperty<com.jxparallel.fx.util.Duration> currentTimeProperty() {
        return (com.jxparallel.fx.beans.property.ReadOnlyObjectProperty) com.jxparallel.fx.Fx.jx(((javafx.animation.Animation) fxPeer()).currentTimeProperty());
    }

    public com.jxparallel.fx.beans.property.IntegerProperty cycleCountProperty() {
        return (com.jxparallel.fx.beans.property.IntegerProperty) com.jxparallel.fx.Fx.jx(((javafx.animation.Animation) fxPeer()).cycleCountProperty());
    }

    public com.jxparallel.fx.beans.property.ReadOnlyObjectProperty<com.jxparallel.fx.util.Duration> cycleDurationProperty() {
        return (com.jxparallel.fx.beans.property.ReadOnlyObjectProperty) com.jxparallel.fx.Fx.jx(((javafx.animation.Animation) fxPeer()).cycleDurationProperty());
    }

    public com.jxparallel.fx.beans.property.ObjectProperty<com.jxparallel.fx.util.Duration> delayProperty() {
        return (com.jxparallel.fx.beans.property.ObjectProperty) com.jxparallel.fx.Fx.jx(((javafx.animation.Animation) fxPeer()).delayProperty());
    }

    public javafx.collections.ObservableMap<java.lang.String, javafx.util.Duration> getCuePoints() {
        return ((javafx.animation.Animation) fxPeer()).getCuePoints();
    }

    public double getCurrentRate() {
        return ((javafx.animation.Animation) fxPeer()).getCurrentRate();
    }

    public com.jxparallel.fx.util.Duration getCurrentTime() {
        return (com.jxparallel.fx.util.Duration) com.jxparallel.fx.Fx.jx(((javafx.animation.Animation) fxPeer()).getCurrentTime());
    }

    public int getCycleCount() {
        return ((javafx.animation.Animation) fxPeer()).getCycleCount();
    }

    public com.jxparallel.fx.util.Duration getCycleDuration() {
        return (com.jxparallel.fx.util.Duration) com.jxparallel.fx.Fx.jx(((javafx.animation.Animation) fxPeer()).getCycleDuration());
    }

    public com.jxparallel.fx.util.Duration getDelay() {
        return (com.jxparallel.fx.util.Duration) com.jxparallel.fx.Fx.jx(((javafx.animation.Animation) fxPeer()).getDelay());
    }

    public com.jxparallel.fx.event.EventHandler<com.jxparallel.fx.event.ActionEvent> getOnFinished() {
        return (com.jxparallel.fx.event.EventHandler) com.jxparallel.fx.Fx.jx(((javafx.animation.Animation) fxPeer()).getOnFinished());
    }

    public double getRate() {
        return ((javafx.animation.Animation) fxPeer()).getRate();
    }

    public com.jxparallel.fx.animation.Animation.Status getStatus() {
        return (com.jxparallel.fx.animation.Animation.Status) com.jxparallel.fx.Fx.jx(((javafx.animation.Animation) fxPeer()).getStatus());
    }

    public double getTargetFramerate() {
        return ((javafx.animation.Animation) fxPeer()).getTargetFramerate();
    }

    public com.jxparallel.fx.util.Duration getTotalDuration() {
        return (com.jxparallel.fx.util.Duration) com.jxparallel.fx.Fx.jx(((javafx.animation.Animation) fxPeer()).getTotalDuration());
    }

    public boolean isAutoReverse() {
        return ((javafx.animation.Animation) fxPeer()).isAutoReverse();
    }

    public void jumpTo(com.jxparallel.fx.util.Duration arg0) {
        ((javafx.animation.Animation) fxPeer()).jumpTo((javafx.util.Duration) com.jxparallel.fx.Fx.fx(arg0));
    }

    public void jumpTo(java.lang.String arg0) {
        ((javafx.animation.Animation) fxPeer()).jumpTo(arg0);
    }

    public com.jxparallel.fx.beans.property.ObjectProperty<com.jxparallel.fx.event.EventHandler<com.jxparallel.fx.event.ActionEvent>> onFinishedProperty() {
        return (com.jxparallel.fx.beans.property.ObjectProperty) com.jxparallel.fx.Fx.jx(((javafx.animation.Animation) fxPeer()).onFinishedProperty());
    }

    public void pause() {
        ((javafx.animation.Animation) fxPeer()).pause();
    }

    public void play() {
        ((javafx.animation.Animation) fxPeer()).play();
    }

    public void playFrom(com.jxparallel.fx.util.Duration arg0) {
        ((javafx.animation.Animation) fxPeer()).playFrom((javafx.util.Duration) com.jxparallel.fx.Fx.fx(arg0));
    }

    public void playFrom(java.lang.String arg0) {
        ((javafx.animation.Animation) fxPeer()).playFrom(arg0);
    }

    public void playFromStart() {
        ((javafx.animation.Animation) fxPeer()).playFromStart();
    }

    public com.jxparallel.fx.beans.property.DoubleProperty rateProperty() {
        return (com.jxparallel.fx.beans.property.DoubleProperty) com.jxparallel.fx.Fx.jx(((javafx.animation.Animation) fxPeer()).rateProperty());
    }

    public void setAutoReverse(boolean arg0) {
        ((javafx.animation.Animation) fxPeer()).setAutoReverse(arg0);
    }

    public void setCycleCount(int arg0) {
        ((javafx.animation.Animation) fxPeer()).setCycleCount(arg0);
    }

    protected void setCycleDuration(com.jxparallel.fx.util.Duration arg0) {
        com.jxparallel.fx.Fx.invoke(fxPeer(), javafx.animation.Animation.class, "setCycleDuration", new Class<?>[] {javafx.util.Duration.class}, (javafx.util.Duration) com.jxparallel.fx.Fx.fx(arg0));
    }

    public void setDelay(com.jxparallel.fx.util.Duration arg0) {
        ((javafx.animation.Animation) fxPeer()).setDelay((javafx.util.Duration) com.jxparallel.fx.Fx.fx(arg0));
    }

    public void setOnFinished(com.jxparallel.fx.event.EventHandler<com.jxparallel.fx.event.ActionEvent> arg0) {
        ((javafx.animation.Animation) fxPeer()).setOnFinished((javafx.event.EventHandler) com.jxparallel.fx.Fx.fx(arg0));
    }

    public void setRate(double arg0) {
        ((javafx.animation.Animation) fxPeer()).setRate(arg0);
    }

    protected void setStatus(com.jxparallel.fx.animation.Animation.Status arg0) {
        com.jxparallel.fx.Fx.invoke(fxPeer(), javafx.animation.Animation.class, "setStatus", new Class<?>[] {javafx.animation.Animation.Status.class}, (javafx.animation.Animation.Status) com.jxparallel.fx.Fx.fx(arg0));
    }

    public com.jxparallel.fx.beans.property.ReadOnlyObjectProperty<com.jxparallel.fx.animation.Animation.Status> statusProperty() {
        return (com.jxparallel.fx.beans.property.ReadOnlyObjectProperty) com.jxparallel.fx.Fx.jx(((javafx.animation.Animation) fxPeer()).statusProperty());
    }

    public void stop() {
        if (fxPeer() instanceof com.jxparallel.fx.Fx.Owned) {
            ((com.jxparallel.fx.Fx.Owned) fxPeer()).callSuper("stop()", new Object[] {});
        } else {
            com.jxparallel.fx.Fx.invoke(fxPeer(), javafx.animation.Animation.class, "stop", new Class<?>[] {});
        }
    }

    public com.jxparallel.fx.beans.property.ReadOnlyObjectProperty<com.jxparallel.fx.util.Duration> totalDurationProperty() {
        return (com.jxparallel.fx.beans.property.ReadOnlyObjectProperty) com.jxparallel.fx.Fx.jx(((javafx.animation.Animation) fxPeer()).totalDurationProperty());
    }

    public enum Status {
        PAUSED,
        RUNNING,
        STOPPED;
    }
}
