package com.jxparallel.fx.animation;

/** JXParallel counterpart of {@link javafx.animation.Interpolator} (generated by scripts/GenerateFxApi.java). */
@SuppressWarnings({"unchecked", "rawtypes", "deprecation"})
public class Interpolator implements com.jxparallel.fx.Fx.Backed {
    private final Object fxPeer;

    protected Interpolator(com.jxparallel.fx.Fx.Wrap wrap, Object peer) {
        this.fxPeer = peer;
    }

    @Override
    public Object fxPeer() {
        return fxPeer;
    }

    @Override
    public boolean equals(Object o) {
        return o == this || fxPeer().equals(com.jxparallel.fx.Fx.fx(o));
    }

    @Override
    public int hashCode() {
        return fxPeer().hashCode();
    }

    @Override
    public String toString() {
        return fxPeer().toString();
    }

    protected Interpolator() {
        this(com.jxparallel.fx.Fx.WRAP, new com.jxparallel.fx.peer.animation.Interpolator());
        com.jxparallel.fx.Fx.own(fxPeer(), this);
    }

    public static final com.jxparallel.fx.animation.Interpolator DISCRETE = (com.jxparallel.fx.animation.Interpolator) com.jxparallel.fx.Fx.jx(javafx.animation.Interpolator.DISCRETE);

    public static final com.jxparallel.fx.animation.Interpolator LINEAR = (com.jxparallel.fx.animation.Interpolator) com.jxparallel.fx.Fx.jx(javafx.animation.Interpolator.LINEAR);

    public static final com.jxparallel.fx.animation.Interpolator EASE_BOTH = (com.jxparallel.fx.animation.Interpolator) com.jxparallel.fx.Fx.jx(javafx.animation.Interpolator.EASE_BOTH);

    public static final com.jxparallel.fx.animation.Interpolator EASE_IN = (com.jxparallel.fx.animation.Interpolator) com.jxparallel.fx.Fx.jx(javafx.animation.Interpolator.EASE_IN);

    public static final com.jxparallel.fx.animation.Interpolator EASE_OUT = (com.jxparallel.fx.animation.Interpolator) com.jxparallel.fx.Fx.jx(javafx.animation.Interpolator.EASE_OUT);

    public static com.jxparallel.fx.animation.Interpolator SPLINE(double arg0, double arg1, double arg2, double arg3) {
        return (com.jxparallel.fx.animation.Interpolator) com.jxparallel.fx.Fx.jx(javafx.animation.Interpolator.SPLINE(arg0, arg1, arg2, arg3));
    }

    public static com.jxparallel.fx.animation.Interpolator TANGENT(com.jxparallel.fx.util.Duration arg0, double arg1) {
        return (com.jxparallel.fx.animation.Interpolator) com.jxparallel.fx.Fx.jx(javafx.animation.Interpolator.TANGENT((javafx.util.Duration) com.jxparallel.fx.Fx.fx(arg0), arg1));
    }

    public static com.jxparallel.fx.animation.Interpolator TANGENT(com.jxparallel.fx.util.Duration arg0, double arg1, com.jxparallel.fx.util.Duration arg2, double arg3) {
        return (com.jxparallel.fx.animation.Interpolator) com.jxparallel.fx.Fx.jx(javafx.animation.Interpolator.TANGENT((javafx.util.Duration) com.jxparallel.fx.Fx.fx(arg0), arg1, (javafx.util.Duration) com.jxparallel.fx.Fx.fx(arg2), arg3));
    }

    protected double curve(double arg0) {
        return (Double) (fxPeer() instanceof com.jxparallel.fx.Fx.Owned ? ((com.jxparallel.fx.Fx.Owned) fxPeer()).callSuper("curve(double)", new Object[] {arg0}) : com.jxparallel.fx.Fx.invoke(fxPeer(), javafx.animation.Interpolator.class, "curve", new Class<?>[] {double.class}, arg0));
    }

    public java.lang.Object interpolate(java.lang.Object arg0, java.lang.Object arg1, double arg2) {
        return (java.lang.Object) com.jxparallel.fx.Fx.jx(((javafx.animation.Interpolator) fxPeer()).interpolate((java.lang.Object) com.jxparallel.fx.Fx.fx(arg0), (java.lang.Object) com.jxparallel.fx.Fx.fx(arg1), arg2));
    }

    public boolean interpolate(boolean arg0, boolean arg1, double arg2) {
        return ((javafx.animation.Interpolator) fxPeer()).interpolate(arg0, arg1, arg2);
    }

    public double interpolate(double arg0, double arg1, double arg2) {
        return ((javafx.animation.Interpolator) fxPeer()).interpolate(arg0, arg1, arg2);
    }

    public int interpolate(int arg0, int arg1, double arg2) {
        return ((javafx.animation.Interpolator) fxPeer()).interpolate(arg0, arg1, arg2);
    }

    public long interpolate(long arg0, long arg1, double arg2) {
        return ((javafx.animation.Interpolator) fxPeer()).interpolate(arg0, arg1, arg2);
    }

    /** Called by the peer: runs the JX (possibly overridden) method. */
    public static Object $hook(Object self, String method, Object[] a) {
        Interpolator jx = (Interpolator) self;
        try {
        switch (method) {
            case "curve(double)":
                return (Object) jx.curve((Double) a[0]);
            default:
                throw new IllegalArgumentException(method);
        }
        } catch (Exception e) {
            throw com.jxparallel.fx.Fx.sneaky(e);
        }
    }
}
