package com.jxparallel.fx.animation;

/** JXParallel counterpart of {@link javafx.animation.KeyValue} (generated by scripts/GenerateFxApi.java). */
@SuppressWarnings({"unchecked", "rawtypes", "deprecation"})
public final class KeyValue implements com.jxparallel.fx.Fx.Backed {
    private final Object fxPeer;

    protected KeyValue(com.jxparallel.fx.Fx.Wrap wrap, Object peer) {
        this.fxPeer = peer;
    }

    @Override
    public Object fxPeer() {
        return fxPeer;
    }

    @Override
    public boolean equals(Object o) {
        return o == this || fxPeer().equals(com.jxparallel.fx.Fx.fx(o));
    }

    @Override
    public int hashCode() {
        return fxPeer().hashCode();
    }

    @Override
    public String toString() {
        return fxPeer().toString();
    }

    public <T> KeyValue(@javafx.beans.NamedArg(value = "target") com.jxparallel.fx.beans.value.WritableValue<T> arg0, @javafx.beans.NamedArg(value = "endValue") T arg1) {
        this(com.jxparallel.fx.Fx.WRAP, new javafx.animation.KeyValue((javafx.beans.value.WritableValue) com.jxparallel.fx.Fx.fx(arg0), (T) com.jxparallel.fx.Fx.fx(arg1)));
        com.jxparallel.fx.Fx.own(fxPeer(), this);
    }

    public <T> KeyValue(@javafx.beans.NamedArg(value = "target") com.jxparallel.fx.beans.value.WritableValue<T> arg0, @javafx.beans.NamedArg(value = "endValue") T arg1, @javafx.beans.NamedArg(value = "interpolator") com.jxparallel.fx.animation.Interpolator arg2) {
        this(com.jxparallel.fx.Fx.WRAP, new javafx.animation.KeyValue((javafx.beans.value.WritableValue) com.jxparallel.fx.Fx.fx(arg0), (T) com.jxparallel.fx.Fx.fx(arg1), (javafx.animation.Interpolator) com.jxparallel.fx.Fx.fx(arg2)));
        com.jxparallel.fx.Fx.own(fxPeer(), this);
    }

    public java.lang.Object getEndValue() {
        return (java.lang.Object) com.jxparallel.fx.Fx.jx(((javafx.animation.KeyValue) fxPeer()).getEndValue());
    }

    public com.jxparallel.fx.animation.Interpolator getInterpolator() {
        return (com.jxparallel.fx.animation.Interpolator) com.jxparallel.fx.Fx.jx(((javafx.animation.KeyValue) fxPeer()).getInterpolator());
    }

    public com.jxparallel.fx.beans.value.WritableValue<?> getTarget() {
        return (com.jxparallel.fx.beans.value.WritableValue) com.jxparallel.fx.Fx.jx(((javafx.animation.KeyValue) fxPeer()).getTarget());
    }

    public com.jxparallel.fx.animation.KeyValue.Type getType() {
        return (com.jxparallel.fx.animation.KeyValue.Type) com.jxparallel.fx.Fx.jx(((javafx.animation.KeyValue) fxPeer()).getType());
    }

    public enum Type {
        BOOLEAN,
        DOUBLE,
        FLOAT,
        INTEGER,
        LONG,
        OBJECT;
    }
}
