package com.jxparallel.fx.concurrent;

/** JXParallel counterpart of {@link javafx.concurrent.ScheduledService} (generated by scripts/GenerateFxApi.java). */
@SuppressWarnings({"unchecked", "rawtypes", "deprecation"})
public class ScheduledService<V> extends com.jxparallel.fx.concurrent.Service<V> {
    protected ScheduledService(com.jxparallel.fx.Fx.Wrap wrap, Object peer) {
        super(wrap, peer);
    }

    public ScheduledService() {
        this(com.jxparallel.fx.Fx.WRAP, new com.jxparallel.fx.peer.concurrent.ScheduledService());
        com.jxparallel.fx.Fx.own(fxPeer(), this);
    }

    public static final com.jxparallel.fx.util.Callback<com.jxparallel.fx.concurrent.ScheduledService<?>, com.jxparallel.fx.util.Duration> EXPONENTIAL_BACKOFF_STRATEGY = (com.jxparallel.fx.util.Callback) com.jxparallel.fx.Fx.jx(javafx.concurrent.ScheduledService.EXPONENTIAL_BACKOFF_STRATEGY);

    public static final com.jxparallel.fx.util.Callback<com.jxparallel.fx.concurrent.ScheduledService<?>, com.jxparallel.fx.util.Duration> LOGARITHMIC_BACKOFF_STRATEGY = (com.jxparallel.fx.util.Callback) com.jxparallel.fx.Fx.jx(javafx.concurrent.ScheduledService.LOGARITHMIC_BACKOFF_STRATEGY);

    public static final com.jxparallel.fx.util.Callback<com.jxparallel.fx.concurrent.ScheduledService<?>, com.jxparallel.fx.util.Duration> LINEAR_BACKOFF_STRATEGY = (com.jxparallel.fx.util.Callback) com.jxparallel.fx.Fx.jx(javafx.concurrent.ScheduledService.LINEAR_BACKOFF_STRATEGY);

    public com.jxparallel.fx.beans.property.ObjectProperty<com.jxparallel.fx.util.Callback<com.jxparallel.fx.concurrent.ScheduledService<?>, com.jxparallel.fx.util.Duration>> backoffStrategyProperty() {
        return (com.jxparallel.fx.beans.property.ObjectProperty) com.jxparallel.fx.Fx.jx(((javafx.concurrent.ScheduledService) fxPeer()).backoffStrategyProperty());
    }

    public boolean cancel() {
        return ((javafx.concurrent.ScheduledService) fxPeer()).cancel();
    }

    public com.jxparallel.fx.beans.property.ReadOnlyObjectProperty<com.jxparallel.fx.util.Duration> cumulativePeriodProperty() {
        return (com.jxparallel.fx.beans.property.ReadOnlyObjectProperty) com.jxparallel.fx.Fx.jx(((javafx.concurrent.ScheduledService) fxPeer()).cumulativePeriodProperty());
    }

    public com.jxparallel.fx.beans.property.ReadOnlyIntegerProperty currentFailureCountProperty() {
        return (com.jxparallel.fx.beans.property.ReadOnlyIntegerProperty) com.jxparallel.fx.Fx.jx(((javafx.concurrent.ScheduledService) fxPeer()).currentFailureCountProperty());
    }

    public com.jxparallel.fx.beans.property.ObjectProperty<com.jxparallel.fx.util.Duration> delayProperty() {
        return (com.jxparallel.fx.beans.property.ObjectProperty) com.jxparallel.fx.Fx.jx(((javafx.concurrent.ScheduledService) fxPeer()).delayProperty());
    }

    protected void executeTask(com.jxparallel.fx.concurrent.Task<V> arg0) {
        com.jxparallel.fx.Fx.invoke(fxPeer(), javafx.concurrent.ScheduledService.class, "executeTask", new Class<?>[] {javafx.concurrent.Task.class}, (javafx.concurrent.Task) com.jxparallel.fx.Fx.fx(arg0));
    }

    protected void failed() {
        if (fxPeer() instanceof com.jxparallel.fx.Fx.Owned) {
            ((com.jxparallel.fx.Fx.Owned) fxPeer()).callSuper("failed()", new Object[] {});
        } else {
            com.jxparallel.fx.Fx.invoke(fxPeer(), javafx.concurrent.ScheduledService.class, "failed", new Class<?>[] {});
        }
    }

    public com.jxparallel.fx.util.Callback<com.jxparallel.fx.concurrent.ScheduledService<?>, com.jxparallel.fx.util.Duration> getBackoffStrategy() {
        return (com.jxparallel.fx.util.Callback) com.jxparallel.fx.Fx.jx(((javafx.concurrent.ScheduledService) fxPeer()).getBackoffStrategy());
    }

    public com.jxparallel.fx.util.Duration getCumulativePeriod() {
        return (com.jxparallel.fx.util.Duration) com.jxparallel.fx.Fx.jx(((javafx.concurrent.ScheduledService) fxPeer()).getCumulativePeriod());
    }

    public int getCurrentFailureCount() {
        return ((javafx.concurrent.ScheduledService) fxPeer()).getCurrentFailureCount();
    }

    public com.jxparallel.fx.util.Duration getDelay() {
        return (com.jxparallel.fx.util.Duration) com.jxparallel.fx.Fx.jx(((javafx.concurrent.ScheduledService) fxPeer()).getDelay());
    }

    public V getLastValue() {
        return (V) com.jxparallel.fx.Fx.jx(((javafx.concurrent.ScheduledService) fxPeer()).getLastValue());
    }

    public com.jxparallel.fx.util.Duration getMaximumCumulativePeriod() {
        return (com.jxparallel.fx.util.Duration) com.jxparallel.fx.Fx.jx(((javafx.concurrent.ScheduledService) fxPeer()).getMaximumCumulativePeriod());
    }

    public int getMaximumFailureCount() {
        return ((javafx.concurrent.ScheduledService) fxPeer()).getMaximumFailureCount();
    }

    public com.jxparallel.fx.util.Duration getPeriod() {
        return (com.jxparallel.fx.util.Duration) com.jxparallel.fx.Fx.jx(((javafx.concurrent.ScheduledService) fxPeer()).getPeriod());
    }

    public boolean getRestartOnFailure() {
        return ((javafx.concurrent.ScheduledService) fxPeer()).getRestartOnFailure();
    }

    public com.jxparallel.fx.beans.property.ReadOnlyObjectProperty<V> lastValueProperty() {
        return (com.jxparallel.fx.beans.property.ReadOnlyObjectProperty) com.jxparallel.fx.Fx.jx(((javafx.concurrent.ScheduledService) fxPeer()).lastValueProperty());
    }

    public com.jxparallel.fx.beans.property.ObjectProperty<com.jxparallel.fx.util.Duration> maximumCumulativePeriodProperty() {
        return (com.jxparallel.fx.beans.property.ObjectProperty) com.jxparallel.fx.Fx.jx(((javafx.concurrent.ScheduledService) fxPeer()).maximumCumulativePeriodProperty());
    }

    public com.jxparallel.fx.beans.property.IntegerProperty maximumFailureCountProperty() {
        return (com.jxparallel.fx.beans.property.IntegerProperty) com.jxparallel.fx.Fx.jx(((javafx.concurrent.ScheduledService) fxPeer()).maximumFailureCountProperty());
    }

    public com.jxparallel.fx.beans.property.ObjectProperty<com.jxparallel.fx.util.Duration> periodProperty() {
        return (com.jxparallel.fx.beans.property.ObjectProperty) com.jxparallel.fx.Fx.jx(((javafx.concurrent.ScheduledService) fxPeer()).periodProperty());
    }

    public void reset() {
        ((javafx.concurrent.ScheduledService) fxPeer()).reset();
    }

    public com.jxparallel.fx.beans.property.BooleanProperty restartOnFailureProperty() {
        return (com.jxparallel.fx.beans.property.BooleanProperty) com.jxparallel.fx.Fx.jx(((javafx.concurrent.ScheduledService) fxPeer()).restartOnFailureProperty());
    }

    public void setBackoffStrategy(com.jxparallel.fx.util.Callback<com.jxparallel.fx.concurrent.ScheduledService<?>, com.jxparallel.fx.util.Duration> arg0) {
        ((javafx.concurrent.ScheduledService) fxPeer()).setBackoffStrategy((javafx.util.Callback) com.jxparallel.fx.Fx.fx(arg0));
    }

    public void setDelay(com.jxparallel.fx.util.Duration arg0) {
        ((javafx.concurrent.ScheduledService) fxPeer()).setDelay((javafx.util.Duration) com.jxparallel.fx.Fx.fx(arg0));
    }

    public void setMaximumCumulativePeriod(com.jxparallel.fx.util.Duration arg0) {
        ((javafx.concurrent.ScheduledService) fxPeer()).setMaximumCumulativePeriod((javafx.util.Duration) com.jxparallel.fx.Fx.fx(arg0));
    }

    public void setMaximumFailureCount(int arg0) {
        ((javafx.concurrent.ScheduledService) fxPeer()).setMaximumFailureCount(arg0);
    }

    public void setPeriod(com.jxparallel.fx.util.Duration arg0) {
        ((javafx.concurrent.ScheduledService) fxPeer()).setPeriod((javafx.util.Duration) com.jxparallel.fx.Fx.fx(arg0));
    }

    public void setRestartOnFailure(boolean arg0) {
        ((javafx.concurrent.ScheduledService) fxPeer()).setRestartOnFailure(arg0);
    }

    protected void succeeded() {
        if (fxPeer() instanceof com.jxparallel.fx.Fx.Owned) {
            ((com.jxparallel.fx.Fx.Owned) fxPeer()).callSuper("succeeded()", new Object[] {});
        } else {
            com.jxparallel.fx.Fx.invoke(fxPeer(), javafx.concurrent.ScheduledService.class, "succeeded", new Class<?>[] {});
        }
    }

    /** Called by the peer: runs the JX (possibly overridden) method. */
    public static Object $hook(Object self, String method, Object[] a) {
        ScheduledService jx = (ScheduledService) self;
        try {
        switch (method) {
            case "failed()":
                jx.failed();
                return null;
            case "succeeded()":
                jx.succeeded();
                return null;
            case "createTask()":
                return jx.createTask();
            case "cancelled()":
                jx.cancelled();
                return null;
            case "running()":
                jx.running();
                return null;
            case "scheduled()":
                jx.scheduled();
                return null;
            default:
                throw new IllegalArgumentException(method);
        }
        } catch (Exception e) {
            throw com.jxparallel.fx.Fx.sneaky(e);
        }
    }
}
