package com.jxparallel.fx.peer.scene;

/** JavaFX peer of {@link com.jxparallel.fx.scene.ImageCursor}; forwards overridable methods to it (generated by scripts/GenerateFxApi.java). */
@SuppressWarnings({"unchecked", "rawtypes", "deprecation", "serial"})
public class ImageCursor extends javafx.scene.ImageCursor implements com.jxparallel.fx.Fx.Owned {
    private Object jxOwner;

    public ImageCursor() {
        super();
    }

    public ImageCursor(@javafx.beans.NamedArg(value = "image") javafx.scene.image.Image arg0) {
        super(arg0);
    }

    public ImageCursor(@javafx.beans.NamedArg(value = "image") javafx.scene.image.Image arg0, @javafx.beans.NamedArg(value = "hotspotX") double arg1, @javafx.beans.NamedArg(value = "hotspotY") double arg2) {
        super(arg0, arg1, arg2);
    }

    @Override
    public Object jxOwner() {
        return jxOwner;
    }

    @Override
    public void jxOwner(Object owner) {
        this.jxOwner = owner;
    }

    @Override
    public Object callSuper(String method, Object[] a) {
        try {
        switch (method) {
            default:
                throw new AbstractMethodError(method);
        }
        } catch (Exception e) {
            throw com.jxparallel.fx.Fx.sneaky(e);
        }
    }
}
