package com.jxparallel.fx.peer.scene;

/** JavaFX peer of {@link com.jxparallel.fx.scene.Scene}; forwards overridable methods to it (generated by scripts/GenerateFxApi.java). */
@SuppressWarnings({"unchecked", "rawtypes", "deprecation", "serial"})
public class Scene extends javafx.scene.Scene implements com.jxparallel.fx.Fx.Owned {
    private Object jxOwner;

    public Scene(@javafx.beans.NamedArg(value = "root") javafx.scene.Parent arg0) {
        super(arg0);
    }

    public Scene(@javafx.beans.NamedArg(value = "root") javafx.scene.Parent arg0, @javafx.beans.NamedArg(value = "width") double arg1, @javafx.beans.NamedArg(value = "height") double arg2) {
        super(arg0, arg1, arg2);
    }

    public Scene(@javafx.beans.NamedArg(value = "root") javafx.scene.Parent arg0, @javafx.beans.NamedArg(value = "width", defaultValue = "-1") double arg1, @javafx.beans.NamedArg(value = "height", defaultValue = "-1") double arg2, @javafx.beans.NamedArg(value = "depthBuffer") boolean arg3) {
        super(arg0, arg1, arg2, arg3);
    }

    public Scene(@javafx.beans.NamedArg(value = "root") javafx.scene.Parent arg0, @javafx.beans.NamedArg(value = "width", defaultValue = "-1") double arg1, @javafx.beans.NamedArg(value = "height", defaultValue = "-1") double arg2, @javafx.beans.NamedArg(value = "depthBuffer") boolean arg3, @javafx.beans.NamedArg(value = "antiAliasing", defaultValue = "DISABLED") javafx.scene.SceneAntialiasing arg4) {
        super(arg0, arg1, arg2, arg3, arg4);
    }

    public Scene(@javafx.beans.NamedArg(value = "root") javafx.scene.Parent arg0, @javafx.beans.NamedArg(value = "width") double arg1, @javafx.beans.NamedArg(value = "height") double arg2, @javafx.beans.NamedArg(value = "fill", defaultValue = "WHITE") javafx.scene.paint.Paint arg3) {
        super(arg0, arg1, arg2, arg3);
    }

    public Scene(@javafx.beans.NamedArg(value = "root") javafx.scene.Parent arg0, @javafx.beans.NamedArg(value = "fill", defaultValue = "WHITE") javafx.scene.paint.Paint arg1) {
        super(arg0, arg1);
    }

    @Override
    public Object jxOwner() {
        return jxOwner;
    }

    @Override
    public void jxOwner(Object owner) {
        this.jxOwner = owner;
    }

    @Override
    public Object callSuper(String method, Object[] a) {
        try {
        switch (method) {
            default:
                throw new AbstractMethodError(method);
        }
        } catch (Exception e) {
            throw com.jxparallel.fx.Fx.sneaky(e);
        }
    }
}
