package com.jxparallel.fx.peer.scene;

/** JavaFX peer of {@link com.jxparallel.fx.scene.SubScene}; forwards overridable methods to it (generated by scripts/GenerateFxApi.java). */
@SuppressWarnings({"unchecked", "rawtypes", "deprecation", "serial"})
public class SubScene extends javafx.scene.SubScene implements com.jxparallel.fx.Fx.Owned {
    private Object jxOwner;

    public SubScene(@javafx.beans.NamedArg(value = "root") javafx.scene.Parent arg0, @javafx.beans.NamedArg(value = "width") double arg1, @javafx.beans.NamedArg(value = "height") double arg2) {
        super(arg0, arg1, arg2);
    }

    public SubScene(@javafx.beans.NamedArg(value = "root") javafx.scene.Parent arg0, @javafx.beans.NamedArg(value = "width") double arg1, @javafx.beans.NamedArg(value = "height") double arg2, @javafx.beans.NamedArg(value = "depthBuffer") boolean arg3, @javafx.beans.NamedArg(value = "antiAliasing") javafx.scene.SceneAntialiasing arg4) {
        super(arg0, arg1, arg2, arg3, arg4);
    }

    @Override
    public Object jxOwner() {
        return jxOwner;
    }

    @Override
    public void jxOwner(Object owner) {
        this.jxOwner = owner;
    }

    @Override
    public Object callSuper(String method, Object[] a) {
        try {
        switch (method) {
            default:
                throw new AbstractMethodError(method);
        }
        } catch (Exception e) {
            throw com.jxparallel.fx.Fx.sneaky(e);
        }
    }
}
