package com.jxparallel.fx.peer.scene.input;

/** JavaFX peer of {@link com.jxparallel.fx.scene.input.InputMethodTextRun}; forwards overridable methods to it (generated by scripts/GenerateFxApi.java). */
@SuppressWarnings({"unchecked", "rawtypes", "deprecation", "serial"})
public class InputMethodTextRun extends javafx.scene.input.InputMethodTextRun implements com.jxparallel.fx.Fx.Owned {
    private Object jxOwner;

    public InputMethodTextRun(@javafx.beans.NamedArg(value = "text") java.lang.String arg0, @javafx.beans.NamedArg(value = "highlight") javafx.scene.input.InputMethodHighlight arg1) {
        super(arg0, arg1);
    }

    @Override
    public Object jxOwner() {
        return jxOwner;
    }

    @Override
    public void jxOwner(Object owner) {
        this.jxOwner = owner;
    }

    @Override
    public Object callSuper(String method, Object[] a) {
        try {
        switch (method) {
            default:
                throw new AbstractMethodError(method);
        }
        } catch (Exception e) {
            throw com.jxparallel.fx.Fx.sneaky(e);
        }
    }
}
