package com.jxparallel.fx.peer.scene.input;

/** JavaFX peer of {@link com.jxparallel.fx.scene.input.KeyCombination}; forwards overridable methods to it (generated by scripts/GenerateFxApi.java). */
@SuppressWarnings({"unchecked", "rawtypes", "deprecation", "serial"})
public class KeyCombination extends javafx.scene.input.KeyCombination implements com.jxparallel.fx.Fx.Owned {
    private Object jxOwner;

    public KeyCombination(javafx.scene.input.KeyCombination.ModifierValue arg0, javafx.scene.input.KeyCombination.ModifierValue arg1, javafx.scene.input.KeyCombination.ModifierValue arg2, javafx.scene.input.KeyCombination.ModifierValue arg3, javafx.scene.input.KeyCombination.ModifierValue arg4) {
        super(arg0, arg1, arg2, arg3, arg4);
    }

    public KeyCombination(javafx.scene.input.KeyCombination.Modifier... arg0) {
        super(arg0);
    }

    @Override
    public Object jxOwner() {
        return jxOwner;
    }

    @Override
    public void jxOwner(Object owner) {
        this.jxOwner = owner;
    }

    @Override
    public Object callSuper(String method, Object[] a) {
        try {
        switch (method) {
            default:
                throw new AbstractMethodError(method);
        }
        } catch (Exception e) {
            throw com.jxparallel.fx.Fx.sneaky(e);
        }
    }
}
