package com.jxparallel.fx.peer.scene.input;

/** JavaFX peer of {@link com.jxparallel.fx.scene.input.MouseEvent}; forwards overridable methods to it (generated by scripts/GenerateFxApi.java). */
@SuppressWarnings({"unchecked", "rawtypes", "deprecation", "serial"})
public class MouseEvent extends javafx.scene.input.MouseEvent implements com.jxparallel.fx.Fx.Owned {
    private Object jxOwner;

    public MouseEvent(@javafx.beans.NamedArg(value = "source") java.lang.Object arg0, @javafx.beans.NamedArg(value = "target") javafx.event.EventTarget arg1, @javafx.beans.NamedArg(value = "eventType") javafx.event.EventType<? extends javafx.scene.input.MouseEvent> arg2, @javafx.beans.NamedArg(value = "x") double arg3, @javafx.beans.NamedArg(value = "y") double arg4, @javafx.beans.NamedArg(value = "screenX") double arg5, @javafx.beans.NamedArg(value = "screenY") double arg6, @javafx.beans.NamedArg(value = "button") javafx.scene.input.MouseButton arg7, @javafx.beans.NamedArg(value = "clickCount") int arg8, @javafx.beans.NamedArg(value = "shiftDown") boolean arg9, @javafx.beans.NamedArg(value = "controlDown") boolean arg10, @javafx.beans.NamedArg(value = "altDown") boolean arg11, @javafx.beans.NamedArg(value = "metaDown") boolean arg12, @javafx.beans.NamedArg(value = "primaryButtonDown") boolean arg13, @javafx.beans.NamedArg(value = "middleButtonDown") boolean arg14, @javafx.beans.NamedArg(value = "secondaryButtonDown") boolean arg15, @javafx.beans.NamedArg(value = "synthesized") boolean arg16, @javafx.beans.NamedArg(value = "popupTrigger") boolean arg17, @javafx.beans.NamedArg(value = "stillSincePress") boolean arg18, @javafx.beans.NamedArg(value = "pickResult") javafx.scene.input.PickResult arg19) {
        super(arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9, arg10, arg11, arg12, arg13, arg14, arg15, arg16, arg17, arg18, arg19);
    }

    public MouseEvent(@javafx.beans.NamedArg(value = "eventType") javafx.event.EventType<? extends javafx.scene.input.MouseEvent> arg0, @javafx.beans.NamedArg(value = "x") double arg1, @javafx.beans.NamedArg(value = "y") double arg2, @javafx.beans.NamedArg(value = "screenX") double arg3, @javafx.beans.NamedArg(value = "screenY") double arg4, @javafx.beans.NamedArg(value = "button") javafx.scene.input.MouseButton arg5, @javafx.beans.NamedArg(value = "clickCount") int arg6, @javafx.beans.NamedArg(value = "shiftDown") boolean arg7, @javafx.beans.NamedArg(value = "controlDown") boolean arg8, @javafx.beans.NamedArg(value = "altDown") boolean arg9, @javafx.beans.NamedArg(value = "metaDown") boolean arg10, @javafx.beans.NamedArg(value = "primaryButtonDown") boolean arg11, @javafx.beans.NamedArg(value = "middleButtonDown") boolean arg12, @javafx.beans.NamedArg(value = "secondaryButtonDown") boolean arg13, @javafx.beans.NamedArg(value = "synthesized") boolean arg14, @javafx.beans.NamedArg(value = "popupTrigger") boolean arg15, @javafx.beans.NamedArg(value = "stillSincePress") boolean arg16, @javafx.beans.NamedArg(value = "pickResult") javafx.scene.input.PickResult arg17) {
        super(arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9, arg10, arg11, arg12, arg13, arg14, arg15, arg16, arg17);
    }

    @Override
    public Object jxOwner() {
        return jxOwner;
    }

    @Override
    public void jxOwner(Object owner) {
        this.jxOwner = owner;
    }

    @Override
    public Object callSuper(String method, Object[] a) {
        try {
        switch (method) {
            default:
                throw new AbstractMethodError(method);
        }
        } catch (Exception e) {
            throw com.jxparallel.fx.Fx.sneaky(e);
        }
    }
}
