package com.jxparallel.fx.scene.input;

/** JXParallel counterpart of {@link javafx.scene.input.DragEvent} (generated by scripts/GenerateFxApi.java). */
@SuppressWarnings({"unchecked", "rawtypes", "deprecation"})
public final class DragEvent extends com.jxparallel.fx.scene.input.InputEvent {
    protected DragEvent(com.jxparallel.fx.Fx.Wrap wrap, Object peer) {
        super(wrap, peer);
    }

    public DragEvent(@javafx.beans.NamedArg(value = "eventType") com.jxparallel.fx.event.EventType<com.jxparallel.fx.scene.input.DragEvent> arg0, @javafx.beans.NamedArg(value = "dragboard") com.jxparallel.fx.scene.input.Dragboard arg1, @javafx.beans.NamedArg(value = "x") double arg2, @javafx.beans.NamedArg(value = "y") double arg3, @javafx.beans.NamedArg(value = "screenX") double arg4, @javafx.beans.NamedArg(value = "screenY") double arg5, @javafx.beans.NamedArg(value = "transferMode") com.jxparallel.fx.scene.input.TransferMode arg6, @javafx.beans.NamedArg(value = "gestureSource") java.lang.Object arg7, @javafx.beans.NamedArg(value = "gestureTarget") java.lang.Object arg8, @javafx.beans.NamedArg(value = "pickResult") com.jxparallel.fx.scene.input.PickResult arg9) {
        this(com.jxparallel.fx.Fx.WRAP, com.jxparallel.fx.Fx.NATIVE ? com.jxparallel.fx.nativeimpl.Native.create(javafx.scene.input.DragEvent.class, new String[] {"eventType", "dragboard", "x", "y", "screenX", "screenY", "transferMode", "gestureSource", "gestureTarget", "pickResult"}, new Object[] {arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9}) : new javafx.scene.input.DragEvent((javafx.event.EventType) com.jxparallel.fx.Fx.fx(arg0), (javafx.scene.input.Dragboard) com.jxparallel.fx.Fx.fx(arg1), arg2, arg3, arg4, arg5, (javafx.scene.input.TransferMode) com.jxparallel.fx.Fx.fx(arg6), (java.lang.Object) com.jxparallel.fx.Fx.fx(arg7), (java.lang.Object) com.jxparallel.fx.Fx.fx(arg8), (javafx.scene.input.PickResult) com.jxparallel.fx.Fx.fx(arg9)));
        com.jxparallel.fx.Fx.own(fxPeer(), this);
    }

    public DragEvent(@javafx.beans.NamedArg(value = "source") java.lang.Object arg0, @javafx.beans.NamedArg(value = "target") com.jxparallel.fx.event.EventTarget arg1, @javafx.beans.NamedArg(value = "eventType") com.jxparallel.fx.event.EventType<com.jxparallel.fx.scene.input.DragEvent> arg2, @javafx.beans.NamedArg(value = "dragboard") com.jxparallel.fx.scene.input.Dragboard arg3, @javafx.beans.NamedArg(value = "x") double arg4, @javafx.beans.NamedArg(value = "y") double arg5, @javafx.beans.NamedArg(value = "screenX") double arg6, @javafx.beans.NamedArg(value = "screenY") double arg7, @javafx.beans.NamedArg(value = "transferMode") com.jxparallel.fx.scene.input.TransferMode arg8, @javafx.beans.NamedArg(value = "gestureSource") java.lang.Object arg9, @javafx.beans.NamedArg(value = "gestureTarget") java.lang.Object arg10, @javafx.beans.NamedArg(value = "pickResult") com.jxparallel.fx.scene.input.PickResult arg11) {
        this(com.jxparallel.fx.Fx.WRAP, com.jxparallel.fx.Fx.NATIVE ? com.jxparallel.fx.nativeimpl.Native.create(javafx.scene.input.DragEvent.class, new String[] {"source", "target", "eventType", "dragboard", "x", "y", "screenX", "screenY", "transferMode", "gestureSource", "gestureTarget", "pickResult"}, new Object[] {arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9, arg10, arg11}) : new javafx.scene.input.DragEvent((java.lang.Object) com.jxparallel.fx.Fx.fx(arg0), (javafx.event.EventTarget) com.jxparallel.fx.Fx.fx(arg1), (javafx.event.EventType) com.jxparallel.fx.Fx.fx(arg2), (javafx.scene.input.Dragboard) com.jxparallel.fx.Fx.fx(arg3), arg4, arg5, arg6, arg7, (javafx.scene.input.TransferMode) com.jxparallel.fx.Fx.fx(arg8), (java.lang.Object) com.jxparallel.fx.Fx.fx(arg9), (java.lang.Object) com.jxparallel.fx.Fx.fx(arg10), (javafx.scene.input.PickResult) com.jxparallel.fx.Fx.fx(arg11)));
        com.jxparallel.fx.Fx.own(fxPeer(), this);
    }

    public static final com.jxparallel.fx.event.EventType<com.jxparallel.fx.scene.input.DragEvent> ANY = (com.jxparallel.fx.event.EventType) com.jxparallel.fx.Fx.jx(javafx.scene.input.DragEvent.ANY);

    public static final com.jxparallel.fx.event.EventType<com.jxparallel.fx.scene.input.DragEvent> DRAG_ENTERED_TARGET = (com.jxparallel.fx.event.EventType) com.jxparallel.fx.Fx.jx(javafx.scene.input.DragEvent.DRAG_ENTERED_TARGET);

    public static final com.jxparallel.fx.event.EventType<com.jxparallel.fx.scene.input.DragEvent> DRAG_ENTERED = (com.jxparallel.fx.event.EventType) com.jxparallel.fx.Fx.jx(javafx.scene.input.DragEvent.DRAG_ENTERED);

    public static final com.jxparallel.fx.event.EventType<com.jxparallel.fx.scene.input.DragEvent> DRAG_EXITED_TARGET = (com.jxparallel.fx.event.EventType) com.jxparallel.fx.Fx.jx(javafx.scene.input.DragEvent.DRAG_EXITED_TARGET);

    public static final com.jxparallel.fx.event.EventType<com.jxparallel.fx.scene.input.DragEvent> DRAG_EXITED = (com.jxparallel.fx.event.EventType) com.jxparallel.fx.Fx.jx(javafx.scene.input.DragEvent.DRAG_EXITED);

    public static final com.jxparallel.fx.event.EventType<com.jxparallel.fx.scene.input.DragEvent> DRAG_OVER = (com.jxparallel.fx.event.EventType) com.jxparallel.fx.Fx.jx(javafx.scene.input.DragEvent.DRAG_OVER);

    public static final com.jxparallel.fx.event.EventType<com.jxparallel.fx.scene.input.DragEvent> DRAG_DROPPED = (com.jxparallel.fx.event.EventType) com.jxparallel.fx.Fx.jx(javafx.scene.input.DragEvent.DRAG_DROPPED);

    public static final com.jxparallel.fx.event.EventType<com.jxparallel.fx.scene.input.DragEvent> DRAG_DONE = (com.jxparallel.fx.event.EventType) com.jxparallel.fx.Fx.jx(javafx.scene.input.DragEvent.DRAG_DONE);

    public void acceptTransferModes(com.jxparallel.fx.scene.input.TransferMode... arg0) {
        if (com.jxparallel.fx.Fx.NATIVE) {
            com.jxparallel.fx.nativeimpl.Native.call(this, com.jxparallel.fx.scene.input.DragEvent.class, "acceptTransferModes", new Class<?>[] {com.jxparallel.fx.scene.input.TransferMode[].class}, void.class, arg0);
            return;
        }
        ((javafx.scene.input.DragEvent) fxPeer()).acceptTransferModes((javafx.scene.input.TransferMode[]) com.jxparallel.fx.Fx.fxArray(arg0, javafx.scene.input.TransferMode.class));
    }

    public com.jxparallel.fx.scene.input.DragEvent copyFor(java.lang.Object arg0, com.jxparallel.fx.event.EventTarget arg1) {
        if (com.jxparallel.fx.Fx.NATIVE) {
            return (com.jxparallel.fx.scene.input.DragEvent) com.jxparallel.fx.nativeimpl.Native.call(this, com.jxparallel.fx.scene.input.DragEvent.class, "copyFor", new Class<?>[] {java.lang.Object.class, com.jxparallel.fx.event.EventTarget.class}, com.jxparallel.fx.scene.input.DragEvent.class, arg0, arg1);
        }
        return (com.jxparallel.fx.scene.input.DragEvent) com.jxparallel.fx.Fx.jx(((javafx.scene.input.DragEvent) fxPeer()).copyFor((java.lang.Object) com.jxparallel.fx.Fx.fx(arg0), (javafx.event.EventTarget) com.jxparallel.fx.Fx.fx(arg1)));
    }

    public com.jxparallel.fx.scene.input.DragEvent copyFor(java.lang.Object arg0, com.jxparallel.fx.event.EventTarget arg1, com.jxparallel.fx.event.EventType<com.jxparallel.fx.scene.input.DragEvent> arg2) {
        if (com.jxparallel.fx.Fx.NATIVE) {
            return (com.jxparallel.fx.scene.input.DragEvent) com.jxparallel.fx.nativeimpl.Native.call(this, com.jxparallel.fx.scene.input.DragEvent.class, "copyFor", new Class<?>[] {java.lang.Object.class, com.jxparallel.fx.event.EventTarget.class, com.jxparallel.fx.event.EventType.class}, com.jxparallel.fx.scene.input.DragEvent.class, arg0, arg1, arg2);
        }
        return (com.jxparallel.fx.scene.input.DragEvent) com.jxparallel.fx.Fx.jx(((javafx.scene.input.DragEvent) fxPeer()).copyFor((java.lang.Object) com.jxparallel.fx.Fx.fx(arg0), (javafx.event.EventTarget) com.jxparallel.fx.Fx.fx(arg1), (javafx.event.EventType) com.jxparallel.fx.Fx.fx(arg2)));
    }

    public com.jxparallel.fx.scene.input.DragEvent copyFor(java.lang.Object arg0, com.jxparallel.fx.event.EventTarget arg1, java.lang.Object arg2, java.lang.Object arg3, com.jxparallel.fx.event.EventType<com.jxparallel.fx.scene.input.DragEvent> arg4) {
        if (com.jxparallel.fx.Fx.NATIVE) {
            return (com.jxparallel.fx.scene.input.DragEvent) com.jxparallel.fx.nativeimpl.Native.call(this, com.jxparallel.fx.scene.input.DragEvent.class, "copyFor", new Class<?>[] {java.lang.Object.class, com.jxparallel.fx.event.EventTarget.class, java.lang.Object.class, java.lang.Object.class, com.jxparallel.fx.event.EventType.class}, com.jxparallel.fx.scene.input.DragEvent.class, arg0, arg1, arg2, arg3, arg4);
        }
        return (com.jxparallel.fx.scene.input.DragEvent) com.jxparallel.fx.Fx.jx(((javafx.scene.input.DragEvent) fxPeer()).copyFor((java.lang.Object) com.jxparallel.fx.Fx.fx(arg0), (javafx.event.EventTarget) com.jxparallel.fx.Fx.fx(arg1), (java.lang.Object) com.jxparallel.fx.Fx.fx(arg2), (java.lang.Object) com.jxparallel.fx.Fx.fx(arg3), (javafx.event.EventType) com.jxparallel.fx.Fx.fx(arg4)));
    }

    public com.jxparallel.fx.scene.input.TransferMode getAcceptedTransferMode() {
        if (com.jxparallel.fx.Fx.NATIVE) {
            return (com.jxparallel.fx.scene.input.TransferMode) com.jxparallel.fx.nativeimpl.Native.call(this, com.jxparallel.fx.scene.input.DragEvent.class, "getAcceptedTransferMode", new Class<?>[] {}, com.jxparallel.fx.scene.input.TransferMode.class);
        }
        return (com.jxparallel.fx.scene.input.TransferMode) com.jxparallel.fx.Fx.jx(((javafx.scene.input.DragEvent) fxPeer()).getAcceptedTransferMode());
    }

    public java.lang.Object getAcceptingObject() {
        if (com.jxparallel.fx.Fx.NATIVE) {
            return (java.lang.Object) com.jxparallel.fx.nativeimpl.Native.call(this, com.jxparallel.fx.scene.input.DragEvent.class, "getAcceptingObject", new Class<?>[] {}, java.lang.Object.class);
        }
        return (java.lang.Object) com.jxparallel.fx.Fx.jx(((javafx.scene.input.DragEvent) fxPeer()).getAcceptingObject());
    }

    public com.jxparallel.fx.scene.input.Dragboard getDragboard() {
        if (com.jxparallel.fx.Fx.NATIVE) {
            return (com.jxparallel.fx.scene.input.Dragboard) com.jxparallel.fx.nativeimpl.Native.call(this, com.jxparallel.fx.scene.input.DragEvent.class, "getDragboard", new Class<?>[] {}, com.jxparallel.fx.scene.input.Dragboard.class);
        }
        return (com.jxparallel.fx.scene.input.Dragboard) com.jxparallel.fx.Fx.jx(((javafx.scene.input.DragEvent) fxPeer()).getDragboard());
    }

    public com.jxparallel.fx.event.EventType<com.jxparallel.fx.scene.input.DragEvent> getEventType() {
        if (com.jxparallel.fx.Fx.NATIVE) {
            return (com.jxparallel.fx.event.EventType) com.jxparallel.fx.nativeimpl.Native.call(this, com.jxparallel.fx.scene.input.DragEvent.class, "getEventType", new Class<?>[] {}, com.jxparallel.fx.event.EventType.class);
        }
        return (com.jxparallel.fx.event.EventType) com.jxparallel.fx.Fx.jx(((javafx.scene.input.DragEvent) fxPeer()).getEventType());
    }

    public java.lang.Object getGestureSource() {
        if (com.jxparallel.fx.Fx.NATIVE) {
            return (java.lang.Object) com.jxparallel.fx.nativeimpl.Native.call(this, com.jxparallel.fx.scene.input.DragEvent.class, "getGestureSource", new Class<?>[] {}, java.lang.Object.class);
        }
        return (java.lang.Object) com.jxparallel.fx.Fx.jx(((javafx.scene.input.DragEvent) fxPeer()).getGestureSource());
    }

    public java.lang.Object getGestureTarget() {
        if (com.jxparallel.fx.Fx.NATIVE) {
            return (java.lang.Object) com.jxparallel.fx.nativeimpl.Native.call(this, com.jxparallel.fx.scene.input.DragEvent.class, "getGestureTarget", new Class<?>[] {}, java.lang.Object.class);
        }
        return (java.lang.Object) com.jxparallel.fx.Fx.jx(((javafx.scene.input.DragEvent) fxPeer()).getGestureTarget());
    }

    public com.jxparallel.fx.scene.input.PickResult getPickResult() {
        if (com.jxparallel.fx.Fx.NATIVE) {
            return (com.jxparallel.fx.scene.input.PickResult) com.jxparallel.fx.nativeimpl.Native.call(this, com.jxparallel.fx.scene.input.DragEvent.class, "getPickResult", new Class<?>[] {}, com.jxparallel.fx.scene.input.PickResult.class);
        }
        return (com.jxparallel.fx.scene.input.PickResult) com.jxparallel.fx.Fx.jx(((javafx.scene.input.DragEvent) fxPeer()).getPickResult());
    }

    public double getSceneX() {
        if (com.jxparallel.fx.Fx.NATIVE) {
            return (Double) com.jxparallel.fx.nativeimpl.Native.call(this, com.jxparallel.fx.scene.input.DragEvent.class, "getSceneX", new Class<?>[] {}, double.class);
        }
        return ((javafx.scene.input.DragEvent) fxPeer()).getSceneX();
    }

    public double getSceneY() {
        if (com.jxparallel.fx.Fx.NATIVE) {
            return (Double) com.jxparallel.fx.nativeimpl.Native.call(this, com.jxparallel.fx.scene.input.DragEvent.class, "getSceneY", new Class<?>[] {}, double.class);
        }
        return ((javafx.scene.input.DragEvent) fxPeer()).getSceneY();
    }

    public double getScreenX() {
        if (com.jxparallel.fx.Fx.NATIVE) {
            return (Double) com.jxparallel.fx.nativeimpl.Native.call(this, com.jxparallel.fx.scene.input.DragEvent.class, "getScreenX", new Class<?>[] {}, double.class);
        }
        return ((javafx.scene.input.DragEvent) fxPeer()).getScreenX();
    }

    public double getScreenY() {
        if (com.jxparallel.fx.Fx.NATIVE) {
            return (Double) com.jxparallel.fx.nativeimpl.Native.call(this, com.jxparallel.fx.scene.input.DragEvent.class, "getScreenY", new Class<?>[] {}, double.class);
        }
        return ((javafx.scene.input.DragEvent) fxPeer()).getScreenY();
    }

    public com.jxparallel.fx.scene.input.TransferMode getTransferMode() {
        if (com.jxparallel.fx.Fx.NATIVE) {
            return (com.jxparallel.fx.scene.input.TransferMode) com.jxparallel.fx.nativeimpl.Native.call(this, com.jxparallel.fx.scene.input.DragEvent.class, "getTransferMode", new Class<?>[] {}, com.jxparallel.fx.scene.input.TransferMode.class);
        }
        return (com.jxparallel.fx.scene.input.TransferMode) com.jxparallel.fx.Fx.jx(((javafx.scene.input.DragEvent) fxPeer()).getTransferMode());
    }

    public double getX() {
        if (com.jxparallel.fx.Fx.NATIVE) {
            return (Double) com.jxparallel.fx.nativeimpl.Native.call(this, com.jxparallel.fx.scene.input.DragEvent.class, "getX", new Class<?>[] {}, double.class);
        }
        return ((javafx.scene.input.DragEvent) fxPeer()).getX();
    }

    public double getY() {
        if (com.jxparallel.fx.Fx.NATIVE) {
            return (Double) com.jxparallel.fx.nativeimpl.Native.call(this, com.jxparallel.fx.scene.input.DragEvent.class, "getY", new Class<?>[] {}, double.class);
        }
        return ((javafx.scene.input.DragEvent) fxPeer()).getY();
    }

    public double getZ() {
        if (com.jxparallel.fx.Fx.NATIVE) {
            return (Double) com.jxparallel.fx.nativeimpl.Native.call(this, com.jxparallel.fx.scene.input.DragEvent.class, "getZ", new Class<?>[] {}, double.class);
        }
        return ((javafx.scene.input.DragEvent) fxPeer()).getZ();
    }

    public boolean isAccepted() {
        if (com.jxparallel.fx.Fx.NATIVE) {
            return (Boolean) com.jxparallel.fx.nativeimpl.Native.call(this, com.jxparallel.fx.scene.input.DragEvent.class, "isAccepted", new Class<?>[] {}, boolean.class);
        }
        return ((javafx.scene.input.DragEvent) fxPeer()).isAccepted();
    }

    public boolean isDropCompleted() {
        if (com.jxparallel.fx.Fx.NATIVE) {
            return (Boolean) com.jxparallel.fx.nativeimpl.Native.call(this, com.jxparallel.fx.scene.input.DragEvent.class, "isDropCompleted", new Class<?>[] {}, boolean.class);
        }
        return ((javafx.scene.input.DragEvent) fxPeer()).isDropCompleted();
    }

    public void setDropCompleted(boolean arg0) {
        if (com.jxparallel.fx.Fx.NATIVE) {
            com.jxparallel.fx.nativeimpl.Native.call(this, com.jxparallel.fx.scene.input.DragEvent.class, "setDropCompleted", new Class<?>[] {boolean.class}, void.class, arg0);
            return;
        }
        ((javafx.scene.input.DragEvent) fxPeer()).setDropCompleted(arg0);
    }
}
