package com.jxparallel.fx.scene.input;

/** JXParallel counterpart of {@link javafx.scene.input.GestureEvent} (generated by scripts/GenerateFxApi.java). */
@SuppressWarnings({"unchecked", "rawtypes", "deprecation"})
public class GestureEvent extends com.jxparallel.fx.scene.input.InputEvent {
    protected GestureEvent(com.jxparallel.fx.Fx.Wrap wrap, Object peer) {
        super(wrap, peer);
    }

    protected GestureEvent(java.lang.Object arg0, com.jxparallel.fx.event.EventTarget arg1, com.jxparallel.fx.event.EventType<? extends com.jxparallel.fx.scene.input.GestureEvent> arg2) {
        this(com.jxparallel.fx.Fx.WRAP, new com.jxparallel.fx.peer.scene.input.GestureEvent((java.lang.Object) com.jxparallel.fx.Fx.fx(arg0), (javafx.event.EventTarget) com.jxparallel.fx.Fx.fx(arg1), (javafx.event.EventType) com.jxparallel.fx.Fx.fx(arg2)));
        com.jxparallel.fx.Fx.own(fxPeer(), this);
    }

    protected GestureEvent(java.lang.Object arg0, com.jxparallel.fx.event.EventTarget arg1, com.jxparallel.fx.event.EventType<? extends com.jxparallel.fx.scene.input.GestureEvent> arg2, double arg3, double arg4, double arg5, double arg6, boolean arg7, boolean arg8, boolean arg9, boolean arg10, boolean arg11, boolean arg12, com.jxparallel.fx.scene.input.PickResult arg13) {
        this(com.jxparallel.fx.Fx.WRAP, new com.jxparallel.fx.peer.scene.input.GestureEvent((java.lang.Object) com.jxparallel.fx.Fx.fx(arg0), (javafx.event.EventTarget) com.jxparallel.fx.Fx.fx(arg1), (javafx.event.EventType) com.jxparallel.fx.Fx.fx(arg2), arg3, arg4, arg5, arg6, arg7, arg8, arg9, arg10, arg11, arg12, (javafx.scene.input.PickResult) com.jxparallel.fx.Fx.fx(arg13)));
        com.jxparallel.fx.Fx.own(fxPeer(), this);
    }

    protected GestureEvent(com.jxparallel.fx.event.EventType<? extends com.jxparallel.fx.scene.input.GestureEvent> arg0) {
        this(com.jxparallel.fx.Fx.WRAP, new com.jxparallel.fx.peer.scene.input.GestureEvent((javafx.event.EventType) com.jxparallel.fx.Fx.fx(arg0)));
        com.jxparallel.fx.Fx.own(fxPeer(), this);
    }

    protected GestureEvent(com.jxparallel.fx.event.EventType<? extends com.jxparallel.fx.scene.input.GestureEvent> arg0, double arg1, double arg2, double arg3, double arg4, boolean arg5, boolean arg6, boolean arg7, boolean arg8, boolean arg9, boolean arg10, com.jxparallel.fx.scene.input.PickResult arg11) {
        this(com.jxparallel.fx.Fx.WRAP, new com.jxparallel.fx.peer.scene.input.GestureEvent((javafx.event.EventType) com.jxparallel.fx.Fx.fx(arg0), arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9, arg10, (javafx.scene.input.PickResult) com.jxparallel.fx.Fx.fx(arg11)));
        com.jxparallel.fx.Fx.own(fxPeer(), this);
    }

    public static final com.jxparallel.fx.event.EventType<com.jxparallel.fx.scene.input.GestureEvent> ANY = (com.jxparallel.fx.event.EventType) com.jxparallel.fx.Fx.jx(javafx.scene.input.GestureEvent.ANY);

    public com.jxparallel.fx.scene.input.GestureEvent copyFor(java.lang.Object arg0, com.jxparallel.fx.event.EventTarget arg1) {
        return (com.jxparallel.fx.scene.input.GestureEvent) com.jxparallel.fx.Fx.jx(((javafx.scene.input.GestureEvent) fxPeer()).copyFor((java.lang.Object) com.jxparallel.fx.Fx.fx(arg0), (javafx.event.EventTarget) com.jxparallel.fx.Fx.fx(arg1)));
    }

    public com.jxparallel.fx.event.EventType<? extends com.jxparallel.fx.scene.input.GestureEvent> getEventType() {
        return (com.jxparallel.fx.event.EventType) com.jxparallel.fx.Fx.jx(((javafx.scene.input.GestureEvent) fxPeer()).getEventType());
    }

    public com.jxparallel.fx.scene.input.PickResult getPickResult() {
        return (com.jxparallel.fx.scene.input.PickResult) com.jxparallel.fx.Fx.jx(((javafx.scene.input.GestureEvent) fxPeer()).getPickResult());
    }

    public double getSceneX() {
        return ((javafx.scene.input.GestureEvent) fxPeer()).getSceneX();
    }

    public double getSceneY() {
        return ((javafx.scene.input.GestureEvent) fxPeer()).getSceneY();
    }

    public double getScreenX() {
        return ((javafx.scene.input.GestureEvent) fxPeer()).getScreenX();
    }

    public double getScreenY() {
        return ((javafx.scene.input.GestureEvent) fxPeer()).getScreenY();
    }

    public double getX() {
        return ((javafx.scene.input.GestureEvent) fxPeer()).getX();
    }

    public double getY() {
        return ((javafx.scene.input.GestureEvent) fxPeer()).getY();
    }

    public double getZ() {
        return ((javafx.scene.input.GestureEvent) fxPeer()).getZ();
    }

    public boolean isAltDown() {
        return ((javafx.scene.input.GestureEvent) fxPeer()).isAltDown();
    }

    public boolean isControlDown() {
        return ((javafx.scene.input.GestureEvent) fxPeer()).isControlDown();
    }

    public boolean isDirect() {
        return ((javafx.scene.input.GestureEvent) fxPeer()).isDirect();
    }

    public boolean isInertia() {
        return ((javafx.scene.input.GestureEvent) fxPeer()).isInertia();
    }

    public boolean isMetaDown() {
        return ((javafx.scene.input.GestureEvent) fxPeer()).isMetaDown();
    }

    public boolean isShiftDown() {
        return ((javafx.scene.input.GestureEvent) fxPeer()).isShiftDown();
    }

    public boolean isShortcutDown() {
        return ((javafx.scene.input.GestureEvent) fxPeer()).isShortcutDown();
    }
}
