package com.jxparallel.fx.scene.input;

/** JXParallel counterpart of {@link javafx.scene.input.KeyEvent} (generated by scripts/GenerateFxApi.java). */
@SuppressWarnings({"unchecked", "rawtypes", "deprecation"})
public final class KeyEvent extends com.jxparallel.fx.scene.input.InputEvent {
    protected KeyEvent(com.jxparallel.fx.Fx.Wrap wrap, Object peer) {
        super(wrap, peer);
    }

    public KeyEvent(@javafx.beans.NamedArg(value = "source") java.lang.Object arg0, @javafx.beans.NamedArg(value = "target") com.jxparallel.fx.event.EventTarget arg1, @javafx.beans.NamedArg(value = "eventType") com.jxparallel.fx.event.EventType<com.jxparallel.fx.scene.input.KeyEvent> arg2, @javafx.beans.NamedArg(value = "character") java.lang.String arg3, @javafx.beans.NamedArg(value = "text") java.lang.String arg4, @javafx.beans.NamedArg(value = "code") com.jxparallel.fx.scene.input.KeyCode arg5, @javafx.beans.NamedArg(value = "shiftDown") boolean arg6, @javafx.beans.NamedArg(value = "controlDown") boolean arg7, @javafx.beans.NamedArg(value = "altDown") boolean arg8, @javafx.beans.NamedArg(value = "metaDown") boolean arg9) {
        this(com.jxparallel.fx.Fx.WRAP, new javafx.scene.input.KeyEvent((java.lang.Object) com.jxparallel.fx.Fx.fx(arg0), (javafx.event.EventTarget) com.jxparallel.fx.Fx.fx(arg1), (javafx.event.EventType) com.jxparallel.fx.Fx.fx(arg2), arg3, arg4, (javafx.scene.input.KeyCode) com.jxparallel.fx.Fx.fx(arg5), arg6, arg7, arg8, arg9));
        com.jxparallel.fx.Fx.own(fxPeer(), this);
    }

    public KeyEvent(@javafx.beans.NamedArg(value = "eventType") com.jxparallel.fx.event.EventType<com.jxparallel.fx.scene.input.KeyEvent> arg0, @javafx.beans.NamedArg(value = "character") java.lang.String arg1, @javafx.beans.NamedArg(value = "text") java.lang.String arg2, @javafx.beans.NamedArg(value = "code") com.jxparallel.fx.scene.input.KeyCode arg3, @javafx.beans.NamedArg(value = "shiftDown") boolean arg4, @javafx.beans.NamedArg(value = "controlDown") boolean arg5, @javafx.beans.NamedArg(value = "altDown") boolean arg6, @javafx.beans.NamedArg(value = "metaDown") boolean arg7) {
        this(com.jxparallel.fx.Fx.WRAP, new javafx.scene.input.KeyEvent((javafx.event.EventType) com.jxparallel.fx.Fx.fx(arg0), arg1, arg2, (javafx.scene.input.KeyCode) com.jxparallel.fx.Fx.fx(arg3), arg4, arg5, arg6, arg7));
        com.jxparallel.fx.Fx.own(fxPeer(), this);
    }

    public static final com.jxparallel.fx.event.EventType<com.jxparallel.fx.scene.input.KeyEvent> ANY = (com.jxparallel.fx.event.EventType) com.jxparallel.fx.Fx.jx(javafx.scene.input.KeyEvent.ANY);

    public static final com.jxparallel.fx.event.EventType<com.jxparallel.fx.scene.input.KeyEvent> KEY_PRESSED = (com.jxparallel.fx.event.EventType) com.jxparallel.fx.Fx.jx(javafx.scene.input.KeyEvent.KEY_PRESSED);

    public static final com.jxparallel.fx.event.EventType<com.jxparallel.fx.scene.input.KeyEvent> KEY_RELEASED = (com.jxparallel.fx.event.EventType) com.jxparallel.fx.Fx.jx(javafx.scene.input.KeyEvent.KEY_RELEASED);

    public static final com.jxparallel.fx.event.EventType<com.jxparallel.fx.scene.input.KeyEvent> KEY_TYPED = (com.jxparallel.fx.event.EventType) com.jxparallel.fx.Fx.jx(javafx.scene.input.KeyEvent.KEY_TYPED);

    public static final java.lang.String CHAR_UNDEFINED = javafx.scene.input.KeyEvent.CHAR_UNDEFINED;

    public com.jxparallel.fx.scene.input.KeyEvent copyFor(java.lang.Object arg0, com.jxparallel.fx.event.EventTarget arg1) {
        return (com.jxparallel.fx.scene.input.KeyEvent) com.jxparallel.fx.Fx.jx(((javafx.scene.input.KeyEvent) fxPeer()).copyFor((java.lang.Object) com.jxparallel.fx.Fx.fx(arg0), (javafx.event.EventTarget) com.jxparallel.fx.Fx.fx(arg1)));
    }

    public com.jxparallel.fx.scene.input.KeyEvent copyFor(java.lang.Object arg0, com.jxparallel.fx.event.EventTarget arg1, com.jxparallel.fx.event.EventType<com.jxparallel.fx.scene.input.KeyEvent> arg2) {
        return (com.jxparallel.fx.scene.input.KeyEvent) com.jxparallel.fx.Fx.jx(((javafx.scene.input.KeyEvent) fxPeer()).copyFor((java.lang.Object) com.jxparallel.fx.Fx.fx(arg0), (javafx.event.EventTarget) com.jxparallel.fx.Fx.fx(arg1), (javafx.event.EventType) com.jxparallel.fx.Fx.fx(arg2)));
    }

    public java.lang.String getCharacter() {
        return ((javafx.scene.input.KeyEvent) fxPeer()).getCharacter();
    }

    public com.jxparallel.fx.scene.input.KeyCode getCode() {
        return (com.jxparallel.fx.scene.input.KeyCode) com.jxparallel.fx.Fx.jx(((javafx.scene.input.KeyEvent) fxPeer()).getCode());
    }

    public com.jxparallel.fx.event.EventType<com.jxparallel.fx.scene.input.KeyEvent> getEventType() {
        return (com.jxparallel.fx.event.EventType) com.jxparallel.fx.Fx.jx(((javafx.scene.input.KeyEvent) fxPeer()).getEventType());
    }

    public java.lang.String getText() {
        return ((javafx.scene.input.KeyEvent) fxPeer()).getText();
    }

    public boolean isAltDown() {
        return ((javafx.scene.input.KeyEvent) fxPeer()).isAltDown();
    }

    public boolean isControlDown() {
        return ((javafx.scene.input.KeyEvent) fxPeer()).isControlDown();
    }

    public boolean isMetaDown() {
        return ((javafx.scene.input.KeyEvent) fxPeer()).isMetaDown();
    }

    public boolean isShiftDown() {
        return ((javafx.scene.input.KeyEvent) fxPeer()).isShiftDown();
    }

    public boolean isShortcutDown() {
        return ((javafx.scene.input.KeyEvent) fxPeer()).isShortcutDown();
    }
}
