package com.jxparallel.fx.scene.input;

/** JXParallel counterpart of {@link javafx.scene.input.MouseButton} (generated by scripts/GenerateFxApi.java). */
@SuppressWarnings({"unchecked", "rawtypes", "deprecation"})
public enum MouseButton {
    NONE,
    PRIMARY,
    MIDDLE,
    SECONDARY;
}
