package com.jxparallel.fx.scene.input;

/** JXParallel counterpart of {@link javafx.scene.input.ScrollEvent} (generated by scripts/GenerateFxApi.java). */
@SuppressWarnings({"unchecked", "rawtypes", "deprecation"})
public final class ScrollEvent extends com.jxparallel.fx.scene.input.GestureEvent {
    protected ScrollEvent(com.jxparallel.fx.Fx.Wrap wrap, Object peer) {
        super(wrap, peer);
    }

    public ScrollEvent(@javafx.beans.NamedArg(value = "source") java.lang.Object arg0, @javafx.beans.NamedArg(value = "target") com.jxparallel.fx.event.EventTarget arg1, @javafx.beans.NamedArg(value = "eventType") com.jxparallel.fx.event.EventType<com.jxparallel.fx.scene.input.ScrollEvent> arg2, @javafx.beans.NamedArg(value = "x") double arg3, @javafx.beans.NamedArg(value = "y") double arg4, @javafx.beans.NamedArg(value = "screenX") double arg5, @javafx.beans.NamedArg(value = "screenY") double arg6, @javafx.beans.NamedArg(value = "shiftDown") boolean arg7, @javafx.beans.NamedArg(value = "controlDown") boolean arg8, @javafx.beans.NamedArg(value = "altDown") boolean arg9, @javafx.beans.NamedArg(value = "metaDown") boolean arg10, @javafx.beans.NamedArg(value = "direct") boolean arg11, @javafx.beans.NamedArg(value = "inertia") boolean arg12, @javafx.beans.NamedArg(value = "deltaX") double arg13, @javafx.beans.NamedArg(value = "deltaY") double arg14, @javafx.beans.NamedArg(value = "totalDeltaX") double arg15, @javafx.beans.NamedArg(value = "totalDeltaY") double arg16, @javafx.beans.NamedArg(value = "textDeltaXUnits") com.jxparallel.fx.scene.input.ScrollEvent.HorizontalTextScrollUnits arg17, @javafx.beans.NamedArg(value = "textDeltaX") double arg18, @javafx.beans.NamedArg(value = "textDeltaYUnits") com.jxparallel.fx.scene.input.ScrollEvent.VerticalTextScrollUnits arg19, @javafx.beans.NamedArg(value = "textDeltaY") double arg20, @javafx.beans.NamedArg(value = "touchCount") int arg21, @javafx.beans.NamedArg(value = "pickResult") com.jxparallel.fx.scene.input.PickResult arg22) {
        this(com.jxparallel.fx.Fx.WRAP, new javafx.scene.input.ScrollEvent((java.lang.Object) com.jxparallel.fx.Fx.fx(arg0), (javafx.event.EventTarget) com.jxparallel.fx.Fx.fx(arg1), (javafx.event.EventType) com.jxparallel.fx.Fx.fx(arg2), arg3, arg4, arg5, arg6, arg7, arg8, arg9, arg10, arg11, arg12, arg13, arg14, arg15, arg16, (javafx.scene.input.ScrollEvent.HorizontalTextScrollUnits) com.jxparallel.fx.Fx.fx(arg17), arg18, (javafx.scene.input.ScrollEvent.VerticalTextScrollUnits) com.jxparallel.fx.Fx.fx(arg19), arg20, arg21, (javafx.scene.input.PickResult) com.jxparallel.fx.Fx.fx(arg22)));
        com.jxparallel.fx.Fx.own(fxPeer(), this);
    }

    public ScrollEvent(@javafx.beans.NamedArg(value = "eventType") com.jxparallel.fx.event.EventType<com.jxparallel.fx.scene.input.ScrollEvent> arg0, @javafx.beans.NamedArg(value = "x") double arg1, @javafx.beans.NamedArg(value = "y") double arg2, @javafx.beans.NamedArg(value = "screenX") double arg3, @javafx.beans.NamedArg(value = "screenY") double arg4, @javafx.beans.NamedArg(value = "shiftDown") boolean arg5, @javafx.beans.NamedArg(value = "controlDown") boolean arg6, @javafx.beans.NamedArg(value = "altDown") boolean arg7, @javafx.beans.NamedArg(value = "metaDown") boolean arg8, @javafx.beans.NamedArg(value = "direct") boolean arg9, @javafx.beans.NamedArg(value = "inertia") boolean arg10, @javafx.beans.NamedArg(value = "deltaX") double arg11, @javafx.beans.NamedArg(value = "deltaY") double arg12, @javafx.beans.NamedArg(value = "totalDeltaX") double arg13, @javafx.beans.NamedArg(value = "totalDeltaY") double arg14, @javafx.beans.NamedArg(value = "multiplierX") double arg15, @javafx.beans.NamedArg(value = "multiplierY") double arg16, @javafx.beans.NamedArg(value = "textDeltaXUnits") com.jxparallel.fx.scene.input.ScrollEvent.HorizontalTextScrollUnits arg17, @javafx.beans.NamedArg(value = "textDeltaX") double arg18, @javafx.beans.NamedArg(value = "textDeltaYUnits") com.jxparallel.fx.scene.input.ScrollEvent.VerticalTextScrollUnits arg19, @javafx.beans.NamedArg(value = "textDeltaY") double arg20, @javafx.beans.NamedArg(value = "touchCount") int arg21, @javafx.beans.NamedArg(value = "pickResult") com.jxparallel.fx.scene.input.PickResult arg22) {
        this(com.jxparallel.fx.Fx.WRAP, new javafx.scene.input.ScrollEvent((javafx.event.EventType) com.jxparallel.fx.Fx.fx(arg0), arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9, arg10, arg11, arg12, arg13, arg14, arg15, arg16, (javafx.scene.input.ScrollEvent.HorizontalTextScrollUnits) com.jxparallel.fx.Fx.fx(arg17), arg18, (javafx.scene.input.ScrollEvent.VerticalTextScrollUnits) com.jxparallel.fx.Fx.fx(arg19), arg20, arg21, (javafx.scene.input.PickResult) com.jxparallel.fx.Fx.fx(arg22)));
        com.jxparallel.fx.Fx.own(fxPeer(), this);
    }

    public ScrollEvent(@javafx.beans.NamedArg(value = "eventType") com.jxparallel.fx.event.EventType<com.jxparallel.fx.scene.input.ScrollEvent> arg0, @javafx.beans.NamedArg(value = "x") double arg1, @javafx.beans.NamedArg(value = "y") double arg2, @javafx.beans.NamedArg(value = "screenX") double arg3, @javafx.beans.NamedArg(value = "screenY") double arg4, @javafx.beans.NamedArg(value = "shiftDown") boolean arg5, @javafx.beans.NamedArg(value = "controlDown") boolean arg6, @javafx.beans.NamedArg(value = "altDown") boolean arg7, @javafx.beans.NamedArg(value = "metaDown") boolean arg8, @javafx.beans.NamedArg(value = "direct") boolean arg9, @javafx.beans.NamedArg(value = "inertia") boolean arg10, @javafx.beans.NamedArg(value = "deltaX") double arg11, @javafx.beans.NamedArg(value = "deltaY") double arg12, @javafx.beans.NamedArg(value = "totalDeltaX") double arg13, @javafx.beans.NamedArg(value = "totalDeltaY") double arg14, @javafx.beans.NamedArg(value = "textDeltaXUnits") com.jxparallel.fx.scene.input.ScrollEvent.HorizontalTextScrollUnits arg15, @javafx.beans.NamedArg(value = "textDeltaX") double arg16, @javafx.beans.NamedArg(value = "textDeltaYUnits") com.jxparallel.fx.scene.input.ScrollEvent.VerticalTextScrollUnits arg17, @javafx.beans.NamedArg(value = "textDeltaY") double arg18, @javafx.beans.NamedArg(value = "touchCount") int arg19, @javafx.beans.NamedArg(value = "pickResult") com.jxparallel.fx.scene.input.PickResult arg20) {
        this(com.jxparallel.fx.Fx.WRAP, new javafx.scene.input.ScrollEvent((javafx.event.EventType) com.jxparallel.fx.Fx.fx(arg0), arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9, arg10, arg11, arg12, arg13, arg14, (javafx.scene.input.ScrollEvent.HorizontalTextScrollUnits) com.jxparallel.fx.Fx.fx(arg15), arg16, (javafx.scene.input.ScrollEvent.VerticalTextScrollUnits) com.jxparallel.fx.Fx.fx(arg17), arg18, arg19, (javafx.scene.input.PickResult) com.jxparallel.fx.Fx.fx(arg20)));
        com.jxparallel.fx.Fx.own(fxPeer(), this);
    }

    public static final com.jxparallel.fx.event.EventType<com.jxparallel.fx.scene.input.ScrollEvent> ANY = (com.jxparallel.fx.event.EventType) com.jxparallel.fx.Fx.jx(javafx.scene.input.ScrollEvent.ANY);

    public static final com.jxparallel.fx.event.EventType<com.jxparallel.fx.scene.input.ScrollEvent> SCROLL = (com.jxparallel.fx.event.EventType) com.jxparallel.fx.Fx.jx(javafx.scene.input.ScrollEvent.SCROLL);

    public static final com.jxparallel.fx.event.EventType<com.jxparallel.fx.scene.input.ScrollEvent> SCROLL_STARTED = (com.jxparallel.fx.event.EventType) com.jxparallel.fx.Fx.jx(javafx.scene.input.ScrollEvent.SCROLL_STARTED);

    public static final com.jxparallel.fx.event.EventType<com.jxparallel.fx.scene.input.ScrollEvent> SCROLL_FINISHED = (com.jxparallel.fx.event.EventType) com.jxparallel.fx.Fx.jx(javafx.scene.input.ScrollEvent.SCROLL_FINISHED);

    public com.jxparallel.fx.scene.input.ScrollEvent copyFor(java.lang.Object arg0, com.jxparallel.fx.event.EventTarget arg1) {
        return (com.jxparallel.fx.scene.input.ScrollEvent) com.jxparallel.fx.Fx.jx(((javafx.scene.input.ScrollEvent) fxPeer()).copyFor((java.lang.Object) com.jxparallel.fx.Fx.fx(arg0), (javafx.event.EventTarget) com.jxparallel.fx.Fx.fx(arg1)));
    }

    public com.jxparallel.fx.scene.input.ScrollEvent copyFor(java.lang.Object arg0, com.jxparallel.fx.event.EventTarget arg1, com.jxparallel.fx.event.EventType<com.jxparallel.fx.scene.input.ScrollEvent> arg2) {
        return (com.jxparallel.fx.scene.input.ScrollEvent) com.jxparallel.fx.Fx.jx(((javafx.scene.input.ScrollEvent) fxPeer()).copyFor((java.lang.Object) com.jxparallel.fx.Fx.fx(arg0), (javafx.event.EventTarget) com.jxparallel.fx.Fx.fx(arg1), (javafx.event.EventType) com.jxparallel.fx.Fx.fx(arg2)));
    }

    public double getDeltaX() {
        return ((javafx.scene.input.ScrollEvent) fxPeer()).getDeltaX();
    }

    public double getDeltaY() {
        return ((javafx.scene.input.ScrollEvent) fxPeer()).getDeltaY();
    }

    public com.jxparallel.fx.event.EventType<com.jxparallel.fx.scene.input.ScrollEvent> getEventType() {
        return (com.jxparallel.fx.event.EventType) com.jxparallel.fx.Fx.jx(((javafx.scene.input.ScrollEvent) fxPeer()).getEventType());
    }

    public double getMultiplierX() {
        return ((javafx.scene.input.ScrollEvent) fxPeer()).getMultiplierX();
    }

    public double getMultiplierY() {
        return ((javafx.scene.input.ScrollEvent) fxPeer()).getMultiplierY();
    }

    public double getTextDeltaX() {
        return ((javafx.scene.input.ScrollEvent) fxPeer()).getTextDeltaX();
    }

    public com.jxparallel.fx.scene.input.ScrollEvent.HorizontalTextScrollUnits getTextDeltaXUnits() {
        return (com.jxparallel.fx.scene.input.ScrollEvent.HorizontalTextScrollUnits) com.jxparallel.fx.Fx.jx(((javafx.scene.input.ScrollEvent) fxPeer()).getTextDeltaXUnits());
    }

    public double getTextDeltaY() {
        return ((javafx.scene.input.ScrollEvent) fxPeer()).getTextDeltaY();
    }

    public com.jxparallel.fx.scene.input.ScrollEvent.VerticalTextScrollUnits getTextDeltaYUnits() {
        return (com.jxparallel.fx.scene.input.ScrollEvent.VerticalTextScrollUnits) com.jxparallel.fx.Fx.jx(((javafx.scene.input.ScrollEvent) fxPeer()).getTextDeltaYUnits());
    }

    public double getTotalDeltaX() {
        return ((javafx.scene.input.ScrollEvent) fxPeer()).getTotalDeltaX();
    }

    public double getTotalDeltaY() {
        return ((javafx.scene.input.ScrollEvent) fxPeer()).getTotalDeltaY();
    }

    public int getTouchCount() {
        return ((javafx.scene.input.ScrollEvent) fxPeer()).getTouchCount();
    }

    public enum HorizontalTextScrollUnits {
        NONE,
        CHARACTERS;
    }

    public enum VerticalTextScrollUnits {
        NONE,
        LINES,
        PAGES;
    }
}
