package com.jxparallel.fx.scene.paint;

/** JXParallel counterpart of {@link javafx.scene.paint.PhongMaterial} (generated by scripts/GenerateFxApi.java). */
@SuppressWarnings({"unchecked", "rawtypes", "deprecation"})
public class PhongMaterial extends com.jxparallel.fx.scene.paint.Material {
    protected PhongMaterial(com.jxparallel.fx.Fx.Wrap wrap, Object peer) {
        super(wrap, peer);
    }

    public PhongMaterial(com.jxparallel.fx.scene.paint.Color arg0, com.jxparallel.fx.scene.image.Image arg1, com.jxparallel.fx.scene.image.Image arg2, com.jxparallel.fx.scene.image.Image arg3, com.jxparallel.fx.scene.image.Image arg4) {
        this(com.jxparallel.fx.Fx.WRAP, new com.jxparallel.fx.peer.scene.paint.PhongMaterial((javafx.scene.paint.Color) com.jxparallel.fx.Fx.fx(arg0), (javafx.scene.image.Image) com.jxparallel.fx.Fx.fx(arg1), (javafx.scene.image.Image) com.jxparallel.fx.Fx.fx(arg2), (javafx.scene.image.Image) com.jxparallel.fx.Fx.fx(arg3), (javafx.scene.image.Image) com.jxparallel.fx.Fx.fx(arg4)));
        com.jxparallel.fx.Fx.own(fxPeer(), this);
    }

    public PhongMaterial(com.jxparallel.fx.scene.paint.Color arg0) {
        this(com.jxparallel.fx.Fx.WRAP, new com.jxparallel.fx.peer.scene.paint.PhongMaterial((javafx.scene.paint.Color) com.jxparallel.fx.Fx.fx(arg0)));
        com.jxparallel.fx.Fx.own(fxPeer(), this);
    }

    public PhongMaterial() {
        this(com.jxparallel.fx.Fx.WRAP, new com.jxparallel.fx.peer.scene.paint.PhongMaterial());
        com.jxparallel.fx.Fx.own(fxPeer(), this);
    }

    public com.jxparallel.fx.beans.property.ObjectProperty<com.jxparallel.fx.scene.image.Image> bumpMapProperty() {
        return (com.jxparallel.fx.beans.property.ObjectProperty) com.jxparallel.fx.Fx.jx(((javafx.scene.paint.PhongMaterial) fxPeer()).bumpMapProperty());
    }

    public com.jxparallel.fx.beans.property.ObjectProperty<com.jxparallel.fx.scene.paint.Color> diffuseColorProperty() {
        return (com.jxparallel.fx.beans.property.ObjectProperty) com.jxparallel.fx.Fx.jx(((javafx.scene.paint.PhongMaterial) fxPeer()).diffuseColorProperty());
    }

    public com.jxparallel.fx.beans.property.ObjectProperty<com.jxparallel.fx.scene.image.Image> diffuseMapProperty() {
        return (com.jxparallel.fx.beans.property.ObjectProperty) com.jxparallel.fx.Fx.jx(((javafx.scene.paint.PhongMaterial) fxPeer()).diffuseMapProperty());
    }

    public com.jxparallel.fx.scene.image.Image getBumpMap() {
        return (com.jxparallel.fx.scene.image.Image) com.jxparallel.fx.Fx.jx(((javafx.scene.paint.PhongMaterial) fxPeer()).getBumpMap());
    }

    public com.jxparallel.fx.scene.paint.Color getDiffuseColor() {
        return (com.jxparallel.fx.scene.paint.Color) com.jxparallel.fx.Fx.jx(((javafx.scene.paint.PhongMaterial) fxPeer()).getDiffuseColor());
    }

    public com.jxparallel.fx.scene.image.Image getDiffuseMap() {
        return (com.jxparallel.fx.scene.image.Image) com.jxparallel.fx.Fx.jx(((javafx.scene.paint.PhongMaterial) fxPeer()).getDiffuseMap());
    }

    public com.jxparallel.fx.scene.image.Image getSelfIlluminationMap() {
        return (com.jxparallel.fx.scene.image.Image) com.jxparallel.fx.Fx.jx(((javafx.scene.paint.PhongMaterial) fxPeer()).getSelfIlluminationMap());
    }

    public com.jxparallel.fx.scene.paint.Color getSpecularColor() {
        return (com.jxparallel.fx.scene.paint.Color) com.jxparallel.fx.Fx.jx(((javafx.scene.paint.PhongMaterial) fxPeer()).getSpecularColor());
    }

    public com.jxparallel.fx.scene.image.Image getSpecularMap() {
        return (com.jxparallel.fx.scene.image.Image) com.jxparallel.fx.Fx.jx(((javafx.scene.paint.PhongMaterial) fxPeer()).getSpecularMap());
    }

    public double getSpecularPower() {
        return ((javafx.scene.paint.PhongMaterial) fxPeer()).getSpecularPower();
    }

    public void impl_updatePG() {
        ((javafx.scene.paint.PhongMaterial) fxPeer()).impl_updatePG();
    }

    public com.jxparallel.fx.beans.property.ObjectProperty<com.jxparallel.fx.scene.image.Image> selfIlluminationMapProperty() {
        return (com.jxparallel.fx.beans.property.ObjectProperty) com.jxparallel.fx.Fx.jx(((javafx.scene.paint.PhongMaterial) fxPeer()).selfIlluminationMapProperty());
    }

    public void setBumpMap(com.jxparallel.fx.scene.image.Image arg0) {
        ((javafx.scene.paint.PhongMaterial) fxPeer()).setBumpMap((javafx.scene.image.Image) com.jxparallel.fx.Fx.fx(arg0));
    }

    public void setDiffuseColor(com.jxparallel.fx.scene.paint.Color arg0) {
        ((javafx.scene.paint.PhongMaterial) fxPeer()).setDiffuseColor((javafx.scene.paint.Color) com.jxparallel.fx.Fx.fx(arg0));
    }

    public void setDiffuseMap(com.jxparallel.fx.scene.image.Image arg0) {
        ((javafx.scene.paint.PhongMaterial) fxPeer()).setDiffuseMap((javafx.scene.image.Image) com.jxparallel.fx.Fx.fx(arg0));
    }

    public void setSelfIlluminationMap(com.jxparallel.fx.scene.image.Image arg0) {
        ((javafx.scene.paint.PhongMaterial) fxPeer()).setSelfIlluminationMap((javafx.scene.image.Image) com.jxparallel.fx.Fx.fx(arg0));
    }

    public void setSpecularColor(com.jxparallel.fx.scene.paint.Color arg0) {
        ((javafx.scene.paint.PhongMaterial) fxPeer()).setSpecularColor((javafx.scene.paint.Color) com.jxparallel.fx.Fx.fx(arg0));
    }

    public void setSpecularMap(com.jxparallel.fx.scene.image.Image arg0) {
        ((javafx.scene.paint.PhongMaterial) fxPeer()).setSpecularMap((javafx.scene.image.Image) com.jxparallel.fx.Fx.fx(arg0));
    }

    public void setSpecularPower(double arg0) {
        ((javafx.scene.paint.PhongMaterial) fxPeer()).setSpecularPower(arg0);
    }

    public com.jxparallel.fx.beans.property.ObjectProperty<com.jxparallel.fx.scene.paint.Color> specularColorProperty() {
        return (com.jxparallel.fx.beans.property.ObjectProperty) com.jxparallel.fx.Fx.jx(((javafx.scene.paint.PhongMaterial) fxPeer()).specularColorProperty());
    }

    public com.jxparallel.fx.beans.property.ObjectProperty<com.jxparallel.fx.scene.image.Image> specularMapProperty() {
        return (com.jxparallel.fx.beans.property.ObjectProperty) com.jxparallel.fx.Fx.jx(((javafx.scene.paint.PhongMaterial) fxPeer()).specularMapProperty());
    }

    public com.jxparallel.fx.beans.property.DoubleProperty specularPowerProperty() {
        return (com.jxparallel.fx.beans.property.DoubleProperty) com.jxparallel.fx.Fx.jx(((javafx.scene.paint.PhongMaterial) fxPeer()).specularPowerProperty());
    }
}
