package com.jxparallel.fx.scene.paint;

/** JXParallel counterpart of {@link javafx.scene.paint.RadialGradient} (generated by scripts/GenerateFxApi.java). */
@SuppressWarnings({"unchecked", "rawtypes", "deprecation"})
public final class RadialGradient extends com.jxparallel.fx.scene.paint.Paint {
    protected RadialGradient(com.jxparallel.fx.Fx.Wrap wrap, Object peer) {
        super(wrap, peer);
    }

    public RadialGradient(@javafx.beans.NamedArg(value = "focusAngle") double arg0, @javafx.beans.NamedArg(value = "focusDistance") double arg1, @javafx.beans.NamedArg(value = "centerX") double arg2, @javafx.beans.NamedArg(value = "centerY") double arg3, @javafx.beans.NamedArg(value = "radius", defaultValue = "1") double arg4, @javafx.beans.NamedArg(value = "proportional", defaultValue = "true") boolean arg5, @javafx.beans.NamedArg(value = "cycleMethod") com.jxparallel.fx.scene.paint.CycleMethod arg6, @javafx.beans.NamedArg(value = "stops") java.util.List<com.jxparallel.fx.scene.paint.Stop> arg7) {
        this(com.jxparallel.fx.Fx.WRAP, new javafx.scene.paint.RadialGradient(arg0, arg1, arg2, arg3, arg4, arg5, (javafx.scene.paint.CycleMethod) com.jxparallel.fx.Fx.fx(arg6), (java.util.List) com.jxparallel.fx.Fx.fxCollection(arg7)));
        com.jxparallel.fx.Fx.own(fxPeer(), this);
    }

    public RadialGradient(@javafx.beans.NamedArg(value = "focusAngle") double arg0, @javafx.beans.NamedArg(value = "focusDistance") double arg1, @javafx.beans.NamedArg(value = "centerX") double arg2, @javafx.beans.NamedArg(value = "centerY") double arg3, @javafx.beans.NamedArg(value = "radius", defaultValue = "1") double arg4, @javafx.beans.NamedArg(value = "proportional", defaultValue = "true") boolean arg5, @javafx.beans.NamedArg(value = "cycleMethod") com.jxparallel.fx.scene.paint.CycleMethod arg6, @javafx.beans.NamedArg(value = "stops") com.jxparallel.fx.scene.paint.Stop... arg7) {
        this(com.jxparallel.fx.Fx.WRAP, new javafx.scene.paint.RadialGradient(arg0, arg1, arg2, arg3, arg4, arg5, (javafx.scene.paint.CycleMethod) com.jxparallel.fx.Fx.fx(arg6), (javafx.scene.paint.Stop[]) com.jxparallel.fx.Fx.fxArray(arg7, javafx.scene.paint.Stop.class)));
        com.jxparallel.fx.Fx.own(fxPeer(), this);
    }

    public double getCenterX() {
        return ((javafx.scene.paint.RadialGradient) fxPeer()).getCenterX();
    }

    public double getCenterY() {
        return ((javafx.scene.paint.RadialGradient) fxPeer()).getCenterY();
    }

    public com.jxparallel.fx.scene.paint.CycleMethod getCycleMethod() {
        return (com.jxparallel.fx.scene.paint.CycleMethod) com.jxparallel.fx.Fx.jx(((javafx.scene.paint.RadialGradient) fxPeer()).getCycleMethod());
    }

    public double getFocusAngle() {
        return ((javafx.scene.paint.RadialGradient) fxPeer()).getFocusAngle();
    }

    public double getFocusDistance() {
        return ((javafx.scene.paint.RadialGradient) fxPeer()).getFocusDistance();
    }

    public double getRadius() {
        return ((javafx.scene.paint.RadialGradient) fxPeer()).getRadius();
    }

    public java.util.List<com.jxparallel.fx.scene.paint.Stop> getStops() {
        return (java.util.List) com.jxparallel.fx.Fx.jxList((java.util.List) ((javafx.scene.paint.RadialGradient) fxPeer()).getStops());
    }

    public boolean isOpaque() {
        return ((javafx.scene.paint.RadialGradient) fxPeer()).isOpaque();
    }

    public boolean isProportional() {
        return ((javafx.scene.paint.RadialGradient) fxPeer()).isProportional();
    }

    public static com.jxparallel.fx.scene.paint.RadialGradient valueOf(java.lang.String arg0) {
        return (com.jxparallel.fx.scene.paint.RadialGradient) com.jxparallel.fx.Fx.jx(javafx.scene.paint.RadialGradient.valueOf(arg0));
    }
}
