package com.jxparallel.fx.collections;

/** JXParallel counterpart of {@link javafx.collections.ArrayChangeListener} (generated by scripts/GenerateFxApi.java). */
@SuppressWarnings({"unchecked", "rawtypes", "deprecation"})
@FunctionalInterface
public interface ArrayChangeListener<T extends com.jxparallel.fx.collections.ObservableArray<T>> {

    void onChanged(T arg0, boolean arg1, int arg2, int arg3);
}
