package com.jxparallel.fx.peer.util;

/** JavaFX peer of {@link com.jxparallel.fx.util.StringConverter}; forwards overridable methods to it (generated by scripts/GenerateFxApi.java). */
@SuppressWarnings({"unchecked", "rawtypes", "deprecation", "serial"})
public class StringConverter<T> extends javafx.util.StringConverter<T> implements com.jxparallel.fx.Fx.Owned {
    private Object jxOwner;

    public StringConverter() {
        super();
    }

    @Override
    public Object jxOwner() {
        return jxOwner;
    }

    @Override
    public void jxOwner(Object owner) {
        this.jxOwner = owner;
    }

    @Override
    public java.lang.String toString(T arg0) {
        if (jxOwner == null) {
            throw new IllegalStateException("toString before the JX object exists");
        }
        return (java.lang.String) com.jxparallel.fx.Fx.fx(com.jxparallel.fx.util.StringConverter.$hook(jxOwner, "toString(Object)", new Object[] {com.jxparallel.fx.Fx.jx(arg0)}));
    }

    @Override
    public T fromString(java.lang.String arg0) {
        if (jxOwner == null) {
            throw new IllegalStateException("fromString before the JX object exists");
        }
        return (T) com.jxparallel.fx.Fx.fx(com.jxparallel.fx.util.StringConverter.$hook(jxOwner, "fromString(String)", new Object[] {com.jxparallel.fx.Fx.jx(arg0)}));
    }

    @Override
    public Object callSuper(String method, Object[] a) {
        try {
        switch (method) {
            default:
                throw new AbstractMethodError(method);
        }
        } catch (Exception e) {
            throw com.jxparallel.fx.Fx.sneaky(e);
        }
    }
}
