package com.jxparallel.fx.scene.control;

/** JXParallel counterpart of {@link javafx.scene.control.Accordion} (generated by scripts/GenerateFxApi.java). */
@SuppressWarnings({"unchecked", "rawtypes", "deprecation"})
public class Accordion extends com.jxparallel.fx.scene.control.Control {
    protected Accordion(com.jxparallel.fx.Fx.Wrap wrap, Object peer) {
        super(wrap, peer);
    }

    public Accordion() {
        this(com.jxparallel.fx.Fx.WRAP, com.jxparallel.fx.Fx.NATIVE ? com.jxparallel.fx.nativeimpl.Native.create(javafx.scene.control.Accordion.class, new String[] {}, new Object[] {}) : new com.jxparallel.fx.peer.scene.control.Accordion());
        com.jxparallel.fx.Fx.own(fxPeer(), this);
    }

    public Accordion(com.jxparallel.fx.scene.control.TitledPane... arg0) {
        this(com.jxparallel.fx.Fx.WRAP, com.jxparallel.fx.Fx.NATIVE ? com.jxparallel.fx.nativeimpl.Native.create(javafx.scene.control.Accordion.class, new String[] {null}, new Object[] {arg0}) : new com.jxparallel.fx.peer.scene.control.Accordion((javafx.scene.control.TitledPane[]) com.jxparallel.fx.Fx.fxArray(arg0, javafx.scene.control.TitledPane.class)));
        com.jxparallel.fx.Fx.own(fxPeer(), this);
    }

    protected com.jxparallel.fx.scene.control.Skin<?> createDefaultSkin() {
        if (com.jxparallel.fx.Fx.NATIVE) {
            return (com.jxparallel.fx.scene.control.Skin) com.jxparallel.fx.nativeimpl.Native.call(this, com.jxparallel.fx.scene.control.Accordion.class, "createDefaultSkin", new Class<?>[] {}, com.jxparallel.fx.scene.control.Skin.class);
        }
        return (com.jxparallel.fx.scene.control.Skin) com.jxparallel.fx.Fx.jx(com.jxparallel.fx.Fx.invoke(fxPeer(), javafx.scene.control.Accordion.class, "createDefaultSkin", new Class<?>[] {}));
    }

    public com.jxparallel.fx.beans.property.ObjectProperty<com.jxparallel.fx.scene.control.TitledPane> expandedPaneProperty() {
        if (com.jxparallel.fx.Fx.NATIVE) {
            return (com.jxparallel.fx.beans.property.ObjectProperty) com.jxparallel.fx.nativeimpl.Native.call(this, com.jxparallel.fx.scene.control.Accordion.class, "expandedPaneProperty", new Class<?>[] {}, com.jxparallel.fx.beans.property.ObjectProperty.class);
        }
        return (com.jxparallel.fx.beans.property.ObjectProperty) com.jxparallel.fx.Fx.jx(((javafx.scene.control.Accordion) fxPeer()).expandedPaneProperty());
    }

    public com.jxparallel.fx.scene.control.TitledPane getExpandedPane() {
        if (com.jxparallel.fx.Fx.NATIVE) {
            return (com.jxparallel.fx.scene.control.TitledPane) com.jxparallel.fx.nativeimpl.Native.call(this, com.jxparallel.fx.scene.control.Accordion.class, "getExpandedPane", new Class<?>[] {}, com.jxparallel.fx.scene.control.TitledPane.class);
        }
        return (com.jxparallel.fx.scene.control.TitledPane) com.jxparallel.fx.Fx.jx(((javafx.scene.control.Accordion) fxPeer()).getExpandedPane());
    }

    public com.jxparallel.fx.collections.ObservableList<com.jxparallel.fx.scene.control.TitledPane> getPanes() {
        if (com.jxparallel.fx.Fx.NATIVE) {
            return (com.jxparallel.fx.collections.ObservableList) com.jxparallel.fx.nativeimpl.Native.call(this, com.jxparallel.fx.scene.control.Accordion.class, "getPanes", new Class<?>[] {}, com.jxparallel.fx.collections.ObservableList.class);
        }
        return (com.jxparallel.fx.collections.ObservableList) com.jxparallel.fx.Fx.jx(((javafx.scene.control.Accordion) fxPeer()).getPanes());
    }

    public void setExpandedPane(com.jxparallel.fx.scene.control.TitledPane arg0) {
        if (com.jxparallel.fx.Fx.NATIVE) {
            com.jxparallel.fx.nativeimpl.Native.call(this, com.jxparallel.fx.scene.control.Accordion.class, "setExpandedPane", new Class<?>[] {com.jxparallel.fx.scene.control.TitledPane.class}, void.class, arg0);
            return;
        }
        ((javafx.scene.control.Accordion) fxPeer()).setExpandedPane((javafx.scene.control.TitledPane) com.jxparallel.fx.Fx.fx(arg0));
    }
}
