package com.jxparallel.fx.scene.control;

/** JXParallel counterpart of {@link javafx.scene.control.Control} (generated by scripts/GenerateFxApi.java). */
@SuppressWarnings({"unchecked", "rawtypes", "deprecation"})
public class Control extends com.jxparallel.fx.scene.layout.Region implements com.jxparallel.fx.scene.control.Skinnable {
    protected Control(com.jxparallel.fx.Fx.Wrap wrap, Object peer) {
        super(wrap, peer);
    }

    protected Control() {
        this(com.jxparallel.fx.Fx.WRAP, com.jxparallel.fx.Fx.NATIVE ? com.jxparallel.fx.nativeimpl.Native.create(javafx.scene.control.Control.class, new String[] {}, new Object[] {}) : new com.jxparallel.fx.peer.scene.control.Control());
        com.jxparallel.fx.Fx.own(fxPeer(), this);
    }

    protected double computeMaxHeight(double arg0) {
        if (com.jxparallel.fx.Fx.NATIVE) {
            return (Double) com.jxparallel.fx.nativeimpl.Native.call(this, com.jxparallel.fx.scene.control.Control.class, "computeMaxHeight", new Class<?>[] {double.class}, double.class, arg0);
        }
        return (Double) com.jxparallel.fx.Fx.invoke(fxPeer(), javafx.scene.control.Control.class, "computeMaxHeight", new Class<?>[] {double.class}, arg0);
    }

    protected double computeMaxWidth(double arg0) {
        if (com.jxparallel.fx.Fx.NATIVE) {
            return (Double) com.jxparallel.fx.nativeimpl.Native.call(this, com.jxparallel.fx.scene.control.Control.class, "computeMaxWidth", new Class<?>[] {double.class}, double.class, arg0);
        }
        return (Double) com.jxparallel.fx.Fx.invoke(fxPeer(), javafx.scene.control.Control.class, "computeMaxWidth", new Class<?>[] {double.class}, arg0);
    }

    protected double computeMinHeight(double arg0) {
        if (com.jxparallel.fx.Fx.NATIVE) {
            return (Double) com.jxparallel.fx.nativeimpl.Native.call(this, com.jxparallel.fx.scene.control.Control.class, "computeMinHeight", new Class<?>[] {double.class}, double.class, arg0);
        }
        return (Double) com.jxparallel.fx.Fx.invoke(fxPeer(), javafx.scene.control.Control.class, "computeMinHeight", new Class<?>[] {double.class}, arg0);
    }

    protected double computeMinWidth(double arg0) {
        if (com.jxparallel.fx.Fx.NATIVE) {
            return (Double) com.jxparallel.fx.nativeimpl.Native.call(this, com.jxparallel.fx.scene.control.Control.class, "computeMinWidth", new Class<?>[] {double.class}, double.class, arg0);
        }
        return (Double) com.jxparallel.fx.Fx.invoke(fxPeer(), javafx.scene.control.Control.class, "computeMinWidth", new Class<?>[] {double.class}, arg0);
    }

    protected double computePrefHeight(double arg0) {
        if (com.jxparallel.fx.Fx.NATIVE) {
            return (Double) com.jxparallel.fx.nativeimpl.Native.call(this, com.jxparallel.fx.scene.control.Control.class, "computePrefHeight", new Class<?>[] {double.class}, double.class, arg0);
        }
        return (Double) com.jxparallel.fx.Fx.invoke(fxPeer(), javafx.scene.control.Control.class, "computePrefHeight", new Class<?>[] {double.class}, arg0);
    }

    protected double computePrefWidth(double arg0) {
        if (com.jxparallel.fx.Fx.NATIVE) {
            return (Double) com.jxparallel.fx.nativeimpl.Native.call(this, com.jxparallel.fx.scene.control.Control.class, "computePrefWidth", new Class<?>[] {double.class}, double.class, arg0);
        }
        return (Double) com.jxparallel.fx.Fx.invoke(fxPeer(), javafx.scene.control.Control.class, "computePrefWidth", new Class<?>[] {double.class}, arg0);
    }

    public com.jxparallel.fx.beans.property.ObjectProperty<com.jxparallel.fx.scene.control.ContextMenu> contextMenuProperty() {
        if (com.jxparallel.fx.Fx.NATIVE) {
            return (com.jxparallel.fx.beans.property.ObjectProperty) com.jxparallel.fx.nativeimpl.Native.call(this, com.jxparallel.fx.scene.control.Control.class, "contextMenuProperty", new Class<?>[] {}, com.jxparallel.fx.beans.property.ObjectProperty.class);
        }
        return (com.jxparallel.fx.beans.property.ObjectProperty) com.jxparallel.fx.Fx.jx(((javafx.scene.control.Control) fxPeer()).contextMenuProperty());
    }

    protected com.jxparallel.fx.scene.control.Skin<?> createDefaultSkin() {
        if (com.jxparallel.fx.Fx.NATIVE) {
            return (com.jxparallel.fx.scene.control.Skin) com.jxparallel.fx.nativeimpl.Native.call(this, com.jxparallel.fx.scene.control.Control.class, "createDefaultSkin", new Class<?>[] {}, com.jxparallel.fx.scene.control.Skin.class);
        }
        return (com.jxparallel.fx.scene.control.Skin) com.jxparallel.fx.Fx.jx(com.jxparallel.fx.Fx.invoke(fxPeer(), javafx.scene.control.Control.class, "createDefaultSkin", new Class<?>[] {}));
    }

    public void executeAccessibleAction(com.jxparallel.fx.scene.AccessibleAction arg0, java.lang.Object... arg1) {
        if (com.jxparallel.fx.Fx.NATIVE) {
            com.jxparallel.fx.nativeimpl.Native.call(this, com.jxparallel.fx.scene.control.Control.class, "executeAccessibleAction", new Class<?>[] {com.jxparallel.fx.scene.AccessibleAction.class, java.lang.Object[].class}, void.class, arg0, arg1);
            return;
        }
        ((javafx.scene.control.Control) fxPeer()).executeAccessibleAction((javafx.scene.AccessibleAction) com.jxparallel.fx.Fx.fx(arg0), (java.lang.Object[]) com.jxparallel.fx.Fx.fxArray(arg1, java.lang.Object.class));
    }

    public double getBaselineOffset() {
        if (com.jxparallel.fx.Fx.NATIVE) {
            return (Double) com.jxparallel.fx.nativeimpl.Native.call(this, com.jxparallel.fx.scene.control.Control.class, "getBaselineOffset", new Class<?>[] {}, double.class);
        }
        return ((javafx.scene.control.Control) fxPeer()).getBaselineOffset();
    }

    public static java.util.List<javafx.css.CssMetaData<? extends javafx.css.Styleable, ?>> getClassCssMetaData() {
        if (com.jxparallel.fx.Fx.NATIVE) {
            return (java.util.List) com.jxparallel.fx.nativeimpl.Native.call(null, com.jxparallel.fx.scene.control.Control.class, "getClassCssMetaData", new Class<?>[] {}, java.util.List.class);
        }
        return javafx.scene.control.Control.getClassCssMetaData();
    }

    public com.jxparallel.fx.scene.control.ContextMenu getContextMenu() {
        if (com.jxparallel.fx.Fx.NATIVE) {
            return (com.jxparallel.fx.scene.control.ContextMenu) com.jxparallel.fx.nativeimpl.Native.call(this, com.jxparallel.fx.scene.control.Control.class, "getContextMenu", new Class<?>[] {}, com.jxparallel.fx.scene.control.ContextMenu.class);
        }
        return (com.jxparallel.fx.scene.control.ContextMenu) com.jxparallel.fx.Fx.jx(((javafx.scene.control.Control) fxPeer()).getContextMenu());
    }

    protected java.util.List<javafx.css.CssMetaData<? extends javafx.css.Styleable, ?>> getControlCssMetaData() {
        if (com.jxparallel.fx.Fx.NATIVE) {
            return (java.util.List) com.jxparallel.fx.nativeimpl.Native.call(this, com.jxparallel.fx.scene.control.Control.class, "getControlCssMetaData", new Class<?>[] {}, java.util.List.class);
        }
        return (java.util.List) com.jxparallel.fx.Fx.invoke(fxPeer(), javafx.scene.control.Control.class, "getControlCssMetaData", new Class<?>[] {});
    }

    public java.util.List<javafx.css.CssMetaData<? extends javafx.css.Styleable, ?>> getCssMetaData() {
        if (com.jxparallel.fx.Fx.NATIVE) {
            return (java.util.List) com.jxparallel.fx.nativeimpl.Native.call(this, com.jxparallel.fx.scene.control.Control.class, "getCssMetaData", new Class<?>[] {}, java.util.List.class);
        }
        return ((javafx.scene.control.Control) fxPeer()).getCssMetaData();
    }

    public com.jxparallel.fx.scene.control.Skin<?> getSkin() {
        if (com.jxparallel.fx.Fx.NATIVE) {
            return (com.jxparallel.fx.scene.control.Skin) com.jxparallel.fx.nativeimpl.Native.call(this, com.jxparallel.fx.scene.control.Control.class, "getSkin", new Class<?>[] {}, com.jxparallel.fx.scene.control.Skin.class);
        }
        return (com.jxparallel.fx.scene.control.Skin) com.jxparallel.fx.Fx.jx(((javafx.scene.control.Control) fxPeer()).getSkin());
    }

    public com.jxparallel.fx.scene.control.Tooltip getTooltip() {
        if (com.jxparallel.fx.Fx.NATIVE) {
            return (com.jxparallel.fx.scene.control.Tooltip) com.jxparallel.fx.nativeimpl.Native.call(this, com.jxparallel.fx.scene.control.Control.class, "getTooltip", new Class<?>[] {}, com.jxparallel.fx.scene.control.Tooltip.class);
        }
        return (com.jxparallel.fx.scene.control.Tooltip) com.jxparallel.fx.Fx.jx(((javafx.scene.control.Control) fxPeer()).getTooltip());
    }

    public boolean isResizable() {
        if (com.jxparallel.fx.Fx.NATIVE) {
            return (Boolean) com.jxparallel.fx.nativeimpl.Native.call(this, com.jxparallel.fx.scene.control.Control.class, "isResizable", new Class<?>[] {}, boolean.class);
        }
        return ((javafx.scene.control.Control) fxPeer()).isResizable();
    }

    protected void layoutChildren() {
        if (com.jxparallel.fx.Fx.NATIVE) {
            com.jxparallel.fx.nativeimpl.Native.call(this, com.jxparallel.fx.scene.control.Control.class, "layoutChildren", new Class<?>[] {}, void.class);
            return;
        }
        com.jxparallel.fx.Fx.invoke(fxPeer(), javafx.scene.control.Control.class, "layoutChildren", new Class<?>[] {});
    }

    public java.lang.Object queryAccessibleAttribute(com.jxparallel.fx.scene.AccessibleAttribute arg0, java.lang.Object... arg1) {
        if (com.jxparallel.fx.Fx.NATIVE) {
            return (java.lang.Object) com.jxparallel.fx.nativeimpl.Native.call(this, com.jxparallel.fx.scene.control.Control.class, "queryAccessibleAttribute", new Class<?>[] {com.jxparallel.fx.scene.AccessibleAttribute.class, java.lang.Object[].class}, java.lang.Object.class, arg0, arg1);
        }
        return (java.lang.Object) com.jxparallel.fx.Fx.jx(((javafx.scene.control.Control) fxPeer()).queryAccessibleAttribute((javafx.scene.AccessibleAttribute) com.jxparallel.fx.Fx.fx(arg0), (java.lang.Object[]) com.jxparallel.fx.Fx.fxArray(arg1, java.lang.Object.class)));
    }

    public void setContextMenu(com.jxparallel.fx.scene.control.ContextMenu arg0) {
        if (com.jxparallel.fx.Fx.NATIVE) {
            com.jxparallel.fx.nativeimpl.Native.call(this, com.jxparallel.fx.scene.control.Control.class, "setContextMenu", new Class<?>[] {com.jxparallel.fx.scene.control.ContextMenu.class}, void.class, arg0);
            return;
        }
        ((javafx.scene.control.Control) fxPeer()).setContextMenu((javafx.scene.control.ContextMenu) com.jxparallel.fx.Fx.fx(arg0));
    }

    public void setSkin(com.jxparallel.fx.scene.control.Skin<?> arg0) {
        if (com.jxparallel.fx.Fx.NATIVE) {
            com.jxparallel.fx.nativeimpl.Native.call(this, com.jxparallel.fx.scene.control.Control.class, "setSkin", new Class<?>[] {com.jxparallel.fx.scene.control.Skin.class}, void.class, arg0);
            return;
        }
        ((javafx.scene.control.Control) fxPeer()).setSkin((javafx.scene.control.Skin) com.jxparallel.fx.Fx.fx(arg0));
    }

    public void setTooltip(com.jxparallel.fx.scene.control.Tooltip arg0) {
        if (com.jxparallel.fx.Fx.NATIVE) {
            com.jxparallel.fx.nativeimpl.Native.call(this, com.jxparallel.fx.scene.control.Control.class, "setTooltip", new Class<?>[] {com.jxparallel.fx.scene.control.Tooltip.class}, void.class, arg0);
            return;
        }
        ((javafx.scene.control.Control) fxPeer()).setTooltip((javafx.scene.control.Tooltip) com.jxparallel.fx.Fx.fx(arg0));
    }

    protected com.jxparallel.fx.beans.property.StringProperty skinClassNameProperty() {
        if (com.jxparallel.fx.Fx.NATIVE) {
            return (com.jxparallel.fx.beans.property.StringProperty) com.jxparallel.fx.nativeimpl.Native.call(this, com.jxparallel.fx.scene.control.Control.class, "skinClassNameProperty", new Class<?>[] {}, com.jxparallel.fx.beans.property.StringProperty.class);
        }
        return (com.jxparallel.fx.beans.property.StringProperty) com.jxparallel.fx.Fx.jx(com.jxparallel.fx.Fx.invoke(fxPeer(), javafx.scene.control.Control.class, "skinClassNameProperty", new Class<?>[] {}));
    }

    public com.jxparallel.fx.beans.property.ObjectProperty<com.jxparallel.fx.scene.control.Skin<?>> skinProperty() {
        if (com.jxparallel.fx.Fx.NATIVE) {
            return (com.jxparallel.fx.beans.property.ObjectProperty) com.jxparallel.fx.nativeimpl.Native.call(this, com.jxparallel.fx.scene.control.Control.class, "skinProperty", new Class<?>[] {}, com.jxparallel.fx.beans.property.ObjectProperty.class);
        }
        return (com.jxparallel.fx.beans.property.ObjectProperty) com.jxparallel.fx.Fx.jx(((javafx.scene.control.Control) fxPeer()).skinProperty());
    }

    public com.jxparallel.fx.beans.property.ObjectProperty<com.jxparallel.fx.scene.control.Tooltip> tooltipProperty() {
        if (com.jxparallel.fx.Fx.NATIVE) {
            return (com.jxparallel.fx.beans.property.ObjectProperty) com.jxparallel.fx.nativeimpl.Native.call(this, com.jxparallel.fx.scene.control.Control.class, "tooltipProperty", new Class<?>[] {}, com.jxparallel.fx.beans.property.ObjectProperty.class);
        }
        return (com.jxparallel.fx.beans.property.ObjectProperty) com.jxparallel.fx.Fx.jx(((javafx.scene.control.Control) fxPeer()).tooltipProperty());
    }
}
