package com.jxparallel.fx.scene.control;

/** JXParallel counterpart of {@link javafx.scene.control.Hyperlink} (generated by scripts/GenerateFxApi.java). */
@SuppressWarnings({"unchecked", "rawtypes", "deprecation"})
@javafx.beans.DefaultProperty("text")
public class Hyperlink extends com.jxparallel.fx.scene.control.ButtonBase {
    protected Hyperlink(com.jxparallel.fx.Fx.Wrap wrap, Object peer) {
        super(wrap, peer);
    }

    public Hyperlink() {
        this(com.jxparallel.fx.Fx.WRAP, com.jxparallel.fx.Fx.NATIVE ? com.jxparallel.fx.nativeimpl.Native.create(javafx.scene.control.Hyperlink.class, new String[] {}, new Object[] {}) : new com.jxparallel.fx.peer.scene.control.Hyperlink());
        com.jxparallel.fx.Fx.own(fxPeer(), this);
    }

    public Hyperlink(java.lang.String arg0) {
        this(com.jxparallel.fx.Fx.WRAP, com.jxparallel.fx.Fx.NATIVE ? com.jxparallel.fx.nativeimpl.Native.create(javafx.scene.control.Hyperlink.class, new String[] {null}, new Object[] {arg0}) : new com.jxparallel.fx.peer.scene.control.Hyperlink(arg0));
        com.jxparallel.fx.Fx.own(fxPeer(), this);
    }

    public Hyperlink(java.lang.String arg0, com.jxparallel.fx.scene.Node arg1) {
        this(com.jxparallel.fx.Fx.WRAP, com.jxparallel.fx.Fx.NATIVE ? com.jxparallel.fx.nativeimpl.Native.create(javafx.scene.control.Hyperlink.class, new String[] {null, null}, new Object[] {arg0, arg1}) : new com.jxparallel.fx.peer.scene.control.Hyperlink(arg0, (javafx.scene.Node) com.jxparallel.fx.Fx.fx(arg1)));
        com.jxparallel.fx.Fx.own(fxPeer(), this);
    }

    protected com.jxparallel.fx.scene.control.Skin<?> createDefaultSkin() {
        if (com.jxparallel.fx.Fx.NATIVE) {
            return (com.jxparallel.fx.scene.control.Skin) com.jxparallel.fx.nativeimpl.Native.call(this, com.jxparallel.fx.scene.control.Hyperlink.class, "createDefaultSkin", new Class<?>[] {}, com.jxparallel.fx.scene.control.Skin.class);
        }
        return (com.jxparallel.fx.scene.control.Skin) com.jxparallel.fx.Fx.jx(com.jxparallel.fx.Fx.invoke(fxPeer(), javafx.scene.control.Hyperlink.class, "createDefaultSkin", new Class<?>[] {}));
    }

    public void fire() {
        if (com.jxparallel.fx.Fx.NATIVE) {
            com.jxparallel.fx.nativeimpl.Native.call(this, com.jxparallel.fx.scene.control.Hyperlink.class, "fire", new Class<?>[] {}, void.class);
            return;
        }
        ((javafx.scene.control.Hyperlink) fxPeer()).fire();
    }

    public boolean isVisited() {
        if (com.jxparallel.fx.Fx.NATIVE) {
            return (Boolean) com.jxparallel.fx.nativeimpl.Native.call(this, com.jxparallel.fx.scene.control.Hyperlink.class, "isVisited", new Class<?>[] {}, boolean.class);
        }
        return ((javafx.scene.control.Hyperlink) fxPeer()).isVisited();
    }

    public java.lang.Object queryAccessibleAttribute(com.jxparallel.fx.scene.AccessibleAttribute arg0, java.lang.Object... arg1) {
        if (com.jxparallel.fx.Fx.NATIVE) {
            return (java.lang.Object) com.jxparallel.fx.nativeimpl.Native.call(this, com.jxparallel.fx.scene.control.Hyperlink.class, "queryAccessibleAttribute", new Class<?>[] {com.jxparallel.fx.scene.AccessibleAttribute.class, java.lang.Object[].class}, java.lang.Object.class, arg0, arg1);
        }
        return (java.lang.Object) com.jxparallel.fx.Fx.jx(((javafx.scene.control.Hyperlink) fxPeer()).queryAccessibleAttribute((javafx.scene.AccessibleAttribute) com.jxparallel.fx.Fx.fx(arg0), (java.lang.Object[]) com.jxparallel.fx.Fx.fxArray(arg1, java.lang.Object.class)));
    }

    public void setVisited(boolean arg0) {
        if (com.jxparallel.fx.Fx.NATIVE) {
            com.jxparallel.fx.nativeimpl.Native.call(this, com.jxparallel.fx.scene.control.Hyperlink.class, "setVisited", new Class<?>[] {boolean.class}, void.class, arg0);
            return;
        }
        ((javafx.scene.control.Hyperlink) fxPeer()).setVisited(arg0);
    }

    public com.jxparallel.fx.beans.property.BooleanProperty visitedProperty() {
        if (com.jxparallel.fx.Fx.NATIVE) {
            return (com.jxparallel.fx.beans.property.BooleanProperty) com.jxparallel.fx.nativeimpl.Native.call(this, com.jxparallel.fx.scene.control.Hyperlink.class, "visitedProperty", new Class<?>[] {}, com.jxparallel.fx.beans.property.BooleanProperty.class);
        }
        return (com.jxparallel.fx.beans.property.BooleanProperty) com.jxparallel.fx.Fx.jx(((javafx.scene.control.Hyperlink) fxPeer()).visitedProperty());
    }
}
