package com.jxparallel.fx.scene.control;

/** JXParallel counterpart of {@link javafx.scene.control.MultipleSelectionModel} (generated by scripts/GenerateFxApi.java). */
@SuppressWarnings({"unchecked", "rawtypes", "deprecation"})
public class MultipleSelectionModel<T> extends com.jxparallel.fx.scene.control.SelectionModel<T> {
    protected MultipleSelectionModel(com.jxparallel.fx.Fx.Wrap wrap, Object peer) {
        super(wrap, peer);
    }

    public MultipleSelectionModel() {
        this(com.jxparallel.fx.Fx.WRAP, new com.jxparallel.fx.peer.scene.control.MultipleSelectionModel());
        com.jxparallel.fx.Fx.own(fxPeer(), this);
    }

    public com.jxparallel.fx.collections.ObservableList<java.lang.Integer> getSelectedIndices() {
        return (com.jxparallel.fx.collections.ObservableList) com.jxparallel.fx.Fx.jx((fxPeer() instanceof com.jxparallel.fx.Fx.Owned ? ((com.jxparallel.fx.Fx.Owned) fxPeer()).callSuper("getSelectedIndices()", new Object[] {}) : com.jxparallel.fx.Fx.invoke(fxPeer(), javafx.scene.control.MultipleSelectionModel.class, "getSelectedIndices", new Class<?>[] {})));
    }

    public com.jxparallel.fx.collections.ObservableList<T> getSelectedItems() {
        return (com.jxparallel.fx.collections.ObservableList) com.jxparallel.fx.Fx.jx((fxPeer() instanceof com.jxparallel.fx.Fx.Owned ? ((com.jxparallel.fx.Fx.Owned) fxPeer()).callSuper("getSelectedItems()", new Object[] {}) : com.jxparallel.fx.Fx.invoke(fxPeer(), javafx.scene.control.MultipleSelectionModel.class, "getSelectedItems", new Class<?>[] {})));
    }

    public com.jxparallel.fx.scene.control.SelectionMode getSelectionMode() {
        return (com.jxparallel.fx.scene.control.SelectionMode) com.jxparallel.fx.Fx.jx(((javafx.scene.control.MultipleSelectionModel) fxPeer()).getSelectionMode());
    }

    public void selectAll() {
        if (fxPeer() instanceof com.jxparallel.fx.Fx.Owned) {
            ((com.jxparallel.fx.Fx.Owned) fxPeer()).callSuper("selectAll()", new Object[] {});
        } else {
            com.jxparallel.fx.Fx.invoke(fxPeer(), javafx.scene.control.MultipleSelectionModel.class, "selectAll", new Class<?>[] {});
        }
    }

    public void selectFirst() {
        if (fxPeer() instanceof com.jxparallel.fx.Fx.Owned) {
            ((com.jxparallel.fx.Fx.Owned) fxPeer()).callSuper("selectFirst()", new Object[] {});
        } else {
            com.jxparallel.fx.Fx.invoke(fxPeer(), javafx.scene.control.MultipleSelectionModel.class, "selectFirst", new Class<?>[] {});
        }
    }

    public void selectIndices(int arg0, int... arg1) {
        if (fxPeer() instanceof com.jxparallel.fx.Fx.Owned) {
            ((com.jxparallel.fx.Fx.Owned) fxPeer()).callSuper("selectIndices(int,int[])", new Object[] {arg0, arg1});
        } else {
            com.jxparallel.fx.Fx.invoke(fxPeer(), javafx.scene.control.MultipleSelectionModel.class, "selectIndices", new Class<?>[] {int.class, int[].class}, arg0, arg1);
        }
    }

    public void selectLast() {
        if (fxPeer() instanceof com.jxparallel.fx.Fx.Owned) {
            ((com.jxparallel.fx.Fx.Owned) fxPeer()).callSuper("selectLast()", new Object[] {});
        } else {
            com.jxparallel.fx.Fx.invoke(fxPeer(), javafx.scene.control.MultipleSelectionModel.class, "selectLast", new Class<?>[] {});
        }
    }

    public void selectRange(int arg0, int arg1) {
        ((javafx.scene.control.MultipleSelectionModel) fxPeer()).selectRange(arg0, arg1);
    }

    public com.jxparallel.fx.beans.property.ObjectProperty<com.jxparallel.fx.scene.control.SelectionMode> selectionModeProperty() {
        return (com.jxparallel.fx.beans.property.ObjectProperty) com.jxparallel.fx.Fx.jx(((javafx.scene.control.MultipleSelectionModel) fxPeer()).selectionModeProperty());
    }

    public void setSelectionMode(com.jxparallel.fx.scene.control.SelectionMode arg0) {
        ((javafx.scene.control.MultipleSelectionModel) fxPeer()).setSelectionMode((javafx.scene.control.SelectionMode) com.jxparallel.fx.Fx.fx(arg0));
    }

    /** Called by the peer: runs the JX (possibly overridden) method. */
    public static Object $hook(Object self, String method, Object[] a) {
        MultipleSelectionModel jx = (MultipleSelectionModel) self;
        try {
        switch (method) {
            case "getSelectedItems()":
                return jx.getSelectedItems();
            case "getSelectedIndices()":
                return jx.getSelectedIndices();
            case "selectAll()":
                jx.selectAll();
                return null;
            case "selectFirst()":
                jx.selectFirst();
                return null;
            case "selectIndices(int,int[])":
                jx.selectIndices((Integer) a[0], (int[]) a[1]);
                return null;
            case "selectLast()":
                jx.selectLast();
                return null;
            case "isEmpty()":
                return (Object) jx.isEmpty();
            case "isSelected(int)":
                return (Object) jx.isSelected((Integer) a[0]);
            case "clearAndSelect(int)":
                jx.clearAndSelect((Integer) a[0]);
                return null;
            case "clearSelection()":
                jx.clearSelection();
                return null;
            case "clearSelection(int)":
                jx.clearSelection((Integer) a[0]);
                return null;
            case "select(Object)":
                jx.select((java.lang.Object) a[0]);
                return null;
            case "select(int)":
                jx.select((Integer) a[0]);
                return null;
            case "selectNext()":
                jx.selectNext();
                return null;
            case "selectPrevious()":
                jx.selectPrevious();
                return null;
            default:
                throw new IllegalArgumentException(method);
        }
        } catch (Exception e) {
            throw com.jxparallel.fx.Fx.sneaky(e);
        }
    }
}
