package com.jxparallel.fx.scene.control;

/** JXParallel counterpart of {@link javafx.scene.control.SelectionMode} (generated by scripts/GenerateFxApi.java). */
@SuppressWarnings({"unchecked", "rawtypes", "deprecation"})
public enum SelectionMode {
    SINGLE,
    MULTIPLE;
}
