package com.jxparallel.fx.scene.control;

/** JXParallel counterpart of {@link javafx.scene.control.Spinner} (generated by scripts/GenerateFxApi.java). */
@SuppressWarnings({"unchecked", "rawtypes", "deprecation"})
public class Spinner<T> extends com.jxparallel.fx.scene.control.Control {
    protected Spinner(com.jxparallel.fx.Fx.Wrap wrap, Object peer) {
        super(wrap, peer);
    }

    public Spinner() {
        this(com.jxparallel.fx.Fx.WRAP, com.jxparallel.fx.Fx.NATIVE ? com.jxparallel.fx.nativeimpl.Native.create(javafx.scene.control.Spinner.class, new String[] {}, new Object[] {}) : new com.jxparallel.fx.peer.scene.control.Spinner());
        com.jxparallel.fx.Fx.own(fxPeer(), this);
    }

    public Spinner(@javafx.beans.NamedArg(value = "min") double arg0, @javafx.beans.NamedArg(value = "max") double arg1, @javafx.beans.NamedArg(value = "initialValue") double arg2) {
        this(com.jxparallel.fx.Fx.WRAP, com.jxparallel.fx.Fx.NATIVE ? com.jxparallel.fx.nativeimpl.Native.create(javafx.scene.control.Spinner.class, new String[] {"min", "max", "initialValue"}, new Object[] {arg0, arg1, arg2}) : new com.jxparallel.fx.peer.scene.control.Spinner(arg0, arg1, arg2));
        com.jxparallel.fx.Fx.own(fxPeer(), this);
    }

    public Spinner(@javafx.beans.NamedArg(value = "min") double arg0, @javafx.beans.NamedArg(value = "max") double arg1, @javafx.beans.NamedArg(value = "initialValue") double arg2, @javafx.beans.NamedArg(value = "amountToStepBy") double arg3) {
        this(com.jxparallel.fx.Fx.WRAP, com.jxparallel.fx.Fx.NATIVE ? com.jxparallel.fx.nativeimpl.Native.create(javafx.scene.control.Spinner.class, new String[] {"min", "max", "initialValue", "amountToStepBy"}, new Object[] {arg0, arg1, arg2, arg3}) : new com.jxparallel.fx.peer.scene.control.Spinner(arg0, arg1, arg2, arg3));
        com.jxparallel.fx.Fx.own(fxPeer(), this);
    }

    public Spinner(@javafx.beans.NamedArg(value = "min") int arg0, @javafx.beans.NamedArg(value = "max") int arg1, @javafx.beans.NamedArg(value = "initialValue") int arg2) {
        this(com.jxparallel.fx.Fx.WRAP, com.jxparallel.fx.Fx.NATIVE ? com.jxparallel.fx.nativeimpl.Native.create(javafx.scene.control.Spinner.class, new String[] {"min", "max", "initialValue"}, new Object[] {arg0, arg1, arg2}) : new com.jxparallel.fx.peer.scene.control.Spinner(arg0, arg1, arg2));
        com.jxparallel.fx.Fx.own(fxPeer(), this);
    }

    public Spinner(@javafx.beans.NamedArg(value = "min") int arg0, @javafx.beans.NamedArg(value = "max") int arg1, @javafx.beans.NamedArg(value = "initialValue") int arg2, @javafx.beans.NamedArg(value = "amountToStepBy") int arg3) {
        this(com.jxparallel.fx.Fx.WRAP, com.jxparallel.fx.Fx.NATIVE ? com.jxparallel.fx.nativeimpl.Native.create(javafx.scene.control.Spinner.class, new String[] {"min", "max", "initialValue", "amountToStepBy"}, new Object[] {arg0, arg1, arg2, arg3}) : new com.jxparallel.fx.peer.scene.control.Spinner(arg0, arg1, arg2, arg3));
        com.jxparallel.fx.Fx.own(fxPeer(), this);
    }

    public Spinner(@javafx.beans.NamedArg(value = "items") com.jxparallel.fx.collections.ObservableList<T> arg0) {
        this(com.jxparallel.fx.Fx.WRAP, com.jxparallel.fx.Fx.NATIVE ? com.jxparallel.fx.nativeimpl.Native.create(javafx.scene.control.Spinner.class, new String[] {"items"}, new Object[] {arg0}) : new com.jxparallel.fx.peer.scene.control.Spinner((javafx.collections.ObservableList) com.jxparallel.fx.Fx.fx(arg0)));
        com.jxparallel.fx.Fx.own(fxPeer(), this);
    }

    public Spinner(@javafx.beans.NamedArg(value = "valueFactory") com.jxparallel.fx.scene.control.SpinnerValueFactory<T> arg0) {
        this(com.jxparallel.fx.Fx.WRAP, com.jxparallel.fx.Fx.NATIVE ? com.jxparallel.fx.nativeimpl.Native.create(javafx.scene.control.Spinner.class, new String[] {"valueFactory"}, new Object[] {arg0}) : new com.jxparallel.fx.peer.scene.control.Spinner((javafx.scene.control.SpinnerValueFactory) com.jxparallel.fx.Fx.fx(arg0)));
        com.jxparallel.fx.Fx.own(fxPeer(), this);
    }

    public static final java.lang.String STYLE_CLASS_ARROWS_ON_RIGHT_HORIZONTAL = javafx.scene.control.Spinner.STYLE_CLASS_ARROWS_ON_RIGHT_HORIZONTAL;

    public static final java.lang.String STYLE_CLASS_ARROWS_ON_LEFT_VERTICAL = javafx.scene.control.Spinner.STYLE_CLASS_ARROWS_ON_LEFT_VERTICAL;

    public static final java.lang.String STYLE_CLASS_ARROWS_ON_LEFT_HORIZONTAL = javafx.scene.control.Spinner.STYLE_CLASS_ARROWS_ON_LEFT_HORIZONTAL;

    public static final java.lang.String STYLE_CLASS_SPLIT_ARROWS_VERTICAL = javafx.scene.control.Spinner.STYLE_CLASS_SPLIT_ARROWS_VERTICAL;

    public static final java.lang.String STYLE_CLASS_SPLIT_ARROWS_HORIZONTAL = javafx.scene.control.Spinner.STYLE_CLASS_SPLIT_ARROWS_HORIZONTAL;

    protected com.jxparallel.fx.scene.control.Skin<?> createDefaultSkin() {
        if (com.jxparallel.fx.Fx.NATIVE) {
            return (com.jxparallel.fx.scene.control.Skin) com.jxparallel.fx.nativeimpl.Native.call(this, com.jxparallel.fx.scene.control.Spinner.class, "createDefaultSkin", new Class<?>[] {}, com.jxparallel.fx.scene.control.Skin.class);
        }
        return (com.jxparallel.fx.scene.control.Skin) com.jxparallel.fx.Fx.jx(com.jxparallel.fx.Fx.invoke(fxPeer(), javafx.scene.control.Spinner.class, "createDefaultSkin", new Class<?>[] {}));
    }

    public void decrement() {
        if (com.jxparallel.fx.Fx.NATIVE) {
            com.jxparallel.fx.nativeimpl.Native.call(this, com.jxparallel.fx.scene.control.Spinner.class, "decrement", new Class<?>[] {}, void.class);
            return;
        }
        ((javafx.scene.control.Spinner) fxPeer()).decrement();
    }

    public void decrement(int arg0) {
        if (com.jxparallel.fx.Fx.NATIVE) {
            com.jxparallel.fx.nativeimpl.Native.call(this, com.jxparallel.fx.scene.control.Spinner.class, "decrement", new Class<?>[] {int.class}, void.class, arg0);
            return;
        }
        ((javafx.scene.control.Spinner) fxPeer()).decrement(arg0);
    }

    public com.jxparallel.fx.beans.property.BooleanProperty editableProperty() {
        if (com.jxparallel.fx.Fx.NATIVE) {
            return (com.jxparallel.fx.beans.property.BooleanProperty) com.jxparallel.fx.nativeimpl.Native.call(this, com.jxparallel.fx.scene.control.Spinner.class, "editableProperty", new Class<?>[] {}, com.jxparallel.fx.beans.property.BooleanProperty.class);
        }
        return (com.jxparallel.fx.beans.property.BooleanProperty) com.jxparallel.fx.Fx.jx(((javafx.scene.control.Spinner) fxPeer()).editableProperty());
    }

    public com.jxparallel.fx.beans.property.ReadOnlyObjectProperty<com.jxparallel.fx.scene.control.TextField> editorProperty() {
        if (com.jxparallel.fx.Fx.NATIVE) {
            return (com.jxparallel.fx.beans.property.ReadOnlyObjectProperty) com.jxparallel.fx.nativeimpl.Native.call(this, com.jxparallel.fx.scene.control.Spinner.class, "editorProperty", new Class<?>[] {}, com.jxparallel.fx.beans.property.ReadOnlyObjectProperty.class);
        }
        return (com.jxparallel.fx.beans.property.ReadOnlyObjectProperty) com.jxparallel.fx.Fx.jx(((javafx.scene.control.Spinner) fxPeer()).editorProperty());
    }

    public void executeAccessibleAction(com.jxparallel.fx.scene.AccessibleAction arg0, java.lang.Object... arg1) {
        if (com.jxparallel.fx.Fx.NATIVE) {
            com.jxparallel.fx.nativeimpl.Native.call(this, com.jxparallel.fx.scene.control.Spinner.class, "executeAccessibleAction", new Class<?>[] {com.jxparallel.fx.scene.AccessibleAction.class, java.lang.Object[].class}, void.class, arg0, arg1);
            return;
        }
        ((javafx.scene.control.Spinner) fxPeer()).executeAccessibleAction((javafx.scene.AccessibleAction) com.jxparallel.fx.Fx.fx(arg0), (java.lang.Object[]) com.jxparallel.fx.Fx.fxArray(arg1, java.lang.Object.class));
    }

    public com.jxparallel.fx.scene.control.TextField getEditor() {
        if (com.jxparallel.fx.Fx.NATIVE) {
            return (com.jxparallel.fx.scene.control.TextField) com.jxparallel.fx.nativeimpl.Native.call(this, com.jxparallel.fx.scene.control.Spinner.class, "getEditor", new Class<?>[] {}, com.jxparallel.fx.scene.control.TextField.class);
        }
        return (com.jxparallel.fx.scene.control.TextField) com.jxparallel.fx.Fx.jx(((javafx.scene.control.Spinner) fxPeer()).getEditor());
    }

    public T getValue() {
        if (com.jxparallel.fx.Fx.NATIVE) {
            return (T) com.jxparallel.fx.nativeimpl.Native.call(this, com.jxparallel.fx.scene.control.Spinner.class, "getValue", new Class<?>[] {}, java.lang.Object.class);
        }
        return (T) com.jxparallel.fx.Fx.jx(((javafx.scene.control.Spinner) fxPeer()).getValue());
    }

    public com.jxparallel.fx.scene.control.SpinnerValueFactory<T> getValueFactory() {
        if (com.jxparallel.fx.Fx.NATIVE) {
            return (com.jxparallel.fx.scene.control.SpinnerValueFactory) com.jxparallel.fx.nativeimpl.Native.call(this, com.jxparallel.fx.scene.control.Spinner.class, "getValueFactory", new Class<?>[] {}, com.jxparallel.fx.scene.control.SpinnerValueFactory.class);
        }
        return (com.jxparallel.fx.scene.control.SpinnerValueFactory) com.jxparallel.fx.Fx.jx(((javafx.scene.control.Spinner) fxPeer()).getValueFactory());
    }

    public void increment() {
        if (com.jxparallel.fx.Fx.NATIVE) {
            com.jxparallel.fx.nativeimpl.Native.call(this, com.jxparallel.fx.scene.control.Spinner.class, "increment", new Class<?>[] {}, void.class);
            return;
        }
        ((javafx.scene.control.Spinner) fxPeer()).increment();
    }

    public void increment(int arg0) {
        if (com.jxparallel.fx.Fx.NATIVE) {
            com.jxparallel.fx.nativeimpl.Native.call(this, com.jxparallel.fx.scene.control.Spinner.class, "increment", new Class<?>[] {int.class}, void.class, arg0);
            return;
        }
        ((javafx.scene.control.Spinner) fxPeer()).increment(arg0);
    }

    public boolean isEditable() {
        if (com.jxparallel.fx.Fx.NATIVE) {
            return (Boolean) com.jxparallel.fx.nativeimpl.Native.call(this, com.jxparallel.fx.scene.control.Spinner.class, "isEditable", new Class<?>[] {}, boolean.class);
        }
        return ((javafx.scene.control.Spinner) fxPeer()).isEditable();
    }

    public java.lang.Object queryAccessibleAttribute(com.jxparallel.fx.scene.AccessibleAttribute arg0, java.lang.Object... arg1) {
        if (com.jxparallel.fx.Fx.NATIVE) {
            return (java.lang.Object) com.jxparallel.fx.nativeimpl.Native.call(this, com.jxparallel.fx.scene.control.Spinner.class, "queryAccessibleAttribute", new Class<?>[] {com.jxparallel.fx.scene.AccessibleAttribute.class, java.lang.Object[].class}, java.lang.Object.class, arg0, arg1);
        }
        return (java.lang.Object) com.jxparallel.fx.Fx.jx(((javafx.scene.control.Spinner) fxPeer()).queryAccessibleAttribute((javafx.scene.AccessibleAttribute) com.jxparallel.fx.Fx.fx(arg0), (java.lang.Object[]) com.jxparallel.fx.Fx.fxArray(arg1, java.lang.Object.class)));
    }

    public void setEditable(boolean arg0) {
        if (com.jxparallel.fx.Fx.NATIVE) {
            com.jxparallel.fx.nativeimpl.Native.call(this, com.jxparallel.fx.scene.control.Spinner.class, "setEditable", new Class<?>[] {boolean.class}, void.class, arg0);
            return;
        }
        ((javafx.scene.control.Spinner) fxPeer()).setEditable(arg0);
    }

    public void setValueFactory(com.jxparallel.fx.scene.control.SpinnerValueFactory<T> arg0) {
        if (com.jxparallel.fx.Fx.NATIVE) {
            com.jxparallel.fx.nativeimpl.Native.call(this, com.jxparallel.fx.scene.control.Spinner.class, "setValueFactory", new Class<?>[] {com.jxparallel.fx.scene.control.SpinnerValueFactory.class}, void.class, arg0);
            return;
        }
        ((javafx.scene.control.Spinner) fxPeer()).setValueFactory((javafx.scene.control.SpinnerValueFactory) com.jxparallel.fx.Fx.fx(arg0));
    }

    public com.jxparallel.fx.beans.property.ObjectProperty<com.jxparallel.fx.scene.control.SpinnerValueFactory<T>> valueFactoryProperty() {
        if (com.jxparallel.fx.Fx.NATIVE) {
            return (com.jxparallel.fx.beans.property.ObjectProperty) com.jxparallel.fx.nativeimpl.Native.call(this, com.jxparallel.fx.scene.control.Spinner.class, "valueFactoryProperty", new Class<?>[] {}, com.jxparallel.fx.beans.property.ObjectProperty.class);
        }
        return (com.jxparallel.fx.beans.property.ObjectProperty) com.jxparallel.fx.Fx.jx(((javafx.scene.control.Spinner) fxPeer()).valueFactoryProperty());
    }

    public com.jxparallel.fx.beans.property.ReadOnlyObjectProperty<T> valueProperty() {
        if (com.jxparallel.fx.Fx.NATIVE) {
            return (com.jxparallel.fx.beans.property.ReadOnlyObjectProperty) com.jxparallel.fx.nativeimpl.Native.call(this, com.jxparallel.fx.scene.control.Spinner.class, "valueProperty", new Class<?>[] {}, com.jxparallel.fx.beans.property.ReadOnlyObjectProperty.class);
        }
        return (com.jxparallel.fx.beans.property.ReadOnlyObjectProperty) com.jxparallel.fx.Fx.jx(((javafx.scene.control.Spinner) fxPeer()).valueProperty());
    }
}
