package com.jxparallel.fx.scene.control;

/** JXParallel counterpart of {@link javafx.scene.control.Tab} (generated by scripts/GenerateFxApi.java). */
@SuppressWarnings({"unchecked", "rawtypes", "deprecation"})
@javafx.beans.DefaultProperty("content")
public class Tab implements com.jxparallel.fx.event.EventTarget, com.jxparallel.fx.css.Styleable, com.jxparallel.fx.Fx.Backed {
    private final Object fxPeer;

    protected Tab(com.jxparallel.fx.Fx.Wrap wrap, Object peer) {
        this.fxPeer = peer;
    }

    @Override
    public Object fxPeer() {
        return fxPeer;
    }

    @Override
    public boolean equals(Object o) {
        return o == this || fxPeer.equals(com.jxparallel.fx.Fx.fx(o));
    }

    @Override
    public int hashCode() {
        return fxPeer.hashCode();
    }

    @Override
    public String toString() {
        return fxPeer.toString();
    }

    public Tab(java.lang.String arg0, com.jxparallel.fx.scene.Node arg1) {
        this(com.jxparallel.fx.Fx.WRAP, com.jxparallel.fx.Fx.NATIVE ? com.jxparallel.fx.nativeimpl.Native.create(javafx.scene.control.Tab.class, new String[] {null, null}, new Object[] {arg0, arg1}) : new com.jxparallel.fx.peer.scene.control.Tab(arg0, (javafx.scene.Node) com.jxparallel.fx.Fx.fx(arg1)));
        com.jxparallel.fx.Fx.own(fxPeer(), this);
    }

    public Tab(java.lang.String arg0) {
        this(com.jxparallel.fx.Fx.WRAP, com.jxparallel.fx.Fx.NATIVE ? com.jxparallel.fx.nativeimpl.Native.create(javafx.scene.control.Tab.class, new String[] {null}, new Object[] {arg0}) : new com.jxparallel.fx.peer.scene.control.Tab(arg0));
        com.jxparallel.fx.Fx.own(fxPeer(), this);
    }

    public Tab() {
        this(com.jxparallel.fx.Fx.WRAP, com.jxparallel.fx.Fx.NATIVE ? com.jxparallel.fx.nativeimpl.Native.create(javafx.scene.control.Tab.class, new String[] {}, new Object[] {}) : new com.jxparallel.fx.peer.scene.control.Tab());
        com.jxparallel.fx.Fx.own(fxPeer(), this);
    }

    public static final com.jxparallel.fx.event.EventType<com.jxparallel.fx.event.Event> SELECTION_CHANGED_EVENT = (com.jxparallel.fx.event.EventType) com.jxparallel.fx.Fx.jx(javafx.scene.control.Tab.SELECTION_CHANGED_EVENT);

    public static final com.jxparallel.fx.event.EventType<com.jxparallel.fx.event.Event> CLOSED_EVENT = (com.jxparallel.fx.event.EventType) com.jxparallel.fx.Fx.jx(javafx.scene.control.Tab.CLOSED_EVENT);

    public static final com.jxparallel.fx.event.EventType<com.jxparallel.fx.event.Event> TAB_CLOSE_REQUEST_EVENT = (com.jxparallel.fx.event.EventType) com.jxparallel.fx.Fx.jx(javafx.scene.control.Tab.TAB_CLOSE_REQUEST_EVENT);

    public com.jxparallel.fx.event.EventDispatchChain buildEventDispatchChain(com.jxparallel.fx.event.EventDispatchChain arg0) {
        if (com.jxparallel.fx.Fx.NATIVE) {
            return (com.jxparallel.fx.event.EventDispatchChain) com.jxparallel.fx.nativeimpl.Native.call(this, com.jxparallel.fx.scene.control.Tab.class, "buildEventDispatchChain", new Class<?>[] {com.jxparallel.fx.event.EventDispatchChain.class}, com.jxparallel.fx.event.EventDispatchChain.class, arg0);
        }
        return (com.jxparallel.fx.event.EventDispatchChain) com.jxparallel.fx.Fx.jx(((javafx.scene.control.Tab) fxPeer()).buildEventDispatchChain((javafx.event.EventDispatchChain) com.jxparallel.fx.Fx.fx(arg0)));
    }

    public com.jxparallel.fx.beans.property.BooleanProperty closableProperty() {
        if (com.jxparallel.fx.Fx.NATIVE) {
            return (com.jxparallel.fx.beans.property.BooleanProperty) com.jxparallel.fx.nativeimpl.Native.call(this, com.jxparallel.fx.scene.control.Tab.class, "closableProperty", new Class<?>[] {}, com.jxparallel.fx.beans.property.BooleanProperty.class);
        }
        return (com.jxparallel.fx.beans.property.BooleanProperty) com.jxparallel.fx.Fx.jx(((javafx.scene.control.Tab) fxPeer()).closableProperty());
    }

    public com.jxparallel.fx.beans.property.ObjectProperty<com.jxparallel.fx.scene.Node> contentProperty() {
        if (com.jxparallel.fx.Fx.NATIVE) {
            return (com.jxparallel.fx.beans.property.ObjectProperty) com.jxparallel.fx.nativeimpl.Native.call(this, com.jxparallel.fx.scene.control.Tab.class, "contentProperty", new Class<?>[] {}, com.jxparallel.fx.beans.property.ObjectProperty.class);
        }
        return (com.jxparallel.fx.beans.property.ObjectProperty) com.jxparallel.fx.Fx.jx(((javafx.scene.control.Tab) fxPeer()).contentProperty());
    }

    public com.jxparallel.fx.beans.property.ObjectProperty<com.jxparallel.fx.scene.control.ContextMenu> contextMenuProperty() {
        if (com.jxparallel.fx.Fx.NATIVE) {
            return (com.jxparallel.fx.beans.property.ObjectProperty) com.jxparallel.fx.nativeimpl.Native.call(this, com.jxparallel.fx.scene.control.Tab.class, "contextMenuProperty", new Class<?>[] {}, com.jxparallel.fx.beans.property.ObjectProperty.class);
        }
        return (com.jxparallel.fx.beans.property.ObjectProperty) com.jxparallel.fx.Fx.jx(((javafx.scene.control.Tab) fxPeer()).contextMenuProperty());
    }

    public com.jxparallel.fx.beans.property.BooleanProperty disableProperty() {
        if (com.jxparallel.fx.Fx.NATIVE) {
            return (com.jxparallel.fx.beans.property.BooleanProperty) com.jxparallel.fx.nativeimpl.Native.call(this, com.jxparallel.fx.scene.control.Tab.class, "disableProperty", new Class<?>[] {}, com.jxparallel.fx.beans.property.BooleanProperty.class);
        }
        return (com.jxparallel.fx.beans.property.BooleanProperty) com.jxparallel.fx.Fx.jx(((javafx.scene.control.Tab) fxPeer()).disableProperty());
    }

    public com.jxparallel.fx.beans.property.ReadOnlyBooleanProperty disabledProperty() {
        if (com.jxparallel.fx.Fx.NATIVE) {
            return (com.jxparallel.fx.beans.property.ReadOnlyBooleanProperty) com.jxparallel.fx.nativeimpl.Native.call(this, com.jxparallel.fx.scene.control.Tab.class, "disabledProperty", new Class<?>[] {}, com.jxparallel.fx.beans.property.ReadOnlyBooleanProperty.class);
        }
        return (com.jxparallel.fx.beans.property.ReadOnlyBooleanProperty) com.jxparallel.fx.Fx.jx(((javafx.scene.control.Tab) fxPeer()).disabledProperty());
    }

    public static java.util.List<javafx.css.CssMetaData<? extends javafx.css.Styleable, ?>> getClassCssMetaData() {
        if (com.jxparallel.fx.Fx.NATIVE) {
            return (java.util.List) com.jxparallel.fx.nativeimpl.Native.call(null, com.jxparallel.fx.scene.control.Tab.class, "getClassCssMetaData", new Class<?>[] {}, java.util.List.class);
        }
        return javafx.scene.control.Tab.getClassCssMetaData();
    }

    public com.jxparallel.fx.scene.Node getContent() {
        if (com.jxparallel.fx.Fx.NATIVE) {
            return (com.jxparallel.fx.scene.Node) com.jxparallel.fx.nativeimpl.Native.call(this, com.jxparallel.fx.scene.control.Tab.class, "getContent", new Class<?>[] {}, com.jxparallel.fx.scene.Node.class);
        }
        return (com.jxparallel.fx.scene.Node) com.jxparallel.fx.Fx.jx(((javafx.scene.control.Tab) fxPeer()).getContent());
    }

    public com.jxparallel.fx.scene.control.ContextMenu getContextMenu() {
        if (com.jxparallel.fx.Fx.NATIVE) {
            return (com.jxparallel.fx.scene.control.ContextMenu) com.jxparallel.fx.nativeimpl.Native.call(this, com.jxparallel.fx.scene.control.Tab.class, "getContextMenu", new Class<?>[] {}, com.jxparallel.fx.scene.control.ContextMenu.class);
        }
        return (com.jxparallel.fx.scene.control.ContextMenu) com.jxparallel.fx.Fx.jx(((javafx.scene.control.Tab) fxPeer()).getContextMenu());
    }

    public java.util.List<javafx.css.CssMetaData<? extends javafx.css.Styleable, ?>> getCssMetaData() {
        if (com.jxparallel.fx.Fx.NATIVE) {
            return (java.util.List) com.jxparallel.fx.nativeimpl.Native.call(this, com.jxparallel.fx.scene.control.Tab.class, "getCssMetaData", new Class<?>[] {}, java.util.List.class);
        }
        return ((javafx.scene.control.Tab) fxPeer()).getCssMetaData();
    }

    public com.jxparallel.fx.scene.Node getGraphic() {
        if (com.jxparallel.fx.Fx.NATIVE) {
            return (com.jxparallel.fx.scene.Node) com.jxparallel.fx.nativeimpl.Native.call(this, com.jxparallel.fx.scene.control.Tab.class, "getGraphic", new Class<?>[] {}, com.jxparallel.fx.scene.Node.class);
        }
        return (com.jxparallel.fx.scene.Node) com.jxparallel.fx.Fx.jx(((javafx.scene.control.Tab) fxPeer()).getGraphic());
    }

    public java.lang.String getId() {
        if (com.jxparallel.fx.Fx.NATIVE) {
            return (java.lang.String) com.jxparallel.fx.nativeimpl.Native.call(this, com.jxparallel.fx.scene.control.Tab.class, "getId", new Class<?>[] {}, java.lang.String.class);
        }
        return ((javafx.scene.control.Tab) fxPeer()).getId();
    }

    public com.jxparallel.fx.event.EventHandler<com.jxparallel.fx.event.Event> getOnCloseRequest() {
        if (com.jxparallel.fx.Fx.NATIVE) {
            return (com.jxparallel.fx.event.EventHandler) com.jxparallel.fx.nativeimpl.Native.call(this, com.jxparallel.fx.scene.control.Tab.class, "getOnCloseRequest", new Class<?>[] {}, com.jxparallel.fx.event.EventHandler.class);
        }
        return (com.jxparallel.fx.event.EventHandler) com.jxparallel.fx.Fx.jx(((javafx.scene.control.Tab) fxPeer()).getOnCloseRequest());
    }

    public com.jxparallel.fx.event.EventHandler<com.jxparallel.fx.event.Event> getOnClosed() {
        if (com.jxparallel.fx.Fx.NATIVE) {
            return (com.jxparallel.fx.event.EventHandler) com.jxparallel.fx.nativeimpl.Native.call(this, com.jxparallel.fx.scene.control.Tab.class, "getOnClosed", new Class<?>[] {}, com.jxparallel.fx.event.EventHandler.class);
        }
        return (com.jxparallel.fx.event.EventHandler) com.jxparallel.fx.Fx.jx(((javafx.scene.control.Tab) fxPeer()).getOnClosed());
    }

    public com.jxparallel.fx.event.EventHandler<com.jxparallel.fx.event.Event> getOnSelectionChanged() {
        if (com.jxparallel.fx.Fx.NATIVE) {
            return (com.jxparallel.fx.event.EventHandler) com.jxparallel.fx.nativeimpl.Native.call(this, com.jxparallel.fx.scene.control.Tab.class, "getOnSelectionChanged", new Class<?>[] {}, com.jxparallel.fx.event.EventHandler.class);
        }
        return (com.jxparallel.fx.event.EventHandler) com.jxparallel.fx.Fx.jx(((javafx.scene.control.Tab) fxPeer()).getOnSelectionChanged());
    }

    public javafx.collections.ObservableMap<java.lang.Object, java.lang.Object> getProperties() {
        if (com.jxparallel.fx.Fx.NATIVE) {
            return (javafx.collections.ObservableMap) com.jxparallel.fx.nativeimpl.Native.call(this, com.jxparallel.fx.scene.control.Tab.class, "getProperties", new Class<?>[] {}, javafx.collections.ObservableMap.class);
        }
        return ((javafx.scene.control.Tab) fxPeer()).getProperties();
    }

    public javafx.collections.ObservableSet<javafx.css.PseudoClass> getPseudoClassStates() {
        if (com.jxparallel.fx.Fx.NATIVE) {
            return (javafx.collections.ObservableSet) com.jxparallel.fx.nativeimpl.Native.call(this, com.jxparallel.fx.scene.control.Tab.class, "getPseudoClassStates", new Class<?>[] {}, javafx.collections.ObservableSet.class);
        }
        return ((javafx.scene.control.Tab) fxPeer()).getPseudoClassStates();
    }

    public java.lang.String getStyle() {
        if (com.jxparallel.fx.Fx.NATIVE) {
            return (java.lang.String) com.jxparallel.fx.nativeimpl.Native.call(this, com.jxparallel.fx.scene.control.Tab.class, "getStyle", new Class<?>[] {}, java.lang.String.class);
        }
        return ((javafx.scene.control.Tab) fxPeer()).getStyle();
    }

    public com.jxparallel.fx.collections.ObservableList<java.lang.String> getStyleClass() {
        if (com.jxparallel.fx.Fx.NATIVE) {
            return (com.jxparallel.fx.collections.ObservableList) com.jxparallel.fx.nativeimpl.Native.call(this, com.jxparallel.fx.scene.control.Tab.class, "getStyleClass", new Class<?>[] {}, com.jxparallel.fx.collections.ObservableList.class);
        }
        return (com.jxparallel.fx.collections.ObservableList) com.jxparallel.fx.Fx.jx(((javafx.scene.control.Tab) fxPeer()).getStyleClass());
    }

    public com.jxparallel.fx.css.Styleable getStyleableParent() {
        if (com.jxparallel.fx.Fx.NATIVE) {
            return (com.jxparallel.fx.css.Styleable) com.jxparallel.fx.nativeimpl.Native.call(this, com.jxparallel.fx.scene.control.Tab.class, "getStyleableParent", new Class<?>[] {}, com.jxparallel.fx.css.Styleable.class);
        }
        return (com.jxparallel.fx.css.Styleable) com.jxparallel.fx.Fx.jx(((javafx.scene.control.Tab) fxPeer()).getStyleableParent());
    }

    public com.jxparallel.fx.scene.control.TabPane getTabPane() {
        if (com.jxparallel.fx.Fx.NATIVE) {
            return (com.jxparallel.fx.scene.control.TabPane) com.jxparallel.fx.nativeimpl.Native.call(this, com.jxparallel.fx.scene.control.Tab.class, "getTabPane", new Class<?>[] {}, com.jxparallel.fx.scene.control.TabPane.class);
        }
        return (com.jxparallel.fx.scene.control.TabPane) com.jxparallel.fx.Fx.jx(((javafx.scene.control.Tab) fxPeer()).getTabPane());
    }

    public java.lang.String getText() {
        if (com.jxparallel.fx.Fx.NATIVE) {
            return (java.lang.String) com.jxparallel.fx.nativeimpl.Native.call(this, com.jxparallel.fx.scene.control.Tab.class, "getText", new Class<?>[] {}, java.lang.String.class);
        }
        return ((javafx.scene.control.Tab) fxPeer()).getText();
    }

    public com.jxparallel.fx.scene.control.Tooltip getTooltip() {
        if (com.jxparallel.fx.Fx.NATIVE) {
            return (com.jxparallel.fx.scene.control.Tooltip) com.jxparallel.fx.nativeimpl.Native.call(this, com.jxparallel.fx.scene.control.Tab.class, "getTooltip", new Class<?>[] {}, com.jxparallel.fx.scene.control.Tooltip.class);
        }
        return (com.jxparallel.fx.scene.control.Tooltip) com.jxparallel.fx.Fx.jx(((javafx.scene.control.Tab) fxPeer()).getTooltip());
    }

    public java.lang.String getTypeSelector() {
        if (com.jxparallel.fx.Fx.NATIVE) {
            return (java.lang.String) com.jxparallel.fx.nativeimpl.Native.call(this, com.jxparallel.fx.scene.control.Tab.class, "getTypeSelector", new Class<?>[] {}, java.lang.String.class);
        }
        return ((javafx.scene.control.Tab) fxPeer()).getTypeSelector();
    }

    public java.lang.Object getUserData() {
        if (com.jxparallel.fx.Fx.NATIVE) {
            return (java.lang.Object) com.jxparallel.fx.nativeimpl.Native.call(this, com.jxparallel.fx.scene.control.Tab.class, "getUserData", new Class<?>[] {}, java.lang.Object.class);
        }
        return (java.lang.Object) com.jxparallel.fx.Fx.jx(((javafx.scene.control.Tab) fxPeer()).getUserData());
    }

    public com.jxparallel.fx.beans.property.ObjectProperty<com.jxparallel.fx.scene.Node> graphicProperty() {
        if (com.jxparallel.fx.Fx.NATIVE) {
            return (com.jxparallel.fx.beans.property.ObjectProperty) com.jxparallel.fx.nativeimpl.Native.call(this, com.jxparallel.fx.scene.control.Tab.class, "graphicProperty", new Class<?>[] {}, com.jxparallel.fx.beans.property.ObjectProperty.class);
        }
        return (com.jxparallel.fx.beans.property.ObjectProperty) com.jxparallel.fx.Fx.jx(((javafx.scene.control.Tab) fxPeer()).graphicProperty());
    }

    public boolean hasProperties() {
        if (com.jxparallel.fx.Fx.NATIVE) {
            return (Boolean) com.jxparallel.fx.nativeimpl.Native.call(this, com.jxparallel.fx.scene.control.Tab.class, "hasProperties", new Class<?>[] {}, boolean.class);
        }
        return ((javafx.scene.control.Tab) fxPeer()).hasProperties();
    }

    public com.jxparallel.fx.beans.property.StringProperty idProperty() {
        if (com.jxparallel.fx.Fx.NATIVE) {
            return (com.jxparallel.fx.beans.property.StringProperty) com.jxparallel.fx.nativeimpl.Native.call(this, com.jxparallel.fx.scene.control.Tab.class, "idProperty", new Class<?>[] {}, com.jxparallel.fx.beans.property.StringProperty.class);
        }
        return (com.jxparallel.fx.beans.property.StringProperty) com.jxparallel.fx.Fx.jx(((javafx.scene.control.Tab) fxPeer()).idProperty());
    }

    public boolean isClosable() {
        if (com.jxparallel.fx.Fx.NATIVE) {
            return (Boolean) com.jxparallel.fx.nativeimpl.Native.call(this, com.jxparallel.fx.scene.control.Tab.class, "isClosable", new Class<?>[] {}, boolean.class);
        }
        return ((javafx.scene.control.Tab) fxPeer()).isClosable();
    }

    public boolean isDisable() {
        if (com.jxparallel.fx.Fx.NATIVE) {
            return (Boolean) com.jxparallel.fx.nativeimpl.Native.call(this, com.jxparallel.fx.scene.control.Tab.class, "isDisable", new Class<?>[] {}, boolean.class);
        }
        return ((javafx.scene.control.Tab) fxPeer()).isDisable();
    }

    public boolean isDisabled() {
        if (com.jxparallel.fx.Fx.NATIVE) {
            return (Boolean) com.jxparallel.fx.nativeimpl.Native.call(this, com.jxparallel.fx.scene.control.Tab.class, "isDisabled", new Class<?>[] {}, boolean.class);
        }
        return ((javafx.scene.control.Tab) fxPeer()).isDisabled();
    }

    public boolean isSelected() {
        if (com.jxparallel.fx.Fx.NATIVE) {
            return (Boolean) com.jxparallel.fx.nativeimpl.Native.call(this, com.jxparallel.fx.scene.control.Tab.class, "isSelected", new Class<?>[] {}, boolean.class);
        }
        return ((javafx.scene.control.Tab) fxPeer()).isSelected();
    }

    public com.jxparallel.fx.beans.property.ObjectProperty<com.jxparallel.fx.event.EventHandler<com.jxparallel.fx.event.Event>> onCloseRequestProperty() {
        if (com.jxparallel.fx.Fx.NATIVE) {
            return (com.jxparallel.fx.beans.property.ObjectProperty) com.jxparallel.fx.nativeimpl.Native.call(this, com.jxparallel.fx.scene.control.Tab.class, "onCloseRequestProperty", new Class<?>[] {}, com.jxparallel.fx.beans.property.ObjectProperty.class);
        }
        return (com.jxparallel.fx.beans.property.ObjectProperty) com.jxparallel.fx.Fx.jx(((javafx.scene.control.Tab) fxPeer()).onCloseRequestProperty());
    }

    public com.jxparallel.fx.beans.property.ObjectProperty<com.jxparallel.fx.event.EventHandler<com.jxparallel.fx.event.Event>> onClosedProperty() {
        if (com.jxparallel.fx.Fx.NATIVE) {
            return (com.jxparallel.fx.beans.property.ObjectProperty) com.jxparallel.fx.nativeimpl.Native.call(this, com.jxparallel.fx.scene.control.Tab.class, "onClosedProperty", new Class<?>[] {}, com.jxparallel.fx.beans.property.ObjectProperty.class);
        }
        return (com.jxparallel.fx.beans.property.ObjectProperty) com.jxparallel.fx.Fx.jx(((javafx.scene.control.Tab) fxPeer()).onClosedProperty());
    }

    public com.jxparallel.fx.beans.property.ObjectProperty<com.jxparallel.fx.event.EventHandler<com.jxparallel.fx.event.Event>> onSelectionChangedProperty() {
        if (com.jxparallel.fx.Fx.NATIVE) {
            return (com.jxparallel.fx.beans.property.ObjectProperty) com.jxparallel.fx.nativeimpl.Native.call(this, com.jxparallel.fx.scene.control.Tab.class, "onSelectionChangedProperty", new Class<?>[] {}, com.jxparallel.fx.beans.property.ObjectProperty.class);
        }
        return (com.jxparallel.fx.beans.property.ObjectProperty) com.jxparallel.fx.Fx.jx(((javafx.scene.control.Tab) fxPeer()).onSelectionChangedProperty());
    }

    public com.jxparallel.fx.beans.property.ReadOnlyBooleanProperty selectedProperty() {
        if (com.jxparallel.fx.Fx.NATIVE) {
            return (com.jxparallel.fx.beans.property.ReadOnlyBooleanProperty) com.jxparallel.fx.nativeimpl.Native.call(this, com.jxparallel.fx.scene.control.Tab.class, "selectedProperty", new Class<?>[] {}, com.jxparallel.fx.beans.property.ReadOnlyBooleanProperty.class);
        }
        return (com.jxparallel.fx.beans.property.ReadOnlyBooleanProperty) com.jxparallel.fx.Fx.jx(((javafx.scene.control.Tab) fxPeer()).selectedProperty());
    }

    public void setClosable(boolean arg0) {
        if (com.jxparallel.fx.Fx.NATIVE) {
            com.jxparallel.fx.nativeimpl.Native.call(this, com.jxparallel.fx.scene.control.Tab.class, "setClosable", new Class<?>[] {boolean.class}, void.class, arg0);
            return;
        }
        ((javafx.scene.control.Tab) fxPeer()).setClosable(arg0);
    }

    public void setContent(com.jxparallel.fx.scene.Node arg0) {
        if (com.jxparallel.fx.Fx.NATIVE) {
            com.jxparallel.fx.nativeimpl.Native.call(this, com.jxparallel.fx.scene.control.Tab.class, "setContent", new Class<?>[] {com.jxparallel.fx.scene.Node.class}, void.class, arg0);
            return;
        }
        ((javafx.scene.control.Tab) fxPeer()).setContent((javafx.scene.Node) com.jxparallel.fx.Fx.fx(arg0));
    }

    public void setContextMenu(com.jxparallel.fx.scene.control.ContextMenu arg0) {
        if (com.jxparallel.fx.Fx.NATIVE) {
            com.jxparallel.fx.nativeimpl.Native.call(this, com.jxparallel.fx.scene.control.Tab.class, "setContextMenu", new Class<?>[] {com.jxparallel.fx.scene.control.ContextMenu.class}, void.class, arg0);
            return;
        }
        ((javafx.scene.control.Tab) fxPeer()).setContextMenu((javafx.scene.control.ContextMenu) com.jxparallel.fx.Fx.fx(arg0));
    }

    public void setDisable(boolean arg0) {
        if (com.jxparallel.fx.Fx.NATIVE) {
            com.jxparallel.fx.nativeimpl.Native.call(this, com.jxparallel.fx.scene.control.Tab.class, "setDisable", new Class<?>[] {boolean.class}, void.class, arg0);
            return;
        }
        ((javafx.scene.control.Tab) fxPeer()).setDisable(arg0);
    }

    protected <E extends com.jxparallel.fx.event.Event> void setEventHandler(com.jxparallel.fx.event.EventType<E> arg0, com.jxparallel.fx.event.EventHandler<E> arg1) {
        if (com.jxparallel.fx.Fx.NATIVE) {
            com.jxparallel.fx.nativeimpl.Native.call(this, com.jxparallel.fx.scene.control.Tab.class, "setEventHandler", new Class<?>[] {com.jxparallel.fx.event.EventType.class, com.jxparallel.fx.event.EventHandler.class}, void.class, arg0, arg1);
            return;
        }
        com.jxparallel.fx.Fx.invoke(fxPeer(), javafx.scene.control.Tab.class, "setEventHandler", new Class<?>[] {javafx.event.EventType.class, javafx.event.EventHandler.class}, (javafx.event.EventType) com.jxparallel.fx.Fx.fx(arg0), (javafx.event.EventHandler) com.jxparallel.fx.Fx.fx(arg1));
    }

    public void setGraphic(com.jxparallel.fx.scene.Node arg0) {
        if (com.jxparallel.fx.Fx.NATIVE) {
            com.jxparallel.fx.nativeimpl.Native.call(this, com.jxparallel.fx.scene.control.Tab.class, "setGraphic", new Class<?>[] {com.jxparallel.fx.scene.Node.class}, void.class, arg0);
            return;
        }
        ((javafx.scene.control.Tab) fxPeer()).setGraphic((javafx.scene.Node) com.jxparallel.fx.Fx.fx(arg0));
    }

    public void setId(java.lang.String arg0) {
        if (com.jxparallel.fx.Fx.NATIVE) {
            com.jxparallel.fx.nativeimpl.Native.call(this, com.jxparallel.fx.scene.control.Tab.class, "setId", new Class<?>[] {java.lang.String.class}, void.class, arg0);
            return;
        }
        ((javafx.scene.control.Tab) fxPeer()).setId(arg0);
    }

    public void setOnCloseRequest(com.jxparallel.fx.event.EventHandler<com.jxparallel.fx.event.Event> arg0) {
        if (com.jxparallel.fx.Fx.NATIVE) {
            com.jxparallel.fx.nativeimpl.Native.call(this, com.jxparallel.fx.scene.control.Tab.class, "setOnCloseRequest", new Class<?>[] {com.jxparallel.fx.event.EventHandler.class}, void.class, arg0);
            return;
        }
        ((javafx.scene.control.Tab) fxPeer()).setOnCloseRequest((javafx.event.EventHandler) com.jxparallel.fx.Fx.fx(arg0));
    }

    public void setOnClosed(com.jxparallel.fx.event.EventHandler<com.jxparallel.fx.event.Event> arg0) {
        if (com.jxparallel.fx.Fx.NATIVE) {
            com.jxparallel.fx.nativeimpl.Native.call(this, com.jxparallel.fx.scene.control.Tab.class, "setOnClosed", new Class<?>[] {com.jxparallel.fx.event.EventHandler.class}, void.class, arg0);
            return;
        }
        ((javafx.scene.control.Tab) fxPeer()).setOnClosed((javafx.event.EventHandler) com.jxparallel.fx.Fx.fx(arg0));
    }

    public void setOnSelectionChanged(com.jxparallel.fx.event.EventHandler<com.jxparallel.fx.event.Event> arg0) {
        if (com.jxparallel.fx.Fx.NATIVE) {
            com.jxparallel.fx.nativeimpl.Native.call(this, com.jxparallel.fx.scene.control.Tab.class, "setOnSelectionChanged", new Class<?>[] {com.jxparallel.fx.event.EventHandler.class}, void.class, arg0);
            return;
        }
        ((javafx.scene.control.Tab) fxPeer()).setOnSelectionChanged((javafx.event.EventHandler) com.jxparallel.fx.Fx.fx(arg0));
    }

    public void setStyle(java.lang.String arg0) {
        if (com.jxparallel.fx.Fx.NATIVE) {
            com.jxparallel.fx.nativeimpl.Native.call(this, com.jxparallel.fx.scene.control.Tab.class, "setStyle", new Class<?>[] {java.lang.String.class}, void.class, arg0);
            return;
        }
        ((javafx.scene.control.Tab) fxPeer()).setStyle(arg0);
    }

    public void setText(java.lang.String arg0) {
        if (com.jxparallel.fx.Fx.NATIVE) {
            com.jxparallel.fx.nativeimpl.Native.call(this, com.jxparallel.fx.scene.control.Tab.class, "setText", new Class<?>[] {java.lang.String.class}, void.class, arg0);
            return;
        }
        ((javafx.scene.control.Tab) fxPeer()).setText(arg0);
    }

    public void setTooltip(com.jxparallel.fx.scene.control.Tooltip arg0) {
        if (com.jxparallel.fx.Fx.NATIVE) {
            com.jxparallel.fx.nativeimpl.Native.call(this, com.jxparallel.fx.scene.control.Tab.class, "setTooltip", new Class<?>[] {com.jxparallel.fx.scene.control.Tooltip.class}, void.class, arg0);
            return;
        }
        ((javafx.scene.control.Tab) fxPeer()).setTooltip((javafx.scene.control.Tooltip) com.jxparallel.fx.Fx.fx(arg0));
    }

    public void setUserData(java.lang.Object arg0) {
        if (com.jxparallel.fx.Fx.NATIVE) {
            com.jxparallel.fx.nativeimpl.Native.call(this, com.jxparallel.fx.scene.control.Tab.class, "setUserData", new Class<?>[] {java.lang.Object.class}, void.class, arg0);
            return;
        }
        ((javafx.scene.control.Tab) fxPeer()).setUserData((java.lang.Object) com.jxparallel.fx.Fx.fx(arg0));
    }

    public com.jxparallel.fx.beans.property.StringProperty styleProperty() {
        if (com.jxparallel.fx.Fx.NATIVE) {
            return (com.jxparallel.fx.beans.property.StringProperty) com.jxparallel.fx.nativeimpl.Native.call(this, com.jxparallel.fx.scene.control.Tab.class, "styleProperty", new Class<?>[] {}, com.jxparallel.fx.beans.property.StringProperty.class);
        }
        return (com.jxparallel.fx.beans.property.StringProperty) com.jxparallel.fx.Fx.jx(((javafx.scene.control.Tab) fxPeer()).styleProperty());
    }

    public com.jxparallel.fx.beans.property.ReadOnlyObjectProperty<com.jxparallel.fx.scene.control.TabPane> tabPaneProperty() {
        if (com.jxparallel.fx.Fx.NATIVE) {
            return (com.jxparallel.fx.beans.property.ReadOnlyObjectProperty) com.jxparallel.fx.nativeimpl.Native.call(this, com.jxparallel.fx.scene.control.Tab.class, "tabPaneProperty", new Class<?>[] {}, com.jxparallel.fx.beans.property.ReadOnlyObjectProperty.class);
        }
        return (com.jxparallel.fx.beans.property.ReadOnlyObjectProperty) com.jxparallel.fx.Fx.jx(((javafx.scene.control.Tab) fxPeer()).tabPaneProperty());
    }

    public com.jxparallel.fx.beans.property.StringProperty textProperty() {
        if (com.jxparallel.fx.Fx.NATIVE) {
            return (com.jxparallel.fx.beans.property.StringProperty) com.jxparallel.fx.nativeimpl.Native.call(this, com.jxparallel.fx.scene.control.Tab.class, "textProperty", new Class<?>[] {}, com.jxparallel.fx.beans.property.StringProperty.class);
        }
        return (com.jxparallel.fx.beans.property.StringProperty) com.jxparallel.fx.Fx.jx(((javafx.scene.control.Tab) fxPeer()).textProperty());
    }

    public com.jxparallel.fx.beans.property.ObjectProperty<com.jxparallel.fx.scene.control.Tooltip> tooltipProperty() {
        if (com.jxparallel.fx.Fx.NATIVE) {
            return (com.jxparallel.fx.beans.property.ObjectProperty) com.jxparallel.fx.nativeimpl.Native.call(this, com.jxparallel.fx.scene.control.Tab.class, "tooltipProperty", new Class<?>[] {}, com.jxparallel.fx.beans.property.ObjectProperty.class);
        }
        return (com.jxparallel.fx.beans.property.ObjectProperty) com.jxparallel.fx.Fx.jx(((javafx.scene.control.Tab) fxPeer()).tooltipProperty());
    }
}
