package com.jxparallel.fx.scene.control;

/** JXParallel counterpart of {@link javafx.scene.control.TableSelectionModel} (generated by scripts/GenerateFxApi.java). */
@SuppressWarnings({"unchecked", "rawtypes", "deprecation"})
public class TableSelectionModel<T> implements com.jxparallel.fx.Fx.Backed {
    private final Object fxPeer;

    protected TableSelectionModel(com.jxparallel.fx.Fx.Wrap wrap, Object peer) {
        this.fxPeer = peer;
    }

    @Override
    public Object fxPeer() {
        return fxPeer;
    }

    @Override
    public boolean equals(Object o) {
        return o == this || fxPeer().equals(com.jxparallel.fx.Fx.fx(o));
    }

    @Override
    public int hashCode() {
        return fxPeer().hashCode();
    }

    @Override
    public String toString() {
        return fxPeer().toString();
    }

    public com.jxparallel.fx.beans.property.BooleanProperty cellSelectionEnabledProperty() {
        return (com.jxparallel.fx.beans.property.BooleanProperty) com.jxparallel.fx.Fx.jx(((javafx.scene.control.TableSelectionModel) fxPeer()).cellSelectionEnabledProperty());
    }

    public void clearAndSelect(int arg0, com.jxparallel.fx.scene.control.TableColumnBase<T, ?> arg1) {
        if (fxPeer() instanceof com.jxparallel.fx.Fx.Owned) {
            ((com.jxparallel.fx.Fx.Owned) fxPeer()).callSuper("clearAndSelect(int,TableColumnBase)", new Object[] {arg0, (javafx.scene.control.TableColumnBase) com.jxparallel.fx.Fx.fxAs(arg1, javafx.scene.control.TableColumnBase.class)});
        } else {
            com.jxparallel.fx.Fx.invoke(fxPeer(), javafx.scene.control.TableSelectionModel.class, "clearAndSelect", new Class<?>[] {int.class, javafx.scene.control.TableColumnBase.class}, arg0, (javafx.scene.control.TableColumnBase) com.jxparallel.fx.Fx.fxAs(arg1, javafx.scene.control.TableColumnBase.class));
        }
    }

    public void clearSelection(int arg0, com.jxparallel.fx.scene.control.TableColumnBase<T, ?> arg1) {
        if (fxPeer() instanceof com.jxparallel.fx.Fx.Owned) {
            ((com.jxparallel.fx.Fx.Owned) fxPeer()).callSuper("clearSelection(int,TableColumnBase)", new Object[] {arg0, (javafx.scene.control.TableColumnBase) com.jxparallel.fx.Fx.fxAs(arg1, javafx.scene.control.TableColumnBase.class)});
        } else {
            com.jxparallel.fx.Fx.invoke(fxPeer(), javafx.scene.control.TableSelectionModel.class, "clearSelection", new Class<?>[] {int.class, javafx.scene.control.TableColumnBase.class}, arg0, (javafx.scene.control.TableColumnBase) com.jxparallel.fx.Fx.fxAs(arg1, javafx.scene.control.TableColumnBase.class));
        }
    }

    public boolean isCellSelectionEnabled() {
        return ((javafx.scene.control.TableSelectionModel) fxPeer()).isCellSelectionEnabled();
    }

    public boolean isSelected(int arg0, com.jxparallel.fx.scene.control.TableColumnBase<T, ?> arg1) {
        return (Boolean) (fxPeer() instanceof com.jxparallel.fx.Fx.Owned ? ((com.jxparallel.fx.Fx.Owned) fxPeer()).callSuper("isSelected(int,TableColumnBase)", new Object[] {arg0, (javafx.scene.control.TableColumnBase) com.jxparallel.fx.Fx.fxAs(arg1, javafx.scene.control.TableColumnBase.class)}) : com.jxparallel.fx.Fx.invoke(fxPeer(), javafx.scene.control.TableSelectionModel.class, "isSelected", new Class<?>[] {int.class, javafx.scene.control.TableColumnBase.class}, arg0, (javafx.scene.control.TableColumnBase) com.jxparallel.fx.Fx.fxAs(arg1, javafx.scene.control.TableColumnBase.class)));
    }

    public void select(int arg0, com.jxparallel.fx.scene.control.TableColumnBase<T, ?> arg1) {
        if (fxPeer() instanceof com.jxparallel.fx.Fx.Owned) {
            ((com.jxparallel.fx.Fx.Owned) fxPeer()).callSuper("select(int,TableColumnBase)", new Object[] {arg0, (javafx.scene.control.TableColumnBase) com.jxparallel.fx.Fx.fxAs(arg1, javafx.scene.control.TableColumnBase.class)});
        } else {
            com.jxparallel.fx.Fx.invoke(fxPeer(), javafx.scene.control.TableSelectionModel.class, "select", new Class<?>[] {int.class, javafx.scene.control.TableColumnBase.class}, arg0, (javafx.scene.control.TableColumnBase) com.jxparallel.fx.Fx.fxAs(arg1, javafx.scene.control.TableColumnBase.class));
        }
    }

    public void selectAboveCell() {
        if (fxPeer() instanceof com.jxparallel.fx.Fx.Owned) {
            ((com.jxparallel.fx.Fx.Owned) fxPeer()).callSuper("selectAboveCell()", new Object[] {});
        } else {
            com.jxparallel.fx.Fx.invoke(fxPeer(), javafx.scene.control.TableSelectionModel.class, "selectAboveCell", new Class<?>[] {});
        }
    }

    public void selectBelowCell() {
        if (fxPeer() instanceof com.jxparallel.fx.Fx.Owned) {
            ((com.jxparallel.fx.Fx.Owned) fxPeer()).callSuper("selectBelowCell()", new Object[] {});
        } else {
            com.jxparallel.fx.Fx.invoke(fxPeer(), javafx.scene.control.TableSelectionModel.class, "selectBelowCell", new Class<?>[] {});
        }
    }

    public void selectLeftCell() {
        if (fxPeer() instanceof com.jxparallel.fx.Fx.Owned) {
            ((com.jxparallel.fx.Fx.Owned) fxPeer()).callSuper("selectLeftCell()", new Object[] {});
        } else {
            com.jxparallel.fx.Fx.invoke(fxPeer(), javafx.scene.control.TableSelectionModel.class, "selectLeftCell", new Class<?>[] {});
        }
    }

    public void selectRange(int arg0, com.jxparallel.fx.scene.control.TableColumnBase<T, ?> arg1, int arg2, com.jxparallel.fx.scene.control.TableColumnBase<T, ?> arg3) {
        if (fxPeer() instanceof com.jxparallel.fx.Fx.Owned) {
            ((com.jxparallel.fx.Fx.Owned) fxPeer()).callSuper("selectRange(int,TableColumnBase,int,TableColumnBase)", new Object[] {arg0, (javafx.scene.control.TableColumnBase) com.jxparallel.fx.Fx.fxAs(arg1, javafx.scene.control.TableColumnBase.class), arg2, (javafx.scene.control.TableColumnBase) com.jxparallel.fx.Fx.fxAs(arg3, javafx.scene.control.TableColumnBase.class)});
        } else {
            com.jxparallel.fx.Fx.invoke(fxPeer(), javafx.scene.control.TableSelectionModel.class, "selectRange", new Class<?>[] {int.class, javafx.scene.control.TableColumnBase.class, int.class, javafx.scene.control.TableColumnBase.class}, arg0, (javafx.scene.control.TableColumnBase) com.jxparallel.fx.Fx.fxAs(arg1, javafx.scene.control.TableColumnBase.class), arg2, (javafx.scene.control.TableColumnBase) com.jxparallel.fx.Fx.fxAs(arg3, javafx.scene.control.TableColumnBase.class));
        }
    }

    public void selectRightCell() {
        if (fxPeer() instanceof com.jxparallel.fx.Fx.Owned) {
            ((com.jxparallel.fx.Fx.Owned) fxPeer()).callSuper("selectRightCell()", new Object[] {});
        } else {
            com.jxparallel.fx.Fx.invoke(fxPeer(), javafx.scene.control.TableSelectionModel.class, "selectRightCell", new Class<?>[] {});
        }
    }

    public void setCellSelectionEnabled(boolean arg0) {
        ((javafx.scene.control.TableSelectionModel) fxPeer()).setCellSelectionEnabled(arg0);
    }

    public boolean isEmpty() {
        return ((javafx.scene.control.TableSelectionModel) fxPeer()).isEmpty();
    }

    public boolean isSelected(int arg0) {
        return ((javafx.scene.control.TableSelectionModel) fxPeer()).isSelected(arg0);
    }

    public com.jxparallel.fx.collections.ObservableList<T> getSelectedItems() {
        return (com.jxparallel.fx.collections.ObservableList) com.jxparallel.fx.Fx.jx(((javafx.scene.control.TableSelectionModel) fxPeer()).getSelectedItems());
    }

    public com.jxparallel.fx.collections.ObservableList<java.lang.Integer> getSelectedIndices() {
        return (com.jxparallel.fx.collections.ObservableList) com.jxparallel.fx.Fx.jx(((javafx.scene.control.TableSelectionModel) fxPeer()).getSelectedIndices());
    }

    public void clearAndSelect(int arg0) {
        ((javafx.scene.control.TableSelectionModel) fxPeer()).clearAndSelect(arg0);
    }

    public void clearSelection() {
        ((javafx.scene.control.TableSelectionModel) fxPeer()).clearSelection();
    }

    public void clearSelection(int arg0) {
        ((javafx.scene.control.TableSelectionModel) fxPeer()).clearSelection(arg0);
    }

    public void select(T arg0) {
        ((javafx.scene.control.TableSelectionModel) fxPeer()).select((T) com.jxparallel.fx.Fx.fx(arg0));
    }

    public void select(int arg0) {
        ((javafx.scene.control.TableSelectionModel) fxPeer()).select(arg0);
    }

    public void selectAll() {
        ((javafx.scene.control.TableSelectionModel) fxPeer()).selectAll();
    }

    public void selectFirst() {
        ((javafx.scene.control.TableSelectionModel) fxPeer()).selectFirst();
    }

    public void selectIndices(int arg0, int... arg1) {
        ((javafx.scene.control.TableSelectionModel) fxPeer()).selectIndices(arg0, arg1);
    }

    public void selectLast() {
        ((javafx.scene.control.TableSelectionModel) fxPeer()).selectLast();
    }

    public void selectNext() {
        ((javafx.scene.control.TableSelectionModel) fxPeer()).selectNext();
    }

    public void selectPrevious() {
        ((javafx.scene.control.TableSelectionModel) fxPeer()).selectPrevious();
    }

    public com.jxparallel.fx.beans.property.ObjectProperty<com.jxparallel.fx.scene.control.SelectionMode> selectionModeProperty() {
        return (com.jxparallel.fx.beans.property.ObjectProperty) com.jxparallel.fx.Fx.jx(((javafx.scene.control.TableSelectionModel) fxPeer()).selectionModeProperty());
    }

    public com.jxparallel.fx.scene.control.SelectionMode getSelectionMode() {
        return (com.jxparallel.fx.scene.control.SelectionMode) com.jxparallel.fx.Fx.jx(((javafx.scene.control.TableSelectionModel) fxPeer()).getSelectionMode());
    }

    public void setSelectionMode(com.jxparallel.fx.scene.control.SelectionMode arg0) {
        ((javafx.scene.control.TableSelectionModel) fxPeer()).setSelectionMode((javafx.scene.control.SelectionMode) com.jxparallel.fx.Fx.fx(arg0));
    }

    public void selectRange(int arg0, int arg1) {
        ((javafx.scene.control.TableSelectionModel) fxPeer()).selectRange(arg0, arg1);
    }

    public T getSelectedItem() {
        return (T) com.jxparallel.fx.Fx.jx(((javafx.scene.control.TableSelectionModel) fxPeer()).getSelectedItem());
    }

    public int getSelectedIndex() {
        return ((javafx.scene.control.TableSelectionModel) fxPeer()).getSelectedIndex();
    }

    public com.jxparallel.fx.beans.property.ReadOnlyIntegerProperty selectedIndexProperty() {
        return (com.jxparallel.fx.beans.property.ReadOnlyIntegerProperty) com.jxparallel.fx.Fx.jx(((javafx.scene.control.TableSelectionModel) fxPeer()).selectedIndexProperty());
    }

    public com.jxparallel.fx.beans.property.ReadOnlyObjectProperty<T> selectedItemProperty() {
        return (com.jxparallel.fx.beans.property.ReadOnlyObjectProperty) com.jxparallel.fx.Fx.jx(((javafx.scene.control.TableSelectionModel) fxPeer()).selectedItemProperty());
    }
}
