package com.jxparallel.fx.scene.control;

/** JXParallel counterpart of {@link javafx.scene.control.TableFocusModel} (generated by scripts/GenerateFxApi.java). */
@SuppressWarnings({"unchecked", "rawtypes", "deprecation"})
public class TableFocusModel<T, TC extends com.jxparallel.fx.scene.control.TableColumnBase<T, ?>> extends com.jxparallel.fx.scene.control.FocusModel<T> {
    protected TableFocusModel(com.jxparallel.fx.Fx.Wrap wrap, Object peer) {
        super(wrap, peer);
    }

    public TableFocusModel() {
        this(com.jxparallel.fx.Fx.WRAP, new com.jxparallel.fx.peer.scene.control.TableFocusModel());
        com.jxparallel.fx.Fx.own(fxPeer(), this);
    }

    public void focus(int arg0, TC arg1) {
        if (fxPeer() instanceof com.jxparallel.fx.Fx.Owned) {
            ((com.jxparallel.fx.Fx.Owned) fxPeer()).callSuper("focus(int,TableColumnBase)", new Object[] {arg0, (javafx.scene.control.TableColumnBase) com.jxparallel.fx.Fx.fxAs(arg1, javafx.scene.control.TableColumnBase.class)});
        } else {
            com.jxparallel.fx.Fx.invoke(fxPeer(), javafx.scene.control.TableFocusModel.class, "focus", new Class<?>[] {int.class, javafx.scene.control.TableColumnBase.class}, arg0, (javafx.scene.control.TableColumnBase) com.jxparallel.fx.Fx.fxAs(arg1, javafx.scene.control.TableColumnBase.class));
        }
    }

    public void focusAboveCell() {
        if (fxPeer() instanceof com.jxparallel.fx.Fx.Owned) {
            ((com.jxparallel.fx.Fx.Owned) fxPeer()).callSuper("focusAboveCell()", new Object[] {});
        } else {
            com.jxparallel.fx.Fx.invoke(fxPeer(), javafx.scene.control.TableFocusModel.class, "focusAboveCell", new Class<?>[] {});
        }
    }

    public void focusBelowCell() {
        if (fxPeer() instanceof com.jxparallel.fx.Fx.Owned) {
            ((com.jxparallel.fx.Fx.Owned) fxPeer()).callSuper("focusBelowCell()", new Object[] {});
        } else {
            com.jxparallel.fx.Fx.invoke(fxPeer(), javafx.scene.control.TableFocusModel.class, "focusBelowCell", new Class<?>[] {});
        }
    }

    public void focusLeftCell() {
        if (fxPeer() instanceof com.jxparallel.fx.Fx.Owned) {
            ((com.jxparallel.fx.Fx.Owned) fxPeer()).callSuper("focusLeftCell()", new Object[] {});
        } else {
            com.jxparallel.fx.Fx.invoke(fxPeer(), javafx.scene.control.TableFocusModel.class, "focusLeftCell", new Class<?>[] {});
        }
    }

    public void focusRightCell() {
        if (fxPeer() instanceof com.jxparallel.fx.Fx.Owned) {
            ((com.jxparallel.fx.Fx.Owned) fxPeer()).callSuper("focusRightCell()", new Object[] {});
        } else {
            com.jxparallel.fx.Fx.invoke(fxPeer(), javafx.scene.control.TableFocusModel.class, "focusRightCell", new Class<?>[] {});
        }
    }

    public boolean isFocused(int arg0, TC arg1) {
        return (Boolean) (fxPeer() instanceof com.jxparallel.fx.Fx.Owned ? ((com.jxparallel.fx.Fx.Owned) fxPeer()).callSuper("isFocused(int,TableColumnBase)", new Object[] {arg0, (javafx.scene.control.TableColumnBase) com.jxparallel.fx.Fx.fxAs(arg1, javafx.scene.control.TableColumnBase.class)}) : com.jxparallel.fx.Fx.invoke(fxPeer(), javafx.scene.control.TableFocusModel.class, "isFocused", new Class<?>[] {int.class, javafx.scene.control.TableColumnBase.class}, arg0, (javafx.scene.control.TableColumnBase) com.jxparallel.fx.Fx.fxAs(arg1, javafx.scene.control.TableColumnBase.class)));
    }

    /** Called by the peer: runs the JX (possibly overridden) method. */
    public static Object $hook(Object self, String method, Object[] a) {
        TableFocusModel jx = (TableFocusModel) self;
        try {
        switch (method) {
            case "isFocused(int,TableColumnBase)":
                return (Object) jx.isFocused((Integer) a[0], (com.jxparallel.fx.scene.control.TableColumnBase) a[1]);
            case "focus(int,TableColumnBase)":
                jx.focus((Integer) a[0], (com.jxparallel.fx.scene.control.TableColumnBase) a[1]);
                return null;
            case "focusAboveCell()":
                jx.focusAboveCell();
                return null;
            case "focusBelowCell()":
                jx.focusBelowCell();
                return null;
            case "focusLeftCell()":
                jx.focusLeftCell();
                return null;
            case "focusRightCell()":
                jx.focusRightCell();
                return null;
            case "getModelItem(int)":
                return jx.getModelItem((Integer) a[0]);
            case "getItemCount()":
                return (Object) jx.getItemCount();
            default:
                throw new IllegalArgumentException(method);
        }
        } catch (Exception e) {
            throw com.jxparallel.fx.Fx.sneaky(e);
        }
    }
}
