package com.jxparallel.fx.scene.control;

/** JXParallel counterpart of {@link javafx.scene.control.TableColumn} (generated by scripts/GenerateFxApi.java). */
@SuppressWarnings({"unchecked", "rawtypes", "deprecation"})
public class TableColumn<S, T> extends com.jxparallel.fx.scene.control.TableColumnBase<S, T> implements com.jxparallel.fx.event.EventTarget {
    protected TableColumn(com.jxparallel.fx.Fx.Wrap wrap, Object peer) {
        super(wrap, peer);
    }

    public TableColumn() {
        this(com.jxparallel.fx.Fx.WRAP, com.jxparallel.fx.Fx.NATIVE ? com.jxparallel.fx.nativeimpl.Native.create(javafx.scene.control.TableColumn.class, new String[] {}, new Object[] {}) : new com.jxparallel.fx.peer.scene.control.TableColumn());
        com.jxparallel.fx.Fx.own(fxPeer(), this);
    }

    public TableColumn(java.lang.String arg0) {
        this(com.jxparallel.fx.Fx.WRAP, com.jxparallel.fx.Fx.NATIVE ? com.jxparallel.fx.nativeimpl.Native.create(javafx.scene.control.TableColumn.class, new String[] {null}, new Object[] {arg0}) : new com.jxparallel.fx.peer.scene.control.TableColumn(arg0));
        com.jxparallel.fx.Fx.own(fxPeer(), this);
    }

    public static final com.jxparallel.fx.util.Callback<com.jxparallel.fx.scene.control.TableColumn<?, ?>, com.jxparallel.fx.scene.control.TableCell<?, ?>> DEFAULT_CELL_FACTORY = (com.jxparallel.fx.util.Callback) com.jxparallel.fx.Fx.jx(javafx.scene.control.TableColumn.DEFAULT_CELL_FACTORY);

    public com.jxparallel.fx.beans.property.ObjectProperty<com.jxparallel.fx.util.Callback<com.jxparallel.fx.scene.control.TableColumn<S, T>, com.jxparallel.fx.scene.control.TableCell<S, T>>> cellFactoryProperty() {
        if (com.jxparallel.fx.Fx.NATIVE) {
            return (com.jxparallel.fx.beans.property.ObjectProperty) com.jxparallel.fx.nativeimpl.Native.call(this, com.jxparallel.fx.scene.control.TableColumn.class, "cellFactoryProperty", new Class<?>[] {}, com.jxparallel.fx.beans.property.ObjectProperty.class);
        }
        return (com.jxparallel.fx.beans.property.ObjectProperty) com.jxparallel.fx.Fx.jx(((javafx.scene.control.TableColumn) fxPeer()).cellFactoryProperty());
    }

    public com.jxparallel.fx.beans.property.ObjectProperty<com.jxparallel.fx.util.Callback<com.jxparallel.fx.scene.control.TableColumn.CellDataFeatures<S, T>, com.jxparallel.fx.beans.value.ObservableValue<T>>> cellValueFactoryProperty() {
        if (com.jxparallel.fx.Fx.NATIVE) {
            return (com.jxparallel.fx.beans.property.ObjectProperty) com.jxparallel.fx.nativeimpl.Native.call(this, com.jxparallel.fx.scene.control.TableColumn.class, "cellValueFactoryProperty", new Class<?>[] {}, com.jxparallel.fx.beans.property.ObjectProperty.class);
        }
        return (com.jxparallel.fx.beans.property.ObjectProperty) com.jxparallel.fx.Fx.jx(((javafx.scene.control.TableColumn) fxPeer()).cellValueFactoryProperty());
    }

    public static <S, T> com.jxparallel.fx.event.EventType<com.jxparallel.fx.scene.control.TableColumn.CellEditEvent<S, T>> editAnyEvent() {
        if (com.jxparallel.fx.Fx.NATIVE) {
            return (com.jxparallel.fx.event.EventType) com.jxparallel.fx.nativeimpl.Native.call(null, com.jxparallel.fx.scene.control.TableColumn.class, "editAnyEvent", new Class<?>[] {}, com.jxparallel.fx.event.EventType.class);
        }
        return (com.jxparallel.fx.event.EventType) com.jxparallel.fx.Fx.jx(javafx.scene.control.TableColumn.editAnyEvent());
    }

    public static <S, T> com.jxparallel.fx.event.EventType<com.jxparallel.fx.scene.control.TableColumn.CellEditEvent<S, T>> editCancelEvent() {
        if (com.jxparallel.fx.Fx.NATIVE) {
            return (com.jxparallel.fx.event.EventType) com.jxparallel.fx.nativeimpl.Native.call(null, com.jxparallel.fx.scene.control.TableColumn.class, "editCancelEvent", new Class<?>[] {}, com.jxparallel.fx.event.EventType.class);
        }
        return (com.jxparallel.fx.event.EventType) com.jxparallel.fx.Fx.jx(javafx.scene.control.TableColumn.editCancelEvent());
    }

    public static <S, T> com.jxparallel.fx.event.EventType<com.jxparallel.fx.scene.control.TableColumn.CellEditEvent<S, T>> editCommitEvent() {
        if (com.jxparallel.fx.Fx.NATIVE) {
            return (com.jxparallel.fx.event.EventType) com.jxparallel.fx.nativeimpl.Native.call(null, com.jxparallel.fx.scene.control.TableColumn.class, "editCommitEvent", new Class<?>[] {}, com.jxparallel.fx.event.EventType.class);
        }
        return (com.jxparallel.fx.event.EventType) com.jxparallel.fx.Fx.jx(javafx.scene.control.TableColumn.editCommitEvent());
    }

    public static <S, T> com.jxparallel.fx.event.EventType<com.jxparallel.fx.scene.control.TableColumn.CellEditEvent<S, T>> editStartEvent() {
        if (com.jxparallel.fx.Fx.NATIVE) {
            return (com.jxparallel.fx.event.EventType) com.jxparallel.fx.nativeimpl.Native.call(null, com.jxparallel.fx.scene.control.TableColumn.class, "editStartEvent", new Class<?>[] {}, com.jxparallel.fx.event.EventType.class);
        }
        return (com.jxparallel.fx.event.EventType) com.jxparallel.fx.Fx.jx(javafx.scene.control.TableColumn.editStartEvent());
    }

    public com.jxparallel.fx.util.Callback<com.jxparallel.fx.scene.control.TableColumn<S, T>, com.jxparallel.fx.scene.control.TableCell<S, T>> getCellFactory() {
        if (com.jxparallel.fx.Fx.NATIVE) {
            return (com.jxparallel.fx.util.Callback) com.jxparallel.fx.nativeimpl.Native.call(this, com.jxparallel.fx.scene.control.TableColumn.class, "getCellFactory", new Class<?>[] {}, com.jxparallel.fx.util.Callback.class);
        }
        return (com.jxparallel.fx.util.Callback) com.jxparallel.fx.Fx.jx(((javafx.scene.control.TableColumn) fxPeer()).getCellFactory());
    }

    public com.jxparallel.fx.beans.value.ObservableValue<T> getCellObservableValue(S arg0) {
        if (com.jxparallel.fx.Fx.NATIVE) {
            return (com.jxparallel.fx.beans.value.ObservableValue) com.jxparallel.fx.nativeimpl.Native.call(this, com.jxparallel.fx.scene.control.TableColumn.class, "getCellObservableValue", new Class<?>[] {java.lang.Object.class}, com.jxparallel.fx.beans.value.ObservableValue.class, arg0);
        }
        return (com.jxparallel.fx.beans.value.ObservableValue) com.jxparallel.fx.Fx.jx(((javafx.scene.control.TableColumn) fxPeer()).getCellObservableValue((S) com.jxparallel.fx.Fx.fx(arg0)));
    }

    public com.jxparallel.fx.beans.value.ObservableValue<T> getCellObservableValue(int arg0) {
        if (com.jxparallel.fx.Fx.NATIVE) {
            return (com.jxparallel.fx.beans.value.ObservableValue) com.jxparallel.fx.nativeimpl.Native.call(this, com.jxparallel.fx.scene.control.TableColumn.class, "getCellObservableValue", new Class<?>[] {int.class}, com.jxparallel.fx.beans.value.ObservableValue.class, arg0);
        }
        return (com.jxparallel.fx.beans.value.ObservableValue) com.jxparallel.fx.Fx.jx(((javafx.scene.control.TableColumn) fxPeer()).getCellObservableValue(arg0));
    }

    public com.jxparallel.fx.util.Callback<com.jxparallel.fx.scene.control.TableColumn.CellDataFeatures<S, T>, com.jxparallel.fx.beans.value.ObservableValue<T>> getCellValueFactory() {
        if (com.jxparallel.fx.Fx.NATIVE) {
            return (com.jxparallel.fx.util.Callback) com.jxparallel.fx.nativeimpl.Native.call(this, com.jxparallel.fx.scene.control.TableColumn.class, "getCellValueFactory", new Class<?>[] {}, com.jxparallel.fx.util.Callback.class);
        }
        return (com.jxparallel.fx.util.Callback) com.jxparallel.fx.Fx.jx(((javafx.scene.control.TableColumn) fxPeer()).getCellValueFactory());
    }

    public static java.util.List<javafx.css.CssMetaData<? extends javafx.css.Styleable, ?>> getClassCssMetaData() {
        if (com.jxparallel.fx.Fx.NATIVE) {
            return (java.util.List) com.jxparallel.fx.nativeimpl.Native.call(null, com.jxparallel.fx.scene.control.TableColumn.class, "getClassCssMetaData", new Class<?>[] {}, java.util.List.class);
        }
        return javafx.scene.control.TableColumn.getClassCssMetaData();
    }

    public com.jxparallel.fx.collections.ObservableList<com.jxparallel.fx.scene.control.TableColumn<S, ?>> getColumns() {
        if (com.jxparallel.fx.Fx.NATIVE) {
            return (com.jxparallel.fx.collections.ObservableList) com.jxparallel.fx.nativeimpl.Native.call(this, com.jxparallel.fx.scene.control.TableColumn.class, "getColumns", new Class<?>[] {}, com.jxparallel.fx.collections.ObservableList.class);
        }
        return (com.jxparallel.fx.collections.ObservableList) com.jxparallel.fx.Fx.jx(((javafx.scene.control.TableColumn) fxPeer()).getColumns());
    }

    public java.util.List<javafx.css.CssMetaData<? extends javafx.css.Styleable, ?>> getCssMetaData() {
        if (com.jxparallel.fx.Fx.NATIVE) {
            return (java.util.List) com.jxparallel.fx.nativeimpl.Native.call(this, com.jxparallel.fx.scene.control.TableColumn.class, "getCssMetaData", new Class<?>[] {}, java.util.List.class);
        }
        return ((javafx.scene.control.TableColumn) fxPeer()).getCssMetaData();
    }

    public com.jxparallel.fx.event.EventHandler<com.jxparallel.fx.scene.control.TableColumn.CellEditEvent<S, T>> getOnEditCancel() {
        if (com.jxparallel.fx.Fx.NATIVE) {
            return (com.jxparallel.fx.event.EventHandler) com.jxparallel.fx.nativeimpl.Native.call(this, com.jxparallel.fx.scene.control.TableColumn.class, "getOnEditCancel", new Class<?>[] {}, com.jxparallel.fx.event.EventHandler.class);
        }
        return (com.jxparallel.fx.event.EventHandler) com.jxparallel.fx.Fx.jx(((javafx.scene.control.TableColumn) fxPeer()).getOnEditCancel());
    }

    public com.jxparallel.fx.event.EventHandler<com.jxparallel.fx.scene.control.TableColumn.CellEditEvent<S, T>> getOnEditCommit() {
        if (com.jxparallel.fx.Fx.NATIVE) {
            return (com.jxparallel.fx.event.EventHandler) com.jxparallel.fx.nativeimpl.Native.call(this, com.jxparallel.fx.scene.control.TableColumn.class, "getOnEditCommit", new Class<?>[] {}, com.jxparallel.fx.event.EventHandler.class);
        }
        return (com.jxparallel.fx.event.EventHandler) com.jxparallel.fx.Fx.jx(((javafx.scene.control.TableColumn) fxPeer()).getOnEditCommit());
    }

    public com.jxparallel.fx.event.EventHandler<com.jxparallel.fx.scene.control.TableColumn.CellEditEvent<S, T>> getOnEditStart() {
        if (com.jxparallel.fx.Fx.NATIVE) {
            return (com.jxparallel.fx.event.EventHandler) com.jxparallel.fx.nativeimpl.Native.call(this, com.jxparallel.fx.scene.control.TableColumn.class, "getOnEditStart", new Class<?>[] {}, com.jxparallel.fx.event.EventHandler.class);
        }
        return (com.jxparallel.fx.event.EventHandler) com.jxparallel.fx.Fx.jx(((javafx.scene.control.TableColumn) fxPeer()).getOnEditStart());
    }

    public com.jxparallel.fx.scene.control.TableColumn.SortType getSortType() {
        if (com.jxparallel.fx.Fx.NATIVE) {
            return (com.jxparallel.fx.scene.control.TableColumn.SortType) com.jxparallel.fx.nativeimpl.Native.call(this, com.jxparallel.fx.scene.control.TableColumn.class, "getSortType", new Class<?>[] {}, com.jxparallel.fx.scene.control.TableColumn.SortType.class);
        }
        return (com.jxparallel.fx.scene.control.TableColumn.SortType) com.jxparallel.fx.Fx.jx(((javafx.scene.control.TableColumn) fxPeer()).getSortType());
    }

    public com.jxparallel.fx.css.Styleable getStyleableParent() {
        if (com.jxparallel.fx.Fx.NATIVE) {
            return (com.jxparallel.fx.css.Styleable) com.jxparallel.fx.nativeimpl.Native.call(this, com.jxparallel.fx.scene.control.TableColumn.class, "getStyleableParent", new Class<?>[] {}, com.jxparallel.fx.css.Styleable.class);
        }
        return (com.jxparallel.fx.css.Styleable) com.jxparallel.fx.Fx.jx(((javafx.scene.control.TableColumn) fxPeer()).getStyleableParent());
    }

    public com.jxparallel.fx.scene.control.TableView<S> getTableView() {
        if (com.jxparallel.fx.Fx.NATIVE) {
            return (com.jxparallel.fx.scene.control.TableView) com.jxparallel.fx.nativeimpl.Native.call(this, com.jxparallel.fx.scene.control.TableColumn.class, "getTableView", new Class<?>[] {}, com.jxparallel.fx.scene.control.TableView.class);
        }
        return (com.jxparallel.fx.scene.control.TableView) com.jxparallel.fx.Fx.jx(((javafx.scene.control.TableColumn) fxPeer()).getTableView());
    }

    public java.lang.String getTypeSelector() {
        if (com.jxparallel.fx.Fx.NATIVE) {
            return (java.lang.String) com.jxparallel.fx.nativeimpl.Native.call(this, com.jxparallel.fx.scene.control.TableColumn.class, "getTypeSelector", new Class<?>[] {}, java.lang.String.class);
        }
        return ((javafx.scene.control.TableColumn) fxPeer()).getTypeSelector();
    }

    public com.jxparallel.fx.scene.Node impl_styleableGetNode() {
        if (com.jxparallel.fx.Fx.NATIVE) {
            return (com.jxparallel.fx.scene.Node) com.jxparallel.fx.nativeimpl.Native.call(this, com.jxparallel.fx.scene.control.TableColumn.class, "impl_styleableGetNode", new Class<?>[] {}, com.jxparallel.fx.scene.Node.class);
        }
        return (com.jxparallel.fx.scene.Node) com.jxparallel.fx.Fx.jx(((javafx.scene.control.TableColumn) fxPeer()).impl_styleableGetNode());
    }

    public com.jxparallel.fx.beans.property.ObjectProperty<com.jxparallel.fx.event.EventHandler<com.jxparallel.fx.scene.control.TableColumn.CellEditEvent<S, T>>> onEditCancelProperty() {
        if (com.jxparallel.fx.Fx.NATIVE) {
            return (com.jxparallel.fx.beans.property.ObjectProperty) com.jxparallel.fx.nativeimpl.Native.call(this, com.jxparallel.fx.scene.control.TableColumn.class, "onEditCancelProperty", new Class<?>[] {}, com.jxparallel.fx.beans.property.ObjectProperty.class);
        }
        return (com.jxparallel.fx.beans.property.ObjectProperty) com.jxparallel.fx.Fx.jx(((javafx.scene.control.TableColumn) fxPeer()).onEditCancelProperty());
    }

    public com.jxparallel.fx.beans.property.ObjectProperty<com.jxparallel.fx.event.EventHandler<com.jxparallel.fx.scene.control.TableColumn.CellEditEvent<S, T>>> onEditCommitProperty() {
        if (com.jxparallel.fx.Fx.NATIVE) {
            return (com.jxparallel.fx.beans.property.ObjectProperty) com.jxparallel.fx.nativeimpl.Native.call(this, com.jxparallel.fx.scene.control.TableColumn.class, "onEditCommitProperty", new Class<?>[] {}, com.jxparallel.fx.beans.property.ObjectProperty.class);
        }
        return (com.jxparallel.fx.beans.property.ObjectProperty) com.jxparallel.fx.Fx.jx(((javafx.scene.control.TableColumn) fxPeer()).onEditCommitProperty());
    }

    public com.jxparallel.fx.beans.property.ObjectProperty<com.jxparallel.fx.event.EventHandler<com.jxparallel.fx.scene.control.TableColumn.CellEditEvent<S, T>>> onEditStartProperty() {
        if (com.jxparallel.fx.Fx.NATIVE) {
            return (com.jxparallel.fx.beans.property.ObjectProperty) com.jxparallel.fx.nativeimpl.Native.call(this, com.jxparallel.fx.scene.control.TableColumn.class, "onEditStartProperty", new Class<?>[] {}, com.jxparallel.fx.beans.property.ObjectProperty.class);
        }
        return (com.jxparallel.fx.beans.property.ObjectProperty) com.jxparallel.fx.Fx.jx(((javafx.scene.control.TableColumn) fxPeer()).onEditStartProperty());
    }

    public void setCellFactory(com.jxparallel.fx.util.Callback<com.jxparallel.fx.scene.control.TableColumn<S, T>, com.jxparallel.fx.scene.control.TableCell<S, T>> arg0) {
        if (com.jxparallel.fx.Fx.NATIVE) {
            com.jxparallel.fx.nativeimpl.Native.call(this, com.jxparallel.fx.scene.control.TableColumn.class, "setCellFactory", new Class<?>[] {com.jxparallel.fx.util.Callback.class}, void.class, arg0);
            return;
        }
        ((javafx.scene.control.TableColumn) fxPeer()).setCellFactory((javafx.util.Callback) com.jxparallel.fx.Fx.fx(arg0));
    }

    public void setCellValueFactory(com.jxparallel.fx.util.Callback<com.jxparallel.fx.scene.control.TableColumn.CellDataFeatures<S, T>, com.jxparallel.fx.beans.value.ObservableValue<T>> arg0) {
        if (com.jxparallel.fx.Fx.NATIVE) {
            com.jxparallel.fx.nativeimpl.Native.call(this, com.jxparallel.fx.scene.control.TableColumn.class, "setCellValueFactory", new Class<?>[] {com.jxparallel.fx.util.Callback.class}, void.class, arg0);
            return;
        }
        ((javafx.scene.control.TableColumn) fxPeer()).setCellValueFactory((javafx.util.Callback) com.jxparallel.fx.Fx.fx(arg0));
    }

    public void setOnEditCancel(com.jxparallel.fx.event.EventHandler<com.jxparallel.fx.scene.control.TableColumn.CellEditEvent<S, T>> arg0) {
        if (com.jxparallel.fx.Fx.NATIVE) {
            com.jxparallel.fx.nativeimpl.Native.call(this, com.jxparallel.fx.scene.control.TableColumn.class, "setOnEditCancel", new Class<?>[] {com.jxparallel.fx.event.EventHandler.class}, void.class, arg0);
            return;
        }
        ((javafx.scene.control.TableColumn) fxPeer()).setOnEditCancel((javafx.event.EventHandler) com.jxparallel.fx.Fx.fx(arg0));
    }

    public void setOnEditCommit(com.jxparallel.fx.event.EventHandler<com.jxparallel.fx.scene.control.TableColumn.CellEditEvent<S, T>> arg0) {
        if (com.jxparallel.fx.Fx.NATIVE) {
            com.jxparallel.fx.nativeimpl.Native.call(this, com.jxparallel.fx.scene.control.TableColumn.class, "setOnEditCommit", new Class<?>[] {com.jxparallel.fx.event.EventHandler.class}, void.class, arg0);
            return;
        }
        ((javafx.scene.control.TableColumn) fxPeer()).setOnEditCommit((javafx.event.EventHandler) com.jxparallel.fx.Fx.fx(arg0));
    }

    public void setOnEditStart(com.jxparallel.fx.event.EventHandler<com.jxparallel.fx.scene.control.TableColumn.CellEditEvent<S, T>> arg0) {
        if (com.jxparallel.fx.Fx.NATIVE) {
            com.jxparallel.fx.nativeimpl.Native.call(this, com.jxparallel.fx.scene.control.TableColumn.class, "setOnEditStart", new Class<?>[] {com.jxparallel.fx.event.EventHandler.class}, void.class, arg0);
            return;
        }
        ((javafx.scene.control.TableColumn) fxPeer()).setOnEditStart((javafx.event.EventHandler) com.jxparallel.fx.Fx.fx(arg0));
    }

    public void setSortType(com.jxparallel.fx.scene.control.TableColumn.SortType arg0) {
        if (com.jxparallel.fx.Fx.NATIVE) {
            com.jxparallel.fx.nativeimpl.Native.call(this, com.jxparallel.fx.scene.control.TableColumn.class, "setSortType", new Class<?>[] {com.jxparallel.fx.scene.control.TableColumn.SortType.class}, void.class, arg0);
            return;
        }
        ((javafx.scene.control.TableColumn) fxPeer()).setSortType((javafx.scene.control.TableColumn.SortType) com.jxparallel.fx.Fx.fx(arg0));
    }

    public com.jxparallel.fx.beans.property.ObjectProperty<com.jxparallel.fx.scene.control.TableColumn.SortType> sortTypeProperty() {
        if (com.jxparallel.fx.Fx.NATIVE) {
            return (com.jxparallel.fx.beans.property.ObjectProperty) com.jxparallel.fx.nativeimpl.Native.call(this, com.jxparallel.fx.scene.control.TableColumn.class, "sortTypeProperty", new Class<?>[] {}, com.jxparallel.fx.beans.property.ObjectProperty.class);
        }
        return (com.jxparallel.fx.beans.property.ObjectProperty) com.jxparallel.fx.Fx.jx(((javafx.scene.control.TableColumn) fxPeer()).sortTypeProperty());
    }

    public com.jxparallel.fx.beans.property.ReadOnlyObjectProperty<com.jxparallel.fx.scene.control.TableView<S>> tableViewProperty() {
        if (com.jxparallel.fx.Fx.NATIVE) {
            return (com.jxparallel.fx.beans.property.ReadOnlyObjectProperty) com.jxparallel.fx.nativeimpl.Native.call(this, com.jxparallel.fx.scene.control.TableColumn.class, "tableViewProperty", new Class<?>[] {}, com.jxparallel.fx.beans.property.ReadOnlyObjectProperty.class);
        }
        return (com.jxparallel.fx.beans.property.ReadOnlyObjectProperty) com.jxparallel.fx.Fx.jx(((javafx.scene.control.TableColumn) fxPeer()).tableViewProperty());
    }

    public static class CellDataFeatures<S, T> implements com.jxparallel.fx.Fx.Backed {
        private final Object fxPeer;

        protected CellDataFeatures(com.jxparallel.fx.Fx.Wrap wrap, Object peer) {
            this.fxPeer = peer;
        }

        @Override
        public Object fxPeer() {
            return fxPeer;
        }

        @Override
        public boolean equals(Object o) {
            return o == this || fxPeer().equals(com.jxparallel.fx.Fx.fx(o));
        }

        @Override
        public int hashCode() {
            return fxPeer().hashCode();
        }

        @Override
        public String toString() {
            return fxPeer().toString();
        }

        public CellDataFeatures(com.jxparallel.fx.scene.control.TableView<S> arg0, com.jxparallel.fx.scene.control.TableColumn<S, T> arg1, S arg2) {
            this(com.jxparallel.fx.Fx.WRAP, com.jxparallel.fx.Fx.NATIVE ? com.jxparallel.fx.nativeimpl.Native.create(javafx.scene.control.TableColumn.CellDataFeatures.class, new String[] {null, null, null}, new Object[] {arg0, arg1, arg2}) : new com.jxparallel.fx.peer.scene.control.TableColumn_CellDataFeatures((javafx.scene.control.TableView) com.jxparallel.fx.Fx.fx(arg0), (javafx.scene.control.TableColumn) com.jxparallel.fx.Fx.fx(arg1), (S) com.jxparallel.fx.Fx.fx(arg2)));
            com.jxparallel.fx.Fx.own(fxPeer(), this);
        }

        public com.jxparallel.fx.scene.control.TableColumn<S, T> getTableColumn() {
            if (com.jxparallel.fx.Fx.NATIVE) {
                return (com.jxparallel.fx.scene.control.TableColumn) com.jxparallel.fx.nativeimpl.Native.call(this, com.jxparallel.fx.scene.control.TableColumn.CellDataFeatures.class, "getTableColumn", new Class<?>[] {}, com.jxparallel.fx.scene.control.TableColumn.class);
            }
            return (com.jxparallel.fx.scene.control.TableColumn) com.jxparallel.fx.Fx.jx(((javafx.scene.control.TableColumn.CellDataFeatures) fxPeer()).getTableColumn());
        }

        public com.jxparallel.fx.scene.control.TableView<S> getTableView() {
            if (com.jxparallel.fx.Fx.NATIVE) {
                return (com.jxparallel.fx.scene.control.TableView) com.jxparallel.fx.nativeimpl.Native.call(this, com.jxparallel.fx.scene.control.TableColumn.CellDataFeatures.class, "getTableView", new Class<?>[] {}, com.jxparallel.fx.scene.control.TableView.class);
            }
            return (com.jxparallel.fx.scene.control.TableView) com.jxparallel.fx.Fx.jx(((javafx.scene.control.TableColumn.CellDataFeatures) fxPeer()).getTableView());
        }

        public S getValue() {
            if (com.jxparallel.fx.Fx.NATIVE) {
                return (S) com.jxparallel.fx.nativeimpl.Native.call(this, com.jxparallel.fx.scene.control.TableColumn.CellDataFeatures.class, "getValue", new Class<?>[] {}, java.lang.Object.class);
            }
            return (S) com.jxparallel.fx.Fx.jx(((javafx.scene.control.TableColumn.CellDataFeatures) fxPeer()).getValue());
        }
    }

    public static class CellEditEvent<S, T> extends com.jxparallel.fx.event.Event {
        protected CellEditEvent(com.jxparallel.fx.Fx.Wrap wrap, Object peer) {
            super(wrap, peer);
        }

        public CellEditEvent(com.jxparallel.fx.scene.control.TableView<S> arg0, com.jxparallel.fx.scene.control.TablePosition<S, T> arg1, com.jxparallel.fx.event.EventType<com.jxparallel.fx.scene.control.TableColumn.CellEditEvent<S, T>> arg2, T arg3) {
            this(com.jxparallel.fx.Fx.WRAP, new com.jxparallel.fx.peer.scene.control.TableColumn_CellEditEvent((javafx.scene.control.TableView) com.jxparallel.fx.Fx.fxAs(arg0, javafx.scene.control.TableView.class), (javafx.scene.control.TablePosition) com.jxparallel.fx.Fx.fxAs(arg1, javafx.scene.control.TablePosition.class), (javafx.event.EventType) com.jxparallel.fx.Fx.fx(arg2), (T) com.jxparallel.fx.Fx.fx(arg3)));
            com.jxparallel.fx.Fx.own(fxPeer(), this);
        }

        public static final com.jxparallel.fx.event.EventType<?> ANY = (com.jxparallel.fx.event.EventType) com.jxparallel.fx.Fx.jx(javafx.scene.control.TableColumn.CellEditEvent.ANY);

        public T getNewValue() {
            return (T) com.jxparallel.fx.Fx.jx(((javafx.scene.control.TableColumn.CellEditEvent) fxPeer()).getNewValue());
        }

        public T getOldValue() {
            return (T) com.jxparallel.fx.Fx.jx(((javafx.scene.control.TableColumn.CellEditEvent) fxPeer()).getOldValue());
        }

        public S getRowValue() {
            return (S) com.jxparallel.fx.Fx.jx(((javafx.scene.control.TableColumn.CellEditEvent) fxPeer()).getRowValue());
        }

        public com.jxparallel.fx.scene.control.TableColumn<S, T> getTableColumn() {
            return (com.jxparallel.fx.scene.control.TableColumn) com.jxparallel.fx.Fx.jx(((javafx.scene.control.TableColumn.CellEditEvent) fxPeer()).getTableColumn());
        }

        public com.jxparallel.fx.scene.control.TablePosition<S, T> getTablePosition() {
            return (com.jxparallel.fx.scene.control.TablePosition) com.jxparallel.fx.Fx.jx(((javafx.scene.control.TableColumn.CellEditEvent) fxPeer()).getTablePosition());
        }

        public com.jxparallel.fx.scene.control.TableView<S> getTableView() {
            return (com.jxparallel.fx.scene.control.TableView) com.jxparallel.fx.Fx.jx(((javafx.scene.control.TableColumn.CellEditEvent) fxPeer()).getTableView());
        }
    }

    public enum SortType {
        ASCENDING,
        DESCENDING;
    }
}
