package com.jxparallel.fx.scene.control;

/** JXParallel counterpart of {@link javafx.scene.control.Toggle} (generated by scripts/GenerateFxApi.java). */
@SuppressWarnings({"unchecked", "rawtypes", "deprecation"})
public interface Toggle {

    javafx.collections.ObservableMap<java.lang.Object, java.lang.Object> getProperties();

    com.jxparallel.fx.scene.control.ToggleGroup getToggleGroup();

    java.lang.Object getUserData();

    boolean isSelected();

    com.jxparallel.fx.beans.property.BooleanProperty selectedProperty();

    void setSelected(boolean arg0);

    void setToggleGroup(com.jxparallel.fx.scene.control.ToggleGroup arg0);

    void setUserData(java.lang.Object arg0);

    com.jxparallel.fx.beans.property.ObjectProperty<com.jxparallel.fx.scene.control.ToggleGroup> toggleGroupProperty();
}
