package com.jxparallel.fx.scene.image;

/** JXParallel counterpart of {@link javafx.scene.image.Image} (generated by scripts/GenerateFxApi.java). */
@SuppressWarnings({"unchecked", "rawtypes", "deprecation"})
public class Image implements com.jxparallel.fx.Fx.Backed {
    private final Object fxPeer;

    protected Image(com.jxparallel.fx.Fx.Wrap wrap, Object peer) {
        this.fxPeer = peer;
    }

    @Override
    public Object fxPeer() {
        return fxPeer;
    }

    @Override
    public boolean equals(Object o) {
        return o == this || fxPeer().equals(com.jxparallel.fx.Fx.fx(o));
    }

    @Override
    public int hashCode() {
        return fxPeer().hashCode();
    }

    @Override
    public String toString() {
        return fxPeer().toString();
    }

    public Image(@javafx.beans.NamedArg(value = "is") java.io.InputStream arg0) {
        this(com.jxparallel.fx.Fx.WRAP, new com.jxparallel.fx.peer.scene.image.Image(arg0));
        com.jxparallel.fx.Fx.own(fxPeer(), this);
    }

    public Image(@javafx.beans.NamedArg(value = "is") java.io.InputStream arg0, @javafx.beans.NamedArg(value = "requestedWidth") double arg1, @javafx.beans.NamedArg(value = "requestedHeight") double arg2, @javafx.beans.NamedArg(value = "preserveRatio") boolean arg3, @javafx.beans.NamedArg(value = "smooth") boolean arg4) {
        this(com.jxparallel.fx.Fx.WRAP, new com.jxparallel.fx.peer.scene.image.Image(arg0, arg1, arg2, arg3, arg4));
        com.jxparallel.fx.Fx.own(fxPeer(), this);
    }

    public Image(@javafx.beans.NamedArg(value = "url") java.lang.String arg0) {
        this(com.jxparallel.fx.Fx.WRAP, new com.jxparallel.fx.peer.scene.image.Image(arg0));
        com.jxparallel.fx.Fx.own(fxPeer(), this);
    }

    public Image(@javafx.beans.NamedArg(value = "url") java.lang.String arg0, @javafx.beans.NamedArg(value = "backgroundLoading") boolean arg1) {
        this(com.jxparallel.fx.Fx.WRAP, new com.jxparallel.fx.peer.scene.image.Image(arg0, arg1));
        com.jxparallel.fx.Fx.own(fxPeer(), this);
    }

    public Image(@javafx.beans.NamedArg(value = "url") java.lang.String arg0, @javafx.beans.NamedArg(value = "requestedWidth") double arg1, @javafx.beans.NamedArg(value = "requestedHeight") double arg2, @javafx.beans.NamedArg(value = "preserveRatio") boolean arg3, @javafx.beans.NamedArg(value = "smooth") boolean arg4) {
        this(com.jxparallel.fx.Fx.WRAP, new com.jxparallel.fx.peer.scene.image.Image(arg0, arg1, arg2, arg3, arg4));
        com.jxparallel.fx.Fx.own(fxPeer(), this);
    }

    public Image(@javafx.beans.NamedArg(value = "url", defaultValue = "\"\"") java.lang.String arg0, @javafx.beans.NamedArg(value = "requestedWidth") double arg1, @javafx.beans.NamedArg(value = "requestedHeight") double arg2, @javafx.beans.NamedArg(value = "preserveRatio") boolean arg3, @javafx.beans.NamedArg(value = "smooth", defaultValue = "true") boolean arg4, @javafx.beans.NamedArg(value = "backgroundLoading") boolean arg5) {
        this(com.jxparallel.fx.Fx.WRAP, new com.jxparallel.fx.peer.scene.image.Image(arg0, arg1, arg2, arg3, arg4, arg5));
        com.jxparallel.fx.Fx.own(fxPeer(), this);
    }

    public void cancel() {
        ((javafx.scene.image.Image) fxPeer()).cancel();
    }

    public com.jxparallel.fx.beans.property.ReadOnlyBooleanProperty errorProperty() {
        return (com.jxparallel.fx.beans.property.ReadOnlyBooleanProperty) com.jxparallel.fx.Fx.jx(((javafx.scene.image.Image) fxPeer()).errorProperty());
    }

    public com.jxparallel.fx.beans.property.ReadOnlyObjectProperty<java.lang.Exception> exceptionProperty() {
        return (com.jxparallel.fx.beans.property.ReadOnlyObjectProperty) com.jxparallel.fx.Fx.jx(((javafx.scene.image.Image) fxPeer()).exceptionProperty());
    }

    public java.lang.Exception getException() {
        return ((javafx.scene.image.Image) fxPeer()).getException();
    }

    public double getHeight() {
        return ((javafx.scene.image.Image) fxPeer()).getHeight();
    }

    public com.jxparallel.fx.scene.image.PixelReader getPixelReader() {
        return (com.jxparallel.fx.scene.image.PixelReader) com.jxparallel.fx.Fx.jx(((javafx.scene.image.Image) fxPeer()).getPixelReader());
    }

    public double getProgress() {
        return ((javafx.scene.image.Image) fxPeer()).getProgress();
    }

    public double getRequestedHeight() {
        return ((javafx.scene.image.Image) fxPeer()).getRequestedHeight();
    }

    public double getRequestedWidth() {
        return ((javafx.scene.image.Image) fxPeer()).getRequestedWidth();
    }

    public double getWidth() {
        return ((javafx.scene.image.Image) fxPeer()).getWidth();
    }

    public com.jxparallel.fx.beans.property.ReadOnlyDoubleProperty heightProperty() {
        return (com.jxparallel.fx.beans.property.ReadOnlyDoubleProperty) com.jxparallel.fx.Fx.jx(((javafx.scene.image.Image) fxPeer()).heightProperty());
    }

    public static com.jxparallel.fx.scene.image.Image impl_fromPlatformImage(java.lang.Object arg0) {
        return (com.jxparallel.fx.scene.image.Image) com.jxparallel.fx.Fx.jx(javafx.scene.image.Image.impl_fromPlatformImage((java.lang.Object) com.jxparallel.fx.Fx.fx(arg0)));
    }

    public java.lang.Object impl_getPlatformImage() {
        return (java.lang.Object) com.jxparallel.fx.Fx.jx(((javafx.scene.image.Image) fxPeer()).impl_getPlatformImage());
    }

    public java.lang.String impl_getUrl() {
        return ((javafx.scene.image.Image) fxPeer()).impl_getUrl();
    }

    public boolean isBackgroundLoading() {
        return ((javafx.scene.image.Image) fxPeer()).isBackgroundLoading();
    }

    public boolean isError() {
        return ((javafx.scene.image.Image) fxPeer()).isError();
    }

    public boolean isPreserveRatio() {
        return ((javafx.scene.image.Image) fxPeer()).isPreserveRatio();
    }

    public boolean isSmooth() {
        return ((javafx.scene.image.Image) fxPeer()).isSmooth();
    }

    public com.jxparallel.fx.beans.property.ReadOnlyDoubleProperty progressProperty() {
        return (com.jxparallel.fx.beans.property.ReadOnlyDoubleProperty) com.jxparallel.fx.Fx.jx(((javafx.scene.image.Image) fxPeer()).progressProperty());
    }

    public com.jxparallel.fx.beans.property.ReadOnlyDoubleProperty widthProperty() {
        return (com.jxparallel.fx.beans.property.ReadOnlyDoubleProperty) com.jxparallel.fx.Fx.jx(((javafx.scene.image.Image) fxPeer()).widthProperty());
    }
}
