package com.jxparallel.fx.scene.image;

/** JXParallel counterpart of {@link javafx.scene.image.PixelFormat} (generated by scripts/GenerateFxApi.java). */
@SuppressWarnings({"unchecked", "rawtypes", "deprecation"})
public class PixelFormat<T extends java.nio.Buffer> implements com.jxparallel.fx.Fx.Backed {
    private final Object fxPeer;

    protected PixelFormat(com.jxparallel.fx.Fx.Wrap wrap, Object peer) {
        this.fxPeer = peer;
    }

    @Override
    public Object fxPeer() {
        return fxPeer;
    }

    @Override
    public boolean equals(Object o) {
        return o == this || fxPeer().equals(com.jxparallel.fx.Fx.fx(o));
    }

    @Override
    public int hashCode() {
        return fxPeer().hashCode();
    }

    @Override
    public String toString() {
        return fxPeer().toString();
    }

    public static com.jxparallel.fx.scene.image.PixelFormat<java.nio.ByteBuffer> createByteIndexedInstance(int[] arg0) {
        return (com.jxparallel.fx.scene.image.PixelFormat) com.jxparallel.fx.Fx.jx(javafx.scene.image.PixelFormat.createByteIndexedInstance(arg0));
    }

    public static com.jxparallel.fx.scene.image.PixelFormat<java.nio.ByteBuffer> createByteIndexedPremultipliedInstance(int[] arg0) {
        return (com.jxparallel.fx.scene.image.PixelFormat) com.jxparallel.fx.Fx.jx(javafx.scene.image.PixelFormat.createByteIndexedPremultipliedInstance(arg0));
    }

    public int getArgb(T arg0, int arg1, int arg2, int arg3) {
        return (Integer) (fxPeer() instanceof com.jxparallel.fx.Fx.Owned ? ((com.jxparallel.fx.Fx.Owned) fxPeer()).callSuper("getArgb(Buffer,int,int,int)", new Object[] {arg0, arg1, arg2, arg3}) : com.jxparallel.fx.Fx.invoke(fxPeer(), javafx.scene.image.PixelFormat.class, "getArgb", new Class<?>[] {java.nio.Buffer.class, int.class, int.class, int.class}, arg0, arg1, arg2, arg3));
    }

    public static com.jxparallel.fx.scene.image.WritablePixelFormat<java.nio.ByteBuffer> getByteBgraInstance() {
        return (com.jxparallel.fx.scene.image.WritablePixelFormat) com.jxparallel.fx.Fx.jx(javafx.scene.image.PixelFormat.getByteBgraInstance());
    }

    public static com.jxparallel.fx.scene.image.WritablePixelFormat<java.nio.ByteBuffer> getByteBgraPreInstance() {
        return (com.jxparallel.fx.scene.image.WritablePixelFormat) com.jxparallel.fx.Fx.jx(javafx.scene.image.PixelFormat.getByteBgraPreInstance());
    }

    public static com.jxparallel.fx.scene.image.PixelFormat<java.nio.ByteBuffer> getByteRgbInstance() {
        return (com.jxparallel.fx.scene.image.PixelFormat) com.jxparallel.fx.Fx.jx(javafx.scene.image.PixelFormat.getByteRgbInstance());
    }

    public static com.jxparallel.fx.scene.image.WritablePixelFormat<java.nio.IntBuffer> getIntArgbInstance() {
        return (com.jxparallel.fx.scene.image.WritablePixelFormat) com.jxparallel.fx.Fx.jx(javafx.scene.image.PixelFormat.getIntArgbInstance());
    }

    public static com.jxparallel.fx.scene.image.WritablePixelFormat<java.nio.IntBuffer> getIntArgbPreInstance() {
        return (com.jxparallel.fx.scene.image.WritablePixelFormat) com.jxparallel.fx.Fx.jx(javafx.scene.image.PixelFormat.getIntArgbPreInstance());
    }

    public com.jxparallel.fx.scene.image.PixelFormat.Type getType() {
        return (com.jxparallel.fx.scene.image.PixelFormat.Type) com.jxparallel.fx.Fx.jx(((javafx.scene.image.PixelFormat) fxPeer()).getType());
    }

    public boolean isPremultiplied() {
        return (Boolean) (fxPeer() instanceof com.jxparallel.fx.Fx.Owned ? ((com.jxparallel.fx.Fx.Owned) fxPeer()).callSuper("isPremultiplied()", new Object[] {}) : com.jxparallel.fx.Fx.invoke(fxPeer(), javafx.scene.image.PixelFormat.class, "isPremultiplied", new Class<?>[] {}));
    }

    public boolean isWritable() {
        return (Boolean) (fxPeer() instanceof com.jxparallel.fx.Fx.Owned ? ((com.jxparallel.fx.Fx.Owned) fxPeer()).callSuper("isWritable()", new Object[] {}) : com.jxparallel.fx.Fx.invoke(fxPeer(), javafx.scene.image.PixelFormat.class, "isWritable", new Class<?>[] {}));
    }

    public enum Type {
        INT_ARGB_PRE,
        INT_ARGB,
        BYTE_BGRA_PRE,
        BYTE_BGRA,
        BYTE_RGB,
        BYTE_INDEXED;
    }
}
