package com.jxparallel.fx.scene.image;

/** JXParallel counterpart of {@link javafx.scene.image.PixelReader} (generated by scripts/GenerateFxApi.java). */
@SuppressWarnings({"unchecked", "rawtypes", "deprecation"})
public interface PixelReader {

    int getArgb(int arg0, int arg1);

    com.jxparallel.fx.scene.paint.Color getColor(int arg0, int arg1);

    com.jxparallel.fx.scene.image.PixelFormat getPixelFormat();

    <T extends java.nio.Buffer> void getPixels(int arg0, int arg1, int arg2, int arg3, com.jxparallel.fx.scene.image.WritablePixelFormat<T> arg4, T arg5, int arg6);

    void getPixels(int arg0, int arg1, int arg2, int arg3, com.jxparallel.fx.scene.image.WritablePixelFormat<java.nio.ByteBuffer> arg4, byte[] arg5, int arg6, int arg7);

    void getPixels(int arg0, int arg1, int arg2, int arg3, com.jxparallel.fx.scene.image.WritablePixelFormat<java.nio.IntBuffer> arg4, int[] arg5, int arg6, int arg7);
}
