package com.jxparallel.fx.beans.property;

/** JXParallel counterpart of {@link javafx.beans.property.DoubleProperty} (generated by scripts/GenerateFxApi.java). */
@SuppressWarnings({"unchecked", "rawtypes", "deprecation"})
public class DoubleProperty extends com.jxparallel.fx.beans.property.ReadOnlyDoubleProperty implements com.jxparallel.fx.beans.property.Property<java.lang.Number>, com.jxparallel.fx.beans.value.WritableDoubleValue {
    protected DoubleProperty(com.jxparallel.fx.Fx.Wrap wrap, Object peer) {
        super(wrap, peer);
    }

    public DoubleProperty() {
        this(com.jxparallel.fx.Fx.WRAP, new com.jxparallel.fx.peer.beans.property.DoubleProperty());
        com.jxparallel.fx.Fx.own(fxPeer(), this);
    }

    public com.jxparallel.fx.beans.property.ObjectProperty<java.lang.Double> asObject() {
        return (com.jxparallel.fx.beans.property.ObjectProperty) com.jxparallel.fx.Fx.jx(((javafx.beans.property.DoubleProperty) fxPeer()).asObject());
    }

    public void bindBidirectional(com.jxparallel.fx.beans.property.Property<java.lang.Number> arg0) {
        ((javafx.beans.property.DoubleProperty) fxPeer()).bindBidirectional((javafx.beans.property.Property) com.jxparallel.fx.Fx.fx(arg0));
    }

    public static com.jxparallel.fx.beans.property.DoubleProperty doubleProperty(com.jxparallel.fx.beans.property.Property<java.lang.Double> arg0) {
        return (com.jxparallel.fx.beans.property.DoubleProperty) com.jxparallel.fx.Fx.jx(javafx.beans.property.DoubleProperty.doubleProperty((javafx.beans.property.Property) com.jxparallel.fx.Fx.fx(arg0)));
    }

    public void setValue(java.lang.Number arg0) {
        ((javafx.beans.property.DoubleProperty) fxPeer()).setValue(arg0);
    }

    public void unbindBidirectional(com.jxparallel.fx.beans.property.Property<java.lang.Number> arg0) {
        ((javafx.beans.property.DoubleProperty) fxPeer()).unbindBidirectional((javafx.beans.property.Property) com.jxparallel.fx.Fx.fx(arg0));
    }

    public void bind(com.jxparallel.fx.beans.value.ObservableValue<? extends java.lang.Number> arg0) {
        if (fxPeer() instanceof com.jxparallel.fx.Fx.Owned) {
            ((com.jxparallel.fx.Fx.Owned) fxPeer()).callSuper("bind(ObservableValue)", new Object[] {(javafx.beans.value.ObservableValue) com.jxparallel.fx.Fx.fx(arg0)});
        } else {
            com.jxparallel.fx.Fx.invoke(fxPeer(), javafx.beans.property.Property.class, "bind", new Class<?>[] {javafx.beans.value.ObservableValue.class}, (javafx.beans.value.ObservableValue) com.jxparallel.fx.Fx.fx(arg0));
        }
    }

    public boolean isBound() {
        return (Boolean) (fxPeer() instanceof com.jxparallel.fx.Fx.Owned ? ((com.jxparallel.fx.Fx.Owned) fxPeer()).callSuper("isBound()", new Object[] {}) : com.jxparallel.fx.Fx.invoke(fxPeer(), javafx.beans.property.Property.class, "isBound", new Class<?>[] {}));
    }

    public void unbind() {
        if (fxPeer() instanceof com.jxparallel.fx.Fx.Owned) {
            ((com.jxparallel.fx.Fx.Owned) fxPeer()).callSuper("unbind()", new Object[] {});
        } else {
            com.jxparallel.fx.Fx.invoke(fxPeer(), javafx.beans.property.Property.class, "unbind", new Class<?>[] {});
        }
    }

    public void set(double arg0) {
        if (fxPeer() instanceof com.jxparallel.fx.Fx.Owned) {
            ((com.jxparallel.fx.Fx.Owned) fxPeer()).callSuper("set(double)", new Object[] {arg0});
        } else {
            com.jxparallel.fx.Fx.invoke(fxPeer(), javafx.beans.value.WritableDoubleValue.class, "set", new Class<?>[] {double.class}, arg0);
        }
    }

    /** Called by the peer: runs the JX (possibly overridden) method. */
    public static Object $hook(Object self, String method, Object[] a) {
        DoubleProperty jx = (DoubleProperty) self;
        try {
        switch (method) {
            case "removeListener(ChangeListener)":
                jx.removeListener((com.jxparallel.fx.beans.value.ChangeListener) a[0]);
                return null;
            case "addListener(ChangeListener)":
                jx.addListener((com.jxparallel.fx.beans.value.ChangeListener) a[0]);
                return null;
            case "removeListener(InvalidationListener)":
                jx.removeListener((com.jxparallel.fx.beans.InvalidationListener) a[0]);
                return null;
            case "addListener(InvalidationListener)":
                jx.addListener((com.jxparallel.fx.beans.InvalidationListener) a[0]);
                return null;
            case "get()":
                return (Object) jx.get();
            case "getName()":
                return jx.getName();
            case "getBean()":
                return jx.getBean();
            case "bind(ObservableValue)":
                jx.bind((com.jxparallel.fx.beans.value.ObservableValue) a[0]);
                return null;
            case "isBound()":
                return (Object) jx.isBound();
            case "unbind()":
                jx.unbind();
                return null;
            case "set(double)":
                jx.set((Double) a[0]);
                return null;
            default:
                throw new IllegalArgumentException(method);
        }
        } catch (Exception e) {
            throw com.jxparallel.fx.Fx.sneaky(e);
        }
    }
}
