package com.jxparallel.fx.beans.property;

/** JXParallel counterpart of {@link javafx.beans.property.ObjectPropertyBase} (generated by scripts/GenerateFxApi.java). */
@SuppressWarnings({"unchecked", "rawtypes", "deprecation"})
public class ObjectPropertyBase<T> extends com.jxparallel.fx.beans.property.ObjectProperty<T> {
    protected ObjectPropertyBase(com.jxparallel.fx.Fx.Wrap wrap, Object peer) {
        super(wrap, peer);
    }

    public ObjectPropertyBase() {
        this(com.jxparallel.fx.Fx.WRAP, new com.jxparallel.fx.peer.beans.property.ObjectPropertyBase());
        com.jxparallel.fx.Fx.own(fxPeer(), this);
    }

    public ObjectPropertyBase(T arg0) {
        this(com.jxparallel.fx.Fx.WRAP, new com.jxparallel.fx.peer.beans.property.ObjectPropertyBase((T) com.jxparallel.fx.Fx.fx(arg0)));
        com.jxparallel.fx.Fx.own(fxPeer(), this);
    }

    public void addListener(com.jxparallel.fx.beans.value.ChangeListener<? super T> arg0) {
        ((javafx.beans.property.ObjectPropertyBase) fxPeer()).addListener((javafx.beans.value.ChangeListener) com.jxparallel.fx.Fx.fx(arg0));
    }

    public void addListener(com.jxparallel.fx.beans.InvalidationListener arg0) {
        ((javafx.beans.property.ObjectPropertyBase) fxPeer()).addListener((javafx.beans.InvalidationListener) com.jxparallel.fx.Fx.fx(arg0));
    }

    public void bind(com.jxparallel.fx.beans.value.ObservableValue<? extends T> arg0) {
        ((javafx.beans.property.ObjectPropertyBase) fxPeer()).bind((javafx.beans.value.ObservableValue) com.jxparallel.fx.Fx.fx(arg0));
    }

    protected void fireValueChangedEvent() {
        com.jxparallel.fx.Fx.invoke(fxPeer(), javafx.beans.property.ObjectPropertyBase.class, "fireValueChangedEvent", new Class<?>[] {});
    }

    public T get() {
        return (T) com.jxparallel.fx.Fx.jx(((javafx.beans.property.ObjectPropertyBase) fxPeer()).get());
    }

    protected void invalidated() {
        com.jxparallel.fx.Fx.invoke(fxPeer(), javafx.beans.property.ObjectPropertyBase.class, "invalidated", new Class<?>[] {});
    }

    public boolean isBound() {
        return ((javafx.beans.property.ObjectPropertyBase) fxPeer()).isBound();
    }

    public void removeListener(com.jxparallel.fx.beans.value.ChangeListener<? super T> arg0) {
        ((javafx.beans.property.ObjectPropertyBase) fxPeer()).removeListener((javafx.beans.value.ChangeListener) com.jxparallel.fx.Fx.fx(arg0));
    }

    public void removeListener(com.jxparallel.fx.beans.InvalidationListener arg0) {
        ((javafx.beans.property.ObjectPropertyBase) fxPeer()).removeListener((javafx.beans.InvalidationListener) com.jxparallel.fx.Fx.fx(arg0));
    }

    public void set(T arg0) {
        ((javafx.beans.property.ObjectPropertyBase) fxPeer()).set((T) com.jxparallel.fx.Fx.fx(arg0));
    }

    public void unbind() {
        ((javafx.beans.property.ObjectPropertyBase) fxPeer()).unbind();
    }

    /** Called by the peer: runs the JX (possibly overridden) method. */
    public static Object $hook(Object self, String method, Object[] a) {
        ObjectPropertyBase jx = (ObjectPropertyBase) self;
        try {
        switch (method) {
            case "getBean()":
                return jx.getBean();
            case "getName()":
                return jx.getName();
            default:
                throw new IllegalArgumentException(method);
        }
        } catch (Exception e) {
            throw com.jxparallel.fx.Fx.sneaky(e);
        }
    }
}
