package com.jxparallel.fx.beans.property;

/** JXParallel counterpart of {@link javafx.beans.property.ReadOnlyLongProperty} (generated by scripts/GenerateFxApi.java). */
@SuppressWarnings({"unchecked", "rawtypes", "deprecation"})
public class ReadOnlyLongProperty extends com.jxparallel.fx.beans.binding.LongExpression implements com.jxparallel.fx.beans.property.ReadOnlyProperty<java.lang.Number> {
    protected ReadOnlyLongProperty(com.jxparallel.fx.Fx.Wrap wrap, Object peer) {
        super(wrap, peer);
    }

    public ReadOnlyLongProperty() {
        this(com.jxparallel.fx.Fx.WRAP, new com.jxparallel.fx.peer.beans.property.ReadOnlyLongProperty());
        com.jxparallel.fx.Fx.own(fxPeer(), this);
    }

    public com.jxparallel.fx.beans.property.ReadOnlyObjectProperty<java.lang.Long> asObject() {
        return (com.jxparallel.fx.beans.property.ReadOnlyObjectProperty) com.jxparallel.fx.Fx.jx(((javafx.beans.property.ReadOnlyLongProperty) fxPeer()).asObject());
    }

    public static <T extends java.lang.Number> com.jxparallel.fx.beans.property.ReadOnlyLongProperty readOnlyLongProperty(com.jxparallel.fx.beans.property.ReadOnlyProperty<T> arg0) {
        return (com.jxparallel.fx.beans.property.ReadOnlyLongProperty) com.jxparallel.fx.Fx.jx(javafx.beans.property.ReadOnlyLongProperty.readOnlyLongProperty((javafx.beans.property.ReadOnlyProperty) com.jxparallel.fx.Fx.fx(arg0)));
    }

    public java.lang.Object getBean() {
        return (java.lang.Object) com.jxparallel.fx.Fx.jx((fxPeer() instanceof com.jxparallel.fx.Fx.Owned ? ((com.jxparallel.fx.Fx.Owned) fxPeer()).callSuper("getBean()", new Object[] {}) : com.jxparallel.fx.Fx.invoke(fxPeer(), javafx.beans.property.ReadOnlyProperty.class, "getBean", new Class<?>[] {})));
    }

    public java.lang.String getName() {
        return (java.lang.String) (fxPeer() instanceof com.jxparallel.fx.Fx.Owned ? ((com.jxparallel.fx.Fx.Owned) fxPeer()).callSuper("getName()", new Object[] {}) : com.jxparallel.fx.Fx.invoke(fxPeer(), javafx.beans.property.ReadOnlyProperty.class, "getName", new Class<?>[] {}));
    }

    /** Called by the peer: runs the JX (possibly overridden) method. */
    public static Object $hook(Object self, String method, Object[] a) {
        ReadOnlyLongProperty jx = (ReadOnlyLongProperty) self;
        try {
        switch (method) {
            case "getBean()":
                return jx.getBean();
            case "getName()":
                return jx.getName();
            case "get()":
                return (Object) jx.get();
            case "addListener(InvalidationListener)":
                jx.addListener((com.jxparallel.fx.beans.InvalidationListener) a[0]);
                return null;
            case "removeListener(InvalidationListener)":
                jx.removeListener((com.jxparallel.fx.beans.InvalidationListener) a[0]);
                return null;
            case "addListener(ChangeListener)":
                jx.addListener((com.jxparallel.fx.beans.value.ChangeListener) a[0]);
                return null;
            case "removeListener(ChangeListener)":
                jx.removeListener((com.jxparallel.fx.beans.value.ChangeListener) a[0]);
                return null;
            default:
                throw new IllegalArgumentException(method);
        }
        } catch (Exception e) {
            throw com.jxparallel.fx.Fx.sneaky(e);
        }
    }
}
