package com.jxparallel.fx.beans.property;

/** JXParallel counterpart of {@link javafx.beans.property.ReadOnlyStringPropertyBase} (generated by scripts/GenerateFxApi.java). */
@SuppressWarnings({"unchecked", "rawtypes", "deprecation"})
public class ReadOnlyStringPropertyBase extends com.jxparallel.fx.beans.property.ReadOnlyStringProperty {
    protected ReadOnlyStringPropertyBase(com.jxparallel.fx.Fx.Wrap wrap, Object peer) {
        super(wrap, peer);
    }

    public ReadOnlyStringPropertyBase() {
        this(com.jxparallel.fx.Fx.WRAP, new com.jxparallel.fx.peer.beans.property.ReadOnlyStringPropertyBase());
        com.jxparallel.fx.Fx.own(fxPeer(), this);
    }

    public void addListener(com.jxparallel.fx.beans.value.ChangeListener<? super java.lang.String> arg0) {
        ((javafx.beans.property.ReadOnlyStringPropertyBase) fxPeer()).addListener((javafx.beans.value.ChangeListener) com.jxparallel.fx.Fx.fx(arg0));
    }

    public void addListener(com.jxparallel.fx.beans.InvalidationListener arg0) {
        ((javafx.beans.property.ReadOnlyStringPropertyBase) fxPeer()).addListener((javafx.beans.InvalidationListener) com.jxparallel.fx.Fx.fx(arg0));
    }

    protected void fireValueChangedEvent() {
        com.jxparallel.fx.Fx.invoke(fxPeer(), javafx.beans.property.ReadOnlyStringPropertyBase.class, "fireValueChangedEvent", new Class<?>[] {});
    }

    public void removeListener(com.jxparallel.fx.beans.value.ChangeListener<? super java.lang.String> arg0) {
        ((javafx.beans.property.ReadOnlyStringPropertyBase) fxPeer()).removeListener((javafx.beans.value.ChangeListener) com.jxparallel.fx.Fx.fx(arg0));
    }

    public void removeListener(com.jxparallel.fx.beans.InvalidationListener arg0) {
        ((javafx.beans.property.ReadOnlyStringPropertyBase) fxPeer()).removeListener((javafx.beans.InvalidationListener) com.jxparallel.fx.Fx.fx(arg0));
    }

    /** Called by the peer: runs the JX (possibly overridden) method. */
    public static Object $hook(Object self, String method, Object[] a) {
        ReadOnlyStringPropertyBase jx = (ReadOnlyStringPropertyBase) self;
        try {
        switch (method) {
            case "get()":
                return jx.get();
            case "getName()":
                return jx.getName();
            case "getBean()":
                return jx.getBean();
            default:
                throw new IllegalArgumentException(method);
        }
        } catch (Exception e) {
            throw com.jxparallel.fx.Fx.sneaky(e);
        }
    }
}
