package com.jxparallel.fx.beans.property;

/** JXParallel counterpart of {@link javafx.beans.property.ReadOnlyIntegerWrapper} (generated by scripts/GenerateFxApi.java). */
@SuppressWarnings({"unchecked", "rawtypes", "deprecation"})
public class ReadOnlyIntegerWrapper extends com.jxparallel.fx.beans.property.SimpleIntegerProperty {
    protected ReadOnlyIntegerWrapper(com.jxparallel.fx.Fx.Wrap wrap, Object peer) {
        super(wrap, peer);
    }

    public ReadOnlyIntegerWrapper(java.lang.Object arg0, java.lang.String arg1, int arg2) {
        this(com.jxparallel.fx.Fx.WRAP, new com.jxparallel.fx.peer.beans.property.ReadOnlyIntegerWrapper((java.lang.Object) com.jxparallel.fx.Fx.fx(arg0), arg1, arg2));
        com.jxparallel.fx.Fx.own(fxPeer(), this);
    }

    public ReadOnlyIntegerWrapper(java.lang.Object arg0, java.lang.String arg1) {
        this(com.jxparallel.fx.Fx.WRAP, new com.jxparallel.fx.peer.beans.property.ReadOnlyIntegerWrapper((java.lang.Object) com.jxparallel.fx.Fx.fx(arg0), arg1));
        com.jxparallel.fx.Fx.own(fxPeer(), this);
    }

    public ReadOnlyIntegerWrapper(int arg0) {
        this(com.jxparallel.fx.Fx.WRAP, new com.jxparallel.fx.peer.beans.property.ReadOnlyIntegerWrapper(arg0));
        com.jxparallel.fx.Fx.own(fxPeer(), this);
    }

    public ReadOnlyIntegerWrapper() {
        this(com.jxparallel.fx.Fx.WRAP, new com.jxparallel.fx.peer.beans.property.ReadOnlyIntegerWrapper());
        com.jxparallel.fx.Fx.own(fxPeer(), this);
    }

    public void addListener(com.jxparallel.fx.beans.value.ChangeListener<? super java.lang.Number> arg0) {
        ((javafx.beans.property.ReadOnlyIntegerWrapper) fxPeer()).addListener((javafx.beans.value.ChangeListener) com.jxparallel.fx.Fx.fx(arg0));
    }

    public void addListener(com.jxparallel.fx.beans.InvalidationListener arg0) {
        ((javafx.beans.property.ReadOnlyIntegerWrapper) fxPeer()).addListener((javafx.beans.InvalidationListener) com.jxparallel.fx.Fx.fx(arg0));
    }

    protected void fireValueChangedEvent() {
        com.jxparallel.fx.Fx.invoke(fxPeer(), javafx.beans.property.ReadOnlyIntegerWrapper.class, "fireValueChangedEvent", new Class<?>[] {});
    }

    public com.jxparallel.fx.beans.property.ReadOnlyIntegerProperty getReadOnlyProperty() {
        return (com.jxparallel.fx.beans.property.ReadOnlyIntegerProperty) com.jxparallel.fx.Fx.jx(((javafx.beans.property.ReadOnlyIntegerWrapper) fxPeer()).getReadOnlyProperty());
    }

    public void removeListener(com.jxparallel.fx.beans.value.ChangeListener<? super java.lang.Number> arg0) {
        ((javafx.beans.property.ReadOnlyIntegerWrapper) fxPeer()).removeListener((javafx.beans.value.ChangeListener) com.jxparallel.fx.Fx.fx(arg0));
    }

    public void removeListener(com.jxparallel.fx.beans.InvalidationListener arg0) {
        ((javafx.beans.property.ReadOnlyIntegerWrapper) fxPeer()).removeListener((javafx.beans.InvalidationListener) com.jxparallel.fx.Fx.fx(arg0));
    }
}
