package com.jxparallel.fx.beans.property;

/** JXParallel counterpart of {@link javafx.beans.property.ReadOnlyProperty} (generated by scripts/GenerateFxApi.java). */
@SuppressWarnings({"unchecked", "rawtypes", "deprecation"})
public interface ReadOnlyProperty<T> extends com.jxparallel.fx.beans.value.ObservableValue<T> {

    java.lang.Object getBean();

    java.lang.String getName();
}
