package com.jxparallel.fx.beans.property;

/** JXParallel counterpart of {@link javafx.beans.property.SimpleFloatProperty} (generated by scripts/GenerateFxApi.java). */
@SuppressWarnings({"unchecked", "rawtypes", "deprecation"})
public class SimpleFloatProperty extends com.jxparallel.fx.beans.property.FloatPropertyBase {
    protected SimpleFloatProperty(com.jxparallel.fx.Fx.Wrap wrap, Object peer) {
        super(wrap, peer);
    }

    public SimpleFloatProperty(java.lang.Object arg0, java.lang.String arg1) {
        this(com.jxparallel.fx.Fx.WRAP, new com.jxparallel.fx.peer.beans.property.SimpleFloatProperty((java.lang.Object) com.jxparallel.fx.Fx.fx(arg0), arg1));
        com.jxparallel.fx.Fx.own(fxPeer(), this);
    }

    public SimpleFloatProperty() {
        this(com.jxparallel.fx.Fx.WRAP, new com.jxparallel.fx.peer.beans.property.SimpleFloatProperty());
        com.jxparallel.fx.Fx.own(fxPeer(), this);
    }

    public SimpleFloatProperty(java.lang.Object arg0, java.lang.String arg1, float arg2) {
        this(com.jxparallel.fx.Fx.WRAP, new com.jxparallel.fx.peer.beans.property.SimpleFloatProperty((java.lang.Object) com.jxparallel.fx.Fx.fx(arg0), arg1, arg2));
        com.jxparallel.fx.Fx.own(fxPeer(), this);
    }

    public SimpleFloatProperty(float arg0) {
        this(com.jxparallel.fx.Fx.WRAP, new com.jxparallel.fx.peer.beans.property.SimpleFloatProperty(arg0));
        com.jxparallel.fx.Fx.own(fxPeer(), this);
    }

    public java.lang.Object getBean() {
        return (java.lang.Object) com.jxparallel.fx.Fx.jx(((javafx.beans.property.SimpleFloatProperty) fxPeer()).getBean());
    }

    public java.lang.String getName() {
        return ((javafx.beans.property.SimpleFloatProperty) fxPeer()).getName();
    }
}
