package com.jxparallel.fx.beans.property;

/** JXParallel counterpart of {@link javafx.beans.property.StringPropertyBase} (generated by scripts/GenerateFxApi.java). */
@SuppressWarnings({"unchecked", "rawtypes", "deprecation"})
public class StringPropertyBase extends com.jxparallel.fx.beans.property.StringProperty {
    protected StringPropertyBase(com.jxparallel.fx.Fx.Wrap wrap, Object peer) {
        super(wrap, peer);
    }

    public StringPropertyBase() {
        this(com.jxparallel.fx.Fx.WRAP, new com.jxparallel.fx.peer.beans.property.StringPropertyBase());
        com.jxparallel.fx.Fx.own(fxPeer(), this);
    }

    public StringPropertyBase(java.lang.String arg0) {
        this(com.jxparallel.fx.Fx.WRAP, new com.jxparallel.fx.peer.beans.property.StringPropertyBase(arg0));
        com.jxparallel.fx.Fx.own(fxPeer(), this);
    }

    public void addListener(com.jxparallel.fx.beans.value.ChangeListener<? super java.lang.String> arg0) {
        ((javafx.beans.property.StringPropertyBase) fxPeer()).addListener((javafx.beans.value.ChangeListener) com.jxparallel.fx.Fx.fx(arg0));
    }

    public void addListener(com.jxparallel.fx.beans.InvalidationListener arg0) {
        ((javafx.beans.property.StringPropertyBase) fxPeer()).addListener((javafx.beans.InvalidationListener) com.jxparallel.fx.Fx.fx(arg0));
    }

    public void bind(com.jxparallel.fx.beans.value.ObservableValue<? extends java.lang.String> arg0) {
        ((javafx.beans.property.StringPropertyBase) fxPeer()).bind((javafx.beans.value.ObservableValue) com.jxparallel.fx.Fx.fx(arg0));
    }

    protected void fireValueChangedEvent() {
        com.jxparallel.fx.Fx.invoke(fxPeer(), javafx.beans.property.StringPropertyBase.class, "fireValueChangedEvent", new Class<?>[] {});
    }

    public java.lang.String get() {
        return ((javafx.beans.property.StringPropertyBase) fxPeer()).get();
    }

    protected void invalidated() {
        com.jxparallel.fx.Fx.invoke(fxPeer(), javafx.beans.property.StringPropertyBase.class, "invalidated", new Class<?>[] {});
    }

    public boolean isBound() {
        return ((javafx.beans.property.StringPropertyBase) fxPeer()).isBound();
    }

    public void removeListener(com.jxparallel.fx.beans.value.ChangeListener<? super java.lang.String> arg0) {
        ((javafx.beans.property.StringPropertyBase) fxPeer()).removeListener((javafx.beans.value.ChangeListener) com.jxparallel.fx.Fx.fx(arg0));
    }

    public void removeListener(com.jxparallel.fx.beans.InvalidationListener arg0) {
        ((javafx.beans.property.StringPropertyBase) fxPeer()).removeListener((javafx.beans.InvalidationListener) com.jxparallel.fx.Fx.fx(arg0));
    }

    public void set(java.lang.String arg0) {
        ((javafx.beans.property.StringPropertyBase) fxPeer()).set(arg0);
    }

    public void unbind() {
        ((javafx.beans.property.StringPropertyBase) fxPeer()).unbind();
    }

    /** Called by the peer: runs the JX (possibly overridden) method. */
    public static Object $hook(Object self, String method, Object[] a) {
        StringPropertyBase jx = (StringPropertyBase) self;
        try {
        switch (method) {
            case "getBean()":
                return jx.getBean();
            case "getName()":
                return jx.getName();
            default:
                throw new IllegalArgumentException(method);
        }
        } catch (Exception e) {
            throw com.jxparallel.fx.Fx.sneaky(e);
        }
    }
}
