#!/bin/sh
# Regenerates the JavaFX-compatible API (jxparallel-fx) and its ControlsFX part
# (jxparallel-fx-controlsfx) with a JDK 8 that bundles JavaFX (JDK8_HOME, default: the 32-bit 8u51
# used by DeviceConfig). Reports: <module>/mirrors/report.txt.
set -e
cd "$(dirname "$0")/.."
JDK="${JDK8_HOME:-/c/Program Files (x86)/Java/jdk1.8.0_51}"
CONTROLSFX="$HOME/.m2/repository/org/controlsfx/controlsfx/8.40.14/controlsfx-8.40.14.jar"
mkdir -p target/fx-gen
"$JDK/bin/javac" -encoding UTF-8 -nowarn -d target/fx-gen scripts/GenerateFxApi.java
for module in jxparallel-fx jxparallel-fx-controlsfx; do
    grep -rl "generated by scripts/GenerateFxApi.java" $module/src/main/java | xargs -r rm
done
"$JDK/bin/java" -cp target/fx-gen GenerateFxApi jxparallel-fx/mirrors/seeds.txt jxparallel-fx/mirrors/handwritten.txt \
    jxparallel-fx/src/main/java > jxparallel-fx/mirrors/report.txt
# The ControlsFX run treats everything jxparallel-fx provides as already mapped.
{ cat jxparallel-fx/mirrors/handwritten.txt; sed -n 's/^GENERATED //p' jxparallel-fx/mirrors/report.txt; } > target/fx-gen/provided.txt
"$JDK/bin/java" -cp "target/fx-gen;$(cygpath -w "$CONTROLSFX")" GenerateFxApi jxparallel-fx-controlsfx/mirrors/seeds.txt target/fx-gen/provided.txt \
    jxparallel-fx-controlsfx/src/main/java > jxparallel-fx-controlsfx/mirrors/report.txt
tail -n 1 jxparallel-fx/mirrors/report.txt jxparallel-fx-controlsfx/mirrors/report.txt
