# Regenerates the JavaFX-compatible API (jxparallel-fx) and its ControlsFX part (jxparallel-fx-controlsfx)
# with a JDK 8 that bundles JavaFX ($env:JDK8_HOME, default: the 32-bit 8u51 used by DeviceConfig).
# PowerShell twin of generate-fx-api.sh. Reports: <module>/mirrors/report.txt.
$ErrorActionPreference = 'Stop'
$root = Split-Path -Parent $PSScriptRoot
Set-Location $root
$jdk = if ($env:JDK8_HOME) { $env:JDK8_HOME } else { 'C:\Program Files (x86)\Java\jdk1.8.0_51' }
$controlsfx = "$env:USERPROFILE\.m2\repository\org\controlsfx\controlsfx\8.40.14\controlsfx-8.40.14.jar"
New-Item -ItemType Directory target\fx-gen -Force | Out-Null
& "$jdk\bin\javac.exe" -encoding UTF-8 -nowarn -d target\fx-gen scripts\GenerateFxApi.java 2>&1 | Where-Object { $_ -notmatch 'JAVA_TOOL' }
foreach ($module in 'jxparallel-fx', 'jxparallel-fx-controlsfx') {
    Get-ChildItem -Recurse "$module\src\main\java" -Filter *.java |
        Where-Object { Select-String -Path $_.FullName -Pattern 'generated by scripts/GenerateFxApi.java' -Quiet } |
        ForEach-Object { [IO.File]::Delete($_.FullName) }
}
& "$jdk\bin\java.exe" -cp target\fx-gen GenerateFxApi jxparallel-fx\mirrors\seeds.txt jxparallel-fx\mirrors\handwritten.txt `
    jxparallel-fx\src\main\java 2>&1 | Where-Object { $_ -notmatch 'JAVA_TOOL' } | Set-Content jxparallel-fx\mirrors\report.txt
# The ControlsFX run treats everything jxparallel-fx provides as already mapped.
$provided = @(Get-Content jxparallel-fx\mirrors\handwritten.txt) + @(Get-Content jxparallel-fx\mirrors\report.txt | Where-Object { $_ -like 'GENERATED *' } | ForEach-Object { $_.Substring(10) })
$provided | Set-Content target\fx-gen\provided.txt
& "$jdk\bin\java.exe" -cp "target\fx-gen;$controlsfx" GenerateFxApi jxparallel-fx-controlsfx\mirrors\seeds.txt target\fx-gen\provided.txt `
    jxparallel-fx-controlsfx\src\main\java 2>&1 | Where-Object { $_ -notmatch 'JAVA_TOOL' } | Set-Content jxparallel-fx-controlsfx\mirrors\report.txt
Get-Content jxparallel-fx\mirrors\report.txt -Tail 1
Get-Content jxparallel-fx-controlsfx\mirrors\report.txt -Tail 1
