"""Writes target/purefx/PureFxBench.java: scripts/FxBackendBench.java with its com.jxparallel.fx imports
swapped for javafx ones, the same application on plain JavaFX (the DeviceConfig before any migration).
Usage: python scripts/make-purefx-bench.py, then compile it with the JDK being measured."""
import os
import re

s = open('scripts/FxBackendBench.java', encoding='utf-8').read()
s = s.replace('import com.jxparallel.fx.Fx;\n', '')
s = re.sub(r'import com\.jxparallel\.fx\.', 'import javafx.', s)
s = s.replace('public class FxBackendBench', 'public class PureFxBench')
s = s.replace('launch(FxBackendBench.class, args);', 'launch(PureFxBench.class, args);')
s = s.replace('Fx.NATIVE ? 1 : 0', '2')
s = s.replace('clock = Fx.NATIVE ? new NativeClock() : new PulseClock();', 'clock = new PulseClock();')
s = s.replace('(Fx.NATIVE ? "native" : "JavaFX")', '"pure JavaFX"')
s = s[:s.index('    /** Native: presented frames')] + s[s.index('    // ---- metrics'):]
s = s.replace('/**\n * One application', '/**\n * GENERATED by scripts/make-purefx-bench.py from FxBackendBench.java: plain JavaFX imports.\n *\n * One application', 1)
os.makedirs('target/purefx', exist_ok=True)
open('target/purefx/PureFxBench.java', 'w', encoding='utf-8').write(s)
