package com.jxparallel.fx.scene;

/** JXParallel counterpart of {@link javafx.scene.LightBase} (generated by scripts/GenerateFxApi.java). */
@SuppressWarnings({"unchecked", "rawtypes", "deprecation"})
public class LightBase extends com.jxparallel.fx.scene.Node {
    protected LightBase(com.jxparallel.fx.Fx.Wrap wrap, Object peer) {
        super(wrap, peer);
    }

    public com.jxparallel.fx.beans.property.ObjectProperty<com.jxparallel.fx.scene.paint.Color> colorProperty() {
        if (com.jxparallel.fx.Fx.NATIVE) {
            return (com.jxparallel.fx.beans.property.ObjectProperty) com.jxparallel.fx.nativeimpl.Native.call(this, com.jxparallel.fx.scene.LightBase.class, "colorProperty", new Class<?>[] {}, com.jxparallel.fx.beans.property.ObjectProperty.class);
        }
        return (com.jxparallel.fx.beans.property.ObjectProperty) com.jxparallel.fx.Fx.jx(((javafx.scene.LightBase) fxPeer()).colorProperty());
    }

    public com.jxparallel.fx.scene.paint.Color getColor() {
        if (com.jxparallel.fx.Fx.NATIVE) {
            return (com.jxparallel.fx.scene.paint.Color) com.jxparallel.fx.nativeimpl.Native.call(this, com.jxparallel.fx.scene.LightBase.class, "getColor", new Class<?>[] {}, com.jxparallel.fx.scene.paint.Color.class);
        }
        return (com.jxparallel.fx.scene.paint.Color) com.jxparallel.fx.Fx.jx(((javafx.scene.LightBase) fxPeer()).getColor());
    }

    public com.jxparallel.fx.collections.ObservableList<com.jxparallel.fx.scene.Node> getScope() {
        if (com.jxparallel.fx.Fx.NATIVE) {
            return (com.jxparallel.fx.collections.ObservableList) com.jxparallel.fx.nativeimpl.Native.call(this, com.jxparallel.fx.scene.LightBase.class, "getScope", new Class<?>[] {}, com.jxparallel.fx.collections.ObservableList.class);
        }
        return (com.jxparallel.fx.collections.ObservableList) com.jxparallel.fx.Fx.jx(((javafx.scene.LightBase) fxPeer()).getScope());
    }

    public void impl_updatePeer() {
        if (com.jxparallel.fx.Fx.NATIVE) {
            com.jxparallel.fx.nativeimpl.Native.call(this, com.jxparallel.fx.scene.LightBase.class, "impl_updatePeer", new Class<?>[] {}, void.class);
            return;
        }
        ((javafx.scene.LightBase) fxPeer()).impl_updatePeer();
    }

    public boolean isLightOn() {
        if (com.jxparallel.fx.Fx.NATIVE) {
            return (Boolean) com.jxparallel.fx.nativeimpl.Native.call(this, com.jxparallel.fx.scene.LightBase.class, "isLightOn", new Class<?>[] {}, boolean.class);
        }
        return ((javafx.scene.LightBase) fxPeer()).isLightOn();
    }

    public com.jxparallel.fx.beans.property.BooleanProperty lightOnProperty() {
        if (com.jxparallel.fx.Fx.NATIVE) {
            return (com.jxparallel.fx.beans.property.BooleanProperty) com.jxparallel.fx.nativeimpl.Native.call(this, com.jxparallel.fx.scene.LightBase.class, "lightOnProperty", new Class<?>[] {}, com.jxparallel.fx.beans.property.BooleanProperty.class);
        }
        return (com.jxparallel.fx.beans.property.BooleanProperty) com.jxparallel.fx.Fx.jx(((javafx.scene.LightBase) fxPeer()).lightOnProperty());
    }

    public void setColor(com.jxparallel.fx.scene.paint.Color arg0) {
        if (com.jxparallel.fx.Fx.NATIVE) {
            com.jxparallel.fx.nativeimpl.Native.call(this, com.jxparallel.fx.scene.LightBase.class, "setColor", new Class<?>[] {com.jxparallel.fx.scene.paint.Color.class}, void.class, arg0);
            return;
        }
        ((javafx.scene.LightBase) fxPeer()).setColor((javafx.scene.paint.Color) com.jxparallel.fx.Fx.fx(arg0));
    }

    public void setLightOn(boolean arg0) {
        if (com.jxparallel.fx.Fx.NATIVE) {
            com.jxparallel.fx.nativeimpl.Native.call(this, com.jxparallel.fx.scene.LightBase.class, "setLightOn", new Class<?>[] {boolean.class}, void.class, arg0);
            return;
        }
        ((javafx.scene.LightBase) fxPeer()).setLightOn(arg0);
    }
}
