package com.jxparallel.fx.scene;

/** JXParallel counterpart of {@link javafx.scene.ParallelCamera} (generated by scripts/GenerateFxApi.java). */
@SuppressWarnings({"unchecked", "rawtypes", "deprecation"})
public class ParallelCamera extends com.jxparallel.fx.scene.Camera {
    protected ParallelCamera(com.jxparallel.fx.Fx.Wrap wrap, Object peer) {
        super(wrap, peer);
    }

    public ParallelCamera() {
        this(com.jxparallel.fx.Fx.WRAP, com.jxparallel.fx.Fx.NATIVE ? com.jxparallel.fx.nativeimpl.Native.create(javafx.scene.ParallelCamera.class, new String[] {}, new Object[] {}) : new com.jxparallel.fx.peer.scene.ParallelCamera());
        com.jxparallel.fx.Fx.own(fxPeer(), this);
    }
}
