package com.jxparallel.fx.peer.scene.text;

/** JavaFX peer of {@link com.jxparallel.fx.scene.text.Text}; forwards overridable methods to it (generated by scripts/GenerateFxApi.java). */
@SuppressWarnings({"unchecked", "rawtypes", "deprecation", "serial"})
public class Text extends javafx.scene.text.Text implements com.jxparallel.fx.Fx.Owned {
    private Object jxOwner;

    public Text(java.lang.String arg0) {
        super(arg0);
    }

    public Text() {
        super();
    }

    public Text(double arg0, double arg1, java.lang.String arg2) {
        super(arg0, arg1, arg2);
    }

    @Override
    public Object jxOwner() {
        return jxOwner;
    }

    @Override
    public void jxOwner(Object owner) {
        this.jxOwner = owner;
    }

    @Override
    public Object callSuper(String method, Object[] a) {
        try {
        switch (method) {
            default:
                throw new AbstractMethodError(method);
        }
        } catch (Exception e) {
            throw com.jxparallel.fx.Fx.sneaky(e);
        }
    }
}
