package com.jxparallel.fx.beans.value;

/** JXParallel counterpart of {@link javafx.beans.value.ObservableNumberValue} (generated by scripts/GenerateFxApi.java). */
@SuppressWarnings({"unchecked", "rawtypes", "deprecation"})
public interface ObservableNumberValue extends com.jxparallel.fx.beans.value.ObservableValue<java.lang.Number> {

    double doubleValue();

    float floatValue();

    int intValue();

    long longValue();
}
