package com.jxparallel.fx.beans.value;

/** JXParallel counterpart of {@link javafx.beans.value.ObservableIntegerValue} (generated by scripts/GenerateFxApi.java). */
@SuppressWarnings({"unchecked", "rawtypes", "deprecation"})
public interface ObservableIntegerValue extends com.jxparallel.fx.beans.value.ObservableNumberValue {

    int get();
}
