package com.jxparallel.fx.beans.value;

/** JXParallel counterpart of {@link javafx.beans.value.WeakChangeListener} (generated by scripts/GenerateFxApi.java). */
@SuppressWarnings({"unchecked", "rawtypes", "deprecation"})
public final class WeakChangeListener<T> implements com.jxparallel.fx.beans.value.ChangeListener<T>, com.jxparallel.fx.beans.WeakListener, com.jxparallel.fx.Fx.Backed {
    private final Object fxPeer;

    protected WeakChangeListener(com.jxparallel.fx.Fx.Wrap wrap, Object peer) {
        this.fxPeer = peer;
    }

    @Override
    public Object fxPeer() {
        return fxPeer;
    }

    @Override
    public boolean equals(Object o) {
        return o == this || fxPeer().equals(com.jxparallel.fx.Fx.fx(o));
    }

    @Override
    public int hashCode() {
        return fxPeer().hashCode();
    }

    @Override
    public String toString() {
        return fxPeer().toString();
    }

    public WeakChangeListener(@javafx.beans.NamedArg(value = "listener") com.jxparallel.fx.beans.value.ChangeListener<T> arg0) {
        this(com.jxparallel.fx.Fx.WRAP, new javafx.beans.value.WeakChangeListener((javafx.beans.value.ChangeListener) com.jxparallel.fx.Fx.fx(arg0)));
        com.jxparallel.fx.Fx.own(fxPeer(), this);
    }

    public void changed(com.jxparallel.fx.beans.value.ObservableValue<? extends T> arg0, T arg1, T arg2) {
        ((javafx.beans.value.WeakChangeListener) fxPeer()).changed((javafx.beans.value.ObservableValue) com.jxparallel.fx.Fx.fx(arg0), (T) com.jxparallel.fx.Fx.fx(arg1), (T) com.jxparallel.fx.Fx.fx(arg2));
    }

    public boolean wasGarbageCollected() {
        return ((javafx.beans.value.WeakChangeListener) fxPeer()).wasGarbageCollected();
    }
}
