package com.jxparallel.fx.beans.value;

/** JXParallel counterpart of {@link javafx.beans.value.WritableLongValue} (generated by scripts/GenerateFxApi.java). */
@SuppressWarnings({"unchecked", "rawtypes", "deprecation"})
public interface WritableLongValue extends com.jxparallel.fx.beans.value.WritableNumberValue {

    long get();

    void set(long arg0);

    void setValue(java.lang.Number arg0);
}
