package com.jxparallel.fx.scene.control.cell;

/** JXParallel counterpart of {@link javafx.scene.control.cell.MapValueFactory} (generated by scripts/GenerateFxApi.java). */
@SuppressWarnings({"unchecked", "rawtypes", "deprecation"})
public class MapValueFactory<T> implements com.jxparallel.fx.util.Callback<com.jxparallel.fx.scene.control.TableColumn.CellDataFeatures<java.util.Map, T>, com.jxparallel.fx.beans.value.ObservableValue<T>>, com.jxparallel.fx.Fx.Backed {
    private final Object fxPeer;

    protected MapValueFactory(com.jxparallel.fx.Fx.Wrap wrap, Object peer) {
        this.fxPeer = peer;
    }

    @Override
    public Object fxPeer() {
        return fxPeer;
    }

    @Override
    public boolean equals(Object o) {
        return o == this || fxPeer.equals(com.jxparallel.fx.Fx.fx(o));
    }

    @Override
    public int hashCode() {
        return fxPeer.hashCode();
    }

    @Override
    public String toString() {
        return fxPeer.toString();
    }

    public MapValueFactory(@javafx.beans.NamedArg(value = "key") java.lang.Object arg0) {
        this(com.jxparallel.fx.Fx.WRAP, com.jxparallel.fx.Fx.NATIVE ? com.jxparallel.fx.nativeimpl.Native.create(javafx.scene.control.cell.MapValueFactory.class, new String[] {"key"}, new Object[] {arg0}) : new com.jxparallel.fx.peer.scene.control.cell.MapValueFactory((java.lang.Object) com.jxparallel.fx.Fx.fx(arg0)));
        com.jxparallel.fx.Fx.own(fxPeer(), this);
    }

    public com.jxparallel.fx.beans.value.ObservableValue<T> call(com.jxparallel.fx.scene.control.TableColumn.CellDataFeatures<java.util.Map, T> arg0) {
        if (com.jxparallel.fx.Fx.NATIVE) {
            return (com.jxparallel.fx.beans.value.ObservableValue) com.jxparallel.fx.nativeimpl.Native.call(this, com.jxparallel.fx.scene.control.cell.MapValueFactory.class, "call", new Class<?>[] {com.jxparallel.fx.scene.control.TableColumn.CellDataFeatures.class}, com.jxparallel.fx.beans.value.ObservableValue.class, arg0);
        }
        return (com.jxparallel.fx.beans.value.ObservableValue) com.jxparallel.fx.Fx.jx(((javafx.scene.control.cell.MapValueFactory) fxPeer()).call((javafx.scene.control.TableColumn.CellDataFeatures) com.jxparallel.fx.Fx.fx(arg0)));
    }
}
