package com.jxparallel.fx.scene.control.cell;

/** JXParallel counterpart of {@link javafx.scene.control.cell.TextFieldTableCell} (generated by scripts/GenerateFxApi.java). */
@SuppressWarnings({"unchecked", "rawtypes", "deprecation"})
@javafx.beans.DefaultProperty("text")
public class TextFieldTableCell<S, T> extends com.jxparallel.fx.scene.control.TableCell<S, T> {
    protected TextFieldTableCell(com.jxparallel.fx.Fx.Wrap wrap, Object peer) {
        super(wrap, peer);
    }

    public TextFieldTableCell() {
        this(com.jxparallel.fx.Fx.WRAP, com.jxparallel.fx.Fx.NATIVE ? com.jxparallel.fx.nativeimpl.Native.create(javafx.scene.control.cell.TextFieldTableCell.class, new String[] {}, new Object[] {}) : new com.jxparallel.fx.peer.scene.control.cell.TextFieldTableCell());
        com.jxparallel.fx.Fx.own(fxPeer(), this);
    }

    public TextFieldTableCell(com.jxparallel.fx.util.StringConverter<T> arg0) {
        this(com.jxparallel.fx.Fx.WRAP, com.jxparallel.fx.Fx.NATIVE ? com.jxparallel.fx.nativeimpl.Native.create(javafx.scene.control.cell.TextFieldTableCell.class, new String[] {null}, new Object[] {arg0}) : new com.jxparallel.fx.peer.scene.control.cell.TextFieldTableCell((javafx.util.StringConverter) com.jxparallel.fx.Fx.fx(arg0)));
        com.jxparallel.fx.Fx.own(fxPeer(), this);
    }

    public void cancelEdit() {
        if (com.jxparallel.fx.Fx.NATIVE) {
            com.jxparallel.fx.nativeimpl.Native.call(this, com.jxparallel.fx.scene.control.cell.TextFieldTableCell.class, "cancelEdit", new Class<?>[] {}, void.class);
            return;
        }
        if (fxPeer() instanceof com.jxparallel.fx.Fx.Owned) {
            ((com.jxparallel.fx.Fx.Owned) fxPeer()).callSuper("cancelEdit()", new Object[] {});
        } else {
            com.jxparallel.fx.Fx.invoke(fxPeer(), javafx.scene.control.cell.TextFieldTableCell.class, "cancelEdit", new Class<?>[] {});
        }
    }

    public com.jxparallel.fx.beans.property.ObjectProperty<com.jxparallel.fx.util.StringConverter<T>> converterProperty() {
        if (com.jxparallel.fx.Fx.NATIVE) {
            return (com.jxparallel.fx.beans.property.ObjectProperty) com.jxparallel.fx.nativeimpl.Native.call(this, com.jxparallel.fx.scene.control.cell.TextFieldTableCell.class, "converterProperty", new Class<?>[] {}, com.jxparallel.fx.beans.property.ObjectProperty.class);
        }
        return (com.jxparallel.fx.beans.property.ObjectProperty) com.jxparallel.fx.Fx.jx(((javafx.scene.control.cell.TextFieldTableCell) fxPeer()).converterProperty());
    }

    public static <S> com.jxparallel.fx.util.Callback<com.jxparallel.fx.scene.control.TableColumn<S, java.lang.String>, com.jxparallel.fx.scene.control.TableCell<S, java.lang.String>> forTableColumn() {
        if (com.jxparallel.fx.Fx.NATIVE) {
            return (com.jxparallel.fx.util.Callback) com.jxparallel.fx.nativeimpl.Native.call(null, com.jxparallel.fx.scene.control.cell.TextFieldTableCell.class, "forTableColumn", new Class<?>[] {}, com.jxparallel.fx.util.Callback.class);
        }
        return (com.jxparallel.fx.util.Callback) com.jxparallel.fx.Fx.jx(javafx.scene.control.cell.TextFieldTableCell.forTableColumn());
    }

    public static <S, T> com.jxparallel.fx.util.Callback<com.jxparallel.fx.scene.control.TableColumn<S, T>, com.jxparallel.fx.scene.control.TableCell<S, T>> forTableColumn(com.jxparallel.fx.util.StringConverter<T> arg0) {
        if (com.jxparallel.fx.Fx.NATIVE) {
            return (com.jxparallel.fx.util.Callback) com.jxparallel.fx.nativeimpl.Native.call(null, com.jxparallel.fx.scene.control.cell.TextFieldTableCell.class, "forTableColumn", new Class<?>[] {com.jxparallel.fx.util.StringConverter.class}, com.jxparallel.fx.util.Callback.class, arg0);
        }
        return (com.jxparallel.fx.util.Callback) com.jxparallel.fx.Fx.jx(javafx.scene.control.cell.TextFieldTableCell.forTableColumn((javafx.util.StringConverter) com.jxparallel.fx.Fx.fx(arg0)));
    }

    public com.jxparallel.fx.util.StringConverter<T> getConverter() {
        if (com.jxparallel.fx.Fx.NATIVE) {
            return (com.jxparallel.fx.util.StringConverter) com.jxparallel.fx.nativeimpl.Native.call(this, com.jxparallel.fx.scene.control.cell.TextFieldTableCell.class, "getConverter", new Class<?>[] {}, com.jxparallel.fx.util.StringConverter.class);
        }
        return (com.jxparallel.fx.util.StringConverter) com.jxparallel.fx.Fx.jx(((javafx.scene.control.cell.TextFieldTableCell) fxPeer()).getConverter());
    }

    public void setConverter(com.jxparallel.fx.util.StringConverter<T> arg0) {
        if (com.jxparallel.fx.Fx.NATIVE) {
            com.jxparallel.fx.nativeimpl.Native.call(this, com.jxparallel.fx.scene.control.cell.TextFieldTableCell.class, "setConverter", new Class<?>[] {com.jxparallel.fx.util.StringConverter.class}, void.class, arg0);
            return;
        }
        ((javafx.scene.control.cell.TextFieldTableCell) fxPeer()).setConverter((javafx.util.StringConverter) com.jxparallel.fx.Fx.fx(arg0));
    }

    public void startEdit() {
        if (com.jxparallel.fx.Fx.NATIVE) {
            com.jxparallel.fx.nativeimpl.Native.call(this, com.jxparallel.fx.scene.control.cell.TextFieldTableCell.class, "startEdit", new Class<?>[] {}, void.class);
            return;
        }
        if (fxPeer() instanceof com.jxparallel.fx.Fx.Owned) {
            ((com.jxparallel.fx.Fx.Owned) fxPeer()).callSuper("startEdit()", new Object[] {});
        } else {
            com.jxparallel.fx.Fx.invoke(fxPeer(), javafx.scene.control.cell.TextFieldTableCell.class, "startEdit", new Class<?>[] {});
        }
    }

    public void updateItem(T arg0, boolean arg1) {
        if (com.jxparallel.fx.Fx.NATIVE) {
            com.jxparallel.fx.nativeimpl.Native.call(this, com.jxparallel.fx.scene.control.cell.TextFieldTableCell.class, "updateItem", new Class<?>[] {java.lang.Object.class, boolean.class}, void.class, arg0, arg1);
            return;
        }
        if (fxPeer() instanceof com.jxparallel.fx.Fx.Owned) {
            ((com.jxparallel.fx.Fx.Owned) fxPeer()).callSuper("updateItem(Object,boolean)", new Object[] {(T) com.jxparallel.fx.Fx.fx(arg0), arg1});
        } else {
            com.jxparallel.fx.Fx.invoke(fxPeer(), javafx.scene.control.cell.TextFieldTableCell.class, "updateItem", new Class<?>[] {java.lang.Object.class, boolean.class}, (T) com.jxparallel.fx.Fx.fx(arg0), arg1);
        }
    }

    /** Called by the peer: runs the JX (possibly overridden) method. */
    public static Object $hook(Object self, String method, Object[] a) {
        TextFieldTableCell jx = (TextFieldTableCell) self;
        try {
        switch (method) {
            case "updateItem(Object,boolean)":
                jx.updateItem((java.lang.Object) a[0], (Boolean) a[1]);
                return null;
            case "cancelEdit()":
                jx.cancelEdit();
                return null;
            case "startEdit()":
                jx.startEdit();
                return null;
            case "commitEdit(Object)":
                jx.commitEdit((java.lang.Object) a[0]);
                return null;
            case "updateSelected(boolean)":
                jx.updateSelected((Boolean) a[0]);
                return null;
            case "updateIndex(int)":
                jx.updateIndex((Integer) a[0]);
                return null;
            default:
                throw new IllegalArgumentException(method);
        }
        } catch (Exception e) {
            throw com.jxparallel.fx.Fx.sneaky(e);
        }
    }
}
