package com.jxparallel.fx.event;

/** JXParallel counterpart of {@link javafx.event.EventDispatcher} (generated by scripts/GenerateFxApi.java). */
@SuppressWarnings({"unchecked", "rawtypes", "deprecation"})
@FunctionalInterface
public interface EventDispatcher {

    com.jxparallel.fx.event.Event dispatchEvent(com.jxparallel.fx.event.Event arg0, com.jxparallel.fx.event.EventDispatchChain arg1);
}
