package com.jxparallel.fx.event;

/** JXParallel counterpart of {@link javafx.event.EventDispatchChain} (generated by scripts/GenerateFxApi.java). */
@SuppressWarnings({"unchecked", "rawtypes", "deprecation"})
public interface EventDispatchChain {

    com.jxparallel.fx.event.EventDispatchChain append(com.jxparallel.fx.event.EventDispatcher arg0);

    com.jxparallel.fx.event.Event dispatchEvent(com.jxparallel.fx.event.Event arg0);

    com.jxparallel.fx.event.EventDispatchChain prepend(com.jxparallel.fx.event.EventDispatcher arg0);
}
