package com.jxparallel.fx.geometry;

/** JXParallel counterpart of {@link javafx.geometry.BoundingBox} (generated by scripts/GenerateFxApi.java). */
@SuppressWarnings({"unchecked", "rawtypes", "deprecation"})
public class BoundingBox extends com.jxparallel.fx.geometry.Bounds {
    protected BoundingBox(com.jxparallel.fx.Fx.Wrap wrap, Object peer) {
        super(wrap, peer);
    }

    public BoundingBox(@javafx.beans.NamedArg(value = "minX") double arg0, @javafx.beans.NamedArg(value = "minY") double arg1, @javafx.beans.NamedArg(value = "minZ") double arg2, @javafx.beans.NamedArg(value = "width") double arg3, @javafx.beans.NamedArg(value = "height") double arg4, @javafx.beans.NamedArg(value = "depth") double arg5) {
        this(com.jxparallel.fx.Fx.WRAP, new com.jxparallel.fx.peer.geometry.BoundingBox(arg0, arg1, arg2, arg3, arg4, arg5));
        com.jxparallel.fx.Fx.own(fxPeer(), this);
    }

    public BoundingBox(@javafx.beans.NamedArg(value = "minX") double arg0, @javafx.beans.NamedArg(value = "minY") double arg1, @javafx.beans.NamedArg(value = "width") double arg2, @javafx.beans.NamedArg(value = "height") double arg3) {
        this(com.jxparallel.fx.Fx.WRAP, new com.jxparallel.fx.peer.geometry.BoundingBox(arg0, arg1, arg2, arg3));
        com.jxparallel.fx.Fx.own(fxPeer(), this);
    }

    public boolean contains(com.jxparallel.fx.geometry.Bounds arg0) {
        return ((javafx.geometry.BoundingBox) fxPeer()).contains((javafx.geometry.Bounds) com.jxparallel.fx.Fx.fx(arg0));
    }

    public boolean contains(com.jxparallel.fx.geometry.Point2D arg0) {
        return ((javafx.geometry.BoundingBox) fxPeer()).contains((javafx.geometry.Point2D) com.jxparallel.fx.Fx.fx(arg0));
    }

    public boolean contains(com.jxparallel.fx.geometry.Point3D arg0) {
        return ((javafx.geometry.BoundingBox) fxPeer()).contains((javafx.geometry.Point3D) com.jxparallel.fx.Fx.fx(arg0));
    }

    public boolean contains(double arg0, double arg1) {
        return ((javafx.geometry.BoundingBox) fxPeer()).contains(arg0, arg1);
    }

    public boolean contains(double arg0, double arg1, double arg2) {
        return ((javafx.geometry.BoundingBox) fxPeer()).contains(arg0, arg1, arg2);
    }

    public boolean contains(double arg0, double arg1, double arg2, double arg3) {
        return ((javafx.geometry.BoundingBox) fxPeer()).contains(arg0, arg1, arg2, arg3);
    }

    public boolean contains(double arg0, double arg1, double arg2, double arg3, double arg4, double arg5) {
        return ((javafx.geometry.BoundingBox) fxPeer()).contains(arg0, arg1, arg2, arg3, arg4, arg5);
    }

    public boolean intersects(com.jxparallel.fx.geometry.Bounds arg0) {
        return ((javafx.geometry.BoundingBox) fxPeer()).intersects((javafx.geometry.Bounds) com.jxparallel.fx.Fx.fx(arg0));
    }

    public boolean intersects(double arg0, double arg1, double arg2, double arg3) {
        return ((javafx.geometry.BoundingBox) fxPeer()).intersects(arg0, arg1, arg2, arg3);
    }

    public boolean intersects(double arg0, double arg1, double arg2, double arg3, double arg4, double arg5) {
        return ((javafx.geometry.BoundingBox) fxPeer()).intersects(arg0, arg1, arg2, arg3, arg4, arg5);
    }

    public boolean isEmpty() {
        return ((javafx.geometry.BoundingBox) fxPeer()).isEmpty();
    }
}
