package com.jxparallel.fx.peer.beans.property;

/** JavaFX peer of {@link com.jxparallel.fx.beans.property.ReadOnlyObjectProperty}; forwards overridable methods to it (generated by scripts/GenerateFxApi.java). */
@SuppressWarnings({"unchecked", "rawtypes", "deprecation", "serial"})
public class ReadOnlyObjectProperty<T> extends javafx.beans.property.ReadOnlyObjectProperty<T> implements com.jxparallel.fx.Fx.Owned {
    private Object jxOwner;

    public ReadOnlyObjectProperty() {
        super();
    }

    @Override
    public Object jxOwner() {
        return jxOwner;
    }

    @Override
    public void jxOwner(Object owner) {
        this.jxOwner = owner;
    }

    @Override
    public T get() {
        if (jxOwner == null) {
            throw new IllegalStateException("get before the JX object exists");
        }
        return (T) com.jxparallel.fx.Fx.fx(com.jxparallel.fx.beans.property.ReadOnlyObjectProperty.$hook(jxOwner, "get()", new Object[] {}));
    }

    @Override
    public void removeListener(javafx.beans.value.ChangeListener<? super T> arg0) {
        if (jxOwner == null) {
            throw new IllegalStateException("removeListener before the JX object exists");
        }
        com.jxparallel.fx.beans.property.ReadOnlyObjectProperty.$hook(jxOwner, "removeListener(ChangeListener)", new Object[] {com.jxparallel.fx.Fx.jx(arg0)});
    }

    @Override
    public void addListener(javafx.beans.value.ChangeListener<? super T> arg0) {
        if (jxOwner == null) {
            throw new IllegalStateException("addListener before the JX object exists");
        }
        com.jxparallel.fx.beans.property.ReadOnlyObjectProperty.$hook(jxOwner, "addListener(ChangeListener)", new Object[] {com.jxparallel.fx.Fx.jx(arg0)});
    }

    @Override
    public void removeListener(javafx.beans.InvalidationListener arg0) {
        if (jxOwner == null) {
            throw new IllegalStateException("removeListener before the JX object exists");
        }
        com.jxparallel.fx.beans.property.ReadOnlyObjectProperty.$hook(jxOwner, "removeListener(InvalidationListener)", new Object[] {com.jxparallel.fx.Fx.jx(arg0)});
    }

    @Override
    public void addListener(javafx.beans.InvalidationListener arg0) {
        if (jxOwner == null) {
            throw new IllegalStateException("addListener before the JX object exists");
        }
        com.jxparallel.fx.beans.property.ReadOnlyObjectProperty.$hook(jxOwner, "addListener(InvalidationListener)", new Object[] {com.jxparallel.fx.Fx.jx(arg0)});
    }

    @Override
    public java.lang.String getName() {
        if (jxOwner == null) {
            throw new IllegalStateException("getName before the JX object exists");
        }
        return (java.lang.String) com.jxparallel.fx.Fx.fx(com.jxparallel.fx.beans.property.ReadOnlyObjectProperty.$hook(jxOwner, "getName()", new Object[] {}));
    }

    @Override
    public java.lang.Object getBean() {
        if (jxOwner == null) {
            throw new IllegalStateException("getBean before the JX object exists");
        }
        return (java.lang.Object) com.jxparallel.fx.Fx.fx(com.jxparallel.fx.beans.property.ReadOnlyObjectProperty.$hook(jxOwner, "getBean()", new Object[] {}));
    }

    @Override
    public Object callSuper(String method, Object[] a) {
        try {
        switch (method) {
            default:
                throw new AbstractMethodError(method);
        }
        } catch (Exception e) {
            throw com.jxparallel.fx.Fx.sneaky(e);
        }
    }
}
