package com.jxparallel.fx.peer.stage;

/** JavaFX peer of {@link com.jxparallel.fx.stage.PopupWindow}; forwards overridable methods to it (generated by scripts/GenerateFxApi.java). */
@SuppressWarnings({"unchecked", "rawtypes", "deprecation", "serial"})
public class PopupWindow extends javafx.stage.PopupWindow implements com.jxparallel.fx.Fx.Owned {
    private Object jxOwner;

    public PopupWindow() {
        super();
    }

    @Override
    public Object jxOwner() {
        return jxOwner;
    }

    @Override
    public void jxOwner(Object owner) {
        this.jxOwner = owner;
    }

    @Override
    public Object callSuper(String method, Object[] a) {
        try {
        switch (method) {
            default:
                throw new AbstractMethodError(method);
        }
        } catch (Exception e) {
            throw com.jxparallel.fx.Fx.sneaky(e);
        }
    }
}
