package com.jxparallel.fx.peer.stage;

/** JavaFX peer of {@link com.jxparallel.fx.stage.WindowEvent}; forwards overridable methods to it (generated by scripts/GenerateFxApi.java). */
@SuppressWarnings({"unchecked", "rawtypes", "deprecation", "serial"})
public class WindowEvent extends javafx.stage.WindowEvent implements com.jxparallel.fx.Fx.Owned {
    private Object jxOwner;

    public WindowEvent(@javafx.beans.NamedArg(value = "source") javafx.stage.Window arg0, @javafx.beans.NamedArg(value = "eventType") javafx.event.EventType<? extends javafx.event.Event> arg1) {
        super(arg0, arg1);
    }

    @Override
    public Object jxOwner() {
        return jxOwner;
    }

    @Override
    public void jxOwner(Object owner) {
        this.jxOwner = owner;
    }

    @Override
    public Object callSuper(String method, Object[] a) {
        try {
        switch (method) {
            default:
                throw new AbstractMethodError(method);
        }
        } catch (Exception e) {
            throw com.jxparallel.fx.Fx.sneaky(e);
        }
    }
}
